### ISSUE TITLE
Zeilenfall

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#1]
Der Zeilenfall auf den Titelseiten ist nicht korrekt (siehe Gedichte und deren Überschriften in KGK 1 und 2). Hier als Beispiel der Anfang von KGK 1 in der Online-Version:
![grafik](https://cloud.githubusercontent.com/assets/23031457/25850462/ab72311c-34c2-11e7-8faf-674eaf1eb229.png)
Erster Versuch eines Issues. Ich hoffe, es funktioniert...

**Comment by Marxistin** [comment]
Lässt sich das bis zum 16. Mai 2017 erledigen?

**Comment by dariok** [comment]
Geprüft auf dev2 und diglib:

* http://diglib.hab.de/content.php?dir=edoc/ed000216&distype=optional&metsID=edoc_ed000216_001_transcript&xml=texts%2F001%2F001_transcript.xml&xsl=scripts/xslt/tei-transcript.xsl
* http://dev2.hab.de/edoc/view.html?id=edoc_ed000216_f001_transcript

**Comment by Marxistin** [comment]
Sieht gut aus!
