### ISSUE TITLE
Vorlagen zum Testen des Transformationsszenarios

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#10]
Zusendung der Vorlagen zum Testen des Transformationsszenarios - siehe Email:

Von: Dr. Stefania Salvadori <salvadori@hab.de> 
An: Dario Kampkaspar <kampkaspar@hab.de> 
Gesendet: **18/05/2017 11:17** 
Betreff: **Vorlagen zum Testen des Transformationsszenarios** 

***
Liste der gesendeten Ueberlieferungen (.docx Files):

- [x] EE 82
- [x] EE 92
- [x] EE 100
- [x] EE 101
- [x] EE 102
- [x] EE 103
- [ ] EE 104
- [x] EE 106
- [x] EE 107
- [x] EE 109
- [x] EE 125
- [x] EE 131

**Comment by Marxistin** [comment]
Es wäre schön, wenn wir nächste Woche am Mittwoch Vormittag erste Ergebnisdateien hätten, über die wir sprechen könnten. Uns ist aber immer noch nicht klar, in welcher Form wir diese Dateien erhalten werden: xml oder html oder PDF?

**Comment by dariok** [comment]
Mittwoch kann ich für die Einleitungen versuchen, aber nicht versprechen.
Das Ergebnis ist das Upload-Formular, mit dem die Dateien auf dev2.hab.de gespeichert werden (wo dann eine HTML-Ansicht möglich ist).

**Comment by Marxistin** [comment]
Da können wir aber jetzt noch nicht reinschauen, oder? Ich finde nur den Zugang zur Spielwiese:
http://dev2.hab.de/edoc/ed000216/start.html

**Comment by Marxistin** [comment]
Das habe ich auch noch gefunden:
http://dev2.hab.de/apps/dashboard/index.html
Brauchen wir dafür ein Passwort?

**Comment by dariok** [comment]
Nein, den Link schicke ich rum, wenn es so weit fertig ist; da hängen neben der reinen Transformation noch ein paar andere Sachen dran.
Der zweite Link hat nichts mit Karlstadt zu tun.

**Comment by dariok** [comment]
Unter http://dev2.hab.de/edoc/ed000240/start.html sind die Einleitungen zu finden; bei denen, bei denen oben noch kein Häkchen steht, gibt es noch Probleme, die ich noch heute oder morgen behebe.
Unter http://dev2.hab.de/edoc/query.html?query=xquery/convert.xql&edition=ed000240 liegt das Formular, mit dem die Texte (Einleitungen) als .docx hochgeladen werden können.

**Comment by stefaniasalvadori** [comment]
Wir können die Einleitungen .docx nicht hochladen. Hier die Fehlermeldung:

![fehler](https://user-images.githubusercontent.com/28624747/27340182-1dc55d9c-55da-11e7-8da2-8e8809659ede.JPG)


Müssen wir uns einloggen? Falls ja, wie?

![unbenannt](https://user-images.githubusercontent.com/28624747/27340131-f1dcac08-55d9-11e7-8b08-34d19a456609.JPG)

**Comment by dariok** [comment]
Das muß ich mir nochmal kurz anschauen, eigentlich solltet ihr direkt schreiben können. Morgen mehr :)

**Comment by dariok** [comment]
Mit dem genannten Namen und Paßwort können nun Einleitungen hochgeladen werden.
