### ISSUE TITLE
EE 83

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#100]
Anbei die EE 83 (KGK 105) als Beispiel für einen handschriftlichen Brief. Zu beachten ist die Ausrichtung der Schlussformel. Habe so lange gebraucht, weil ich immer wieder mit den Formaten KS:Anrede und KS: kritische Anmerkung über mehrere Wörter experimentierte. Nun neu definiert und alte Formate gelöscht. Unklar ist noch die Formatierung des Briefgegenstandes (odere Arguments) auf der Adressseite: "Rector doctor Martinus und auch etlichen lection halben zu Witenberg
[EE83Text2017-01-26.docx](https://github.com/dariok/karlstadt-issues/files/1667319/EE83Text2017-01-26.docx)
"

**Comment by dariok** [comment]
Eine erste Version ist unter http://dev2.hab.de/edoc/view.html?id=edoc_ed000240_083_transcript zu finden. An der Ausrichtung muß ich noch ein wenig experimentieren, da benutzt Word verschiedene Mechanismen. 

Hier noch die Datei mit den eingefügten Absatz-Marken: 
[EE83Text2017-01-26.docx](https://github.com/dariok/karlstadt-issues/files/1689328/EE83Text2017-01-26.docx)

**Comment by Wallsporn** [comment]
Die mitgeschickte Transformation gibt nur ein Wort aus: "Universitet"
Die Absatzmarken werden mit hinterlegten Fragezeichen ausgegeben. Ich weiß nicht, wie ich die Absatzmarken selbst einbaue. Ich denke, wir müssen eine Möglichkeit finden, dass auch wir Editoren diese Absatzmarken einfügen können, oder?

![grafik](https://user-images.githubusercontent.com/28565515/35736973-40f1e35a-082a-11e8-87d2-51a87c2afcbb.png)

**Comment by dariok** [comment]
Der Text ist noch da, aber weiter unten - bei Texten mit Marginalie ist im Moment oben ein Bereich, in dem die Marginalien ungeordnet sind; das liegt daran, daß ich gerade die Marginalien überarbeitet, damit sie beim Ändern der Größe oder Ausblenden der rechten Seite weiter richtig angezeigt werden. Das sollte bis nächste Woche passen.

Das Absatzzeichen ist das `F05E` - in Word erst `F05E` tippen und dann `Alt-C` drücken und dann sollte das Zeichen eingefügt werden (funktioniert mit allen Sonderzeichen, wen der "Hex-Codepunkt" genutzt wird).

**Comment by Wallsporn** [comment]
Ok, hab es gesehen. Der Satz in Opener und Closer entspricht nun - fast - dem Originalsatz. Der Closer (Schlussformel) war rechtsbündig.
Bei mir entsteht folgendes Zeichen: 
![grafik](https://user-images.githubusercontent.com/28565515/35745664-59aaf7a0-0844-11e8-9a37-29f78c1bdc44.png)

Soll das so? Ist das die Absatzmarke? Weiß leider gerade nicht, was ein "Hex-Codepunkt" ist ...

**Comment by dariok** [comment]
Aus der Umsetzung hat sich ergeben: Ändert sich in einem closer die Ausrichtung, muß eine Absatzmarke stehen.

[EE83Text2017-01-26 (1).docx](https://github.com/dariok/karlstadt-issues/files/1756093/EE83Text2017-01-26.1.docx)

**Comment by dariok** [comment]
Umsetzung der Ausrichtung erfolgt weitgehend mit https://github.com/dariok/ed000240/commit/f82662ccbbc160dd7d7121e2b540704115d1e0e4

**Comment by dariok** [comment]
@Wallsporn Bitte prüfen.
