### ISSUE TITLE
KGK 90

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#102]
Fehler in KGK 90:
- es fehlt das Faksimile
- alle Anmerkungen (Text- und Sachapparat) sind im Apparat ohne Annmerkungszeichen

**Comment by dariok** [comment]
Den zweiten Punkt kann ich nicht nachvollziehen - unter http://dev2.hab.de/edoc/view.html?id=edoc_ed000216_f069_transcript sehe ich im Apparat `a` bis `em` und auch `1` bis `669`.

**Comment by Wallsporn** [comment]
Ja, ok - hätte einen Screenshot machen müssen, aber nun ist es ja in Ordnung

**Comment by dariok** [comment]
Okay, super
