### ISSUE TITLE
Marginalienproblem bei verbreiterter Ansicht (alle EE)

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#103]
Wenn per Klick auf die Rechtspfeile die verbreiterte Ansicht gewählt wird, wandern die Marginalien NICHT mit! Die Orginalzuordnung der Marginalien ist nur in der schmalen Ansicht gewährleistet.

**Comment by dariok** [comment]
Okay, da schaue ich gerade rein.
Die Marginalien werden dann erst einmal etwas schief sitzen, aber ich hoffe, das bis Montag erledigt zu haben

**Comment by stefaniasalvadori** [comment]
@dariok - vermutlich hängt alles mit der Zuordnung der Marginalien zusammen, aber alle EE-Texte mit Marginalien sind durcheinander geraten. (z.B. EE1, 2, 52, 64)
Ich wollte das bloss signalisieren. 
Wenn das Problem Dir bekannt ist, einfach mein Comment ignorieren
Wenn wir das Problem woanders und besser (new Issue?) signalisieren müssen, einfach Bescheid geben.

**Comment by Wallsporn** [comment]
Es wäre vielleicht besser, den Nutzern zu signalisieren, dass gerade Umbauarbeiten stattfinden: "In Bearbeitung", "Technischer Umbau" o.ä. So sieht es sonst erst mal chaotisch aus.

**Comment by dariok** [comment]
Die Marginalien sollten jetzt wieder passen. Bitte testen.

**Comment by stefaniasalvadori** [comment]
Die Marginalien sehen nun deutlich besser aus. Die verbreiterte und die normale Ansicht (per Klick auf die Rechtspfeile) sind kaum zu unterscheiden. Damit sind die Digitalisate in der normalen Ansicht nicht optimal angezeigt - die Spalte ist so eng, dass man die Digitalisate verkleiner und verschieben muss. 

Details sollen noch verbessert werden.
Die Marginalien überlappen sich manchmal.
Z.B aus KGK I, Nr. 64 (Augustinkommentar) - aber es gibt mehrere Überlappungen:

![grafik](https://user-images.githubusercontent.com/28624747/36040144-f50be0e4-0dc4-11e8-892a-dfb2b54195c6.png)

Die Überschriften (Paragraphen, etc) waren zentriert, oder? Und wozu der Pfeil? Wenn ich darauf klicke, passiert nichts.

![grafik](https://user-images.githubusercontent.com/28624747/36040294-536ef720-0dc5-11e8-9dae-088ed93d76c7.png)

Noch ein Test-Case, den ich mir angeguckt habe.
Gleich (Überlappungen und Überschiften) gilt für KGK I, Nr. 1 (De Intentionibus), wo - darüber hinaus - die Liste am Anfang falsch angezeigt ist:

![grafik](https://user-images.githubusercontent.com/28624747/36040564-2106b8a8-0dc6-11e8-9a51-0ec196bfc325.png)

**Comment by dariok** [comment]
Für den Textteil gibt es eine Mindest- und Höchstbreite. Wenn das Fenster zu schmal ist, bleibt der Text bei der Mindestbreite, also wird das Digitalisat schmaler. Über der Maximalbreite wird der Textteil nicht breiter, aber das Digitalisat.

Die Maximalbreite hilft auch, die Überlappungen zu verringern.

Die anderen Punkte verlege ich in eigene Issues.
