### ISSUE TITLE
Format KS: Zitat im Text (quote)

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#104]
Format KS: Zitat im Text (quote) ist auch mit Absatzvorlage formatiert -> neuformatieren mit Zeichenvorlage?

![grafik](https://user-images.githubusercontent.com/28565515/35686652-12c5522c-076d-11e8-9917-3766fb0c932c.png)

**Comment by dariok** [comment]
Ja, kann als Zeichenvorlage abgeändert werden
