### ISSUE TITLE
KGK I und KGK II nicht mehr abrufbar

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#106]
Ich kann weder KGK I noch KGK II visualisieren:
![unbenannt](https://user-images.githubusercontent.com/28624747/35695622-5fc704cc-0785-11e8-9775-766d681fd847.JPG)

**Comment by dariok** [comment]
Eine erste Änderung habe ich jetzt vorgenommen. Bitte testen

**Comment by stefaniasalvadori** [comment]
Ja, danke Dario!
Jetzt ist sowohl KGK I als auch KGK II abrufbar.
Ich prüfe morgen nochmals in Details.

**Comment by Marxistin** [comment]
KGK II ist kein Problem. Allerdings kommen für KGK I Fehlermeldungen für alle "Contents", die nicht zu "Dokumente" gehören. Ich gelange also nicht mehr zur "Bibliographie"...
http://dev2.hab.de/edoc/view.html?id=edoc_ed000216_fg_bibliography#

**Comment by dariok** [comment]
Sollte jetzt wieder funktionieren, bitte prüfen

**Comment by Marxistin** [comment]
Header in der Bibliographie ist verdoppelt:
![grafik](https://user-images.githubusercontent.com/23031457/36020732-eba00eb8-0d83-11e8-9e30-a6b57fd2a41a.png)
Aufgerufen habe ich:
http://dev2.hab.de/edoc/view.html?id=edoc_ed000216_bibliography#

**Comment by stefaniasalvadori** [comment]
Das gilt auch für Vorwort, Einleitung, Chronologie.. etc. 
D.h. für alle Seiten, mit Ausname der "Dokumente"
![grafik](https://user-images.githubusercontent.com/28624747/36022669-2324e1dc-0d8a-11e8-92a7-a9fd2a91dff6.png)
![grafik](https://user-images.githubusercontent.com/28624747/36022692-39030eb6-0d8a-11e8-8bfa-b416fe4f65c7.png)
![grafik](https://user-images.githubusercontent.com/28624747/36022699-419d5bb2-0d8a-11e8-8fa7-24262049d431.png)
