### ISSUE TITLE
Transformation EE 126 Fehler

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#107]
Intro:
- keine Wiedergabe der Anmerkungen (als Fußnoten formatiert)

Text:
- EE 126 endet nach Anm. 25, Ursache unbekannt
- bei Zeilenumbruch im Wort, das mit `<rs>` getaggt, bleibt Trennungsstrich
- Expansion noch nicht in XML umgewandelt
- 
[EE126Intro2018-02-01.docx](https://github.com/dariok/karlstadt-issues/files/1689596/EE126Intro2018-02-01.docx)
[EE-126-Text2018-02-01.docx](https://github.com/dariok/karlstadt-issues/files/1689599/EE-126-Text2018-02-01.docx)

Buchtitel Originalsatz nicht berücksichtigt

**Comment by Wallsporn** [comment]
Hänge euch die überarbeiteten Dateien von EE 126 und 128 an.
[EE126Intro2018-02-15.docx](https://github.com/dariok/karlstadt-issues/files/1730612/EE126Intro2018-02-15.docx)
[EE-126-Text2018-02-15.docx](https://github.com/dariok/karlstadt-issues/files/1730617/EE-126-Text2018-02-15.docx)
[EE128Intro2018-02-01.docx](https://github.com/dariok/karlstadt-issues/files/1730618/EE128Intro2018-02-01.docx)
[EE128Text2018-02-02.docx](https://github.com/dariok/karlstadt-issues/files/1730619/EE128Text2018-02-02.docx)

**Comment by dariok** [comment]
[EE-126-Text2018-02-15.docx](https://github.com/dariok/karlstadt-issues/files/1778663/EE-126-Text2018-02-15.docx)

Bitte prüfen.
