### ISSUE TITLE
Transformation EE 128 Intro Fehler

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#108]
- Wie in EE 126Intro werden die Anmerkungen nicht ausgegeben.
- Fehler in Ausgabe der Handschrift: Angaben hinter Standort fehlen (trotz Spatium vor Komma in Word-Dokument)
- Gesamter Text hinter "2. Entstehung und Inhalt" wieder als "KS: EE-V
[EE128Intro2018-02-01.docx](https://github.com/dariok/karlstadt-issues/files/1689883/EE128Intro2018-02-01.docx)
erweis" formatiert, obwohl vorher alle Formatierungen gelöscht und zurückgesetzt wurden.

**Comment by dariok** [comment]
Weiter in #125
