### ISSUE TITLE
Reihenfolge der EE auf WDB?

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#11]
Die Reihenfolge stimmt online noch nicht. 
Ein Beispiel dazu: Nr. 6 (Scheurl an Karlstadt) steht vor Nr. 5 (Preisgedicht). Die weitere Reihenfolge habe ich nicht mehr überprüft.

**Comment by dariok** [comment]
Die Reihenfolge ist jetzt korrigiert.
