### ISSUE TITLE
Probleme beim Hochladen EE 82 und EE 92

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#113]
In der Online Edition von KGK II ist EE 82 nicht mehr abrufbar. Ich bekomme diese Fehlermeldung:

![grafik](https://user-images.githubusercontent.com/28624747/36200665-b86066e4-117d-11e8-8058-e72745ef15ad.png)

Wenn ich nochmals die EE 82 (sowohl intro und text) hochlade, bekomme ich diese Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/28624747/36200701-d69f0f7a-117d-11e8-9aa7-95d53f849668.png)

**Comment by stefaniasalvadori** [comment]
Das gilt auch für EE 92 - online nur unvollständig -, wenn ich sie neu hochlade

![grafik](https://user-images.githubusercontent.com/28624747/36200811-22664626-117e-11e8-8bb3-e87cf1415e43.png)

**Comment by dariok** [comment]
Das geschieht, wenn die Transformation nicht erkennen kann, ob es eine Einleitung oder eine Transkription ist. Ich arbeite an passenden Tests.

**Comment by stefaniasalvadori** [comment]
Die Einleitung wird hochgeladen - in der Überlieferung fehlt der vorletzte Absatz.
Anmerkungen sind nicht angezeigt.
In "Entstehung und Inhalt" sind die Formatierungen für Personen und Orte nicht angezeigt.

Hier die Word-Fassung:
[EE82intro2018-2-14.docx](https://github.com/dariok/karlstadt-issues/files/1725130/EE82intro2018-2-14.docx)

**Comment by stefaniasalvadori** [comment]
Änliche Probleme habe ich mit der Einleitung von EE 82 - sie ist komplett, fehlen jedoch Anm. und Namen/Orte.
EE 82 text --> die Transformation klappt nicht
EE 92 text ---> Transformation klappt - nur die Thesenreihe ist weiterhin ein Problem
Hier die Dateien - wir besprechen sie morgen
[EE82text2018-2-14.docx](https://github.com/dariok/karlstadt-issues/files/1725203/EE82text2018-2-14.docx)
[EE92intro2018-2-14.docx](https://github.com/dariok/karlstadt-issues/files/1725204/EE92intro2018-2-14.docx)
[EE92text2018-2-14.docx](https://github.com/dariok/karlstadt-issues/files/1725205/EE92text2018-2-14.docx)

**Comment by dariok** [comment]
Einzelheiten jetzt in eigenen Issues
