### ISSUE TITLE
Upload: Probleme mit Berechtigungen

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#114]

**Comment by Wallsporn** [comment]
Upload der verbesserten Dateien nicht möglich wegen Arbeit an Datenbank?

![grafik](https://user-images.githubusercontent.com/28565515/36210873-e3b2dcf6-119f-11e8-946c-42e404ba63df.png)

**Comment by dariok** [comment]
@Wallsporn Nein, gerade keine Arbeiten an der Datenbank. Vielleicht ist genau beim Upload die Anmeldung ausgelaufen. Ich konnte gerade ohne Probleme hochladen.

**Comment by stefaniasalvadori** [comment]
Upload funktioniert auch bei mir nicht. Ich habe nochmals mit EE 82  (vgl #113) versucht:

![grafik](https://user-images.githubusercontent.com/28624747/36214344-950a302c-11a9-11e8-997e-3deed341fa7b.png)

**Comment by dariok** [comment]
Das Problem konnte entstehen, wenn ich vorher eine Datei hochgeladen hatte.
Ich habe nun die Berechtigungen korrigiert. Alle Uploads sollten nun wieder möglich sein.

**Comment by stefaniasalvadori** [comment]
Noch nicht... Beim Hochladen der EE 82_intro bekomme ich diese Fehlermeldung: 

![grafik](https://user-images.githubusercontent.com/28624747/36217270-4b98232e-11b1-11e8-8983-856a1c93499e.png)

**Comment by dariok** [comment]
Ich habe nun auch die Berechtigungen für die Verzeichnisse angepaßt. Ein Test gerade mit 126 Intro als Benutzer Karlstadt hat funktioniert

**Comment by stefaniasalvadori** [comment]
Ja, das Hochladen funktioniert nun - danke
Einige Probleme bestehen jedoch weiterhin; ich signalisiere sie aber im enstsprechenden Issue
