### ISSUE TITLE
088A Intro

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#124]
- [x] Zitate haben noch "
- [x] später prüfen: Hochstellung r/v in FN (funktioniert aktuell)

**Comment by stefaniasalvadori** [comment]
[EE88Aintro2018-2-16.docx](https://github.com/dariok/karlstadt-issues/files/1731234/EE88Aintro2018-2-16.docx)

**Comment by stefaniasalvadori** [comment]
[EE88Aintro2018-2-16.docx](https://github.com/dariok/karlstadt-issues/files/1731246/EE88Aintro2018-2-16.docx)
