### ISSUE TITLE
Verschollene / verlorene EEen können nicht aufgerufen werden

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#13]

**Comment by Marxistin** [comment]
Weitere Einzelheiten / weitere Fragen dazu:
Nr. 9 (Karlstadt an Scheurl) kann auf beiden Plattformen aufgerufen werden.
Irritierend ist nun aber noch, dass 

- Nr.  9 die einzige EE ist, bei der noch "(verloren)" steht. Bei den anderen EEen steht "verschollen:"

- Nr. 3 und Nr. 4 öffnet sich eine "Beschreibung", bei Nr. 9, 12, 13, 15 eine "Einleitung"

Weiter habe ich nun nicht geschaut, denke aber dass noch nicht alles aktuell ist.

**Comment by dariok** [comment]
Auch prüfen: 044B

**Comment by dariok** [comment]
»Beschreibung« → »Einleitung« in allen Fällen ersetzt

**Comment by dariok** [comment]
verloren → verschollen bei 9, 32, 33, 38, 39, 40, 41, 65, 68
