### ISSUE TITLE
bibliography -> bibl/ref

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#132]
vgl. dariok/w2tei#15

**Comment by dariok** [comment]
Umgesetzt in https://github.com/dariok/w2tei/commit/86fbdee9b737474619cf9567c6121e343ba5144d

**Comment by stefaniasalvadori** [comment]
Zum Testen habe ich EE82 nochmals hochgeladen.

Soweit ich sehe sind die bibliographische Angaben im Text getaggt (bis auf ein paar Quellen - die vermutlich in der nun verwendete Xml-Bibliography nicht drin waren).

Die bibliographische Angaben sind aber in der Einleitungen NICHT getaggt. 
(in Xml finde ich nur die Grundkodierung <bibl>)

Sehe ich richtig?

Ich habe nun das Issue hier nochmals geöffnet - wenn es nicht richtig ist, bitte ein neues Issue evtl. öffnen.
