### ISSUE TITLE
Bibliographie in W.DB

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#135]
Am Anfang Verdoppelung (?) der Titelzeile:
![grafik](https://user-images.githubusercontent.com/23031457/36848645-2a8aa94c-1d62-11e8-9be6-7f969e67abb7.png)

**Comment by dariok** [comment]
Bereits erledigt in #134 bzw. https://github.com/dariok/karlstadt/commit/420f338ddaa59b5ae97ceec2eb99478cb79745d0

**Comment by Marxistin** [comment]
Sieht aber in der Bibliography immer noch so aus:
http://dev2.hab.de/edoc/view.html?id=edoc_ed000216_bibliography#

**Comment by dariok** [comment]
Liegt bei Dir vermutlich noch im Cache. Strg+R

**Comment by Marxistin** [comment]
Stimmt. Jetzt geht es.

... bis auf die blauen Pfeile. Bei denen tut sich immer noch nichts.


Am 01.03.2018 um 15:29 schrieb Dario Kampkaspar:

**Comment by dariok** [comment]
Die Pfeile sind noch offen, vgl. #136

**Comment by Marxistin** [comment]
Kann die Seite nicht mehr öffnen. Fehlermeldung sieht so aus:
![grafik](https://user-images.githubusercontent.com/23031457/37707111-329bcf8a-2d02-11e8-9748-1a486d0fd8f4.png)
Kann das damit zusammenhängen, dass ich meine "bibliography_AM_2018-03-19" unter dem Namen "bibliography,xml" auf "db/edoc/ed000240/register/" gespeichert habe?

**Comment by dariok** [comment]
Ja, das ist das Problem, genau genommen, daß in beiden Dateien die gleiche ID steht. Wenn Du einer ältere Version speicherst, mußt Du hier die xml:id entfernen oder abändern.

**Comment by Marxistin** [comment]
Das verstehe ich nicht. Ich habe meine aktuellste Version umbenannt. Gab es in der bibliography.xml-Datei Änderungen, die in meiner Datei nicht vorhanden waren? Ist also die als bibliogrpaphy.xml gespeicherte Version aktueller bzw. anders als meine?

**Comment by Marxistin** [comment]
... und wie lösen wir das Problem nun?

**Comment by Marxistin** [comment]
Ich habe nun die von mir weiter bearbeitete bibliography (jetzt mit Datum 2018-03-21) auf den server gespeichert.

**Comment by Marxistin** [comment]
Kannst Du beide Versionen zusammenbauen? Ich mach jetzt nix mehr...

**Comment by dariok** [comment]
Das Problem ist, daß beide Dateien anfangen mit

    <TEI [...]
	xml:id="edoc_ed000216_bibliography">

Damit kann die Anzeige nicht zwischen den beiden unterscheiden.
Wenn Du mehrere Versionen auf dem Server speicherst, darf nur bei der aktuellsten Version diese ID vergeben sein, bei den anderen muß sie raus.
Nebenbei wichtig: für die 2. Phase muß die ID lauten: `edoc_ed000240_bibliograhpy`, denn sonst gibt es noch die Überschneidung mit der 1. Phase.

Ich korrigiere das auf dem Server gerade.

**Comment by dariok** [comment]
Das ist erledigt. Die Anzeige erhältst Du über http://dev2.hab.de/edoc/view.html?id=edoc_ed000240_bibliography

**Comment by Marxistin** [comment]
Vielen Dank.
Wenn ich nicht direkt an dieser bibliography.xml weiterarbeiten möchte, würde ich sie mir runterladen und mit meinen Namensergänzungen (_AM_Jahr-Monat_Tag) weiterbearbeiten, oder?

**Comment by Marxistin** [comment]
Nächste Frage: Die Datei bietet mir nicht mehr an, zwischen verschiedenen Schematron (heißt das so?) zu wählen und zeigt mir diverse Fehlermeldungen, die ich nicht korrigieren kann:
![grafik](https://user-images.githubusercontent.com/23031457/37764395-e2116bd6-2dc1-11e8-9247-9b3036a1558c.png)

**Comment by dariok** [comment]
1) Ja, das kannst Du jederzeit machen
2) Ich schaue mir die Punkte mal an

**Comment by Marxistin** [comment]
Darum geht es mir nicht. Ich möchte gerne auswählen können zwischen "Alle", "Editoren" und noch was (hab vergessen, wie das genau hieß). Mit der Editoren-Schema (oder -Schematron) bin ich bisher immer gut gefahren.

**Comment by dariok** [comment]
Schon verstanden. Ich habe im Schematron nun eine Phase „Editoren“ eingefügt, die nur die relevanten Punkte umfaßt.

**Comment by Marxistin** [comment]
Danke.

**Comment by dariok** [comment]
Keine Ursache :)

**Comment by Marxistin** [comment]
Mir ist aufgefallen, dass Antiquariatskatalog Kocher-Benzing (ohne Leerzeichen dazwischen) ganz ans Ende des Literaturverzeichnisses gerutscht ist. Das mag daran liegen, dass ich den Namen Kocher-Benzing getaggt habe, "Antiquariatskatalog" aber noch davor steht. Kann ich auch gerne wieder rausnehmen.
Die Überschrift "3. Hilfsmittel" unterbricht auch nicht die Auflistung von Literaturverzeichnis und Hilfsmittel:
![grafik](https://user-images.githubusercontent.com/23031457/37823478-e24ffdec-2e89-11e8-9c57-ca9e2b2d96de.png)
Ist sie vielleicht zu kurz dafür?

**Comment by dariok** [comment]
Die Reihenfolge beim Antiquariatskatalog ist das Problem - eigentlich haben wir immer erst den Autor, dann den Titel. Andersherum gibt es Probleme.

Das zweite verstehe ich nicht, was meinst Du?

**Comment by Marxistin** [comment]
Aland gehört zu den Hilfmitteln, sollte deshalb unter der Überschrift "3. Hilfsmittel" stehen und nicht eingerückt an den Antiquariatskatalog anschließen. Irritierend war für mich diese Einrückung, darum habe ich vermutet, dass 3. Hilfsmittel nicht lang genug war, also aus zuwenig Zeichen besteht. Kann aber auch eine falsche Vermutung sein.

**Comment by Marxistin** [comment]
Der Antiquariatskatalog sollte unter "A" stehen. Wenn es keine andere Lösung und keine Einwände von den Editoren gibt, würde ich alles in Großbuchstaben setzen, also mit <name> taggen. Oder geht das auch nicht?

**Comment by Marxistin** [comment]
Habe jetzt meine neueste Fassung (von heute) unter dem Namen "bibliography.xml" auf den Server hochgeladen (mit "Datei speichern unter URL". Wie lange dauert es, bis er diese Fassung zeigt? Ich habe diverse Hilfsmittel ergänzt, die er mir nicht anzeigt.
Ich habe meine Datei auch noch auf den Karlstadt-Server gestellt. Wenn nötig, kann Harald diese Version auch noch hochladen.
In etwa einer halben Stunde werde ich das Büro verlassen. Korsika ruft :-)

**Comment by dariok** [comment]
Die Änderungen erscheinen sofort nach dem Speichern. Wenn bei Dir noch etwas altes angezeigt wird, kann es am Cache liegen.

Beim Antiquariatskatalog bin ich mir nicht sicher, ob es so sinnvoll ist. Warum soll ausgerechnet der als einziges Buch in der Liste nach dem Titel einsortiert werden?

**Comment by Marxistin** [comment]
Stimmt. Den Cache hatte ich vergessen. Jetzt stehen sie alle da.

Der Antiquariatskatalog stand bereits in KGK I mit dieser Sortierung. Vermutlich, weil er auch so zitiert wird. Da sollen sich die Editoren den Kopf drüber zerbrechen. Mich würde es nicht stören, dass er als einziges Buch nach dem Titel einsortiert wird.
Tschüß. Korsika ruft!
