### ISSUE TITLE
Link nach oben funktioniert nicht

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#136]
... bei Zwischenüberschriften

- ersatzlos entfernen?
- ähnlich Projektnavigation eine Nav. innerhalb der Datei einblenden? vgl. dariok/karlstadt#28

**Comment by Wallsporn** [comment]
Wie sollte letzteres aussehen? (Der Link funktioniert nicht bzw. erzeugt einen errror)

**Comment by dariok** [comment]
Die Überlegung wäre, ähnlich dem Inhaltsverzeichnis für die Edition beim Klick auf "Navigation einblenden" ein Inhaltsverzeichnis zu erzeugen, das sich aus den Zwischenüberschriften generiert.
