### ISSUE TITLE
KS Kommentar im textkrit. Apparat - z.B. in EE92

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#141]
Wenn ich alles als KS Kommetar formatiere, wird alles kursiviert - funguntur soll NICHT kursiviert werden
![grafik](https://user-images.githubusercontent.com/28624747/37523234-9c83aef2-2926-11e8-9aa8-fc7db0f81dec.png)
Wenn ich nur Kommentar als KS Kommentar formatiere, lat. Wörter nicht, wird den lat. Text am Ende der Anm. wird nicht angezeigt - vgl. Anm r und x:
![grafik](https://user-images.githubusercontent.com/28624747/37523316-d601869a-2926-11e8-99d6-af28f39d508c.png)

Im Anhang die Word-Fassung
[EE92text2018-3-14.docx](https://github.com/dariok/karlstadt-issues/files/1819354/EE92text2018-3-14.docx)

**Comment by dariok** [comment]
[EE92text2018-3-14.docx](https://github.com/dariok/karlstadt-issues/files/1819969/EE92text2018-3-14.docx)

Die Vorlage KS Kommentar muß auf kursiv eingestellt sein, der Originaltext dann später manuell wieder recte gesetzt werden.
