### ISSUE TITLE
Trennung im Seiteumbruch - z.B. EE92

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#142]
Hier ein Beispiel

![grafik](https://user-images.githubusercontent.com/28624747/37523648-e4f7652e-2927-11e8-81a3-cbdf5fb84d00.png)

[EE92text2018-3-14.docx](https://github.com/dariok/karlstadt-issues/files/1819358/EE92text2018-3-14.docx)

**Comment by dariok** [comment]
[EE92text2018-3-14.docx](https://github.com/dariok/karlstadt-issues/files/1820131/EE92text2018-3-14.docx)

Beim Umbruch:

`iustissi-[A3v]`
`mam`

**Comment by Wallsporn** [comment]
Aber doch im fortlaufenden Text, oder?
iustissi-[A3v]mam ...

**Comment by dariok** [comment]
Nein, der Anfang der neuen Zeile/Seite steht dann auch in der neuen Zeile:

    ... iustissi-[A3v]
    mam ...
