### ISSUE TITLE
Textapparat

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#143]
Textapparat EE 126
ich habe in Anm. be (in Word Anm. eee) zwei Lesarten. Wenn ich in Word das trennende Semikolon angebe, wird es in der HTML-Ausgabe verdoppelt. Was ist zu tun? KS Kommentar kann nicht verwendet werden. So belassen?

![grafik](https://user-images.githubusercontent.com/28565515/37781899-f69474ce-2df1-11e8-8312-424853ca27a8.png)

**Comment by dariok** [comment]
Schau mal, ob das Semikolon kursiv ist. Wenn nicht, wird es als Teil der Lesart angenommen und daher steht dann einmal ein Semikolon (recte) als Teil der Lesart und einmal eines (kursiv) als Trenner – das läßt sich aber nicht unterscheiden.
Ich habe bisher gezögert, das Semikolon automatisch zu entfernen, denn es könnte ja tatsächlich Teil der Lesart sein (bei Stefania haben wir z.B. den Fall, daß sich auch die Zeichensetzung unterscheidet).

**Comment by Wallsporn** [comment]
Ja, richtig - und ich dachte, ich hätte es kursiviert ... Alles ok

**Comment by dariok** [comment]
Okay, super :)
