### ISSUE TITLE
KGK I+II OnlineEdition - Browser Probleme mit Internet Explorer

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#144]
In Internet Exploren kann man die Dokumente nicht sehen, d.h. wenn ich auf "Dokumente" klicke, passiert nichts

![grafik](https://user-images.githubusercontent.com/28624747/39047522-82177e24-449a-11e8-9d0e-1c74b6280e34.png)

Bei Mozilla gibt es dagegen kein Problem:

![grafik](https://user-images.githubusercontent.com/28624747/39047574-aea293a2-449a-11e8-907e-f5b5a6c787e2.png)

**Comment by dariok** [comment]
Ist ein Problem, da der IE mittlerweile zu alt ist. Ich hoffe, ich habe das umgehen können, es sollte jetzt funktionieren.
