### ISSUE TITLE
@DarioK - LogIn in GitHub für Timo Jansse

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#145]
@dariok - wie kann Timo Jansse - der seit 1. April im unseren Projekt tätig ist - sich anmelden? Einfach Sign-Up in GitHub oder muss Du ihn einladen?
Danke im Voraus!

**Comment by dariok** [comment]
Er muß sich bei guthub anmelden und mir dann seinen Benutzernamen mitteilen. Dann kann ich ihn einladen.

**Comment by stefaniasalvadori** [comment]
Danke Dario. Das kläre ich mit Timo am Montag. LG

**Comment by stefaniasalvadori** [comment]
Hier Timos Username:
**timojanssentj**

**Comment by dariok** [comment]
Ich habe ihn eingeladen, er sollte jetzt Zugriff haben.
