### ISSUE TITLE
Bibliographie, Quellenverzeichnis, Abstände in der <abbr>

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#148]
Die Angaben der Abbreviation stehen zum Teil ohne Leerzeichen, zum Teil mit Leerzeichen. Ein System habe ich dahinter nicht finden können. Was sollte ich wie anpasssen?
Hier ein Beispiel:
![grafik](https://user-images.githubusercontent.com/23031457/39350495-a223b066-49fe-11e8-89a2-ea3cadc8859d.png)

**Comment by dariok** [comment]
Der Unterschied ist, daß bei Chrysopassus das `title` fehlt. Es steht recte, statt kursiv.
Bei den Kursiven aber wirkt der Abstand zu klein, ich werde ihn dann etwas vergrößern.

**Comment by Marxistin** [comment]
Danke :-)
title ergänzt, Vergrößerung des Abstands find ich gut.

**Comment by dariok** [comment]
Es ist jetzt auch ein festes Spatium vor dem kursiven Titel.
