### ISSUE TITLE
Layout bei Thesenreihen mit dd prüfen

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#15]
Vgl. Nr. 88

**Comment by Marxistin** [comment]
Sollte nicht der Hinweis auf 66-2 im Inhaltsverzeichnis besser gelöscht werden? Das gilt auch für den Hinweis auf 66-1 bei Nr. 85.

**Comment by dariok** [comment]
Das ist auf dev2 behoben; diglib folgt später

**Comment by dariok** [comment]
vgl. #53
