### ISSUE TITLE
Sach- und textkritische Anm. innerhalb einer "KS: kritische Anmerkung über mehrere Wörter" nicht angezeit

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#159]
Textkritische Anm. und SachAnm. innerhalb einer "KS: kritische Anmerkung über mehrere Wörter" werden nicht (mehr) angezeigt. Das ist echt ein Problem, da (vor allem in der Leipziger Disputation) diese "Anm. innerhalb Anm." unzählig sind. 

Das funktionierte früher, bzw. war eine textkrit. Anm. innerhalb einer _KS: krit. Anm. über mehrere Wörter_ in EE132A (KGK 173) vor 10 Minuten noch angezeigt - nicht aber die Sachanmerkung!
Ich habe nun die Word-Fassung nochmals hochgeladen und nun ist auch die textkrit Anm. weg.
So sieht es in der online Edition aus:

![grafik](https://user-images.githubusercontent.com/28624747/41104748-65cd7078-6a6c-11e8-9160-d7f906613d64.png)

Wordvorlage hier
[EE.132Atext_2018-6-7.docx](https://github.com/dariok/karlstadt-issues/files/2080735/EE.132Atext_2018-6-7.docx)

**Comment by dariok** [comment]
MIt diesem Text funktioniert es nun

**Comment by stefaniasalvadori** [comment]
Grande! 
Auch mit den ersten 10 Seiten der Leipziger Disputation funktioniert es nun
Ich prüfe später alle Anm. nochmals und melde mich falls Probleme auftauchen.
Erstmal aber einfach: DANKE+GRAZIE!
