### ISSUE TITLE
Aufruf des Digitalisats durch Klicken auf Seitenumbruch

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#16]
Kommentar/Textkritik wird aufgerufen durch Mouse-Over auf Anmekrungszeichen. Wird über Digitalisat eingeblendet und kann durch Klicken auf ein Schließkreuz geschlossen werden.
Durch Klicken auf Anmerkungszeichen wird Kommentar/Textkritik als Endnote dargestellt (dies eventuell bereits bis 15.6.)

**Comment by stefaniasalvadori** [comment]
Danke Dario - es sieht sehr gut aus!

**Comment by Wallsporn** [comment]
auch von meiner Seite sollte schon längst ein Danke kommen - wir wissen um Deinen Urlaub. zu KGK 64 demnächst
