### ISSUE TITLE
KGK 138 = EE 81 Trennungsproblem

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#163]
Probleme der Worttrennung bei mit Registereintrag belegtem Wort, hier "Augu- stae"

![grafik](https://user-images.githubusercontent.com/28565515/41461375-d60f8adc-708f-11e8-8d0d-17eee961c223.png)

**Comment by dariok** [comment]
Hoffentlich gelöst mit https://github.com/dariok/w2tei/commit/348283f9b319864e289566557501c86cec6f9fe5
