### ISSUE TITLE
EE 109=KGK 139 (Franziskanerdisputation) - Digi nicht erreichbar

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#169]
In EE109 = KGK 139 funktioniert dad Link auf Digitalisat nicht.
Hier nochmals das richtige Link:
https://gdz.sub.uni-goettingen.de/id/PPN885662997?tify={%22pages%22:[15],%22view%22:%22info%22}

**Comment by dariok** [comment]
Bei mir funktioniert der Link und geht auch auf die richtige Stelle; bitte prüfen.

**Comment by stefaniasalvadori** [comment]
Ja, nun funktioniert es auch bei mir.
