### ISSUE TITLE
Spatien im Wort

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#173]
Es tauchen unnötige Spatien auf, vorzugsweise in Anmerkungen bei Worten mit Personenmarkierung, s. Anm. 1 und 10:
![grafik](https://user-images.githubusercontent.com/28565515/44984311-8fe8bc00-af7c-11e8-9372-c25542a2f21a.png)

**Comment by dariok** [comment]
Die Namen werden nun zusammengezogen. Damit das funktioniert, muß ich alles zusammenziehen, was an Namen aufeinander folgt – zwischen zwei Namen, Orten muß also mindestens ein Leerzeichen, Komma, etc. stehen, das nicht als Ort oder Person markiert ist.
