### ISSUE TITLE
Fehler bei Ziffernhochstellung

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#174]
Fehler bei der Ziffernhochstellung bei der bibliographischen Angabe Walch, vgl. Anm. 1
![grafik](https://user-images.githubusercontent.com/28565515/44984352-b73f8900-af7c-11e8-8870-2376aa4b9433.png)

**Comment by dariok** [comment]
Ausgabe von „super“ sollte nicht mehr vorkommen und nach neuem Hochladen auch die überzählige „2“ nicht mehr vorkommen.

**Comment by stefaniasalvadori** [comment]
Jetzt sieht es so aus - d.h. mit Verdoppelung der überzählige "2":
![unbenannt](https://user-images.githubusercontent.com/28624747/46602629-fcf9ef00-caf0-11e8-9f50-897902b69059.JPG)

Woran liegt das Problem?
