### ISSUE TITLE
Zeilenumbruch mit Marginalie

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#175]
Bei Zeilenumbruch im Wort mit Marginalie wird Trennstrich unnötig wiedergegeben, vgl. "Augu- stae". Evtl. händisch lösen?

![grafik](https://user-images.githubusercontent.com/28565515/44984447-07b6e680-af7d-11e8-8e45-c0d362013420.png)

**Comment by dariok** [comment]
Der Fall hier war rs+Marginalie+lb+rs – dieser sollte jetzt korrekt verarbeitet werden.
