### ISSUE TITLE
Verdoppelung bei Zeilenumbruch

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#176]
KGK 138 (EE 81)
Bisher nur einmal: Verdoppelung bei Zeilenumbruch utranque par[A3v]tem par[A3v]tem 
![grafik](https://user-images.githubusercontent.com/28565515/44984511-54022680-af7d-11e8-9693-706e612ac12f.png)

**Comment by dariok** [comment]
Das Problem hier scheint zu sein, daß der Umbruch A3v auf einer eigenen Zeile steht. Wenn er am Anfang der Textzeile steht, sollte es funktionieren.
