### ISSUE TITLE
Marginalien überlappend / verschoben

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#177]
KGK 138 (EE 81)
Marginalien überlappen bzw. bei breiterer Ansicht verschieben sich
Problem grundsätzlich durchdenken? Aber wie?

**Comment by dariok** [comment]
Ich hoffe, daß ich für die Positionierung jetzt eine bessere Lösung gefunden habe.
Ggf. sollten wir aber noch einmal darüber nachdenken, wie man deutlich macht, wo eine Marginalie im Text hingehört.
