### ISSUE TITLE
Link in Bibliography

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#186]
Beim Grimm-Wörterbuch soll ein Link eingefügt werden. Mein Versuch war nicht erfolgreich. 

So sieht es online aktuell aus:
DWb — Grimm, Jacob; Grimm, Wilhelm: Deutsches Wörterbuch, 16 Bde. in 32 Teilbänden, Leipzig 1854–1961.
Den Link hab ich in xml eingefügt. Das sieht dann so aus:

    <bibl xml:id="grimm_woerterbuch_1854">
        <abbr>DWb</abbr>Grimm, Jacob; Grimm, Wilhelm: Deutsches Wörterbuch, 16 Bde. in
        32 Teilbänden, Leipzig 1854–1961<ptr type="link" target="http://woerterbuchnetz.de/cgi-bin/WBNetz/wbgui_py?sigle=DWB"/>.</bibl>

Warum geht das nicht?

**Comment by dariok** [comment]
Bisher gab es schlicht keine Ausgabe von Links aus der Bibliographie. Werde das bei Gelegenheit umsetzen.

**Comment by Marxistin** [comment]
In welcher Datei hast Du die Änderung durchgeführt? In bibliography.xml steht noch mein Versuch mit <ptr>. Online steht es aber mit <a href> :
<p id="grimm_woerterbuch_1854" class="exemplar">
					<span class="abbr">DWb — </span>Grimm, Jacob; Grimm, Wilhelm: Deutsches Wörterbuch, 16 Bde. in
					32 Teilbänden, Leipzig 1854–1961 [<a target="blank" href="http://woerterbuchnetz.de/cgi-bin/WBNetz/wbgui_py?sigle=DWB">Link</a>] 
Bevor ich nun Änderungen an "bibliography.xml" durchführe, wüsste ich doch gern woran ist bin...

**Comment by Marxistin** [comment]
Dieses Schreibprogramm löscht meine "Zitate". Nächster Versuch.
Deine Online-Umsetzung:
![grafik](https://user-images.githubusercontent.com/23031457/50154665-4bcebc80-02ca-11e9-9352-c12d91c939a2.png)
Meine Kodierung in bibliography.xml:
![grafik](https://user-images.githubusercontent.com/23031457/50154744-87698680-02ca-11e9-8ddf-1d35c5c7f415.png)

**Comment by Marxistin** [comment]
Kann ich die bibliography.xml bearbeiten und hochfahren? Oder überschreibe ich dann Deine Korrekturen? Gibt es noch weitere Korrekturen? Welches ist die aktuellste Version von bibliography.xml???

**Comment by dariok** [comment]
Ich habe an der bibliography.xml nichts geändert, nur an der Ausgabe; Du kannst jederzeit weiterarbeiten.

**Comment by Marxistin** [comment]
Das beantwortet aber nicht die Frage, ob ich es korrekt kodiert habe. Ansonsten könnte ich die Kodierung mit <ptr> auch weglassen, nicht wahr? Es wäre gut zu wissen, wie ich es am besten umsetze, damit keine Nachkodierungen oder sonstige Änderungen in darauf aufbauenden Ausgaben (PDF? LaTeX?) notwendig werden.
