### ISSUE TITLE
Navigationliste KGK II

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#190]
Damit wir es nicht vergesssen:
Die Navigationliste für KGK II muss angepasst/korrigiert werden. Einheiten nicht chronologisch sortiert und mit falschen KGK Nr. 

@Harald, wollen wir nächste Woche die Navigationliste gemeinsam prüfen und evtl. die EE nochmals hochladen?

@dariok Die Navigationliste muss per Hand angepasst werden, oder? Falls Ja, melden wir uns nächste Woche mit einer Liste der Fehler. Oder reicht es, die EE nochmals hochzuladen?

**Comment by dariok** [comment]
@stefaniasalvadori Ich habe die Liste einmal aktualisiert; kann aber nicht sagen, ob das Ergebnis so korrekt ist.

**Comment by stefaniasalvadori** [comment]
Ich schaue mir sofort die Liste an - Danke!
Bevor ich vergesse:
In der Haupt-Navigationliste ist ein Fehler (KGK 108 muss weg) aufgetreten:

![cattura](https://user-images.githubusercontent.com/28624747/49114380-5a602000-f298-11e8-8298-5da6061f2cb0.PNG)

**Comment by stefaniasalvadori** [comment]
Es gibt Verdoppelung nur im Jahr 1520 (alte Einheiten, die wir nochmals hochlden muessen):

![cattura](https://user-images.githubusercontent.com/28624747/49114780-55e83700-f299-11e8-8904-601d22041398.PNG)
Verba Dei waere 146

und 
![cattura](https://user-images.githubusercontent.com/28624747/49114877-934cc480-f299-11e8-8f51-e034fa134a84.PNG)
Verschollen: Franciscus Seyler waere 160
Von Vermoegen des Ablass --> KGK 161
Von geweiht Wasser --> KGK 162
De Canonicis --> KGK 163
Bedingung --> KGK 164
Missive --> KGK 165
etc.

Ich vermute aber, die Liste wird aktualisiert beim naechsten Hochladen der EE vom Jahr 1520

Fuer die EE vom Jahr 1519 gibt es kleinen Layout Fehler im Titel und Datierung. Die sollen nachkodiert werden, oder?
Brauchst Du eine detaillierte Liste der kleinen Fehler?

**Comment by dariok** [comment]
Die überzählige 108 habe ich rausgeschmissen. Alle anderen Einträge sollten aktualisiert werden, wenn ein Text hochgeladen wird.
