### ISSUE TITLE
EE 102 und EE 103 - Probleme beim Hochladen

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#192]
Folgende Fehlermeldung bekomme ich beim Hochladen von EE102_intro und EE103_text (beide EE sind schon Online vorhanden)

![unbenannt](https://user-images.githubusercontent.com/28624747/47294571-c900ec80-d60d-11e8-80d0-ec249871b3a9.JPG)

**Comment by stefaniasalvadori** [comment]
Es funktioniert noch nicht - habe gerade nochmals versucht, die EE hochzuladen

**Comment by dariok** [comment]
Bitte einmal mit Strg+r die Upload-Seite neu laden und neu anmelden (falls dort noch „karlstadt“ steht, da einmal drauf klicken und nach Strg+r neu anmelden).

**Comment by stefaniasalvadori** [comment]
Ja! Nun funktioniert es
Danke!
