### ISSUE TITLE
EE 81 Text: Zeichen für Expan - keine Expan-Kodierung

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#193]
Zeichen für Expan erscheinen durch unterschiedliche Schriftarten verschieden, womöglich auch durch unterschiedliche (automatische) Spracheinstellungen etc.
Diese Zeichen erzeugen keine <expan>-Kodierung in XML, vgl. EE 81 Text
[EE81Text2018-09-16.docx](https://github.com/dariok/karlstadt-issues/files/2502312/EE81Text2018-09-16.docx)

**Comment by Wallsporn** [comment]
Ist es möglich, verschiedene Zeichen dieser Art summiert zu erfassen und in <expan> zu transformieren? Wie sind sie von Auslassungs-Apostroph zu unterscheiden?

**Comment by dariok** [comment]
Das Problem wird in vielen Fällen sein, daß Word automatisch umwandelt – vom ' zu einem ’
Letzteren kann ich eben nicht automatisch konvertieren, weil es sonst zu Chaos kommt.
Die automatische Änderung läßt sich aber in Word – bei „Autokorrektur“ ausschalten, das sollte das Problem reduzieren

**Comment by Wallsporn** [comment]
Das mache ich /machen wir grundsätzlich, nur bei Formatierungen schaltet sie sich oft wieder ein. Darauf müssen wir achten. Ok.
