### ISSUE TITLE
EE103 - endgültige Formatierungensentscheidungen 

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#195]
Ich möchte in diesem Issue die Formatierungsentscheidungen festlegen, damit sie übersichtlicher für alle sind.

1) Formatierung von textkrit. Anm. mit Kommentare AuRd-Gl etc.
- soll ich immer so Formatieren: ... text + AuRd-Gl + Witness  (= Witness IMMER am Ende)
Es sieht so aus:
![unbenannt](https://user-images.githubusercontent.com/28624747/47416799-c79f0380-d776-11e8-93f4-c96d7fda6787.JPG)
Und in Xml:
![unbenannt](https://user-images.githubusercontent.com/28624747/47416837-da193d00-d776-11e8-884e-650e2d129c19.JPG)

Wenn ich text + Witness + AuRd-Gl schreibe, wird AuRd-Gl  nicht visualisiert.

@dariok - ist es richtig?

**Comment by stefaniasalvadori** [comment]
Alles klar!
Ich war verunsichert, da "AuRd-Gl" manchmals nicht angezeigt wird.
Du schreibst aber: "2 AuRd-Gl und Vergleichbare werden als @rend des rdg umgesetzt (**teils noch nicht angezeigt**). "
Ergo: Ich bleibe bei der Reihenfolge Text - Witness - Kommentare.  Falls irgendetwas nicht angezeigt wird, warte ich einfach darauf, dass wir so weit sind.

Merci vielmal nochmals!

**Comment by stefaniasalvadori** [comment]
Die Reihenfolge sollte **Tex – Witness – Kommentare** gilt immer? auch für "hinzugefügt" und "korrigiert"?

Für "hinzugefügt" scheint in Ordnung - als @rend des rdg umgesetzt

Für "korrigiert in" und similia, scheint es nicht zu funktionieren. **Mein Vorschlag**: Für Korrekturen bleibe ich bei der Reihenfolge _Text - Witness - Kommentare_, wo alle "Kommentare" (_korrigiert in_, _hsl. korrigiert in_; etc.) als KS Kommentar formatiert werden. Wäre so einfacher?

Hier Stand der Dinge.
Bisher hatte ich:
- in Word: 
a) Anno 1519 _hinzugefügt a3_ 
b) sactissimum _a1;_ _korrigiert in_ sanctissimum _a2_
- Online
a)
![unbenannt](https://user-images.githubusercontent.com/28624747/47439816-53338700-d7ad-11e8-89b7-d088c89fb461.JPG)
b)
![unbenannt](https://user-images.githubusercontent.com/28624747/47440016-af96a680-d7ad-11e8-86d3-420fc67f59f7.JPG)

- Xml
a)
![unbenannt](https://user-images.githubusercontent.com/28624747/47439855-69d9de00-d7ad-11e8-88e5-084f23be8a67.JPG)
b)
![unbenannt](https://user-images.githubusercontent.com/28624747/47440070-c89f5780-d7ad-11e8-866f-dfd50f70c262.JPG)

**Comment by dariok** [comment]
Vielleicht sollten wir noch einmal eine Liste erstellen mit allen Formen, die wir im Moment benutzen; ich übersehe wohl immer wieder welche.

**Comment by stefaniasalvadori** [comment]
Hier die Liste der Formen, die noch nicht richtig transformiert und angezeigt sind:

- [ ]  **_vom Editor verbessert für_**
In EE103 habe ich sehr oft diese Forme + text + Witness (da ich Drucke und Handschrift berucksichtige)
Es wird manchmal so transformiert (auch in EE82, 92 etc - **ACHTUNG**: dort haben wir die Forme "verbessert für" - sollen wir die vereinheitlichen?):
![unbenannt](https://user-images.githubusercontent.com/28624747/47488609-03080380-d845-11e8-9c6c-fb8300198cdd.JPG)


Manchmal so:
![unbenannt](https://user-images.githubusercontent.com/28624747/47488517-d48a2880-d844-11e8-8619-7d54d6d7d96a.JPG)

![unbenannt](https://user-images.githubusercontent.com/28624747/47488537-e075ea80-d844-11e8-8944-313fe899d352.JPG)

- [ ] **_fehlt_ + Witness**
So in Xml:
![unbenannt](https://user-images.githubusercontent.com/28624747/47488786-5712e800-d845-11e8-80f3-93b9df8260e9.JPG)

- [ ] **_hinzugefügt_ + Witness**  / **_hsl. hinzugefügt_ + Witness** / **_am Rand hinzugefügt_ + Witness** / **_über der Zeile hinzugefügt_ + Witness** / **_am Rand hsl. hinzugefügt_ + Witness**
In Xml sehrn unheinheitlich
**MEIN VORSCHLAG**: Ich könnte diese Formel umformulieren und bei der Reihenfolge bleiben:
Tex¹ – Witness – Kommentare²
1 Wenn kein Text da ist, dann @ 
2 alle obergenannte Formel (hinzugefügt, am Rand hinzugefügt, hsl. hinzugefügt, ect.) formatiere ich als KS-Kommentar

Wenn so funktionieren kann, würde ich 1 Tag darin investieren, damit die Transformation endgültig klappen kann

- [ ] _**korrigiert in**_
Auch hier ist sehr schwierig.
Bisher hatte ich; _korrigiert in_ Text Witness
Wollen wir wie oben bei Tex¹ – Witness – Kommentare² bleiben? 

- [ ]  **Im Anschluss an hsl. Korrektur in A5Lp**
Das kommt am Ende der textkrit. Anm - das soll ich als KS - Kommetar formatieren, oder?

- [ ]  AuRd-Gl / InRd-Gl / ObRd-Gl / AuRd-Gl
darüber aber wir gestern geredet - ich warte einfach darauf, bis wir so weit sind, und alle diese Formel richtig angezeigt sind.

**Comment by dariok** [comment]
Ich habe jetzt noch einmal sehr viel an den kritischen Anmerkungen gebastelt, aber ich hoffe, daß ich jetzt die meisten Fälle gefunden habe.
Dadurch sollte sowohl das „@“ wieder wegfallen als auch die Au/InRd-Gl richtig verarbeitet werden.
Ich werde mir jetzt nochmal die LD stückweise durchschauen, was mir auffällt.
Ihr könnt auch testen, aber bitte beachten, daß noch nicht alles richtig angezeigt wird – ich muß noch die Skripte zum Anzeigen aktualisieren.

**Comment by stefaniasalvadori** [comment]
DANKE @dariok !
Soll ich die "@" löschen und  (in 10/15 Minuten) die Word-Fassung Dir senden und hochladen? 
Oder soll ich lieber abwarten? 
Wie es Dir am besten passt

**Comment by dariok** [comment]
Du kannst die „@“ löschen und hochladen. Ich werde dann über das aktuelle Ergebnis drüberschauen und die Fehler bearbeiten.

**Comment by stefaniasalvadori** [comment]
Ich habe die Datei nun hochgeladen.
"@" gelöscht. 
Hier die neue Word-Fassung:
[EE103text2018-11-02.docx](https://github.com/dariok/karlstadt-issues/files/2541935/EE103text2018-11-02.docx)
