### ISSUE TITLE
Formatierung der Autorenstellen

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#196]
In Fällen wie:
Ps. Ambr. = Ps. Ambr. = Prosp. vocat. gent. 1,10(8)

- Das Ganze als KS Autorenstelle formatieren?
- Nur 
> Ps. Ambr. = Prosp. vocat. gent. 1,10(8)

 als KS Autorenstelle formatieren?

- Zweimal als KS Autorenstelle formatieren? Einmal Ps. Ambr. und einmal Prosp. vocat. etc?

**Comment by dariok** [comment]
Das hängt davon ab, was im Register stehen soll.
Wir brauchen dann ggf. noch eine Liste, von wo aus verwiesen werden soll.

In diesem Beispiel: Wenn der Eintrag sein soll unter „Prosp.“, dann diesen Teil markieren.
Wir können dann bei „Ps. Ambr“ einen Verweis machen.
