### ISSUE TITLE
<expan> innerhalb Formatierungen (KS-Personen / KS textkrit. Anm. über mehrerer Wörter)

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#198]
**Expansionen** innerhalb Formatierungen (KS-Personen / KS textkrit. Anm. über mehrerer Wörter) werden nicht transformiert. 
So sieht es in XML aus:
![unbenannt](https://user-images.githubusercontent.com/28624747/47486864-98a19400-d841-11e8-9e27-2ccc15d58ed6.JPG)

![unbenannt](https://user-images.githubusercontent.com/28624747/47486903-abb46400-d841-11e8-88bf-0501a3905529.JPG)

Ist es schlimm?

**Comment by dariok** [comment]
Das läßt sich später per Schema finden; ich werde es aber noch verbessern.

**Comment by dariok** [comment]
Expansionen, die mit ' gekennzeichnet sind, sollten jetzt korrekt umgesetzt werden. Es ist aber wichtig, daß beide ' in der gleichen Markierung sitzen:

    Carolst'adius'

muß komplett als Person markiert sein; ist das letzte ' nicht in der Markierung, kann die Expansion nicht kodiert werden.

**Comment by stefaniasalvadori** [comment]
In Ordnung.
Nur, die Word-Fassung die ich heute Nachmittags transformiert habe, funktioniert nun nicht mehr.
Hier die Fehlermeldung, die ich bekomme:
![unbenannt](https://user-images.githubusercontent.com/28624747/47583261-333fc700-d957-11e8-9947-e32c1aeab284.JPG)

Und hier die Word-Datei
[EE103text2018-10-25_FORMATIERT.docx](https://github.com/dariok/karlstadt-issues/files/2520227/EE103text2018-10-25_FORMATIERT.docx)

Hast Du eine Ahnung, woran es liegt?

**Comment by dariok** [comment]
Ich habe nur eine Vermutung, die ich jetzt korrigiert habe.
Ich habe noch eingebaut, daß in solchen Fällen ein paar Informationen gespeichert werden, damit ich die Stelle besser finde.

**Comment by stefaniasalvadori** [comment]
Danke!
Lass mich wissen, ob ich den Text nochmals hochladen soll/muss/kann

**Comment by dariok** [comment]
Du kannst es nochmal probieren. Sollte es nochmal einen Fehler geben, kann ich ihn jetzt hoffentlich besser einkreisen.

**Comment by stefaniasalvadori** [comment]
Hier die Fehlermeldung, die ich noch bekommen:
![unbenannt](https://user-images.githubusercontent.com/28624747/47604715-bddb0180-d9fd-11e8-8a8e-d4e89a6ca824.JPG)

Hier die Word-Fassung:
[EE103text2018-10-25_FORMATIERT.docx](https://github.com/dariok/karlstadt-issues/files/2521787/EE103text2018-10-25_FORMATIERT.docx)

Das Problem habe ich auch beim Hochladen der (schon damals problemlos hochgeladenen) Einleitung EE103

**Comment by dariok** [comment]
Funktioniert jetzt wieder.

**Comment by stefaniasalvadori** [comment]
Yessa! 
@dariok santo subito!
