### ISSUE TITLE
expansionen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#20]
Wir hatten meines Wissens nicht geklärt, wie Expansionen in Word zu "kodieren" sind. Stefania und ich habe jetzt Expansionen einfach mit Apostroph gekennzeichnet: chur'furstlich' etc. Da schon benutzt, möchten wir dieses einfache Zeichen vorschlagen.

**Comment by dariok** [comment]
Die Expansionen können weiter so gekennzeichnet werden; eine weitere Kennzeichnung sollte nicht nötig sein.

**Comment by Marxistin** [comment]
Kann geschlossen werden
