### ISSUE TITLE
Intro werden nicht transformiert

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#204]
Sicher Fehler in meiner Formatierung, aber derzeit werden (meine) Einleitungen nicht transformiert. Ich hänge zwei an; wir können aber auch Montag Fehler klären.
[EE83Intro2018-11-02.docx](https://github.com/dariok/karlstadt-issues/files/2543128/EE83Intro2018-11-02.docx)
[EE81Intro2018-09-16.docx](https://github.com/dariok/karlstadt-issues/files/2543129/EE81Intro2018-09-16.docx)

**Comment by Wallsporn** [comment]
Die Fehler in der Transformation einfacher Textapparatnoten hängen mit den Aktualisierungen zusammen?
Vgl. EE83 Text
![grafik](https://user-images.githubusercontent.com/28565515/47925013-66d1a280-debd-11e8-9630-5dc71f873654.png)

**Comment by dariok** [comment]
Fehler behoben, beide Einleitungen sind hochgeladen.
