### ISSUE TITLE
KS_Kommentar prüfen

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#208]
LD, Anm. „afg“ („documentis 43“)

**Comment by dariok** [comment]
sic/@wit ausgeben

**Comment by dariok** [comment]
@stefaniasalvadori Bitte einmal in der LD prüfen, ob die Fälle mit KS Kommentar jetzt richtig angezeigt werden.

**Comment by stefaniasalvadori** [comment]
Ja, jetzt wird es richtig angezeigt! Danke!
(bis auf 2 Fälle - wahrscheinlich Formatierungsfehler - die schaue ich morgen genauer an)
