### ISSUE TITLE
Problemen mit dem Transformationsszenarios 

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#21]
Die Transformation von EE 103[=129] funktioniert nicht ganz. 
Wenn ich die Handschrift (Überschrift 2), [a:] (Sigel) und Titel (text) kodiere, bekomme ich diese Fehlermeldung:
![unbenannt](https://user-images.githubusercontent.com/28624747/27425320-5148b11e-5738-11e7-9105-cc841c84cf18.JPG)
Wenn ich die Handschrift raus nehme oder als Text kodiere, dann funktionier der Rest (Frühdrücke A bis D) ganz normal.
Hier auch die Word-Dateien mit Fehlermeldung, die ich hochgeladen habe:
[EE103_Intro_2017_6_22.docx](https://github.com/dariok/karlstadt-issues/files/1094173/EE103_Intro_2017_6_22.docx)

**Comment by dariok** [comment]
Funktioniert jetzt: http://dev2.hab.de/edoc/view.html?id=edoc_ed000240_103_introduction

**Comment by stefaniasalvadori** [comment]
Ja, aber mit Verdoppelung von Literatur und Editionen:
![unbenannt](https://user-images.githubusercontent.com/28624747/27433140-a42abd12-5753-11e7-8501-f1029d57e946.JPG)

**Comment by dariok** [comment]
Das habe ich korrigiert.
Kurzer Hinweis: Bei A und D war ein Problem im Impressum: Hinter dem Drucker war das Komma in der Klammer, weshalb das Impressum nicht ausgegeben wurde. Das habe ich vor dem Hochladen korrigiert.

**Comment by stefaniasalvadori** [comment]
Danke!
Das Komma muss ich auch in meiner Word-Datei nun korrigieren. 
Ist nun das Problem generell aufgelöst? Darf ich danach die Word-File nochmals hocladen oder lieber nicht?
