### ISSUE TITLE
Fehler in EE 81: Marginalien verschwunden, Worte verschwunden, fehlende Zentrierung

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#210]
-	Zentrierung der Anrede nicht ausgegeben
-	Marginalien verschwunden:
„Quibus nominibus ab adversariis impetatur, pro cuiusque libidine“
„Libertas Christiana quo evasit“ fehlt völlig
„Hodie in potestatem Papae et privilegia Rhoma'nae' eccle'siae' tamen graviter peccatur, in deum impune“ 
-	FN an Marginalie „Caietanus satis benignus Lutherii paedagogus Augustae.“ nicht ausgegeben bei Zeilenumbruch von "Augu|stae"
-	A4v Ger|manos, [meros blennones] <- letzteres verschwunden 
-	"Caie-tanis" <- Trennungstrich erhalten
-	Rho-ma[no]: <expan> nicht um ganzes Wort, sondern mit Trennung einsetzend, vermutlich weil am Zeilenanfang zudem Marginalie

**Comment by dariok** [comment]
Auch hier benötige ich die Word-Datei, um etwas sagen zu können.

**Comment by Wallsporn** [comment]
[EE81Text2018-09-16.docx](https://github.com/dariok/karlstadt-issues/files/2575813/EE81Text2018-09-16.docx)

**Comment by dariok** [comment]
Danke, schaue gleich rein.
