### ISSUE TITLE
freie Texte in Textapparatnoten nicht ausgegeben

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#211]
EE81 Text ANm. a und g
freie Texte in Textapparatnoten wie "verbessert für" nicht ausgegeben

![grafik](https://user-images.githubusercontent.com/28565515/48024835-f1c2cf00-e141-11e8-8959-3aee674a9bcd.png)
[EE83Text2018-11-02.docx](https://github.com/dariok/karlstadt-issues/files/2550502/EE83Text2018-11-02.docx)

**Comment by dariok** [comment]
Auch das sollte bereits erledigt sein.
