### ISSUE TITLE
Zusammenziehen von Wörtern EE 83

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#212]
EE83 Text
Petrus Burckhart zuammengezogen zu PetrusBurckhart (vermutlich wegen an <rs> anschließende Fußnoten)
![grafik](https://user-images.githubusercontent.com/28565515/48024916-3c444b80-e142-11e8-883a-134b892add43.png)

**Comment by dariok** [comment]
Das sollte durch die letzten Änderungen erledigt sein; bitte neu hochladen.
