### ISSUE TITLE
EE83 Intro Verweise auf Anmerkungen mit Fehlern

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#213]
Verweise auf andere Anmerkungen in Anm. 5 und 7 fehlerhaft
Bei Registermarkierung von "Kfst. Friedrich" unnötiges Spatium "Kfst . Friedrich" [daher hier Markierung von "Kfst." als Person herausgenommen]
![grafik](https://user-images.githubusercontent.com/28565515/48025176-f340c700-e142-11e8-8f04-a204026ff7f7.png)

**Comment by dariok** [comment]
Hm, Word speichert hier tatsächlich 6 einzelne Verweise ohne Ziel:

    <w:r>
					<w:t xml:space="preserve"> s. u. Anm. </w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="begin" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:instrText xml:space="preserve"> NOTEREF _Ref511739426 \h </w:instrText>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="separate" />
				</w:r>
				<w:r w:rsidR="004C1B70">
					<w:t>17</w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="end" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:t xml:space="preserve">, </w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="begin" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:instrText xml:space="preserve"> NOTEREF _Ref511739435 \h </w:instrText>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="separate" />
				</w:r>
				<w:r w:rsidR="004C1B70">
					<w:t>18</w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="end" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:t xml:space="preserve">, </w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="begin" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:instrText xml:space="preserve"> NOTEREF _Ref511739441 \h </w:instrText>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="separate" />
				</w:r>
				<w:r w:rsidR="004C1B70">
					<w:t>19</w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="end" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:t xml:space="preserve">, </w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="begin" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:instrText xml:space="preserve"> NOTEREF _Ref511739445 \h </w:instrText>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="separate" />
				</w:r>
				<w:r w:rsidR="004C1B70">
					<w:t>20</w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="end" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:t xml:space="preserve">, </w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="begin" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:instrText xml:space="preserve"> NOTEREF _Ref511739452 \h </w:instrText>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="separate" />
				</w:r>
				<w:r w:rsidR="004C1B70">
					<w:t>22</w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="end" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:t xml:space="preserve">, </w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="begin" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:instrText xml:space="preserve"> NOTEREF _Ref511739457 \h </w:instrText>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="separate" />
				</w:r>
				<w:r w:rsidR="004C1B70">
					<w:t>26</w:t>
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:fldChar w:fldCharType="end" />
				</w:r>
				<w:r w:rsidR="006F08E7">
					<w:t>#</w:t>
				</w:r>
				<w:r w:rsidR="00CA39D1">
					<w:t xml:space="preserve">; vgl. </w:t>
				</w:r>

Ich brauche die originale Word-Datei, um das nachvollziehen zu können.

**Comment by Wallsporn** [comment]
Habe noch einmal die Querverweise auf die Endnoten gelegt, da waren Fehler entstanden - wodurch auch immer (ist Word wirklich so instabil?)
[EE83Intro2018-11-02.docx](https://github.com/dariok/karlstadt-issues/files/2575827/EE83Intro2018-11-02.docx)

**Comment by dariok** [comment]
Mir ist aufgefallen, daß manche Dinge sich ändern, wenn man eine Datei mit verschiedenen Versionen von Word öffnet und wieder abspeichert. Leider konnte ich da noch kein System erkennen :(
Ich will versuchen, diese Fälle abzufangen, daß nicht diese unsinnigen Verweise entstehen.

**Comment by dariok** [comment]
So, das sollte jetzt auch wieder funktionieren.
Habe es gerade hochgeladen, bitte prüfen.
