### ISSUE TITLE
Bücher als Sigle

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#215]
Die wit „WA“ und wird nicht mit tiefgestelltem Rest ausgegeben.

@Wallsporn welche Sonderfälle gab es noch? EA?

**Comment by Wallsporn** [comment]
EA, Riederer, Kähler (ohne Probleme in EE 108), Enders

**Comment by dariok** [comment]
Die „langen“, also über 5 Zeichen, sollten kein Problem sein.
