### ISSUE TITLE
EE82 text kann nicht hochgeladen werden

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#218]
Die EE82 Text hatte ich gestern problemlos hochgeladen.
Nun funktioniert es nicht mehr - hier die Fehlermeldung:
![unbenannt](https://user-images.githubusercontent.com/28624747/48209144-b65c1680-e374-11e8-9bdc-6f1e93a6e4be.JPG)

Und hier die Word-Fassung:
[EE82text2018-11-7.docx](https://github.com/dariok/karlstadt-issues/files/2562383/EE82text2018-11-7.docx)

**Comment by dariok** [comment]
Bitte nochmal versuchen. In einer krit. Anmerkung ("- nach Abk.") das Ende als Kommentar formatieren, das führt sonst auch zu einem Fehler.

**Comment by stefaniasalvadori** [comment]
Es sieht so aus, als ob ich mich nicht mehr einloggen kann (in Google Chrome und Internet Explorer).
Ich trage user und password ein, werde aber nicht eingeloggt.
Morgen frage ich @timojanssentj und Harald, ob sie sich einloggen koennen.

**Comment by stefaniasalvadori** [comment]
Danke Dario, ich korrigiere.
Ich habe keine Ahnung, warum der Login bei mir nicht funktioniert.
Morgen versuche ich mit einem anderen PC

**Comment by Wallsporn** [comment]
Ja, auch bei mir funktioniert der Zugang gar nicht mehr: entweder blockiert er vollkommen die Anmeldung, als hätte ich mich nicht angemeldt oder ich bekommen eine Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/28565515/48319623-5bdee680-e610-11e8-858c-23b3434b4c5b.png)

**Comment by dariok** [comment]
Kann ich leider nicht nachvollziehen, das Login funktioniert bei mir. Liegt vmtl. am Browser-Cache; einmal komplett schließen und neu aufmachen sollte reichen, sonst den Cache leeren.

**Comment by stefaniasalvadori** [comment]
Ich habe gerade Cache+Chronologie entleert - es funktioniert nicht.
Auch wenn ich user+login eingebe, werde ich nicht eingeloggt. 
Auch auf PC und zweiten Laptop geht nicht.
Ich probiere später nochmals
Die Adresse ist jedoch dies hier, oder?
http://dev2.hab.de/edoc/query.html?query=scripts/xquery/convert.xql&ed=ed000240

**Comment by Wallsporn** [comment]
Ja, bei mir leider ebenso. Cache leere ich nach jeder Sitzung, bei mir genauso wie gestern: entweder gar keine Anzeige wie nicht angemeldet oder aber die obige Fehlermeldung.
Auch Timo kann sich nicht anmelden.
Ist es am besten, einen neuen Zugang zu schaffen?
Ansonsten Bitte an Dario: Schwierigkeiten treten auf, das passiert. Nur bitte kurz zurückmelden, ob Du zeitlich einschätzen kannst, wie es weitergeht. Wir waren ja auf sehr gutem Weg - jetzt holpert es etwas, aber wir kriegen das ja wohl hoffentlich alles hin. Und ja: we know you have a lot to do ...

**Comment by dariok** [comment]
Hm, Jemand hat den Benutzer gelöscht. Habe ihn jetzt neu erstellt und getestet; es sollte also wieder funktionieren

**Comment by stefaniasalvadori** [comment]
Ja! Ich kann mich einloggen! 
Fast geschafft - beim Hochladen der EE bekommen ich nun diese Fehlermeldung:

![cattura](https://user-images.githubusercontent.com/28624747/48349985-13621000-e686-11e8-9b58-5114fc5e109b.PNG)

**Comment by Wallsporn** [comment]
dito

**Comment by dariok** [comment]
Okay, das hing noch mit dem davor zusammen; müßte jetzt aber auch funktionieren.

**Comment by stefaniasalvadori** [comment]
Quasi!, ultimo sforzo:
hier die Fehlermeldung, die ich bekomme:
![cattura](https://user-images.githubusercontent.com/28624747/48354652-83769300-e692-11e8-8380-e61b15d7870e.PNG)

**Comment by dariok** [comment]
Okay, auch das sollte jetzt wieder gehen.

**Comment by Wallsporn** [comment]
Bei mir leider noch immer kein "appropriate access" - ich versuche es morgen
![grafik](https://user-images.githubusercontent.com/28565515/48358895-04865800-e69c-11e8-849b-07460c5040b0.png)

**Comment by stefaniasalvadori** [comment]
Auch bei mir genau so, wie bei Harald: I do not have write access on that resource
Ich hatte extra laptop heruntergefahren, cache entleert etc - es funktioniert noch nicht

**Comment by dariok** [comment]
*s* okay, nochmal probieren

**Comment by dariok** [comment]
Das kann ich leider nicht nachvollziehen; ich habe mich als karlstadt eingeloggt und kann problemlos schreiben.
Die Meldung zur Zeile 129 paßt auch nicht, diese Zeile gibt es im Skript nicht mehr. Das sieht also mehr nach einem Fehler im Browser aus.

**Comment by stefaniasalvadori** [comment]
Ich habe gerade chronologie und cache entleert. Es klappt nicht - wie gestern abend.
Keine Ahnung.
Ich versuche heute nachmittagas mit einem anderen PC

**Comment by dariok** [comment]
Sehr seltsam... Ich baue gerade die komplette Anmeldung neu auf, das dauert noch ein paar Augenblicke.

**Comment by dariok** [comment]
Bitte noch einmal versuchen. Bei mir klappt es weiterhin.

**Comment by stefaniasalvadori** [comment]
Wenn ich nun das Upload-Formular eingebe, bekomme ich so etwas:
![cattura](https://user-images.githubusercontent.com/28624747/48414111-0eff2b00-e74a-11e8-8b6b-e5797241079c.PNG)

Ich habe extra nun mit Internet Exploren (nicht mit Chrome versucht)

**Comment by dariok** [comment]
Ich kann gerade nicht die ganze Adresse sehen – steht am Ende noch `&ed=ed000240`?

**Comment by stefaniasalvadori** [comment]
hier die Adresse
http://dev2.hab.de/edoc/query.html?query=scripts/xquery/convert.xql&edition=ed000240#

**Comment by dariok** [comment]
Bitte einmal mit http://dev2.hab.de/edoc/query.html?query=scripts/xquery/convert.xql&ed=ed000240 versuchen

**Comment by stefaniasalvadori** [comment]
Ja, nun ist richtig!
Ich versuche mich zu loggen und eine EE hochzuladen, ok?

**Comment by stefaniasalvadori** [comment]
Einloggen darf ich, nur bei Hochladen einer EE lande ich hier:
![cattura](https://user-images.githubusercontent.com/28624747/48417271-a4062200-e752-11e8-88ac-912fa14c5434.PNG)

**Comment by Wallsporn** [comment]
Ja, bei mir dieselbe Oberfläche beim Hochladen der Textdateien - Intro dagegen finkioniert nun

**Comment by dariok** [comment]
Okay, neuer Versuch, bitte nochmal ein transcript hochladen.

**Comment by stefaniasalvadori** [comment]
Klappt nicht -- ich lande nochmals bei Wien-Diarium und wird ein ERROR wie oben angezeigt

**Comment by dariok** [comment]
Wenn es jetzt nicht klappt, dann muß ich die Unterscheidung Intro/Transcript aus dem Namen der Datei holen... Bitte nochmal versuchen.

**Comment by stefaniasalvadori** [comment]
Es sollte klappen!!!!
Was in meiner EE82 falsch ist, prüfe ich später, aber sie wird (wenigstens den Titel) transformiert!
Ich melde mich später, danke nochmals!

![cattura](https://user-images.githubusercontent.com/28624747/48421324-89d14180-e75c-11e8-9417-d5be9dcecd4d.PNG)

**Comment by dariok** [comment]
Hm, versuch einmal, hinter „Text“ noch ein leere Zeile einzufügen.

**Comment by stefaniasalvadori** [comment]
Ein leere Zeile sthet schon hinter "Text"
[EE82text2018-11-11.docx](https://github.com/dariok/karlstadt-issues/files/2576884/EE82text2018-11-11.docx)

**Comment by stefaniasalvadori** [comment]
Und es sieht so aus, als ob die EE am falschen Platz hochgeladen/gespeichert wird:
![cattura](https://user-images.githubusercontent.com/28624747/48424405-e20b4200-e762-11e8-87c1-253f2b2b9b62.PNG)

**Comment by dariok** [comment]
Irgendwas speichert Word doch in der leeren Zeile.
Ich habe jetzt mal wieder was geändert; soweit ich es sehe, ergibt das keine Probleme, hoffe, daß das auch so bleibt.
Bei Anm. ax (vmtl. xx in Word) den Teil „- nach Abk. in B1, B2“ als Kommentar formatieren.

**Comment by stefaniasalvadori** [comment]
Quite strange...
Ich habe mehrmals alle Formatierungen in der leeren Zeilen geloescht.

Wenn ich den Titel als "EE Titel" formatiere, wird nur den TItel transformiert:
![cattura](https://user-images.githubusercontent.com/28624747/48430001-978fc280-e76e-11e8-8196-39b2268ecd21.PNG)

Wenn ich "EE 82 [=Nr. 105]" als "KS Ueberschrift" formatiere, ist den Text (nicht aber den Titel) transformiert:
![cattura](https://user-images.githubusercontent.com/28624747/48430265-33b9c980-e76f-11e8-8b9a-7c27e0c80e0f.PNG)

**Comment by dariok** [comment]
Der Titel muß EETitel bleiben.
Füge aber bitte eine weitere leere Zeile hinter "Titel" ein.

**Comment by dariok** [comment]
Ich habe gerade in der Datei die Zeilen hinter Text und vor A1r gelöscht, eine Zeile eingefügt und dann dort die Formatierungen gelöscht. Die Transformation klappt problemlos:
http://dev2.hab.de/edoc/view.html?id=edoc_ed000240_082_transcript

**Comment by stefaniasalvadori** [comment]
Ok - ich muss immer wieder F5 drucken
Als ich Dein Link abgerufen hatte, hatte ich nur den Titel
F5 --> full text wurde angezeigt.
Dass muss ich mir merken

**Comment by stefaniasalvadori** [comment]
Kannst Du Dario bitte alle hochgeladene files von EE82 im dev2 löschen?

Ich kann weiterhin die EE nich hochladen - weder die Intro noch den Text.
Alle andere EE (EE88A, 92, 100,101,102) habe ich problemlos hochgeladen (nur ein paar Details sollen verbessert werden, jedoch auch später)

EE82/KGK 105 taucht verdoppelt auf - in der Navigationliste der Dokumente und im Hauptmenu (neben Biblio und Dokumente).
Das Hochladen der EE82_intro dauert lange und wird falsch angezeigt
EE82, wie heute, kein chance, obwohl ich "die Zeilen hinter Text und vor A1r gelöscht, eine Zeile eingefügt und dann dort die Formatierungen gelöscht."

Ich versuche evtl morgen nochmals, sonst: pace! 
(Vielleicht die Tatsache, dass ich mit meinem Laptop arbeite, bereitet Probleme?)

**Comment by dariok** [comment]
Von EE082 werden mir sowohl die Einleitung als auch das transcript angezeigt, hochgeladen um 23:00 bzw. 23:15 - das muß von Dir gewesen sein, da ich zu der Zeit nichts gemacht habe, scheint also auch von Dir aus zu funktionieren.

**Comment by dariok** [comment]
Den überzähligen Eintrag im Inhaltsverzeichnis habe ich entfernt.

---

Was mir noch einfällt: Ist das Word auf Deinem Laptop auf Italienisch eingestellt? Vielleicht überschreibt Word dort "Überschrift1" (für "Text" oder "Einleitung") mit "titolo1"? Das würde dazu führen, daß zwar der Titel richtig umgesetzt wird, aber der Text fehlt.

**Comment by stefaniasalvadori** [comment]
Fatto - funziona!
text vollständig transformiert!
Dario Santo Subito! 
Merci nochmals!

**Comment by dariok** [comment]
Ich bin froh, daß wir dieses Rätsel gelöst haben :)

**Comment by stefaniasalvadori** [comment]
Ich auch! 
Danke nochmals!
