### ISSUE TITLE
bibliography lässt sich nicht hochladen

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#219]
Ich kann die "bibliography" nicht (mehr) hochladen. Bisher lief es über "Datei speichern unter URL..." Am Freitag hat es noch funktioniert. Als Ziel habe ich bisher diese URL benutzt:

oxygen:/eXist-db%20dev2.hab.de$eXist-db%20dev2.hab.de/db/edoc/ed000240/register/bibliography.xml

Ich erhalte folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/23031457/48350993-24f8e700-e689-11e8-8811-a653bdfc022b.png)

**Comment by dariok** [comment]
Auch das liegt am gelöschten und wiederhergestellten Benutzer.
Bitte nochmal versuchen.

**Comment by Marxistin** [comment]
Gleiche Fehlermeldung trotz geleertem Cache.

**Comment by dariok** [comment]
Habe einmal alle Berechtigungen gelöscht und neu gesetzt; bitte noch einmal versuchen.

**Comment by Marxistin** [comment]
Jetzt funktioniert es. Super!

**Comment by dariok** [comment]
Hervorragend :)
