### ISSUE TITLE
Transformation - Untertitel 

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#22]
In EE 82 [=Nr. 104] ist der Untertitel (und die Zeite Ort, Datum) nicht ausgegeben.
Das liegt wahrscheinlich auf dem Umbruch zwischen Titel und Untertitel
![unbenannt](https://user-images.githubusercontent.com/28624747/27492003-df6ea4b4-5844-11e7-8569-d65b4a373865.JPG)

Ähnlich auch in EE81 [Nr.136]
![unbenanntee81](https://user-images.githubusercontent.com/28624747/27492060-1327c682-5845-11e7-8f42-10b9780ee378.JPG)

**Comment by Marxistin** [comment]
Hier sollte zwischen Ober- und Untertitel ein Zeilenumbruch generiert werden.

**Comment by stefaniasalvadori** [comment]
Hier die aktuellen Word-Datei von
EE81 = KGK 136
EE82 = KGK 104
[EE-81-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1418651/EE-81-Uberlieferung.docx)

**Comment by stefaniasalvadori** [comment]
[EE82_Intro_2017_10_26.docx](https://github.com/dariok/karlstadt-issues/files/1418656/EE82_Intro_2017_10_26.docx)
