### ISSUE TITLE
Transformation der Intro gestört

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#220]
Die Transformationen der Introductions sind in der Hinsichtgestört, dass abgesehen von Titel dere gesamte Inhalt nicht übernommen wird.
![grafik](https://user-images.githubusercontent.com/28565515/48408306-503b0f00-e739-11e8-894f-0c73129c1195.png)

**Comment by dariok** [comment]
Das schaue ich mir sofort an.

**Comment by dariok** [comment]
083 intro sieht auf den ersten Blick gut aus (bis auf die Verweise), der Text fehlt aber... Kannst Du mir den bitte einmal anhängen?

**Comment by Wallsporn** [comment]
[EE83Intro2018-11-02.docx](https://github.com/dariok/karlstadt-issues/files/2575932/EE83Intro2018-11-02.docx)
[EE81Intro2018-09-16.docx](https://github.com/dariok/karlstadt-issues/files/2575934/EE81Intro2018-09-16.docx)

**Comment by dariok** [comment]
Okay, die Erkennung von Intro oder Transkript sollte jetzt besser funktionieren.
Bitte für diese beiden EE die Transkripte noch einmal hochladen.
