### ISSUE TITLE
EE82 Intro falsch angezeigt

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#222]
Die EE82 Intro wird falsch angezeigt.
Ich habe die Datei hochgeladen, die ich am 7. November problemlos transformieren könnte.
Die Xml sieht in Ordnung aus
![cattura](https://user-images.githubusercontent.com/28624747/48488912-198cf380-e822-11e8-89cd-9f07c61f8c5a.PNG)

Ich beobachte: Die Intro (Word Fassung) ist sehr schwer (2,52MB!) - keine Ahnung warum

**Comment by dariok** [comment]
Kannst Du mir die Datei anhängen oder zumailen, bitte?

**Comment by stefaniasalvadori** [comment]
Hier die Datei, die ich letzte Woche hochgeladen hatte:
[EE82intro2018-11-7.docx](https://github.com/dariok/karlstadt-issues/files/2581167/EE82intro2018-11-7.docx)

**Comment by dariok** [comment]
Danke, ich schaue gleich rein

**Comment by dariok** [comment]
Schaut auch jetzt gut aus.

**Comment by stefaniasalvadori** [comment]
Ja, jetzt sieht es gut aus. Danke!
