### ISSUE TITLE
Kursivierungen in Sachanmerkunken

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#224]
Ich signalisiere folgende Störung - kann aber auch sein, dass sie mit der PDF-Herstellung zu tun hat.

Kursivierungen in den Sachanmerkungen werden am Ende des Text wiederholt:

Am Ende der Transkription:
![unbenannt](https://user-images.githubusercontent.com/28624747/48702622-a3a5d500-ebf1-11e8-844d-e35e4a03e697.JPG)

in Anm (die ersten 2 Beispiele, von 3):
![unbenannt](https://user-images.githubusercontent.com/28624747/48702645-b3bdb480-ebf1-11e8-8c46-f8dc7eb6fec2.JPG)

![unbenannt](https://user-images.githubusercontent.com/28624747/48702671-ca640b80-ebf1-11e8-9a5c-9b1be2072499.JPG)

**Comment by timojanssentj** [comment]
Ähnliches geschieht auch mit Formatierungen im Fußnotentext.
![ee79_storung](https://user-images.githubusercontent.com/38648721/48760775-3b192f80-eca7-11e8-8ae3-a6e8977837a1.PNG)

**Comment by Wallsporn** [comment]
EE83 ebenso
![grafik](https://user-images.githubusercontent.com/28565515/48778344-366b7000-ecd5-11e8-9590-f1388020997f.png)

**Comment by dariok** [comment]
Mit den aktuellen Tranformationen kann ich das tatsächlich nicht nachvollziehen.
Ich korrigiere diese Fälle jetzt manuell und lade lade außerdem alle Transformationen noch einmal frisch hoch – vielleicht hatte ich hier eine vergessen.
Sagt mir bitte gleich bescheid, wenn es nach dem Hochladen auftritt und hängt mir gleich die Datei dazu an.
