### ISSUE TITLE
EE78 Epitome Handhabung von Text und Randglossen

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#225]
Hei! Der Text von der Epitome inklusive Randglossen wurde von mir nun formatiert. Es stellt sich nun die Frage, wie diese am Besten hochgeladen werden soll: entweder als eine zusammenhängende oder zwei einzelne Dateien (Text und Randglossen getrennt). Zur Veranschaulichung hänge ich die Datei mal dran.
[EE78_text&RdGl_2018-10-24.docx](https://github.com/dariok/karlstadt-issues/files/2595670/EE78_text.RdGl_2018-10-24.docx)

**Comment by dariok** [comment]
Hier werde ich noch ein wenig experimentieren müssen.
In jedem Fall wird hier Handarbeit anfallen.
