### ISSUE TITLE
EE 77 und EE 85 text

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#228]
Es erfolgt keine Texttransformation, d.h. er erkennt die Einheit ab "Text" in Überschrift 1 formatiert gar nicht. 
![ee85 storung](https://user-images.githubusercontent.com/38648721/48791588-53626c00-ecf2-11e8-9d09-eb01629fc167.PNG)

**Comment by dariok** [comment]
Der Text wurde nicht als Text erkannt, weil keine Textkritik vorhanden war (was das Unterscheidungskriterium ist); ich habe das jetzt noch erweitert.

Ich habe die Einleitungen wiederhergestellt und die Texte aufgespielt.

Die Datei von EE085-Text enthält übrigens nur „jkhjk“.

**Comment by Wallsporn** [comment]
Ok, wir prüfen morgen. Nachdem wir verschiedene Upload-Versuche durchprobiert hatten, versuchten wirs es mit einer quasi leeren Datei, daher der kryptische Inhalt - der sich uns nicht einmal in der XML zeigte. Wenn es erledigt ist, umso besser.

**Comment by timojanssentj** [comment]
Nun kollidieren wahrscheinlich die beiden Dateien miteinander. Ich habe versucht, die eigentliche Datei hochzuladen und es kam das hier: 

![ee85](https://user-images.githubusercontent.com/38648721/48890976-8dd72080-ee3a-11e8-86b0-839a944a35a9.PNG)

**Comment by dariok** [comment]
Ich habe die doppelte mal entfernt; bitte noch einmal hochladen

**Comment by timojanssentj** [comment]
Geht leider immer noch nicht. Selbes Problem auch bei EE 93 Text

**Comment by dariok** [comment]
Bitte noch einmal probieren. Leider habe ich gerade keine wirklich stabile Internet-Verbindung; es kann sein, daß wir es ein paar Mal versuchen müssen

**Comment by timojanssentj** [comment]
EE 77 geht nun! EE 85 leider noch nicht.

**Comment by dariok** [comment]
Okay, ich habe es eingrenzen können, danke

**Comment by dariok** [comment]
Beim Speichern wurde die Nr. der EE nicht gefunden; ich hoffe, daß es jetzt klappt

**Comment by timojanssentj** [comment]
Das Hochladen funktioniert nun. Leider nimmt er die Zeilen nach "Text" nicht auf.
![unbenannt](https://user-images.githubusercontent.com/38648721/48895410-4d30d480-ee45-11e8-9987-e335c9799d50.PNG)

**Comment by dariok** [comment]
Bitte noch einmal versuchen

**Comment by timojanssentj** [comment]
Es hat funktioniert! Danke dir!

**Comment by dariok** [comment]
Super :)
