### ISSUE TITLE
EE81 Marginalie: Verdoppelungen von Teilen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#230]
Verdoppelung von Teilen der Marginalie (neu beim letzten Upload)
![grafik](https://user-images.githubusercontent.com/28565515/48893563-ee695c00-ee40-11e8-8ce9-624f84957cf0.png)

**Comment by dariok** [comment]
Das Problem hier sind die Zeilenumrüch in den Marginalien. Ich hoffe, daß ich das jetzt umgehen kann; sonst bitte versuchen, in den Marginalien keine Umbrüche zu benutzen

**Comment by dariok** [comment]
Habe ich in die Liste überführt und wird dann bei der Erstellung der Druckfahne geprüft
