### ISSUE TITLE
Intro bibl. Angaben und Kursivierungen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#232]
In HTML der Intros scheinen grundsätzlich Kursivierungen nicht wiedergegeben und bibliographische Angaben nicht hinterlegt zu werden. In XML ok

**Comment by dariok** [comment]
Die Kursivierungen sollten nicht einfach als hi umgesetzt werden; das ist jetzt der Fall und bei neuem Hochladen sollte das passen.
bibl dann morgen.

**Comment by dariok** [comment]
Auch bibl sollte jetzt in den Einleitungen besser verarbeitet werden. Nach dem nächsten Upload sollte jetzt alles passen.
