### ISSUE TITLE
EE 110 Textapparat Transformationsprobleme

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#235]
Textapparatprobleme:
1. Note cs "vom Editor verbessert für" wird zu "vom Editor korrigiert für:"
[Erste Variante in KGK I verwendet, grudnsätzlich keine Doppelpunkte für editorische Anweisungen im Apparat]
2. Note y: "B; hinzugefügt Korrekturverzeichnis ...." - nicht transformiert
3. Note bx: "handschriftlich hinzugefügt A5..." - nicht transformiert
4. Note co-cr: "fehlt A,B; handschriftlich hinzugefügt A5..." - nicht transformiert
5. Note af (Word ff) Text aus Apparat in obigen Text gezogen, s.u.
![grafik](https://user-images.githubusercontent.com/28565515/48898455-1eb6f780-ee4d-11e8-8e8f-90fdee93184b.png)

**Comment by Wallsporn** [comment]
Es sollte nicht mehr so grundsätzlich am Textapparat gearbeitet werden, dass neue Fehler entstehen könnten. Daher schlage ich vor, dass wir auch gerne über eine Umstellung der Formulierungen im Apparat nachdenken können, die Probleme verursachen.

**Comment by dariok** [comment]
zu 1.: Es wird hier ja nicht der Text übernommen, sondern die dazugehörige Kodierung mit choice, sic und corr erstellt. Ich habe die Ausgabe davon jetzt auf „verbessert“ geändert.

**Comment by dariok** [comment]
zu 2.: diese ganze Anm. ist als KSKommentar formatiert; einfach ohne Zeichenvorlage kursiv und alles wird ausgegeben.

**Comment by dariok** [comment]
Auch die Fälle in 3 und 4 sind jeweils komplett als KSKommentar formatiert.

**Comment by dariok** [comment]
In Fall 5 ist der hintere Teil als KSKommentar formatiert.
