### ISSUE TITLE
Orts/PersonenRegister

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#236]
@dariok 
kannst Du bitte uns nochmals erklären, wie wir das Orts/PersonenRegister in Dev2 erweitern können?
Dev 2, Ordner e240?
Vor allem: Wie sollen wir die <expan> in Namen angeben? einfach Carolosta'dius'?

Bei Korrekturlesen möchte ich eine Liste der Varianten der Namen in meinen EE erstellen, damit sie mit GND-Nr verknüpft sind und die Nachkodierung-Arbeit reduziert werden kann..

**Comment by dariok** [comment]
Auf dev2, Ordner `/db/edoc/ed000240/register`: hier befinden sich die Register.

In einem Eintrag z.B. zu einer Person einfach hinter den vorhandenen `persName` einfügen (z.B. Luther):

    <persName type="vorl">Martino Luthero</persName>

Expansionszeichen nicht übernehmen: diese sind bereits durch die Kodierung ersetzt, sodaß, wenn es richtig kodiert wurde, „Martino Luth'ero'“ auch hiervon erfaßt wird.

**Comment by stefaniasalvadori** [comment]
Grazie mille!
Ich teste in den kommenden Tagen
