### ISSUE TITLE
EE 100 - Transformation - Eckige Klammern im Titel (longtitle)

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#24]
Bei der Transformation von EE 100 [=Nr.126] tauchen Probleme auf, die auch in anderen EE auftauchen.

1. Ein Kommata ist am Ende des Titels authomatisch ergänzt

1.  In den verschollenen EE die ganze Datierung soll in eckigen Klammern stehen. Hier ist eine Klammer (nach "Wittenberg") zu viel.

![unbenanntee100](https://user-images.githubusercontent.com/28624747/27492662-4d8d42aa-5847-11e7-8e05-47927cb7a5b8.JPG)

**Comment by Marxistin** [comment]
Komma ist gelöscht. 
Eckige Klammer hinter Wittenberg weiterhin vorhanden

**Comment by dariok** [comment]
Hier benötige ich eine aktuelle Word-Datei, um das Problem zu testen; danke.

**Comment by stefaniasalvadori** [comment]
Hier die Word-Datei:

[EE 100_Intro_2017_6_7.docx](https://github.com/dariok/karlstadt-issues/files/1381871/EE.100_Intro_2017_6_7.docx)

**Comment by dariok** [comment]
merci vielmol

**Comment by dariok** [comment]
[EE.100_Intro_2017_6_7.docx](https://github.com/dariok/karlstadt-issues/files/1412299/EE.100_Intro_2017_6_7.docx)

Durch die Kommata in der Signatur kann die Reihenfolge nicht korrekt ausgelesen werden. Alternativ müßten sonst die Teile der Signatur (Institution, Signatur, Seiten) durch Semikolon statt Komma voneinander getrennt werden.
