### ISSUE TITLE
Personen- und Ortregister - Referenzierung 

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#240]
Hallo @dariok wir benötigen ein paar Infos zum Personenregister:

1) Müssen alle Personen-Namen in XML richtig referenziert sein, **bevor** Du die endugültige Druck-PDF via LaTeX generiert? Wenn ich richtig verstehe, die authomatische Referenzierung erfolgt (wenn die Namen-Varianten im Register eingetragen sind) beim Hochladen. Das bedeutet, wenn wir Dir grünes Licht geben, um die PDF zu herstellen, dürfen wir die Word-Dateien nicht mehr hochladen - deshalb sollte die Referenzierung schon erledigt sein. Oder verstehe ich falsch und wir können nachher die Personennamen referenzieren?

2) Was sollen wir mit den Namen machen, die in Personenregister KGK I nicht drin waren? Sollen wir die HAB abwarten? Oder selbst diese Namen ins Register eintragen?
Wenn wir das selber kodieren müssen, reichen die Grundinformationen, Name + GND Nummer zur referenzierung? 
Bitte lass uns wissen, was es (vor allem aus zeitökonomischen Gründen) sinnvoller wäre

3) Ich bearbeiete momentan alle Namen und Namen-Varianten in meinen EE. Die kann ich Anfang nächster Woche in XML-Register eintragen. Danach lade ich die EE nochmals hoch (bin gerade auch bein Hochladen - einzelne Probleme signalisiere ich in enstprechenden Issues). Ab Mitte nächster Woche werden alle Korrektuern und Nachkorierungen in meinen EE nur in XML eingetragen. Soll ich auch Ort-Register parallel bearbeiten? Wie?

**Comment by dariok** [comment]
Hallo Stefania,

ad 1) vor der endgültigen PDF müssen die Personennamen referenziert sein, denn hieraus wird auch das Register erstellt. Das muß aber nicht zwingend in der Word-Datei passieren, sondern kann auch direkt in der XML geschehen. Dazu sind alle Stellen, an denen eine Person oder ein Ort markiert, aber noch nicht referenziert ist, mit einer „TODO“-Markierung versehen, die in Oxygen als blaue Marke angezeigt wird.
Wir müssen einen Zeitpunkt festlegen, ab dem wir die Dateien (zumindest für den Druck) nicht mehr verändern. 

ad 2) Fehlende Namen sollten ins Register eingetragen werden. Wichtig ist hierbei eigentlich nur die Ansetzung des Namens (mit `surname`, `forename`, `nameLink`, `addName`; dazu gibt es auch eine Seite im Wiki, die ich ggf. nochmal überarbeite). Wenn die GND oder andere Daten schnell gefunden sind, kann man sie eintragen, aber auch das ist nicht zwingend wichtig für die Registererstellung und läßt sich hervorragend später erledigen.

ad 3) Im Ortsregister ist es ähnlich wie bei den Personen – hier kannst Du die Formen als `placeName type="vorl"` hinterlegen (ein Beispiel habe ich bei Leipzig schon eingetragen).

**Comment by stefaniasalvadori** [comment]
Hallo Dario,
danke für die ausführliche Antwort, die mir sehr hilft!

ad 1) ja, sicher können die Namen auch in XML referenziert werden, aber die Zeit ist m.E. kurz und je mehr wir die Namen in Word referenzieren können, desto weniger müssen wir nachkodieren. Wenn der Band KGK II Ende März/Anfang April ins Druk gehen muss, mussen wir bald die endgültigen Dateien hochladen und nicht mehr verändern, damit Du an die Druck-PDF arbeiten kannst. Vielleicht könntest Du uns einen Zeitpunkt nennen? Das wäre vielleicht am besten.

ad 2) ok! ich versuche die neue Namen ins Register einzutragen. Kannst Du bitte heute oder morgen ein Back-Up machen? Es wäre vielleicht wünschwert

ad 3) ok - ich schaue mir an, merci

**Comment by dariok** [comment]
Wir sollten bis Ende Januar die Texte so weit wie möglich fertig haben. Einzelne können wir sicher ein paar Tage nach hinten verschieben, aber ich sollte Anfang Februar anfangen, zu setzen, damit für die Fahnenkorrektur genug Zeit bleibt.

Ein Backup des Ortsregisters habe ich schon erstellt, Du kannst jederzeit anfangen.

**Comment by stefaniasalvadori** [comment]
Ok, perfetto! Danke!

**Comment by stefaniasalvadori** [comment]
Für neue Personennamen, ist diese Grundkodierung (als Beispiel) ausreichend:

<person xml:id=“Johann Kochel“>
<persName>
<forename>Johann</forename>
<surname>Kochel</surname>
</persName>
<idno type=“url“>http://d-nb.info/gnd/140844333</idno>
</person>

**Comment by dariok** [comment]
Ja, das reicht völlig aus.
