### ISSUE TITLE
EE101 - KGK 129 Text - Zeileumbruch komisch angezeigt

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#241]
Die Transformation der Einheiten klappt fast immer problemlos - danke @dariok nochmals!!!

Ein Problem habe ich bei Zeileumbruch des Texts EE101/KGK 129 in der Online Edition (Umbruch auch Mitte in der Zeile)

Dies hier sollte in einer Zeile stehen (und das Problem betrifft die ganze EE)
![cattura](https://user-images.githubusercontent.com/28624747/50600691-32289a00-0eb2-11e9-92f8-c36083549525.PNG)

Und hier die Word Datei
[EE101text2019-1-1.docx](https://github.com/dariok/karlstadt-issues/files/2721238/EE101text2019-1-1.docx)

**Comment by stefaniasalvadori** [comment]
Es kann sein, dass ich was falsch formatiert habe....
Ich prüfe die EE sofort und melde mich in Kurze

**Comment by dariok** [comment]
Nein, das ist eher nicht Dein Fehler. Das Skript geht davon aus, daß die Schlußformeln immer ein eigener Absatz sind, daher ist hier der ganze Text als `closer` formatiert.

**Comment by stefaniasalvadori** [comment]
Ja, in der Tat. Das Problem liegt daran, dass die Schlussformeln in der Mitte der vorletzten Zeile anfängt. Wenn ich auch einen Absatz-Zeichen einfüge, wir den ganzen Text als closer formatiert.
Was ist D.E sinnvoller?
a) in Word die ganze EE als KS Text formatieren und die Schlussformeln erst danach in XML enstprechend kodieren?
b) in Word die Schlussformel formatieren und in XML den Text nachkodieren. 
Mir ist es egal - you decide!

**Comment by dariok** [comment]
Ich würde die Schlußformel erst später im XML markieren, das ist die schnellste und einfachste Lösung.

**Comment by stefaniasalvadori** [comment]
Oro benon!
Dann ist die EE schon richtig formatiert und hochgeladen. Danke nochmals!
