### ISSUE TITLE
EE103/KGK 131 - Text - Probleme bei der Transformation

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#242]
Ich kann die EE103/KGK 131 nicht transformieren. Ich habe heute Stunden lang versucht.... I give up

Ich vermute, irgendetwas in der Referenzierung der Namen klappt nicht. Hier die Fehlermeldung:

![cattura](https://user-images.githubusercontent.com/28624747/50600885-ce52a100-0eb2-11e9-8113-fce285d5220a.PNG)

Hier die Word-Fassung (die Namen-Varianten dieser EE habe ich ins XML-Register noch NICHT eingetragen)
[EE103text2019-1-1.docx](https://github.com/dariok/karlstadt-issues/files/2721245/EE103text2019-1-1.docx)

**Comment by dariok** [comment]
Ja, das kann an den Namen liegen. Ich schaue da später nochmal detailliert rein.

**Comment by dariok** [comment]
Es gibt zwei problematische textkrit. Anm., einmal zu „ludibrium.“, die andere hat „cernicem” im Text.
Bei der ersten ist das Problem die Formulierung „von ... bis...“, das gibt durcheinander.
Bei der zweiten muß ich schauen.

Ich habe das Skript aber so angepaßt, daß in diesen Fällen die Transformation weiterläuft, die Dtei ist jetzt online.

**Comment by stefaniasalvadori** [comment]
Danke Dario.
Ich aktualisiere die Online Version, mit der ich seit ein paar Stunden arbeite. 
Und schaue mir die zwei Stellen, die Du erwähnst.

**Comment by stefaniasalvadori** [comment]
Die erste Stelle: "zu „ludibrium.“

Es war KS Zwischenüberschrift + textkrit. Anmerkung über mehrere Wörter.

Nun ist die Zeile einfach als Zwischenüberschrift. Die Anm. werde ich nachkodieren.

Ob es klappt, weiss ich noch nicht. Ich lade die EE am Donnerstag nochmals hoch.

**Comment by stefaniasalvadori** [comment]
Erstmal - die Transformation klappt nun WUNDERBAR - @dariok danke! 

Es gibt nur layout Details, die verbessert werden müssen, ich weiss es aber nicht, ob es an *Word Formatierung oder *XML Transformation oder *HTML/PDF Anpassung.
Und zwar Stelle wie:
(in Word)
![unbenannt](https://user-images.githubusercontent.com/28624747/50971611-b3041900-14e4-11e9-839f-b1463e95c327.JPG)

Sie sind in HTML und PDF folgendermasse (text "recipere" vor a1 fehlt) angezeigt:
![unbenannt](https://user-images.githubusercontent.com/28624747/50971736-0fffcf00-14e5-11e9-9800-b75e3cc77b30.JPG)


![unbenannt](https://user-images.githubusercontent.com/28624747/50971761-1f7f1800-14e5-11e9-8810-58920bdcf2a5.JPG)

Die XML (aus der Online Version) sieht aber richtig aus...:
![unbenannt](https://user-images.githubusercontent.com/28624747/50971663-e050c700-14e4-11e9-837c-8822ebdeab31.JPG)


Hast Du @dariok eine Idee, woran es liegt? Formatierung?

**Comment by dariok** [comment]
Die Anzeige dieser Variante sollte jetzt stimmen. Ich habe das auch für TeX umgesetzt, bei der nächsten PDF ist das dann also auch korrigiert.

**Comment by stefaniasalvadori** [comment]
Grandioso! Es klappt! Merci vielmal!

**Comment by dariok** [comment]
Super :)
