### ISSUE TITLE
EE104/KGK 132 - Text mit Beilagen

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#243]
Die Transformation des Texts klappt. Die Einheit hat aber 2 Beilagen die ich einfach als Text formatiert habe.
Diese EE muss ich nachkodieren - Das mache ich nächste Woche, wenn die Personen referenziert sind und die Word-Fassung nicht mehr hochgeladen wird.

@dariok kannst Du bitte mir sagen, wie ich die Beilagen kodieren muss.
Oder kannst Du mir die XML einer EE mit Beilagen aus KGK I, damit ich mich orientieren kann?

Danke im Voraus!

**Comment by dariok** [comment]
Ich muß selbst nochmal im Wiki nachschauen – ich meine, es gibt dafür eine eigene `div type="beilage"` – aber ich bin nicht ganz sicher.

**Comment by dariok** [comment]
Ich habe das Wiki hierfür gerade überarbeitet

**Comment by stefaniasalvadori** [comment]
Hallo Dario,
danke!
Das schaue mir sofor an!
