### ISSUE TITLE
Hochgeladene EE für "schnelle" PDF

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#244]
Hier meine EE (Korrekturen HB und AZ schon eingearbeitet - Korrekturen TK nächste Woche einzuarbeiten oder zu nachkodieren), die ich Hochgeladen habe und zur Herstellung einer schnellen "ArbeitsPDF" zur Verfügung stehen.
@dariok wir können die PDF Herstellung sofort testen oder bis nächste Woche (wann ich nochmals meine EE hochladen will, damit die Personennamen referenziert werden). 
Lass uns einfach wissen, was Du für sinnvoller hältst

**- EE82 / KGK 105**
- [x] Intro
- [x] Text
**- EE92 / KGK 117**
- [x] Intro
- [x] Text
**- EE100 / KGK 128 (verschollen)**
- [x] intro
**- EE101 / KGK 129**
- [x] Intro
- [x] Text --> Achtung: Schlussformel muss nachkodiert werden
**- EE102 / KGK 130**
- [x] Intro
- [x] Text
**- EE103 / KGK 131**
- [x] Intro
Achtung --> Text kann nicht transformiert werden (siehe #242 )
**- EE104 / KGK 132**
- [x] Intro
- [x] Text ---> Achtung: Text mit Beilagen, muss nachkodiert werden (siehe #243 )
**- EE106 / KGK 134**
- [x] Intro
Achtung - Transformation des Text noch problematisch - Weitere Details mit Editoren zu besprechen
**- EE107 / KGK 135**
- [x] Intro 
- [x] Text

**Comment by dariok** [comment]
Okay, dann erstelle ich hieraus eine Vorschau-PDF für's Wochenende

**Comment by Wallsporn** [comment]
Von meiner Seite:
- EE81
Text
Intro
- EE83
Text
Intro
- EE108
Text
Intro

Ende nächster Woche EE110

**Comment by stefaniasalvadori** [comment]
Die Briefe und die EE Bubenheimers sind auch fertig - sie können in PDF transformiert werden.
Hier die Liste

- EE 77
- [ ] Text
- [ ]  Intro
- EE77A
- [ ] text
- EE79
- [ ] intro
- [ ] text
- EE80
- [ ] intro
- [ ] text
- EE84
- [ ] intro
- [ ] text
- EE85
- [ ] intro
- [ ] text
- EE89
- [ ] intro
- [ ] text
- EE89A
- [ ] intro
- [ ] text
- EE88
- [ ] intro
- [ ] text
- EE88A
- [ ] intro
- [ ] text
- EE88B
- [ ] intro
- [ ] text
- EE90
- [ ] intro
- [ ] text
- EE93
- [ ] intro
- [ ] text
- EE893A
- [ ] intro
- [ ] text
- EE93B
- [ ] intro
- [ ] text
- EE95
- [ ] intro
- [ ] text
- EE94
- [ ] intro
- [ ] text
- EE96
- [ ] intro
- [ ] text
- EE97
- [ ] intro
- [ ] text
- EE98
- [ ] intro
- [ ] text
- EE99
- [ ] intro
- [ ] text
- EE105
- [ ] intro
- [ ] text
- EE107A
- [ ] intro
- [ ] text
- EE111
- [ ] intro
- [ ] text
- EE111A
- [ ] intro
- [ ] text
- EE111B
- [ ] intro
- [ ] text

**Comment by dariok** [comment]
Bei EE077A, EE084, EE089A, EE088B, EE093A, EE93B, EE094 gibt es nur eine Intro, da verschollen; ich habe die Liste angepaßt.
Die weiteren EE schaue ich mir später an.
