### ISSUE TITLE
Kleine Fehler in Transformation

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#245]
Bei einigen bibliographischen Angaben wird automatisch ein (dort unnötiges) Spatium for dem Komma mit folgender Seitenangabe generiert:
EE81intro: Rhenanus, Briefwechsel , 203
EE108intro: Liber Decanorum , 144

Fehlende Hinterlegung mit bibliographischen Angaben trotz Eintrags in Bibliographie:
EE108text 
Bonaventura, Opera omnia (Florentina)
Kriechbaum, Grundzüge

**Comment by dariok** [comment]
Bei Bonaventura fehlte ein Leerzeichen vor „(Florentina)“
Bei Kriechbaum ist ein Umbruch vor dem Text

**Comment by Wallsporn** [comment]
In der Bibliographie? Im Wordtext fehlt nicht das Leerzeichen noch sehe ich einen Umbruch.
Was sollen wir dagegen tun, dass die abbr mit einem Zeilenumbruch endet?

**Comment by dariok** [comment]
Ja, in der Bibliographie. Ich habe das jetzt manuell geändert und einen Test eingebaut, der diese Fälle anmerkt. Beim Bearbeiten der Bibliographie muß dann darauf geachtet werden, daß die `abbr` nicht mit Leerzeichen etc. anfängt oder endet und daß zwischen dem Titel und Zusätzen wie „(Florentina)“ ein Leerzeichen steht.

**Comment by Marxistin** [comment]
**Wo** hast Du das geändert? In der bibliography.xml? Wenn nicht, würde ich das gerne dort so anpassen, das in Zukunft keine weiteren manuellen Änderungen notwendig werden.  Dann ist mir noch aufgefallen, dass ich in Oxygen aktuell nicht mehr die Validierung für "Editoren" auswählen kann.
Die Fehlermeldungen kann ich zum Teil nicht auflösen:

Falscher Apostroph! (z. B. Zeile 931, wodurch kann ich ihn ersetzen?)

Schrägtriche [sic!] kompress setzen (z. B. Zeile 491, wie kann ich das umsetzen?)

VD-16/17-, GW- oder EDIT16-Nummer sowie Moreau in tei:idno mit  passendem @type kodieren. (z. B. Zeile 466: gibt es ein Kürzel für Moreau? / z. B. Zeile 1097-1102: soll hier MGWJ verlinkt werden?)

Keine Anführungszeichen verwenden, sondern tei:quote oder tei:term (kann ich nachvollziehen und ändern)

Divis durch Halbgeviert ersetzen (wie kann ich das über die Tastatur ändern?)
