### ISSUE TITLE
Details zu verbessern für die Transformation in HTML/PDF

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#246]
Achtung, sehr oft Zeilenumbruch innerhalb Wort problematisch - Fehler in der Transformation in XML:
Z.B aus EE103 (vgl. auch #242 ) 

XML
![unbenannt](https://user-images.githubusercontent.com/28624747/50972447-f52e5a00-14e6-11e9-8a12-bd5251ce1430.JPG)

PDF
![unbenannt](https://user-images.githubusercontent.com/28624747/50972308-9a94fe00-14e6-11e9-9bd2-9384eecd3306.JPG)

HTML
![unbenannt](https://user-images.githubusercontent.com/28624747/50972358-b9939000-14e6-11e9-9ae1-5d87326453a2.JPG)

**Comment by dariok** [comment]
Okay, zumindest in der Konstellation hier sollte der Fehler nicht mehr auftreten. Beim nächsten Upload sollte es passen.

**Comment by stefaniasalvadori** [comment]
Nein, der Fehler scheint nicht behoben zu sein.
Ich habe gerade die EE103 nochmals hochgeladen. Und zur Sicherheit auch F5 gedruckt.
Ich probiere morgen nochmals

**Comment by dariok** [comment]
Mein Fehler: ich hab vergessen, das Skript auf hochzuladen. Jetzt sollte es aber gehen.

**Comment by stefaniasalvadori** [comment]
Perfetto! Habe grade EE103_tetx hochgeladen: es klappt! Danke!
