### ISSUE TITLE
KGK-II-PDF Fehler allgemein

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#247]
- [x]	es fehlt immer „Bearbeitet von“
- [ ]	Trennungsfehler (online noch in EE110text im Buchtitel)
- [x]	scheinbar werden die bibliogr. Angaben in den Briefen K.-Spalatin nicht transformiert, wahrscheinlich, weil sie keine Siglen aufweisen (sind formatiert)
- [ ]	Marginalien in KGK 138 noch überlappend
- [ ]	Kolumnentitel sind Langtitel und damit viel zu lang (nächste Woche festlegen), Datum im Kolumnentitel kürzen (Monate -> Ziffern)
- [x]	Punkte am Ende der bibliogr. Angaben in Überlieferung verdoppelt

- [x] QV zwischen Anm. werden in der PDF nicht angezeigt, sondern durch "Anm. KGK II" ersetzt (die Verlinkung funktioniert dagegen in HTML)

**Comment by Wallsporn** [comment]
Trennungsfehler in EE110 in Online-Version
![grafik](https://user-images.githubusercontent.com/28565515/51041340-0300df80-15ba-11e9-8f7e-8be257c69a6f.png)

**Comment by Wallsporn** [comment]
EE110 Intro und Text können in nächste PDF mit geladen werden

**Comment by dariok** [comment]
Kurze Notizen:

Trennung in 110: Das war ein Sonderfall, weil das Wort doppelt getrennt ist. Das wollte ich nicht im Skript lösen, weil das zu viel Aufwand ist. Ich habe es mit anderen Punkten auf eine Liste geschrieben, was manuell zu tun ist, wenn die Texte fertig sind.

Die Marginalien brauchen manuelle Arbeit – in 138 sind die so lang und oft, daß da eine ganz andere Lösung her muß.

Wenn die Kolumnentitel festgelegt sind, dann können wir sie in einer Datei hinterlegen und dann automatisch beim Hochladen übernehmen; dann stimmen sie auch in der PDF
