### ISSUE TITLE
EE138 - Fehler2

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#249]
Intro
Probleme bei Darstellung des Zeilenumbruchs in Überlieferung [Anpassung in HTML nicht übernommen]

![grafik](https://user-images.githubusercontent.com/28565515/51042146-dc43a880-15bb-11e9-9c27-2ec72bac0ad0.png)

**Comment by Wallsporn** [comment]
Text
Martinus Lutherius ᵃ ³ <- Abstand der Anmerkungsziffern

![grafik](https://user-images.githubusercontent.com/28565515/51042221-0ac18380-15bc-11e9-8da2-6b2f2130e10a.png)

**Comment by dariok** [comment]
Die Trennstriche sind nicht die richtigen, es sollte das Unicode-Zeichen `2016` sein. Beim Upload wird innerhalb eines Titels das andere Zeichen durch das richtige ersetzt, nicht aber an anderer Stelle.
Wenn es im Browser richtig aussieht, liegt das daran daß der Browser einfach einen anderen Font nimmt.

Ich habe den Upload jetzt abgeändert, sodaß diese Striche überall im Text geändert werden.
