### ISSUE TITLE
EE 103 - Transformation Hoch- und tiefgestellte Zeichen

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#25]
Bei der Transformation der EE 103 [Nr.129] hat fast alles geklappt.
Nur die tief- hoch-gestellten Buchstaben (nochmals ein Problem, die auch in anderen EE auftaucht) sind zu verbessern:

Z.B. in Überlieferung [B:]

1.  r und v hochgestellt
![unbenanntee103_a](https://user-images.githubusercontent.com/28624747/27492900-197eed82-5848-11e7-9f03-262f1109b834.JPG)

1. in "weitere Exemplare", [B1] und [B2] --> 1 und 2 tiefgestellt
![ee103_b](https://user-images.githubusercontent.com/28624747/27492910-296c8e34-5848-11e7-91d5-7055c955bf1d.JPG)

**Comment by Marxistin** [comment]
Siehe auch #44

**Comment by dariok** [comment]
Nr. 138, Nr. 110, Nr. 111 ebenfall

**Comment by dariok** [comment]
- [ ] 115 / 092alt
- [ ] 129 / 103alt
und passim
