### ISSUE TITLE
Orte/Personen ohne ref in HTML hervorheben

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#255]

**Comment by dariok** [comment]
@stefaniasalvadori @wallsporn In den Texten wird nun in einem hellen grün (Personen) bzw. hellen blau (Orte) hervorgehoben, wenn kein `@ref` zugeordnet werden konnte. Das sollte es erleichtern, problematische Stellen zu finden (z.B. auch solche, wo ein Ort versehentlich als Person markiert ist ode rumgekehrt).

**Comment by stefaniasalvadori** [comment]
@dariok sehr schön udn sehr hilfreich! Danke!
Nur - die einfache **schon formatierten** Varianten (**Karlstadt** oder **Erfurt** oder **Rom** etc.), die bisher referenziert waren, sind nun markiert und nicht mehr getagt. Soll ich auch diese Basic-Formen als vorl: in xml eintragen?

![unbenannt](https://user-images.githubusercontent.com/28624747/51172403-76089f80-18b3-11e9-86ee-9bf524b1c0fb.JPG)

**Comment by stefaniasalvadori** [comment]
Karlstadt habe ich nun unter type:vorl ergänzt und es klappt.
Nur die Ortsnamen bleiben offen - bevor ich alle als type:vorl ergänze, warte ich auf Deine Ruckmeldung

**Comment by dariok** [comment]
Die Änderung im Ortsregister habe ich jetzt vorgenommen. Damit sollte die Erkennung der Orte jetzt auch besser funktionieren.

**Comment by stefaniasalvadori** [comment]
Das klappt wunderbar @dariok  - DANKE
