### ISSUE TITLE
PDF zum aktuellen Stand

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#259]
@dariok kannst Du bitte uns eine neue vollständige PDF (mit Personen- und Ortregister) senden?
Nur wenn es nicht zu zeitaufwendig ist.

Ich habe nochmals alle Personen- und Ortsnamen geprüft und ggf. in XML korrigiert/ergänzt.
Die Hervorhebung in HTML ist einfach genial - ein Wunder! Das hilft die Kodierung, Referentierung und Verbesserung der Formatierungs- oder Tippfehler enorm. Danke @dariok

**Comment by dariok** [comment]
Freut mich, daß es hilft. Ich mache euch gleich eine PDF

**Comment by dariok** [comment]
Hier die aktuelle PDF, wie immer ohne manuelle Eingriffe im Textteil
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2760371/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
In dieser PDF tauchen im Personen- und Ortsregister manche (schon verlinkten) Namen nicht auf.
Z.B
Karl von Miltitz
oder 
Grimma 

Es sieht aber so aus, als ob sie in der Online Edition referenziert wären und auch in XML sind sie mit id refernziert.

Vielleicht tauchen sie in der nächsten PDF auf, ich wollte aber das Problem sofort signalisieren
