### ISSUE TITLE
idno Moreau / USTC in bibliography

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#261]
idno type="moreau" 
und 
idno type="ustc"
wird in html (noch ?) nicht umgesetzt.

**Comment by Marxistin** [comment]
Das soll genauso laufen wie beim VD16. Im Tag findet sich ein Link zu einer Publikation.

**Comment by Wallsporn** [comment]
Nein, Moreau hat keinen permanenten Online-Link (nur Google Books, aber ... wir wissen ja)

**Comment by dariok** [comment]
Gut, dann sollte es jetzt passen.
