### ISSUE TITLE
allgemeine Personenreferenzierung - Nachkodierungsarbeit 2

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#263]
@dariok Darf ich morgen, die Personennamen, die noch nicht getaggt sind (Herzog, Paulus, Fuerst, etc.) handisch nachzukodieren oder soll ich noch warten?

**Comment by dariok** [comment]
Du kannst sie jederzeit einarbeiten. Ich warte mit den weiteren manuellen Korrekturen, bis Du mir eine Datei als „fertig“ signalisierst.

**Comment by stefaniasalvadori** [comment]
Hintergrund meiner Frage war, Du wolltest ein Plug-In für diese Fällen (Herzog, Bishof, etc) einbauen.
Wenn das Plug-In demnächst zur Verfügung steht, dann spare ich mir auch diese manuelle Tagging-Arbeit. Wenn Du aber meinst, es dauer noch eine Weile, dann fänge ich an, diese Personennamen nachzukodieren - ich habe  von Seite-Umfang mehr als alle andere, ich brauche mehr Zeit für diese Arbeit.
Lass mich wissen, was Du für sinnvoller hältst

**Comment by dariok** [comment]
Für das Plugin muß ich noch ein paar Änderungen vornehmen, damit die Registereinträge abgerufen werden können und das entsprechend bei der Transformation umgesetzt wird. Leider ist die Abfrage etwas komplexer, als ich gehofft habe – das Plugin an sich ist fertig.

Um euch beim Warten etwas Arbeit abzunehmen, hänge ich hier in ein paar Minuten ein Plugin für oXygen an, das euch beim Eintragen der Verweise in `@ref` unterstützt.

**Comment by stefaniasalvadori** [comment]
No stress Dario - ich kann auch nachkodieren, ist es überhaupt kein Problem.  Die Hervorhebung in der OnlineEdition ist schon eine sehr sehr grosse Hilfe und hat (mir mindenstens) sehr viel Arbeit abgenommen.
Es ist nur eine Koordination Frage: Es wäre mir ärgerlich, wenn ich die Arbeit mache und in ein paar Tage das Plug-In fertig ist. Dann warte ich ein bisschen lieber. 
Ich werde heute andere Korrekturen übernehmen, ist es deshalb mit der Personen-Referenzierung von mir aus nicht dringend.

**Comment by dariok** [comment]
Das Plugin für oxygen ist bereits erledigt, da es in diesem Fall sehr einfach ist.

Im Verzeichnis von oxygen (also z.B. c:\Programme\oxygen) gibt es ein Unterverzeichnis „frameworks\tei\resources\“. Dort bitte eine XML-Datei „cc_config.xml“ erstellen und folgendes hineinkopieren:

    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.oxygenxml.com/ns/ccfilter/config http://www.oxygenxml.com/ns/ccfilter/config/ccConfigSchemaFilter.xsd"
	xmlns="http://www.oxygenxml.com/ns/ccfilter/config">
        <match elementName="rs" elementNS="http://www.tei-c.org/ns/1.0" attributeName="ref">
            <xslt href="http://dev2.hab.de/edoc/ed000240/register/getent.xsl" useCache="false" action="replace"/>
        </match>
    </config>

Nach einem Neustart von Oxygen gibt es dann eine Vervollständigung bei den Personen: im Attribut `@ref` anfangen zu tippen und es werden nach 3 Buchstaben Vorschläge angezeigt (mit dem ersten Namenseintrag aus dem Register als Tooltip).

**Comment by stefaniasalvadori** [comment]
Danke Dario. Ich experimentiere das Word-Plug-In heute nachmittags.

Zur noch nicht verlinkten Personen/Orte --> Ich habe Varianten und Referenzierungen nur in meinen EE eingetragen, wo eigentlich nur die "allgemeine Personennamen" (Herzog, Fuerst, etc.) noch offen bleiben.

**Comment by dariok** [comment]
Bei Bedarf kann ich auch noch eine Liste erstellen mit den Orten/Personenformen, die besonders oft nicht umgesetzt sind

**Comment by stefaniasalvadori** [comment]
Warte mal, Dario - wir laden alle EE nochmals hoch, danach geben Dir Bescheid, ob eine Liste erstellt werden muss
Danke erstmal Dir
