### ISSUE TITLE
Probleme bei der Transformation der QV zwischen Anm in der PDF

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#264]
Die QV zwischen Anmerkungen innerhalb einer EE (intro oder text), die schon in Word verlinkt sind, werden nun in der PDF angezeigt, jedoch mit Verdoppelung.

Z.B.
in Word: _siehe dazu Anm. **29**_
in Pdf: _siehe dazu Anm. **S. 98 Anm. 29**_

Natuerlich koennten wir in Word das Wort "Anm." weglassen, das waere aber zeitaufwendig. Lasst das Problem sich automatisch regeln?

Darueberhinaus sind die (automatisch generierten) Seiteangaben momentan falsch, wenn ich sie in der PDF suche! Anhand der letzten PDF waere im obergenannten Beispiel **S. 106 Anm. 29** zu erwarten

**Comment by dariok** [comment]
Ich versuche, das doppelte „Anm.“ zu entfernen, wo es geht.

Die Seitenzahlen in der PDF werden erst später überall korrekt sein, wenn alle Texte zumindest einen festen Umbruch erhalten haben. Im Moment gibt es noch mehrere Stellen, die sich im Durchlauf auf eine andere Seite verschieben können, weshalb die Seitenzahlen dann nicht stimmen.
