### ISSUE TITLE
Probleme bei der Referenzierung von Bibelstellen mit mehreren Versen

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#265]
Soweit ich sehe tauchen Bibelstellen mit mehreren Versen (z.B. Tit 1,7 u. 10) im Register nicht auf.
Angesichts des Zeitdruckes sollen wir uns ueberlegen, ob wir diese Stellen in Word sofort korrigieren muessen.

**Comment by dariok** [comment]
Bibelstellen mit mehreren Versen gibt es einmal mit „und“ und einmal mit „;“ – weiterhin noch andere Formen, wenn ein anderes Kapitel dazukommt. Ich werde die Bibelstellen markieren und beim Prüfen ggf. händisch die Einträge für das Register erstellen.
Wenn ihr es in Word ändert, müßte auch der Wortlaut geändert werden, was dann wiederum nachher Arbeit für die Fahnenkorrektur ist. Es ist schneller, gezielt diese Stellen in der XML zu prüfen.

**Comment by stefaniasalvadori** [comment]
- Ok, die zwei Stelle korrigiere ich
- Ja, "und"-Varianten getrennt ins Register --> 1 Kor. 2,4;6 --> einmal unter 1 Kor 2,4 + einmal unter 1 Kor 2,6
- Die Vereinheitlichung und, u. ; bespreche ich heute mit den Editoren. Ich melde mich spaeter

**Comment by dariok** [comment]
Bei der Transformation von Transkriptionen werden jetzt Varianten mit „und”, „u.“ und „;“ getrennt. Wenn das nicht richtig klappt, sollte das Schema das melden und die Stelle im Register der PDF auffallen
