### ISSUE TITLE
<gap> innerhalb von <term type="title">

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#266]
In der Bibliographie akzeptiert Oxygene `<gap>` innerhalb eines Werktitel nicht.
Ich möchte 
Bernhard Dappens „Articuli … contra Lutheranos“. 
kodieren.
Sollte doch heißen:
`Bernhard Dappens <term type="title">Articuli <gap/> contra Lutheranos</term>`
Die Fehlermeldung lautet:

Invalid content was found starting with element '{"http://www.tei-c.org/ns/1.0":gap}'. One of            '{"http://www.tei-c.org/ns/1.0":seg}' is expected.

**Comment by Marxistin** [comment]
![grafik](https://user-images.githubusercontent.com/23031457/51477873-00587400-1d8a-11e9-9093-478a35c89fcf.png)

**Comment by Marxistin** [comment]
Rätselhaft, warum die Befehle einfach weggelöscht werden. 
Jetzt also ohne spitze Klammern:
In der Bibliographie akzeptiert Oxygene (gap) innerhalb eines Werktitels (term type="title") nicht.

**Comment by dariok** [comment]
Die spitzen Klammern werden nicht übernommen, da der Browser sie als HTML-Elemente interpretiert, es aber keine sind. Solche Stellen kann man als Code markieren (mit einem ` davor und dahinter), dann wird es angezeigt.

Ich werde `<gap>` an dieser Stelle einfügen.

**Comment by dariok** [comment]
Die Variante habe ich eingefügt und die Stelle ist jetzt valide.

**Comment by Marxistin** [comment]
In meiner Datei nicht :-(
![grafik](https://user-images.githubusercontent.com/23031457/51601990-1db24d00-1f06-11e9-9b1b-9a2474e67044.png)

**Comment by dariok** [comment]
Wenn Du lokal arbeitest, dann bitte ersetzen:
`<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude" xsi:schemaLocation="http://www.tei-c.org/ns/1.0 http://dev2.hab.de/edoc/ed000240/rules/register.xsd" xml:id="edoc_ed000240_bibliography">`

**Comment by Marxistin** [comment]
Nochmal Danke!
