### ISSUE TITLE
Zur PDF-Erstellung - spitze Klammern

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#267]
In Word werden spitze Klammern verwendet (in Handschriften - für Auslassungen und Stellen, die nicht entziffern werden können)

![unbenannt](https://user-images.githubusercontent.com/28624747/51485371-2720a580-1d9e-11e9-94e2-a40eaffe7ff1.JPG)

Diese normalen spitze klammern entsprechen nicht unseren Editionsrichtlinien:
![unbenannt](https://user-images.githubusercontent.com/28624747/51485487-81ba0180-1d9e-11e9-9f4d-993cf39eba29.JPG)

@dariok kannst Du sie vereinheitlichen oder mussen wir Sondernzeichnen verwenden?

**Comment by dariok** [comment]
- `<...>` sollte bereits zu `gap` werden (wenn nicht, bitte die Stelle mitteilen, dann muß ich diesen Fall neu anschauen)
- `<text>` sollte immer zu `supplied` werden

Dir Ausgabe müßte ich mir nochmal anschauen, das war in der 1. Phase irgendwie kompliziert.

**Comment by stefaniasalvadori** [comment]
Nein, die werden nicht als gap kodiert. In XML sehen sie so aus:
![unbenannt](https://user-images.githubusercontent.com/28624747/51487080-b62fbc80-1da2-11e9-9a90-dffaa02a78aa.JPG)

Diese ist eine besondere Art von Auslassung - das ist eine **Lacuna**.

Diese Stellen <...> sollten als **gap reason="example"/** kodiert werden, oder? 

Ein Beispiel dafür hast Du in den RandGlossen Epitome und - was hier ich als Bild anhänge - in der Einleitung zur Leipziger Disputation, Anm. 47 und 50
![unbenannt](https://user-images.githubusercontent.com/28624747/51488581-36a3ec80-1da6-11e9-8db2-83443145176e.JPG)

**Comment by dariok** [comment]
Für Lacunæ sieht die TEI `gap reason="lacuna"` vor.

In Einleitungen (dort insbesondere in Fußnoten) wird `...` in der Regel nicht kodiert, weil eben nicht klar ersichtlich ist, was sie an diesem Punkt bedeuten: eine Lacuna oder eine vom Editor beabsichtigte Auslassung.

Wie Du bereits am Anfang geschrieben hast, ist die nicht einheitlich Verwendung hier ein Problem. Dieses läßt sich aber nicht ohne Weiteres automatisch auflösen. Entweder müssen wir Formatvorlagen einführen, oder es muß einheitlich verwendet werden:
- `<...>` für eine Lacuna (= `<gap reason="lacuna"/>`)
- `[...]` für eine absichtliche Auslassung unstrittigen Textes (= `<gap reason="omitted" />`) – dies betrifft i.d.R. Zitate
- `<abc>` für eine Konjektur des Editors (= `<supplied>abc</supplied>`)
- `[abc]` für eine Ergänzung des Editors bei schlecht lesbaren, aber sicher erschließbaren Textstellen (= `<unclear>abc</unclear>`)

**Comment by stefaniasalvadori** [comment]
Es geht um Stellen - in Handschriften - die nicht lesbar sind oder die ich nicht entziffern kann. 
In meinen Anmerkungen werde ich die Stellen haendisch als lacuna nachkodieren.
Wichtig ist es, dass die Transformation in den RandGlossen zur Epitome automatisch klappt - was hoffentlich der Fall ist

**Comment by dariok** [comment]
Vielleicht haben wir uns hier mißverstanden. 
Wenn in Word geschrieben ist `<...>` sollte dies zu `gap` kodiert werden, was dann mit den leichten Winkeln ausgegeben wird. Dafür ist kein Sonderzeichen nötig. Wenn es an einzelnen Stellen nicht klappt, wie in der Intro zur LD, dann schaue ich mit die Stellen nochmal an.

Hast Du die Intro zur LD schon händisch bearbeitet?

**Comment by stefaniasalvadori** [comment]
In Ordnung - Danke! - ich bin dabei die LD nachzukodieren. Diese Stellen (in den Anm. - das ist das Problem) kodiere ich als gap. Falls es nicht klappt, markiere ich für Dich die Stelle in der PDF
