### ISSUE TITLE
Probleme in der PDF von EE88A (KGK Nr. 113)

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#268]
In der Transformation von EE88A beobachten wir folgende Probleme:

**EINLEITUNG:**
- Anm. am Ende von KS:Zitatblock werden in der PDF nicht transformiert. In der Online Edition sie sind aber richtig angezeigt. 

ONLINE:
![unbenannt](https://user-images.githubusercontent.com/28624747/51532005-4ae7f800-1e3f-11e9-8930-94b197b9fc97.JPG)

PDF:
![unbenannt](https://user-images.githubusercontent.com/28624747/51532101-8d113980-1e3f-11e9-8a97-20465d6ddcde.JPG)

TRANSKRIPT:
- Die QV zwischen Anm. (mit QV-Word-Funktion automatisch verlinkt) werden merkwürdigerweise nicht transformiert (es klappt sonst immer, in allen EE). Weder in der Online Edition noch in der PDF.

- Merkürdigerweise waren auch die »« in Anm. 2 verscwunden. Ich könnte sie nun wiederherstelln, indem ich den Punkt nach dem Schluss-Anführungszeichen verschoben habe. 
So: die Stelle **per fidem.«** --> Anführungszeichen waren weg
Ich habe so korrigiert: per **fidem«.** ---> Anführungszeichen wieder angezeigt
Hast Du eine Erklärung dafür - das Phänomen hatte ich nirgendwo beobachtet...

Ich hänge die Dateien hier an:
[EE88Aintro2019-1-22.docx](https://github.com/dariok/karlstadt-issues/files/2782534/EE88Aintro2019-1-22.docx)
[EE88A_Text_2019-01-22.docx](https://github.com/dariok/karlstadt-issues/files/2782535/EE88A_Text_2019-01-22.docx)

**Comment by dariok** [comment]
Ich weiß nicht, warum, aber hier ist in der FN2 Chaos im Word. Ich könnte versuchen, die Verlinkung der Fußnoten umzustellen, würde das aber gerne vermeiden, wenn das Problem sonst nicht auftaucht.
