### ISSUE TITLE
EE 107 - Link

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#27]
In EE 107 klappt die Verlinkung nach "(Autograph)" nicht.
![ee107](https://user-images.githubusercontent.com/28624747/27493342-d5a04564-5849-11e7-9a44-30dfdcc758a0.JPG)

Hier auch die Word Datei
[EE 107_Intro_2017_6_22.docx](https://github.com/dariok/karlstadt-issues/files/1098561/EE.107_Intro_2017_6_22.docx)

**Comment by dariok** [comment]
Mit https://github.com/dariok/w2tei/commit/baa20f751b84c1a675511180cdd6c0674c7527cd behoben.
