### ISSUE TITLE
Abweichungen zwischen Online Edition und PDF

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#271]
Manchmal sind Details, die in der Online Edition richtig angezeigt sind, in der PDF einfach weg.
Sollen wir diese Fälle einzeln signalisieren?

Hier erstmal ein Beispiel aus EE100=KGK 128

OnLine
![unbenannt](https://user-images.githubusercontent.com/28624747/51551762-72ef4f80-1e6f-11e9-9057-15fc9152f141.JPG)

Und PDF
![unbenannt](https://user-images.githubusercontent.com/28624747/51551788-80a4d500-1e6f-11e9-8a4b-f59f70e53906.JPG)

**Comment by stefaniasalvadori** [comment]
Ich signalisiere auch die Bindestriche, die in der PDF manchmals "komisch" aussehen:

![unbenannt](https://user-images.githubusercontent.com/28624747/51559557-835cf580-1e82-11e9-9d27-6f2d7f2dee3a.JPG)

**Comment by dariok** [comment]
Zur ersten Frage: Das hatten wir beim 1. Band mal gesagt, daß bei verschollenen an der Stelle nicht „Literatur“ ausgegeben wird. Ich weiß aber nicht mehr, warum... Baue es wieder ein.

**Comment by dariok** [comment]
Die hochgestellten Halbgeviert werden dann auch vor den Druckfahnen erledigt oder beim nächsten Upload einer Datei.
