### ISSUE TITLE
Verweise und ihre Formatierung

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#272]
In der XML sind die Verweis bisher nicht mit einem Tagging hinterlegt. Soll das noch eingebaut werden? Genügen unsere bisherigen Kennzeichnungen mit Gitterkreuz (EE81_text_Anm. 1#), ohne Formatierung mit KS EE:Verweis? Oder ist beides (Gitterkreuz und Formatierung) notwendig, ohne dass ein Tagging generiert wird? Ich habe bisher beides gemacht, Stefania würde die Formatierungen morgen einbauen - wenn sie wirklich notwendig sind. In der nächsten Woche wollen wir alle Dateien hochladen - danach möglichst nur noch auf Basis der XML nachkodieren bzw. taggen.

**Comment by stefaniasalvadori** [comment]
Nein, nein, die Formatierung in meinen EE ist schon gemacht. KS:EE Verweis wird aber in XML nicht getaggt, Ich bin nur beim Nachkodieren, d.h. ich kann die schon nachkodierten EE nicht nochmals hochladen, sonst die tagging-arbeit in XML ist weg. 
@dariok wenn Du die Transformation der Formatierung KS:EE Verweis einbauen musst, lass uns bitte wissen, wann das erfolgen kann.
Die Stellen in den bisherigen EE kann ich auch nachkodieren, nicht aber in der LD (pietà, bitte!), an der ich morgen arbeiten wollte und die uebrigen Stellen in XML nachkodieren wollte.

**Comment by dariok** [comment]
Ich werde den Upload nochmal anschauen, daß die Form `EE(Nr.)_(text/intro)_Anm ...` beim Upload besser umgesetzt wird.
Bei den schon hochgeladenen Dateien ändere ich das manuell.

**Comment by stefaniasalvadori** [comment]
Danke Dario - macht Dir aber kein Kopf fuer die schon hochgeladene Dateien.  Die werden fast alle nochmals hochgeladen.
Bisher habe ich nur EE82, EE92, EE100 und EE101 nachkodiert. Die kann ich leider nicht nochmals hochladen, kann aber die EEVerweise selbst nachkodieren. No problem. 
Alle andere EE muessen sowieso nochmals hochgeladen werden. Spar Dir diese Arbeit.
Hauptsache ist es, die Anpassung des Upload nicht zeitaufwendig und ich kann morgen mit der LD anfangen.

**Comment by dariok** [comment]
Ich habe gerade etwas vorbereitet, das ich morgen früh testen werde. Wenn alle Test klappen, wird es bei den EE, die neu hochgeladen werden, entsprechend umgesetzt. Bei allen anderen kann ich es später anwenden.

**Comment by stefaniasalvadori** [comment]
Wunderbar! Merci vielmal Dario!
Dann lass uns morgen wissen, wann und ob es klappt - danach beginne ich mit der Nachkodierung der LD

**Comment by dariok** [comment]
Die Skripte sind jetzt aktiv und die Form wird umgesetzt zu einem ptr, auch wenn die Stelle nicht als KS:EE-Verweis markiert ist.
Bei den bereits händisch vorbereiteten Texten läßt sich das nachher übernehmen.

**Comment by stefaniasalvadori** [comment]
Ich habe gerade die Einleitung zu EE102 hochgeladen. 
In XML sind die Verweise (EE102_text## und similia) nirgendwo getaggt.

**Comment by dariok** [comment]
Schaue ich gleich rein

**Comment by stefaniasalvadori** [comment]
Merci! - lass mich wissen, falls ich helfen kann

**Comment by dariok** [comment]
Bitte noch einmal hochladen

**Comment by stefaniasalvadori** [comment]
Hochgeladen - jetzt klappt es, für QV wie EE103_text_Anm. 113#:
![unbenannt](https://user-images.githubusercontent.com/28624747/51598021-f440f380-1efc-11e9-8489-d56ebd0d2e74.JPG)

Für die allgemeine EE-Verweise (etwa **EE82_text##** oder **EE82##** oder **EE82_text_adductis notariis duobus#**) gibt es **kein Tag**. Das werden wir in der PDF markieren und Du ergänzt sie manuel, oder?

**Comment by dariok** [comment]
Ich kann noch schauen, ob ich `EE82_text##` umsetzen kann, aber ich glaube, das wird insgesamt nicht so häufig vorkommen.

**Comment by dariok** [comment]
Gut, das wird ab jetzt beim Upload auch umgesetzt bzw. dann später bei den Fahnen korrigiert.

**Comment by dariok** [comment]
EE82_intro sollte auch schon funktionieren (hoffe ich zumindest ;)) Den Rest machen wir dann manuell

**Comment by stefaniasalvadori** [comment]
Ok, wunderbar! Danke!
Ich werde Dir heute Abend/morgen früh darum bitten, eine neue PDF meiner EE zu erstellen.
Ich sollt mit der Nachkodierung bis dahin fast durch sein.

Mein Ziel wäre, in der (Schnelle)PDF von morgen in den kommenden Tagen (beim Korrekturlesung meiner EE) Dir schon alle Hinweise zu schreiben, damit Du die fehlende QV, LayOut Probleme und so weiter sofort, pur a pur, bei Erstellung der erste Druckfahnen in LaTex, einarbeiten kannst. Damit muss ich in die erste Druckfahen (Ende Februar), nur checken, ob alles in Ordnung ist und die Korrektueren/Änderungen in meinen EE drastrisch reduzieren. Das ist m.E. sinnvoller, grosse Korrekturen in den Druckfahnen vorzunehmen ist immer problematisch. 

Wäre es Dir recht?

**Comment by dariok** [comment]
Okay, machen wir so.
