### ISSUE TITLE
Textapparat an Marginalien fehlerhaft

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#273]
EE78 Probleme beim Textapparat mit Marginalien
Gibt "hinzugefügt ..." nicht aus, daraus wird "folgt", selbst bei Formatierung mit KS Kommentar
s. Note ap und ba
Zudem zieht die Transfo die angemerkte Textstelle ins Nichts! (bei Note ba die "15")
![grafik](https://user-images.githubusercontent.com/28565515/51602753-12f8b780-1f08-11e9-8e03-3f12009e82de.png)

**Comment by dariok** [comment]
Die Anm. ba ist falsch formatiert. Sie sollte so aussehen:

_fehlt A; hinzugefügt_ 15 _AK_

ohne weitere Formatierungen. Dann sollte alles klappen.

**Comment by Wallsporn** [comment]
Danke, ja, besser, aber viele Fehler auch in anderen Fußnoten. Alex und Timo gehen die ganze Datei durch, wenn ich es schaffe, schaue ich auf einige Fehler, und wir schicken sie Dir später

**Comment by timojanssentj** [comment]
Das ist die besagte Datei. Die gelbmarkierten textkritischen Anmerkungen werden nicht entsprechend umgewandelt.

[EE78_txt_TJ-AZ_last_2019-01-23.docx](https://github.com/dariok/karlstadt-issues/files/2787614/EE78_txt_TJ-AZ_last_2019-01-23.docx)

**Comment by dariok** [comment]
- Anm. ah (hh): Durchstreichungen werden bisher nicht verwendet und daher nicht umgesetzt
- bi (ddd) und andere: bei textkrit. Anm. zu einem Wort, das über den Zeilenumbruch getrennt wird, Marginalien immer hinter die kritische Anmerkung setzen (Word-Einstellung: Anker, an Buchstaben)
- mehrere Anmerkungen sind ähnlich ba falsch formatiert; weitere Lesarten (auch Korrekturen) nicht mit Halbgeviert abtrennen (sondern mit Semikolon) und nicht als Kommentar markieren
