### ISSUE TITLE
Gap in Anmerkungen nicht getaggt/kodiert

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#274]
Die gap sind in den Anmerkungen nicht kodiert - niergendwo

![unbenannt](https://user-images.githubusercontent.com/28624747/51611579-da64d800-1f1f-11e9-9e00-dadd72d2eb25.JPG)

Ist es ein Problem, @dariok ?
Kann man das automatisch in XML ersetzen/korrigieren?

**Comment by dariok** [comment]
Ich schaue gerade, woran es liegt.
Es läßt sich schnell automatisch ersetzen, von daher kein großes Problem.

**Comment by stefaniasalvadori** [comment]
Prima!
Danke! Dann lassen wir diese Stellen erstmal so stehen lassen - Du wirdst sie direkt in XML ersetzen.

**Comment by dariok** [comment]
Okay, Intros die ab jetzt hochgeladen werden, wollten automatisch `gap` bekommen. Den Rest erledige ich bei der Konversion (diese Stellen werden außerdem durch das Schema angemerkt).
