### ISSUE TITLE
Abweichungen zwischen html und PDF - Leipziger Disputation EE103

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#276]
Ich beobachte gerade, dass  viele textkritische Anm. in der EE103 (LD) sind in der Online Edition richtig angezeigt, nicht aber in der PDF.

Die sind in XML m.E. richtig kodiert...

Hier z.B. die textkrit. Anm. r, wie sie in XML aussieht:
![unbenannt](https://user-images.githubusercontent.com/28624747/51631367-d1d6c680-1f4c-11e9-8f9b-562acee26197.JPG)

In der Onlineedition ist sie richtig angezeigt. In der PDF ist sie nicht im Apparat und falsch im Text markiert...

Ich werden den Text der LD morgen nachkodieren. Falls Du eine Idee hast, woran das liegt, wäre schön. Oder lass mich einfach wissen, ob mit richtige HTML/XML kann ich nachkodieren, und Du wirdst die Scripts für die PDF später anpassen.

Danke im Voraus

**Comment by dariok** [comment]
Die gute Nachricht: da es online richtig ist, ist es kein Problem im XML, sondern nir in der Konversion zur PDF.

**Comment by stefaniasalvadori** [comment]
meno male... :-)

Wäre es Dir recht, wenn ich Dir morgen nachmittags grünes Licht gebe, eine PDF meiner EE zu erstellen? Ich mochte gerne sie morgen Abend ausdrucken
