### ISSUE TITLE
komplexe textkrit. Anm. übere mehrere Wörter in LD

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#277]
@dariok 
ich bin nicht in der Lage, einige sehr komplexe (=lange) textkrit. Anm. über mehrere Wörter(/Zeilen/Seiten) nachzukodieren.

Soll ich Dir die Stelle direkt in die PDF markieren?
Das wäre m.E. sicherer - es geht um nicht so viele Stelle und das Experimentieren von mir in XML bring nichts...

**Comment by dariok** [comment]
Nein, da solltest Du Dich nicht mit aufhalten. Markiere mir die Stellen in der PDF und ich kodiere sie dann.

**Comment by stefaniasalvadori** [comment]
DANKE!!!
Ich muss nun nur die Personennamen im Text nachkodieren, danach bin ich mit der LD fertig.
Ich mache auch EE104 fertig, danach gebe ich Dir Signal für DF erstellung.
GRAZIE MILLE

**Comment by stefaniasalvadori** [comment]
@dariok 
Mit der Nachkodierung der LD bin ich fertig.
Ich kann leider die Online Edion nicht abrufen - sie ist wahrscheinlich überfordert (zu viel in Cashe? - ich habe aber mit F5 versucht, es klappt nicht)

Ich habe nun die Korrekturen in XML gespeichert.
Kannst Du die HTML regenerieren?

Wenn ja, ich schaue nochmals durch, danach ist die EE für schnell-PDF-erstellung fertig

**Comment by dariok** [comment]
@stefaniasalvadori Die HTML-Anzeige kann jetzt auch mit einem Sonderfall der LD umgehen.

**Comment by stefaniasalvadori** [comment]
@dariok ich weiss es nicht, wie ich mich bei Dir bedanken kann! Stupendo!

Die LD ist nun nachkodiert - restliche Korrekturen erfolgen nur in XML. LayOut Probleme markiere ich in die nächste schnelle-PDF.

Ich prüfe, mache auch EE104 fertig und dann melde ich mich heute nachmittags für die PDF erstellung

**Comment by dariok** [comment]
Immer gerne. Sag Bescheid, dann erstelle ich eine neue PDF vom aktuellen Stand.
