### ISSUE TITLE
EE 78, Literatur taucht nicht auf

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#278]
[EE78_intro_2019-01-24.docx](https://github.com/dariok/karlstadt-issues/files/2791278/EE78_intro_2019-01-24.docx)

**Comment by dariok** [comment]
Die Angaben in der Literatur müssen als bibliographische Angabe formatiert werden, dann werden sie umgesetzt.

**Comment by timojanssentj** [comment]
Ah! Völlig übersehen. Danke dir!

**Comment by dariok** [comment]
Kein Problem
