### ISSUE TITLE
Zeilenumbruch in Marginalien

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#279]
Marginalien mit Zeilenumbrüche werden nicht richtig angezeigt - weder in HTML noch in der PDF. In XML waren auch weg, bzw. war nur die letzte Zeile kodiert (übriger Text, vorhergehende Zeilen, weg)

Ich  habe nun alle Zeilenumbrücje (= Enter-Taste) gelöscht. Nun sind alle Marginalien in HTML richtig angezeigt und in XML vollständig kodiert. 

Gilt das für alle EE, oder?

**Comment by dariok** [comment]
Ja, in Marginalien funktionieren Zeilenumbrüche nicht – das liegt daran, wie die Marginalien in Word erstellt werden.

**Comment by stefaniasalvadori** [comment]
Danke Dir - ich bestätige das auch Alex! - Er arbeitet an seiner Auslegung
