### ISSUE TITLE
Transformation - Detailfehler in den Kurztiteln der "Navigations-Liste"

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#28]
Die von Dir hochgeladenen Beispielen hatten die richtige EE-Nummer, aber eine alte KGK-Nummer.
Auch wenn die neuen Word-Dateien aktualisiert wurden und entsprechen die Numerierung in der einzelnen hochgeladenen EE richtig angegeben ist, sind die Titel in der "Navigation-Liste" mit einer alten (KGK) Numerierung angegeben. Deshalb sind Verdoppelungen entstanden.

Z.B. EE 124, EE 125, 131, 155, 161...

![listenavigation](https://user-images.githubusercontent.com/28624747/27493666-d5ba5002-584a-11e7-9f6d-814e0346df1c.JPG)

**Comment by dariok** [comment]
Es sollten jetzt der Titel und die Nummer aktualisiert werden. Bitte ausprobieren.

**Comment by Wallsporn** [comment]
Im Inhaltsverzeichnis tauchen weiterhin alte und neue Nummer nebeneinander auf (Nr. 135, 161). Zudem erscheint bei Nr. 135 (=EE 108) nach unserem vergebenen Titel die Transkription beider Druckvorlagen!

**Comment by dariok** [comment]
Entschuldigung, das hatte ich zu kurz geschrieben: Die Nummer und der Titel werden aktualisiert, wenn die Datei neu hochgeladen wird.

Falls gewünscht, kann ich aber die Titel überall aktualisieren.

**Comment by dariok** [comment]
Das zweite Problem sollte neu nicht mehr auftreten.

**Comment by dariok** [comment]
Die Titel habe ich einmal komplett aktualisiert

**Comment by Wallsporn** [comment]
Sehr gut, danke, es funktioniert. Auch das Layout der Angaben im Inhaltsverzeichnis ist besser, die Ortsangabe nun vom Titel abgegrenzt. Es erscheinen aber immer noch einerseits zuviele eckige Klammern wie in EE 133 = Nr. 164, andererseits fehlt das in eckigen Klammern Erschlossen völlig wie in EE 132 (Nr. 167) und anderswo.

**Comment by stefaniasalvadori** [comment]
Im Inhaltverzeichnis von KGK II sind **kleine Details** (fehlenden Datierungen, eckige Klammern, ect.) zu verbessern. Alle verschollenen EE haben Datierung in eckigen Klammern.

Bitte folgende EE im Inhaltverzeichnis prüfen:
KGK 112 --> verschollene: in [  ]
KGK 117 -- fehlende Datierung / verschollene: in [  ]
KGK 119 --> Spatium vor Datierung in [] / Verdoppelung von "verschollene"
KGK 126 --> fehlende eckige Klammer in der Datierung --> auch in der Ueberlieferung (Titel)
KGK 134 -->  verschollene: in [  ]
KGK 135 --> fehlende eckige Klammer in der Datierung --> auch in der Ueberlieferung (Titel)
KGK 138 ---> 1. Kommata löschen, Monatangabe in [  ]
KGK 141 ---> fehlende Datierung, auch in der Ueberlieferung [EE76_JuniC_Intro_2017-6-21.docx](https://github.com/dariok/karlstadt-issues/files/1208371/EE76_JuniC_Intro_2017-6-21.docx)
KGK 146 ---> verschollene: in [  ]
KGK 154 --> verschollene: in [  ]
KGK 157 ---> Spatium und Kommata vor der Datierung löschen
KGK 158 --> [ ] ergänzen: **[**Ende September/ Anfang Oktober**]**
KGK 165 --> fehlende Datierung, auch in der Ueberlieferung  [EE-139-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1208381/EE-139-Uberlieferung.docx)
KGK 166 --> fehlende Datierung --> @Wallsporn ergänzen? (Reminder via Email in Kurze)

**Comment by dariok** [comment]
KGK 165 noch problematisch
