### ISSUE TITLE
Schnelle PDF - EE82/92/100-104/106-107

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#280]
@dariok 
Ich habe nun alle meine EE nachkodiert.
Wenn Du mir eine PDF folgender EE (intro + text) - wenn möglich, mit Register - erstellen kannst, wäre super

- [ ] EE82

- [ ] EE92

- [ ] EE100

- [ ] EE101

- [ ] EE102

- [ ] EE103

- [ ] EE104   (hier habe ich sehr lange versucht, die Beilagen richtig zu kodieren. Ich war aber nicht in der Lage, sorry. Ich habe aber händisch die Überlieferung -Verdoppelt, Beilage 1 A+B; Beilage 2 A+B) zu kodieren. Nur die Überschirft "**Beilage 1: Johannes Eck an Kurfürst Friedrich III., Leipzig, 1519, 22. Juli**" und "**Beilage 2: Kurfürst Friedrich III. an Johannes Eck, Altenburg, 1519, 24. Juli**" wusste ich nicht, wie ich kodieren muss.

- [ ] EE106

- [ ] EE107

In der PDF, die Du mir erstellt, markiere ich die QV und die LayOut Verbesserungen (und ich korrigiere evtl. übrige Fehler direkt in XML)

**Comment by stefaniasalvadori** [comment]
Auch EE88A - Bubenheimers Einheit - schaue ich mir gerne an, wenn Du sie in PDF umwandelt

**Comment by dariok** [comment]
Mache mich an die Arbeit.

**Comment by dariok** [comment]
Im Text habe ich jetzt die Beilagen kodiert.

In der Einleitung: was sind die Texte für die Beilagen oder sind die in der gleichen Vorlage?

**Comment by stefaniasalvadori** [comment]
In der Einleitung hast Du:
Vorlage fuer den Brief Ks.:
Editionen: Wit deutsch 9, fol. 69v–70r [Digitalisat] 

Danach hast Du sofort die Erste Beilage
Beilage 1: Johannes Eck an Kurfürst Friedrich III., Leipzig, 1519, 22. Juli
Die entsprechenden Vorlagen sind die Drucke
A: fol. A2r-A4r
B: fol. A2r-A4r
Edition: WA.B 1

Danach kommt die 2. Beilage, die in denselben Drucken wie Beilage 1 ist:
Beilage 2: Kurfürst Friedrich III. an Johannes Eck, Altenburg, 1519, 24. Juli
A: 4r
B: 4r
Editon: WA.B 1

Am schluss die Literatur zur Edition in Barge

**Comment by stefaniasalvadori** [comment]
Hier die Word-Datei der Intro, damit Du die Ueberlieferung sehen kannst
Alte Version - bitte NICHT hochladen! ;-)
[EE104intro2018-12-14.docx](https://github.com/dariok/karlstadt-issues/files/2793284/EE104intro2018-12-14.docx)

**Comment by dariok** [comment]
Diese Variante hatten wir bisher nicht, sondern immer nur weitere Handschriften als Beilage. Das muß ich mir nochmal anschauen.

**Comment by dariok** [comment]
Da muß ich nochmal etwas drüber nachdenken und schauen, wie wir das lösen.
Ich mache die PDF jetzt ohne das fertig und überlege es am Wochenende.

[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2793802/karlstadt-2.pdf)

**Comment by dariok** [comment]
Daß die Marginalien fehlen lag an einem Fehler seit dem letzten Update von LaTeX. Ich habe ein paar Dinge umstellen müssen, es sollte aber das Ergebnis stimmen.
Ich stelle gleich eine PDF ein.

**Comment by stefaniasalvadori** [comment]
Danke Dario!
Ich arbeite an der alten (von Donnerstag abend) PDF und trage erst Mittwoch meine Kommentare zu den QV und LayOut Details fuer Dich in die neue PDF ein.

Ich signalisiere dass die Marginalien fehlen noch in dieser neuen PDF - die QV auf Marginalien werde ich im Kommentar irgendwie markieren

**Comment by stefaniasalvadori** [comment]
@dariok 
bei naechster Erstellung der PDF kannst Du bitte die Marginalien berucksichtigen? No stress, wann Du eine neue PDF erstellt.
Grund dafuer:
Ich bin beim Korrekturlesen der LD - vor allem des textkrit. Apparatus. Die Numerierung ist ein bisschend durcheinander, da die textkrit. Anm zu Marginalien fehlen. D.h. ich kann nicht vollstaendig die Edition pruefen

**Comment by stefaniasalvadori** [comment]
@dariok 
Ich habe alle textkrit. Anm. in der LD geprueft. Manchmals passieren seltsame Dinge in der Transformation, die ich nicht nachvollziehen kann. 
2 Fragen:
1) Ich versuche die Fehler direkt in XML korriegeren, vermutlich bin ich aber nicht immer in der Lage, die fehlerhafte Transformation durch eine richtige Kodierung zu ersetzen. Waere Dir recht, wenn ich die Stelle, die ich nicht korrigieren kann, in der PDF markiere?
2) Es waere mir lieber die Stelle in der alten PDF (von vergangenen Donnerstag) zu markieren. Waere Dir recht? Ich wurde dann auch die Infos zu QV und LayOut in derselben PDF eintragen.

**Comment by dariok** [comment]
Wie gesagt, daß die Marginalien fehlen ist nicht mein Fehler, sondern ist ein Fehler vom letzten Softwareupdate bei LaTeX - da muß ich auch erst auf eine Behebung warten.

Du kannst mir alles in der PDF markieren, ich kümmere mich dann drum.

**Comment by stefaniasalvadori** [comment]
Perfect!
Dann brauche ich keine neue PDF!
Einige Sachen kann ich selber korrigieren.
Du bekommst von Mir die PDF von Donnerstag mit allen Hinweisen zur Erstellung der Druck-PDF.
Danke Dir nochmals!

**Comment by stefaniasalvadori** [comment]
Perfect!
Dann brauche ich keine neue PDF!
Einige Sachen kann ich selber korrigieren.
Du bekommst von Mir die PDF von Donnerstag mit allen Hinweisen zur Erstellung der Druck-PDF.
Danke Dir nochmals!

**Comment by dariok** [comment]
Das Update ist heute gekommen, hier eine Pdf mit Marginalien
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2807435/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
@dariok DANKE!!

Die Korrekturen zu EE82-EE102 habe ich schon in der PDF von Donnerstag eingetragen.

Waere ich Dir recht, wenn ich mit 2 PDF arbeite und ab der LD (EE103) die Korrekturen in diese neue PDF einarbeite (und gleichzeitig alle textkrit. Anm. pruefe)? 

Let me know, was es Dir am besten passt. Ich faenge heute nachmittags mit der LD/PDF an.

**Comment by stefaniasalvadori** [comment]
Danke @dariok 

Dann bekommst eine PDF mit Korrekturen zu EE82 bis EE102 + eine PDF mit Korrekturen zu EE103 bis EE196

Nach meiner Erfahrung ist die Ersetzung der QV (EE##_text/intro) durch "KGK I" in PDF nicht optimal. Ich weiss es nicht mehr, ob schon vollstaendige QV sind (z.B. mit Agabe der Anm.-Nummer) oder QV, die vervollstaendigt (durch Seiten und Zeile-Angabe aus der PDF) werden muessen.
Fuer mich ist nun irrilevant - ich pruefe alle "KGK I", einige streiche ich durch (= loesche ich sie in XML, wenn sie nicht notwendig sind - weniger Arbeit fuer alle!), falls noetig trage ich in PDF-Kommentar die Seiten/Zeileangabe fuer Dich.
