### ISSUE TITLE
Einbindung des dev-Servers fuer Timo

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#281]
Wir brauchen die Einbindung des dev-Servers fuer Timo, damit er bei der Register-Arbeit helfen kann.
Kannst Du kurz hier via GitHub nochmals beschreiben, wie das funktioniert?
Oder kann er Dich irgendwo kurz (per Telefon oder Skype) erreichen?

**Comment by dariok** [comment]
- In Oxygen den Datenquellen-Explorer anzeigen (Fenster, Ansicht, Datenquellen-Explorer); dort oben rechts die Einstellungen auswählen.
- eXist-db XML Verbindung erstellen
- Host: dev2.hab.de
- port: 80
- Benutzer und Paßwort: bekannt
- Bestätigen und dann erscheint die Verbindung in der Auflistung.

**Comment by timojanssentj** [comment]
Was kommt in die Zeile "eXist Admin Client JWS?

**Comment by Wallsporn** [comment]
Bei mir:
exist/webstart/exist.jnlp

**Comment by stefaniasalvadori** [comment]
auch bei mir, soweit ich sehen kann

**Comment by timojanssentj** [comment]
Bei mir erscheint diese Fehlermeldung.
![grafik](https://user-images.githubusercontent.com/38648721/51897802-dc131d80-23af-11e9-85b3-1bceb1d85135.png)

**Comment by dariok** [comment]
In diesem Fall bitte folgendes versuchen:
In den Einstellungen zur Datenbankverbidung in der unteren Liste („Verbidungen“ oder “Connections”) die Eigenschaften der Verbindung aufrufen und bei den Details unter „XML DB URI“ den Teil „exist/“ löschen, es sollte also nur „xmldb:exist://dev2.hab.de:80/xmlrpc“ dort stehen.

Fall es auch dann noch nicht funktioniert, bitte die Verbidung komplett löschen und neu erstellen. Im Assistenten dann unter „eXist Admin Client JWS“ wiederum „exist/“ löschen (also nur „webstart/exist.jnlp“) und nach dem Bestätigen die oben genannte Änderung in den Verbindungen vornehmen.

Leider unterscheiden sich die Versionen da ein wenig.

**Comment by timojanssentj** [comment]
Danke! Installieren konnte ich die Verbindung nun, allerdings scheitert es nun an der Anmeldung. Das Fenster schließt nur kurz, um danach wieder aufzutauchen. 
![grafik](https://user-images.githubusercontent.com/38648721/51908039-f3123980-23c8-11e9-92ab-a191df62b5cd.png)

**Comment by Wallsporn** [comment]
Ahnunglose sollen Situationen nicht verwirren, aber meine Anmeldung ist nicht als guest. Aber das hättest Du sicherlich schon gesehen, Dario

![grafik](https://user-images.githubusercontent.com/28565515/51909092-02df4d00-23cc-11e9-829e-9a6963a95e14.png)

**Comment by timojanssentj** [comment]
Also: ich habe nun Oxygen auf meinem Macbook eingerichtet und nun findet er den Pfad und meldet sich an. Warum auch immer...
