### ISSUE TITLE
EE 86 Text, Uploadschwierigkeit

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#283]
Beim Upload der Text-Datei von EE 86 erscheint folgende Mitteilung:
![grafik](https://user-images.githubusercontent.com/38648721/51741228-a19b3f00-2096-11e9-90cf-24aaeecb1e2f.png)

**Comment by dariok** [comment]
Das sollte jetzt funktionieren.

**Comment by timojanssentj** [comment]
ist oben, danke!
