### ISSUE TITLE
textkrit. Anm.: -z fehlt

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#284]
Zumindest bei den dreistelligen in der LD: aay - ab - aba (oder so ähnlich)

**Comment by stefaniasalvadori** [comment]
die textkrit. Anm. "z" fehlt überhall in der PDF - auch in der einfache Variante "z"
Die Reihenfolge ist auch in anderen EE: y) [...] **a)** [...] aa)
Siehe z.B. EE92, wo eine textktkrit. Anm (die nummer i zu viennense in der Online Edition) in der PD verdoppelt wird
