### ISSUE TITLE
Vorwerk: Gesamteinleitung, Richtlinien etc.

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#285]
Die Gesamteinleitung in KGK II von Herrn Kaufmann ist fertig, sukzessive kommen Chronographie, Richtlinien, Abkürzungsverzeichnisse
Sollen wir das irgendwie formatieren? Oder einfach als Word an Dich per gitHub senden? Ablegen auf dev2 funktioniert für uns nicht, oder?

**Comment by dariok** [comment]
Die Texte könnt ihr mir einfach hier bei github einstellen, ich konvertiere sie dann und hänge sie an die nächste vollständige PDF an.
