### ISSUE TITLE
QV in PDF durch KGK I ersetzen?

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#286]
@dariok 
Wir hatten in Word sehr oft die genaue Stelle fuer QV angegeben.
EE??_text_(folgt Zitat aus transkript)#
EE??_intro_(folgt Zitat aus intro)#
Wie heute schon mitgeteilt, sind nun  diese Angaben in PDF durch "KGK I", in XML durch ein Pointer ersetzt worden.

Sind damit unsere genauen Anagaben zu den QV-Stellen einfach weg?
Wenn ja, waere es nicht besser, wenn wir die WORD-Angabe einfach uebernehmen und diese Transformation in KGK I/Pointer abschalten?

**Comment by dariok** [comment]
Der Text wird nicht in die XML übernommen, da es sonst bei der Ausgabe verwirrend wäre, ist aber an anderer Stelle noch vorhanden.
Ich kann entweder für die noch offenen Uploads die Umsetzung zum ptr wieder ausschalten oder aber den Text trotzdem mit ausgeben. Wie es euch lieber ist.

**Comment by dariok** [comment]
Im Moment wird ausschließlich der Fall behandelt, daß `EE text|intro ...##` steht, wobei zwischen intro/text und ## keine Elemente stehen dürfen.

Ich habe das nun dahin abgeändert, daß Text länger als 10 Zeichen wieder mit ausgegeben wird (unter 10 Zeichen sind Verweise auf Anmerkungen)

**Comment by stefaniasalvadori** [comment]
Harald wird sich melden und Dir sagen, was es ihm am besten passt.

Ich bin mit meinen EE fast fertig und fast alle korrekturen und nachkodierungen in XML oder in PDF eingetragen, deshalb habe ich eine Loesung gefunden, damit Du hoffentlich bequem arbeiten kannst. Hervorhebungen erlauben Dir, die QV sehr schnell in der PDF zu sehen und entsprechen in XML zu taggen.
Ich habe gesehen, dass auch Faellen, wo es zwischen intro/text und ## Text/Zitaten gab, nun als KGK I ersetzt wurden.
Ich habe nun in meinen EE - in der schnellen PDF - folgendes gemacht:

- Die  KGK I die schon in XML alle infos enthalten (Anm.Nummer etc) habe ich gruen markiert

- Die EE..# d.h. QV auf allgemeine Einheiten, die keine weitere Infos benoetigen, habe ich ebenso Gruen markiert

- Angaben wie EENr_text/info_Text## die NICHT durch KGK I ersetzt wurden (Zitat steht in der PDF vollstaendig), habe ich gruen markiert, damit Du nicht zu viel Zeit darin investieren muss, sie zu finden.

- Angaben, die durch KGK I ersetzt wurden, aber in meiner WORD Vorlage Zitate enthielten (die ich in XML nicht sehen koennte) habe ich GELB markiert und im kommentar (auf die gelbe markierung clicken) das Zitat (oder Seiten/Zeilenangaben) nochmals kopiert, damit Du die Stelle zur Verlinkung schnell finden kannst

- QV  auf EE die ich nicht Ediert habe und momentan nicht richtig zitieren kann, habe ich ROT markiert und werde in der DruckPDF ergaenzen (sind aber sehr sehr wenige Faelle)

**Comment by dariok** [comment]
Okay! Ich werde am Samstag und Sonntag durch die Texte durchgehen.

**Comment by stefaniasalvadori** [comment]
In Ordnung
Heute Abend sende ich Dir die (2) PDF
Ich habe alle genau beschrieben, was ich gemacht habe und was noch offen bleibt.
Du gibt mir Bescheid, falls Du von mir noch etwas brauchst oder falls ich Deine Arbeit erleichtern kann.

Bis nachher

**Comment by dariok** [comment]
Alles klar!
