### ISSUE TITLE
EE82/88A/92/100/101/102/103/104/106/107 - zur Erstellung der Druck-PDF

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#287]
@dariok 
Hier sende ich die Unterlagen zur Erstellung der Druck-PDF meiner EE (+ UBs EE88A). Sie sind nun auch in XML fertig. Personen- und Ortsnamen alle getaggt. 
Anhand der Register aus der PDF habe ich einige Formatierungs-Kodierungsfehler behoben. 
Im Anhang hast Du 2 PDF. In der ersten sind EE82/88A/92/100/101/102. In der zweiten sind EE103/104/106/107 (s.u. die Liste auch).
In den PDF habe ich alle Infos eingetragen, die m.D zur Erstellung der Druck-PDF (inklusive QV) notwendig sind.
Ich erklaere hier nicht in Details, da ich Erklaerungen in den PDF eingefuegt habe. 
Falls Fragen stehe ich zur Verfuegung.
In der LD sind manche textkrit. Anm. in XML zu korrigieren. Ich habe leider keine grosse Erfahrung mit XML, es ist aber ein learning-by-doing-process und habe (endlich!) einiges in diesen Tagen (vielleicht) verstanden. Deshalb lass mich wissen, ob ich noch versuchen muss, einige textkrit. Anm in der LD in XML zu kodieren/korrigieren. In generell, lass mich wissen, ob un wie ich Deine Arbeit unterstuetzen kann.

Hier nochmals die Liste der EE und wo Du sie finden kannst. 

- [x]  EE82 (PDF1)

- [x] EE88A (PDF1)

- [x] EE92 (PDF1)

- [x] EE100 (PDF1)

- [x] EE101 (PDF1)

- [x] EE102 (PDF1)

- [x] EE103 (PDF2)

- [x] EE104 (PDF2)

- [x] EE106 (PDF2)

- [x] EE107 (PDF2)

[PDF1_karlstadt-KGK2_DruckPDF_EE82bis102.pdf](https://github.com/dariok/karlstadt-issues/files/2819185/PDF1_karlstadt-KGK2_DruckPDF_EE82bis102.pdf)
[PDF2_karlstadt-KGK2_DruckPDF_EE103bis107.pdf](https://github.com/dariok/karlstadt-issues/files/2823475/PDF2_karlstadt-KGK2_DruckPDF_EE103bis107.pdf)

**Comment by dariok** [comment]
Ich schaue es über das Wochenende durch und melde mich, wenn ich Fragen habe.

**Comment by stefaniasalvadori** [comment]
No stress! und danke Dario - notte!

**Comment by dariok** [comment]
Eingriffe von meiner Seite:
- EE82 intro:
  - Anm. 16, letzter Verweis korrigiert auf Anm. ay

**Comment by dariok** [comment]
Eine PDF zur 082 (mit den weiteren Texten zur Info wegen der Seitenangaben, aber ohne, daß diese Texte bearbeitet sind): 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2825157/karlstadt-2.pdf)

**Comment by dariok** [comment]
PDF zur 088A: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2825889/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
Danke Dario - ich habe erst jetzt gesehen, da ich am WE krank war. Ich schaue mir die Druckfahnen beider EE in den kommenden Tagen an. Danach melde ich mich und gebe Dir Bescheid.

Eins ist mir aber aufgefallen: **Die Kolumnentitel müssen angepasst/korrigiert werden** - mindenstens für EE82 und 88A. Die Liste mit den von uns gesegneten Kolumnentitel findest Du in #289

**Comment by dariok** [comment]
Noch ein kleines Update für die 092, da waren 2 Verweise nicht korrekt.
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2827266/karlstadt-2.pdf)

:) Ich freue mich sehr, daß wir auf diese Weise gut vorankommen!

**Comment by stefaniasalvadori** [comment]
Hier erstmal die EE88A - die ich gerne in den kommenden Tagen an Bubenheimer weiterleiten möchte.
Alles in Ordnung nur
**INTRO**
Ein Lay-Out Vorschlag in der Überlieferung
**TEXT**
Die Folioangabe [77r] ist verschwunden. 
**REGISTER**
Personennamen und Autorenstellen (hier Augustinus und Aug.) müssen zusammengestellt werden. Das wird erst am Ende, mit Angriff ins Register, oder? Das müssen wir jetzt nicht berücksichtigen und korrigieren, oder?

[Druckfahne_EE88A_StS.pdf](https://github.com/dariok/karlstadt-issues/files/2828680/Druckfahne_EE88A_StS.pdf)

**Comment by dariok** [comment]
PDF zur EE100
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2833246/karlstadt-2.pdf)

**Comment by dariok** [comment]
Zur EE88A:
Die Autorenstellen sollten zusammengeführt werden. 2 mögliche Gründe, daß es nicht passiert: im ref (und auch im Text) der Autorenstelle sollte immer ein Punkt hinter dem abgekürzten Namen sein und die Abkürzung muß ich in der Transformation eingetragen haben. Das war z.B. bei Quintilian nicht der Fall; solche Fälle einfach kurz signalisieren, dann kann ich sie aufnehmen.

[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2835447/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
Danke! Ich habe die EE100 in der oberen Liste abgehakt!

Zu EE88A -> perfetto! Die EE leite ich sofort an Bubenheimer. Er kann die EE absegnen, danach ist sie fertig und fehlt nur das Imprimatur

Zu EE82/92/100 --> ich werde die Texte morgen oder übermorgen durchlesen. Darf ich alle 3 EE in der PDF von EE100 korrekturlesen?

**Comment by stefaniasalvadori** [comment]
@dariok 

Zu EE88A --> in TEXT --> kann man den Abstand zwischen These 6 und 7 reduzieren, damit die letzte These auf S. 126 kommt?

**Comment by dariok** [comment]
Diese Punkte möchte ich eingentlich erst dann angehen, wenn die Texte fertig sind und es tatsächlich an die Druckfahnen geht. Ich kann das manuell in der LaTeX-Datei korrigieren. Wenn ich dann aber einen Anker für ein Zitat setzen muß und neu transformiere, ist diese Änderung wieder weg – daher kommen die Dinge besser erst beim Erstellen der Druckfahnen. Vorher mache ich keine manuellen Eingriffe in die Datei, sondern die PDF ist unverändert das, was automatisch produziert wird.

**Comment by stefaniasalvadori** [comment]
In Ordnung! No problem. Inhaltlich ist die EE fertig - Bubenheimer wird dann die Druckfahnen bekommen und sie absegnen, wenn sie da sind.
Danke Dir nochmals.

**Comment by dariok** [comment]
Beim ersten Band sind irgendwo ein paar Korrekturen von Bubenheimer untergegangen – das möchte ich durch das strikte Vorgehen verhindern.
Ich bin aber guter Dinge, daß wir nicht allzu viele Probleme offen haben werden.

**Comment by stefaniasalvadori** [comment]
Er hat die EE 3mal durchgesehen - zur Sicherheit leite ich ihm die EE nochmals weiter. Ich gehe aber davon aus, dass alles richtig ist.
Das gilt auch für meine EE: Ich prüfe diese letzte PDF, es sollte aber keine größe Korrektur notwendig sein, nur Spatien und similia. Wenn diese PDF in Odnung sind, bleibt mir in den Druckfahnen nur die Kontrolle von 1) LayOut 2) QV 3) Binnendiff. Karlstadt. 
Falls ich was vergesse oder übersehe oder falls ich etwas sofort erledigen sollte, damit Du bequemer arbeiten kannst, bitte um Rückmeldung.

**Comment by stefaniasalvadori** [comment]
@dariok 
In der letzte PDF von EE88A_TEXT ist die erste textkrit. Anm. weg. 
Im Text (Ende These 4) als "z" angezeigt. Im Apparat ganz weg. 
[EE88A_StS_6Feb2019.pdf](https://github.com/dariok/karlstadt-issues/files/2835616/EE88A_StS_6Feb2019.pdf)

**Comment by dariok** [comment]
PDF 101: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2836150/karlstadt-2.pdf)

**Comment by dariok** [comment]
EE88A: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2836200/karlstadt-2.pdf)

**Comment by dariok** [comment]
PDF für 102: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2837382/karlstadt-2.pdf)

**Comment by dariok** [comment]
@stefaniasalvadori Bzgl. LD, Anm. ef und ähnliche: es steht eigentlich immer die Reihenfolge  Ort, „hinzugefügt“, falls der Text verschieden ist vom Lemma, Textzeuge. Ich ziehe jetzt „-Gl“ immer nach hinten.

**Comment by stefaniasalvadori** [comment]
@dariok 
Ja, ich bin einverstanden - "X-Gl" immer hinten

**Comment by dariok** [comment]
@stefaniasalvadori Ein Punkt ist mir in der LD bei den krit. Anm. aufgefallen: Eigentlich ist es immer so, daß wir den Text einer Lesart weglassen, wenn er dem Lemma entspricht. Es gibt aber einige Anmerkungen (nach der letzten PDF) z.B.

pn: Im Text steht „liberum arbitrium“, in der Anmerkung: „gratia a 1 ; durchgestrichen und liberum arbitrium am Rand hinzugefügt a 3“ – nach unseren bisherigen Regeln hieße das, daß in a3 „liberum arbitrium“ gestrichen ist und am Rand (wieder) hinzugefügt wurde. 
Hier wurde ja aber „gratia“ gestrichen und durch „liberum arbitrium“ am Rand ersetzt. Diesen und andere ähnliche Fälle habe ich jetzt entsprechend kodiert.

pe: im Text steht „venit“, in der Anm.: „voluit A 1–5 ; durchgestrichen und venit am Rand hinzugefügt A 5Lp“ – auch hier wurde wohl „voluit“ in A5Lp gestrichen.

In diesen Fällen ist es ja so, daß das Lemma aus der hsl. Korrektur in A5Lp stammt. An anderer Stelle hast Du dafür geschrieben „vom Editor verbessert für ... – im Anschluss an hsl. Korrektur in A5Lp“.

Ich bin aber eben mehrfach drüber gestolpert und mußte überlegen, welcher Text nun ersetzt wurde. Das solltet ihr vielleicht noch einmal besprechen.

**Comment by stefaniasalvadori** [comment]
@dariok 
Du hast völlig recht
Durch die mehrere Umformulierungen des textkrit. Apparatus habe ich den Überblick verloren und solche Anm. nicht mehr vereinheitlicht - Mein Fehler, sorry

Falls ich jetzt irgendwie helfen kann, gib mir einfach Bescheid

**Comment by Wallsporn** [comment]
Wie würdet Ihr umformulieren - im schlimmsten Falle betrifft mich das auch. Immer mit "vom Editor verbessert für ... – im Anschluss an hsl. Korrektur in ..."? ich habe das Problem auch. Zudem überschneidet sich unsere Sigle A5Lp - aber da wir die Exemplare in den Überlieferungen beschreiben und unterscheiden, ist es wohl ok

**Comment by Wallsporn** [comment]
In der WDB endet die LD übrigens - zumindest nach meinem Aufruf - auf fol. A4v, warum auch immer

**Comment by stefaniasalvadori** [comment]
@Harald
Ich wollte die Anm. „vom Editor verbessert für ... – im Anschluss an hsl. Korrektur in A5Lp“ als Standard verwenden.
Wenn aber zusätzliche Infos hatte (z.B. in Anm. pe "durchgestrichen") hatte ich anders formuliert. Ich hätte einfach vereinheitlichen sollen und diese zusätzliche Infos weglassen. 
Ich plädiere deshalb für  **„vom Editor verbessert für ... – im Anschluss an hsl. Korrektur in A5Lp"**

Die Sigel A5Lp (hast Du auch A**5**Lp?)ist auch m.E. nicht problematisch, da Sie innerhalb der Überlieferung der entsprechenden EE beschreibt ist

**Comment by dariok** [comment]
Ich kodiere diese Stellen manuell so, wie ich sie verstehe – es sind nicht extrem viele. Ich könnte die Ausgabe dann so einstellen, daß dann z.B. steht „voluit A1–5 ; voluit durchgestrichen und venit am Rand hinzugefügt A5Lp“ – das ist auf jeden Fall eindeutig. Bei der Kontrolle könnte ihr dann schauen, ob es anders heißen sollte und wir passen es dann ggf. wieder an.
Die Variante „im Anschluss an...“ müßte sich (wenn ich jetzt nichts übersehe) auch aus der Kodierung erzeugen lassen, also keine Handarbeit nötig.

@Wallsporn Ich gehe die LD absatzweise durch, weil sonst die Validierung zu lange dauert und ich nichts machen kann. Wenn ich sie hochlade, sind das immer nur die Abschnitte, die ich schon bearbeitet habe.

**Comment by stefaniasalvadori** [comment]
@dariok 
Danke - Du entscheidest, was Dir bequemer und weniger zeitaufwendig ist und ich passe mich an. Bei der Kontrolle würde ich nur die fehlerhaften Stellen/Formulierungen signalisieren. Kleine übrige Unheinheitlichkeiten in der Formulierung werden so stehen.
Die Variante  „im Anschluss an...“  was - soweit ich sehen könnte - in der Tat schon richtig kodiert.

FRAGE: Kleine Fehler in der momentan hochgeladene HTML (wo in der PDF die Stelle richtig war) habe ich gesehen - soll ich sie sofort melden oder erst in der neuen PDF eintragen?

**Comment by dariok** [comment]
Ich habe für die Formulierung „im Anschluss an“ jetzt auch eine Kodierungsvariante erstellt. Bei Gelegenheit trage ich das auch noch ins Wiki ein.

Fehler bitte erst in der neuen PDF – die HTML ist noch „vorläufig“

**Comment by stefaniasalvadori** [comment]
Ottimo! 
Danke nochmals

**Comment by dariok** [comment]
@stefaniasalvadori Anm. ry: welcher Text ist in a3 gestrichen?

**Comment by stefaniasalvadori** [comment]
- zu anm ry: a3 hat erstmal "doc Eckio und Karoˈlostadioˈ begeben" ergänzt und danach durchgestrichen, da a3 die falsche Zeile (aus dem Druck) kopiert hatte. In a3 ist die Ergänzung von a3 "doc Eckio und Karoˈlostadioˈ begeben" deshalb gestrichen 

- Anm. sb - ja bitte, Punkt innerhalb textkrit. Anm. sb-sb

**Comment by dariok** [comment]
Mecri

**Comment by dariok** [comment]
In FN 227 ändere ich „Ex“ zu „2. Mose“

**Comment by stefaniasalvadori** [comment]
ja, bitte - Danke

**Comment by dariok** [comment]
Hier die PDF zur LD:
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2898053/karlstadt-2.pdf)

**Comment by dariok** [comment]
PDF zu EE104: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2898448/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
Danke @ fuer die PDF der LD (=EE103) und der Einheit mit Beilagen (= EE104)
Ich widme mich diese Woche dem Korrekturlesen dieser von Dir bearbeiteten PDF.

Darf ich **morgen und/oder uebermorgen** einige Tippfehler (Korrekturen von HB an der LD / einzelne Buchstaben und Spatien), direkt in XML korrigieren? 

Ich versuche auch die "Fehler" im Personenregister zu beheben, bzw. die entsprechende Kodierungen in XML zu verbessern - falls Fragen (vor allem bei Referenzierung der Autorennamen wie z.B. Aug.+Autorenstelle) melde ich mich hier

**Comment by dariok** [comment]
@stefaniasalvadori Ich werde heute Abend die 106 und 107 fertigstellen, dann kannst Du alle gewünschten Korrekturen einbringen.
Ein kleiner Hinweis, den ich vergessen haben zu schreiben: Verweise auf 078 und 110 habe ich noch offen gelassen, damit Harald und Alejandro noch weiter an ihren Einheiten arbeiten können. Diese Stellen mache ich dann im nächsten Durchgang.

**Comment by stefaniasalvadori** [comment]
Alles klar - Danke! Lass mich einfach wissen, ob ich die QV auf EE78 und 110 in der PDF fuer Dich nochmals markieren soll, damit die Einarbeitung dieser Stellen beim naechsten Durchgang einfacher sei.

**Comment by dariok** [comment]
Hier die PDF zur EE106: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2903263/karlstadt-2.pdf)

@stefaniasalvadori Wenn ein QV fehlt, wäre es super, wenn Du ihn markieren kannst, damit ich ihn nicht übersehe.

**Comment by stefaniasalvadori** [comment]
Perfetto! 
Ja, ich markiere sie in der PDF gerne!

**Comment by Wallsporn** [comment]
Die Verweise auf EE110 können vorgenommen werden. Meine Einheiten sind fertig, habe nur letzten Donnerstag in derselben Einheit eine Veränderung auf XML vorgenommen. Würde morgen Vormittag noch einmal die PDF durchsehen - hier scheint, anders als in EE78, die letzte Version verwendet. Danach können von Dir, Dario, weiterbearbeitet werden.

**Comment by dariok** [comment]
Und abschließend die 107: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2905202/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
Danke @dariok !
Ich werde morgen mit den Korrekturen in XML anfangen - kannst Du bitte noch ein Back-Up der XML-Dateien der aktuellen EE machen? Ich werde nur einzelbe Buchstaben oder Spatien korrigieren, zur Sicherheit waere jedoch besser, wenn die von Dir bearbeiteten XML-Files irgendwo gespeichert sind! :-)

Ich habe das textkrit. Apparat der LD schon geprueft - nur 12 Stellen  (von mehr als 1.500) sollten leicht korrigiert werden (= die Formulierung ist nicht korrekt oder die Anm. sind nicht in der PDF angezeigt). Ich versuche selber diese Stellen in XML zu korrigieren. Wen ich nicht das nicht kann, signalisiere ich diese letzte Korrekturen in der PDF. Sonst ist alles richtig - grandioso, davvero! Merci vielmal nochmals!

Ich melde mich aber mit meinen letzten Korrekturen und LayOut Hinweise, erst wenn Du mit den EE von Alex und Harald fertig bist.

**Comment by dariok** [comment]
Alle XML-Dateien sind über github versioniert, es kann also nicht allzu viel passieren.

Layout: bisher ist noch keine Satzarbeit passiert, daher sind Layout-Anmerkungen im Moment nicht sinnvoll, sofern es nicht um spezielles wie Unterschriften etc. geht.

**Comment by stefaniasalvadori** [comment]
In Ordnung! 

Mit Lay-Out Hinweise meine ich kleine Einruckungen, die vsl. schon jetzt kodiert/einarbeitet werden koennen (z.B. ein Block-Zitat in Einleitung zur LD, Ueberlieferung). Du kannst aber ignorieren, was nun nicht sinnvoll ist, no problem

**Comment by stefaniasalvadori** [comment]
@dariok 
Kannst Du bitte eine PDF aller meinen EE nach aktuellem Stand herstellen? 
Falls es zu Zeitaufwendig ist, mach nichts - ich arbeite mit den "alten" PDF, no Problem. Die Priorität haben nun Haralds und Alex EE. 

Ich bin mit meinen kleinen Korrekturen fertig und möchte die QV in einer einzigen PDF prüfen und meine letzten Korrekturen für Dich in dieser PDF eintragen (statt in den einzelnen - 10 - PDF). Das erleicht m.E. meine und Deine Arbeit.

**Comment by dariok** [comment]
Hier die gewünschte PDF: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2942504/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
Danke!
Ich trage nun die letzte Korrekturen in diese PDF ein. Die sind wenige und betreffen: fehlende oder nicht richtige QV + sehr wenige (7-8 Stelle) textkrit. Anm. in der LD, wo kliene Details zu korrigieren sind (wenn möglich, sonst streichen wir die entsprechenden Anm. e finito!) + kleine Lay-Out Fehler (die mit der Kodierung zu tun haben, z.B. KS Anrede etc.). 
Die Binnendifferenzierungen die im Register nicht richtig sind, signalisere ich entsprechend im Register. 

Damit kannst Du in einer PDF alle meine Korrekturen haben.
