### ISSUE TITLE
Einleitungstexte und Kolumnentitel zur Druck-PDF - KGK II

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#289]
@dariok 
hier 

- [ ] Einleitung zu KGK II - Thomas Kaufmann

- [ ] Liste der Kolumnen-Titel

Die andere Einleitungstexte (Chronologie, Liste der Abk., Editionsrichtlinien) folgen in den kommenden Tagen. Koennen wir diese Texte erst in 10 Tagen senden?

FRAGE : In Vergleich zu KGK I, muessen wir in die Liste der Abk und Editionsrichtlinien nur einige Aenderungen und Ergaenzungen einfuegen. Was waere sinnvoller?
- Die die WORD-Datei der Liste Abk/Editionsrichtlinien nochmals senden
- Nur die Aenderungen und Ergaenzungen im Vergleich von den schon vorhandenen Dateien aus KGK I mitteilen? 
Lass uns wissen, was es Dir am besten passt.

[Karlstadt, Einleitung in Bd. II_TK_StS_HB_2019_02_01.docx](https://github.com/dariok/karlstadt-issues/files/2822244/Karlstadt.Einleitung.in.Bd.II_TK_StS_HB_2019_02_01.docx)
[KGK-II-KolTitel_2019_02_01.docx](https://github.com/dariok/karlstadt-issues/files/2822245/KGK-II-KolTitel_2019_02_01.docx)

**Comment by dariok** [comment]
Es sollte reichen, wenn ihr mir die paar Änderungen mitteilt; ich kann sie dann eintragen.

**Comment by stefaniasalvadori** [comment]
Hier die neue Fassung der Intro von Th.Kaufmann - ich habe eine Korrektur Bubenheimers (Reflexionen, nicht Reflektionen) eingearbeitet.

[Karlstadt.Einleitung.in.Bd.II_TK_StS_HB_UB_2019_2_4.docx](https://github.com/dariok/karlstadt-issues/files/2828773/Karlstadt.Einleitung.in.Bd.II_TK_StS_HB_UB_2019_2_4.docx)

**Comment by Wallsporn** [comment]
Ich füge hier noch einmal die Vorwerktexte an
[Kurztitelverzeichnis_2019-03-20.docx](https://github.com/dariok/karlstadt-issues/files/2991559/Kurztitelverzeichnis_2019-03-20.docx)
[ListeAbk_KGK II_StS_AZ_HB.pdf](https://github.com/dariok/karlstadt-issues/files/2991560/ListeAbk_KGK.II_StS_AZ_HB.pdf)
[ABvK_ Chron_1519.docx](https://github.com/dariok/karlstadt-issues/files/2991562/ABvK_.Chron_1519.docx)
