### ISSUE TITLE
Ligatur sp

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#29]
EE 82 und 108 Lang-S mit p wird zur Ligatur [z.B. EE 108 dispuatate]

![grafik](https://user-images.githubusercontent.com/28565515/27536799-00435486-5a71-11e7-8e63-47050df575ce.png)

**Comment by dariok** [comment]
sollte behoben sein

**Comment by Marxistin** [comment]
Stimmt
