### ISSUE TITLE
Korrekturen an PDF für EE81, 83, 108, 110

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#290]
Der Arbeitsprozess ist so super! Wir sind effektiver als vorher. Danke.
Hier meine Korrekturpunkte:

allg. Probleme bei der PDF-Transformation
-	EE81 und EE110 bei originalem Seitenumbruch  [A1v] entsteht Zeilenumbruch und Absatz (in Word vor und hinter Seitenumbruch Umbruchszeichen)
-	Probleme bei der Erfassung als Registereintrag bei:
-	a) Trennungszeichen in mit Registereintrag versehenem Wort (EE83)
-	b) Registereinträgen in Marginalien, die in getrenntem Wort des Haupttextes (EE81 und 83)
-	EE81 Marginalien überlappend [Idee: Texteinrückung]

Spezialfälle:
-	in Textapparat fälschlich „folgt“ eingefügt EE81 Anm. a und EE110 Anm. b
-	EE110 „Thome Eschau“ durch Marginalie getrennt, daher „Thome“ ausgelesen als Aquin aus, Zusammenhang mit „Eschau“ gestört
-	EE81 Verdoppelungen bei Trennungen/Marginalien/Registeransetzungen:„ornatissimi natissimi viri“
-	EE110 Verdoppelung im Titel bei dreifach getrenntem Wort
-	EE110text Trennungszeichen fehlen im Buchtitel
-	EE83 es fehlen die Punkte im Titel: Kfst Friedrich III 
-	fehlende Anführungszeichen
-	EE83text Anm. 4 Anführungszeichen nicht französisch
-	EE83 letzte Textapparatnote z fehlt [Zählung seltsam: auf g folgt z]
-	EE110text Anm. 9, 16, 19, 22, 41, 42, 44, 73, 74, 75, 76, 78, 125-127, 129-132, 135, 137 u.ö. fehlende Anführungszeichen
-	EE110 Textapp. aw, ax, ay, gi seltsame Ausrufezeichen (!)
-	EE110 Note bq durcheinander
-	EE110 Note dm Tieferstellung und Spatium fehlen
-	EE110 Note ea „hsl.“ fehlt

Spezielle Registerfehler: vgl. PDF

Registerarbeiten allgemein:
-	augenscheinlich müssen, wenn <persReg type=“vorl“> angelegt, auch die angesetzten Namen mit einem solchen eintrag versehen werden, andernfalls werden sie nicht gefunden
-	GND in Ortsregister – Fehler?
-	<idno> fehlt bei vielen Ortsregistereinträgen, die dann als fehlerhaft geparst/gemeldet
-	Unterscheidung gleichlautender Orts- udn Registereinträge (Bsp. Karlstadt)
-	bei mehreren Namenseingaben im Ortsregister entsprechend Vorlage scheinbar Problem bei der Hauptansetzung im Register
-	Probleme bei Abkürzungen von Autoren mit Werk (Plin. nat. etc.) in Format Autorenstelle bei Umsetzung ins Register
-	Petrus Zedlitz Fontinus <- diese Ansetzung! nicht Fontanus

unklare Ansetzungen
EE83intro Magister Volmar
EE83text Universitet, euer chrufürstliche Gnaden, Philippo etc.
EE81intro Petri (Drucker)
EE81 und EE110 Paulus, Petrus

[karlstadt-2-2019-02-01-hb-korr.pdf](https://github.com/dariok/karlstadt-issues/files/2825537/karlstadt-2-2019-02-01-hb-korr.pdf)

**Comment by dariok** [comment]
Danke für die Korrekturen und Anmerkungen. Es freut mich sehr, daß ihr mit dem Workflow gut arbeiten könnt :)
Ich werde mir diese Punkte gleich als nächste ansehen.
