### ISSUE TITLE
Expansionszeichen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#291]
Expansionszeichen als Problem, vgl. die Zeichen in angehängter EE110-Worddatei
Ich habe alle Zeichen in einem Vorgang einheitlich ersetzt und als Junicode formatiert. Angezeigt werden sie nun mit dem Font SBL hebrew [den ich nie eingestellt habe!] - whyever
Ergebnis ebenfalls uneinheitlich, s. in der PDF S. 419 bei praestantissimis und Wittenbergensium

![grafik](https://user-images.githubusercontent.com/28565515/52177366-0d308b00-27c0-11e9-943e-2332b9656289.png)
[EE81Text2019-01-24.docx](https://github.com/dariok/karlstadt-issues/files/2825543/EE81Text2019-01-24.docx)

**Comment by Wallsporn** [comment]
Habe mehrfach versucht, die expansion in Wittenbergensium neu zu formatieren, habe U+0027 eingegeben, nichts in XML, habe das Zeichen aus Praestantissimus herauskopiert, nichts in XML.
Das Problem hatten wir bereits
Nachtaggen???
Neueste Datei angehängt (Arbeit nur an dem Expansionszeichen)

[EE81Text2019-01-24.docx](https://github.com/dariok/karlstadt-issues/files/2826002/EE81Text2019-01-24.docx)

**Comment by Wallsporn** [comment]
Würde morgen an die XML gehen - Expansionstagging durchgehen und letzte Personentaggings (für unspezifische Bezeichnungen wie Rector, Kfstl. Gnaden etc.) - ist das ok? Ich würde dann nicht mehr Word-Dateien hochladen

**Comment by dariok** [comment]
Ja, ist okay. Ich werde morgen die LD machen und eine schnelle PDF der Epitome auf dem Stand von heute.
