### ISSUE TITLE
Schnelle PDF EE28/76/77/77a/78/79/80/84/85/86/87/88/88B789/89A/90/91/93/93A/93B/94/95/96/97/98/99/105/107A/111/111A/111B

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#294]
@dariok kannst Du bitte eine schnelle PDF folgender EE, in den Orts- und Personennamen nun vollständig verlinkt sind

- [X] EE77
- [x] EE77A
- [x] EE78
- [x] EE79
- [x] EE80
- [x] EE84
- [x] EE85
- [x] EE86
- [x] EE87
- [x] EE88
- [x] EE88B
- [x] EE89
- [x] EE89A
- [x] EE90
- [x] EE91
- [x] EE93
- [x] EE93A
- [x] EE93B
- [x] EE94
- [x] EE95
- [x] EE96
- [x] EE97
- [x] EE98
- [x] EE99
- [x] EE105
- [x] EE107A
- [x] EE111
- [x] EE111A
- [x] EE111B

**Comment by dariok** [comment]
PDF außer Epitome: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2838502/karlstadt-2.pdf)

**Comment by dariok** [comment]
PDF der Epitome nach aktuellem Stand (Intro und Text): 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2838521/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
@dariok von Alejandro Zorzin (auch via Email 07/02/2019 10Uhr43):
Hallo Dario,
danke für die prompte Übersendung der PDF's.
Folgende Texte vermisse ich darunter:
1) 110 Currus: TEXT (habe nur die PDF der Einleitung) **= EE86**
2) 120 Wagen: Einleitung (habe nur die PDF vom Text)  **= EE87**
3) 142 Verschollen: Widmungsvorrede an Kfst Friedrich [vor 22.Dez.1519] **= EE 111B**
Könntest du mir die bitten nachschicken? Es wäre toll, wenn ich sie noch hier in GÖ ausdrucken könnte (bin heute noch bis 15:30 in GÖ)
LG
Alejandro
