### ISSUE TITLE
Kleinere Probleme in Alejandros EEs

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#295]
In einigen EEs will er nicht so richtig die Personenformatierung übernehmen (meist weil sie über einen Umbruch läuft). Die Fälle haben Alejandro und ich in dieser Word-Datei dokumentiert. Vielleicht könntest Du mal drüberschauen Dario. Danke dir!
[PersonOrt-Varianten_KGK-II.docx](https://github.com/dariok/karlstadt-issues/files/2840338/PersonOrt-Varianten_KGK-II.docx)

**Comment by stefaniasalvadori** [comment]
KGK 100 Txt: Georgio Spa - latino
KGK 115 Txt: Georgio Spala - tino
KGK 103	intro: [Straßburg oder Schlettstadt] -> h**ier würde ich natürlich 2 Einträge setzen ->Ja**
KGK 103	intro: Pistorius [als Familiengruppe?] -> Familieneinträge haben wir nicht -> **auslassen?? -> ja**
KGK 103	txt: Paulus / Aufnahme im XML-Reg verbessern -> **unklar -> verstehe ich auch nicht**
KGK 116	txt: Aldenbur -gensi
KGK 127	Joanni ecci (über Zeilenbruch nicht erkannt)
