### ISSUE TITLE
EE82/88A/92/100/101/102/103/104/106/107 - bearbeitete EE für Druck-PDF

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#298]
In diesem Issue werde ich die PDF der von @dariok bearbeiteten und von Editor nochmlas geprüften Einheiten einzeln senden. (damit wir=ich die PDF und Dateien nicht verwechsele(n)). 
Die PDF, die ich hier sende, enthalten die endgültigen Korrekturen und sind nun für die LaTex Bearbeitung fertig.

- [ ] EE82
- [x] EE88A
- [ ] EE92
- [ ] EE100
- [ ] EE101
- [ ] EE102
- [ ] EE103
- [ ] EE104
- [ ] EE106
- [ ] EE107

**Comment by stefaniasalvadori** [comment]
Hier die von Bubenheimer abgesegnete PDF von EE88A (mail StS 08.02.2019 13:00)
Sie enthält nur ein paar kleine Korrekturen.
@dariok -> Bubenheimer hat die Binnendifferenzierung für diese EE schon festgelegt. Die habe ich in diese PDF **nicht** eingetragen. Binnendifferenzierungen Karstadt werden in einem Schritt anhand der Druckfahnen seitens allen Editoren gesendet, damit wir die Einheitlichkeit aller Referenzierungen abstimmen können und Korrekturen/Anpassungen vermeiden, ok?
@dariok Bubenheimer bedankt sich ganz herzlich bei Dir für Deine Arbeit, Dario - Er ist mit dieser EE sehr zufrieden

[EE88A_2019_02_08_StS_DK_UB.pdf](https://github.com/dariok/karlstadt-issues/files/2845148/EE88A_2019_02_08_StS_DK_UB.pdf)

**Comment by dariok** [comment]
Hier die PDF mit den Korrekturen zur 088A: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3077861/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
Danke @dariok 
Diese PDF habe ich @Bubenheimer weitergeleitet - er hat diese EE als fertig gesegnet. Das einzige ist eine bibliographische Angabe in Anm. 5 Text: **Winterbottom, Quintiliani**. Sie ist nicht referenziert, vermute ich. Nach Rücksprache mit UB: Bitte diese Angabe löschen (damit wir sie NICHT in die Biblio einfügen müssen) - für klassische Autoren ist sowieso keine neue Edition, nur die Stelle (Liber/cap./etc) wird angegeben. 

Soll ich direkt in XML die Stelle korrigieren? Oder willst Du es machen und mir eine neue PDF, wo ich die BD Ks auch eintragen kann? 

PS
Fettmarkierungen für fehlende Referenzierungen finde ich sehr hilfreich

**Comment by bubenheimer** [comment]
@stefaniasalvadori Sie spammen mit @bubenheimer den falschen Adressaten :(
