### ISSUE TITLE
EE109

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#299]
Kannst Du eine schnelle PDF von EE109 (Franziskaner Disputation) in den kommenden Tagen erstellen?
Timo wird nächste Woche die PDF nochmals durchlesen und prüfen.

**Comment by dariok** [comment]
@stefaniasalvadori 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2848985/karlstadt-2.pdf)

**Comment by timojanssentj** [comment]
Könntest Du bitte eine neue schnelle PDF von EE109 anfertigen? Das wäre super!

**Comment by dariok** [comment]
Hier eine PDF vom aktuellen Stand: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2906209/karlstadt-2.pdf)

**Comment by timojanssentj** [comment]
Überführung der Einheit kann beginnen. Liebe Grüße!
