### ISSUE TITLE
Die Nummerierung der Editionseinheiten in "Nr. 1" / "Nr. 2" ändern

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#3]
Bisher steht dort noch Nr. 01 / Nr. 2 usw.

**Comment by Marxistin** [comment]
Auch hier hoffen wir, dass es bis zum 16. Mai durchgeführt werden kann.

**Comment by dariok** [comment]
Die Ergebnisse sind in den Links unter #1 zu sehen.

**Comment by Marxistin** [comment]
Die Zählung der Dokumente in "contents" auf der Spielwiese gefällt mir sehr gut.
