### ISSUE TITLE
Verdoppelung der Punkte

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#30]
Wie schon Mittwoch besprochen: Verdoppelung der Punkte am Ende eines Eintrags

**Comment by Marxistin** [comment]
Tritt auf am Ende "Editionsvorlage" und "Weitere  Exemplare"

**Comment by dariok** [comment]
Falls sich noch Doppelungen finden, bitte wieder öffnen oder einen neuen Issue anlegen.
