### ISSUE TITLE
Probleme Transfo HTML

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#301]
Fehler in Transformation - wichtig für Kontrollen
EE77intro
Fehler in Überlieferung und bibl. Angaben (in XML ok, in HTML verschwunden)

![grafik](https://user-images.githubusercontent.com/28565515/52966446-9bebfd00-33a7-11e9-8c61-73e2641e326d.png)

**Comment by dariok** [comment]
Ausgabe Literatur in FN etc. in https://github.com/dariok/ed000240/commit/ff2a28719f8d47af404b0fb84f690b99f956af5a
Ausgabe Literaturlisten in Einleitung in https://github.com/dariok/ed000240/commit/c76f27cc28447970f78edd26c61f25b7045b2404
