### ISSUE TITLE
PDF EE 78, 81, 83, 108, 110

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#302]
Bitte um schnelle PDF von EE 78, 81, 83, 108, 110

**Comment by dariok** [comment]
Hier eine PDF aller Texte nach aktuellem Stand:
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2898073/karlstadt-2.pdf)

**Comment by Wallsporn** [comment]
Danke. schaue morgen rein und signalisiere dann eventuelle Problem

**Comment by Wallsporn** [comment]
Hallo Dario,
keine Ahnung, warum aber EE78 der neuen PDF entspricht nicht dem letzten Stand, den ich am Donnerstag hochgeladen habe. Die Unterschiede sind z.B. in der Einleitung gleich in der 1. Anm. sichtbar. Bitte eine PDF auf neuester Grundlage erstellen. Ich wollte kontrollieren und Fehler signalisieren, damit Du die endgütige XML herstellen kannst

**Comment by dariok** [comment]
Hier nochmal eine PDF zur 078 nach dem Stand, der gerade auf dev2 ist: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2905228/karlstadt-2.pdf)

**Comment by Wallsporn** [comment]
Danke, nun ist sie auf dem neuesten Stand!

**Comment by dariok** [comment]
@Wallsporn @stefaniasalvadori Wo soll ich jetzt weitermachen? Sprich, welche Texte sind jetzt so weit, daß ich ans XML kann?

**Comment by stefaniasalvadori** [comment]
@dariok - das wird Dir @Wallsporn signalisieren

von mir aus (= von meinen EE), gibt es erstmal nichts zu bearbeiten - ich sende meine letzten Korrekturen, wenn alle andere EE (von HB, AZ und TJ) bearbeitet sind

**Comment by Wallsporn** [comment]
@dariok 
Bitte mit EE81, EE83, EE108, EE110 weitermachen, Quick-PDF ist gecheckt und mit Kommentaren sowie einer Beschreibung der vorliegenden Fehler in Worddoc angehängt
Die meisten sind kleine Transformationsfehler. Ungefähr an 10 Stellen handelt es sich um Tippfehler, Fehlkodierungen/formatierungen oder anders Vergessenes meinerseits - soll ich das in XML nacharbeiten? Habe alles vermerkt (PDF und Doc)
[karlstadt-2-2019-02-24-hb.pdf](https://github.com/dariok/karlstadt-issues/files/2910975/karlstadt-2-2019-02-24-hb.pdf)
[Manuskript_EE81_83_108_110_Fehler-2019-02-27.docx](https://github.com/dariok/karlstadt-issues/files/2910978/Manuskript_EE81_83_108_110_Fehler-2019-02-27.docx)

**Comment by dariok** [comment]
@Wallsporn Bei Nr. 106, Einleitung soll ein Punkt hinter die Folio-Angabe und vor die Anmerkung zur Handschirft; bisher hatten wir dort keinen Punkt, da die Anmerkung („Kanzleihandschrift...“) ja mit Halbgeviert abgetrennt ist.
Soll dort jetzt generell ein Punk hin und dafür der Strich weg?

**Comment by dariok** [comment]
PDF zur EE083/Nr. 106: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2912507/karlstadt-2.pdf)

**Comment by dariok** [comment]
PDF zur EE108 / Nr. 137: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2914947/karlstadt-2.pdf)

**Comment by dariok** [comment]
PDF zur EE081: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2917238/karlstadt-2.pdf)

**Comment by dariok** [comment]
@Wallsporn Zur 110 Einleitung:
- FN2: falscher Verweis kodiert (später ID in Bibliographie geändert?)
- FN18: die angegebene Stelle befindet sich in einer FN
- FN19: jede Erwähnung mit Zeilenverweis?
- FN36: Da ist kein Text, auf den verwiesen werden soll...
- FN76: „BR“ → „Br“: (Tippfehler wie auf S.544, das habe ich daher ebenfalls korrigiert.)

Mehrere Stellen: Verweise auf Texte von Stefania und Alejandro: diese kann ich erst machen, wenn die anderen nicht mehr an ihren Texten arbeiten.

**Comment by Wallsporn** [comment]
@dariok 
- FN 2: ID ist @friedensburg_geschichte_1917 statt @friedensburg_geschichte
- FN 18: nein, der Satz "exemplum suarum literarum penes me extat" ist im Text (Missverständnis?)
- FN 19: wenn möglich, ja - ich kann die genauen Stellen angeben
- FN 36: Verweis auf "leguleius"
- FN 76: danke! War mir im Nachhinein auch aufgefallen
Soll ich das nachkodieren?

**Comment by dariok** [comment]
@Wallsporn 
Die Erwähnungen für FN 18 bitte durchgeben. Auf B4r finde ich nichts, auf C2v 3 STück, C5r gibt es nicht, dafür aber Treffer auf D2v...

**Comment by dariok** [comment]
@Wallsporn Intro, FN 70: „faces subdere“ nicht im Text, sondern „faces subdidisse“; später: „argumenta coniugata“ nicht im Text, sondern „argumentorum, quae coniugata appellantur“ (die anderen Stellen in den FN dazu). Ich habe die Stellen im Text genommen.

**Comment by Wallsporn** [comment]
@dariok 
FN 19: oje, was ein Durcheinander, entschuldige bitte. Folgende Stellen sind anzugeben:
A4v Emserius scribendae adversum me
C2v 	Emserius ab Asa --- neque vereor vel Eckium vel Emserium
C3r iactator Emserius
D2v 	Emserio vituperoni
D5r Emserus eius me plumis pinxit

Die Fußnote kann so aussehen:
Karlstadt führt den Brief Emsers explizit als Anlass für die Epistola an (EE110text_Emserius scribendae adversum me#); weitere Verweise auf ihn EE110text_neque vereor vel Eckium vel Emserium#, EE110text_Emserius ab Asa#, EE110text_Emserio vituperoni# und EE110text_Emserus eius me plumis pinxit#.

**Comment by Wallsporn** [comment]
FN 70: beides richtig

**Comment by dariok** [comment]
@Wallsporn: Danke, ist so umgesetzt!

**Comment by dariok** [comment]
@Wallsporn Anm. d, e etc.: Geviertstrich steht, da als Kommentar markiert.

Anm. 153: Die ersten Verweise sollen auf 103 gehen, nicht auf 110, oder?

**Comment by Wallsporn** [comment]
Anm. 153: Ja! (grr, verwechselt)

Geviertstrich überall da, wo als Kommentar markiert? Ich dachte, das wäre nur eine Behelfskonstruktion, weil die Transformation nicht anders funktionierte. Klassisch im Textapparat wäre ein Semikolon oder Geviertstrich. Wir haben nun beides. Daher meine Frage (in Absprache mit Stefania): wäre ein Austauch mit Semikolon aufwendig und v.a. gefährlich hinsichtlich ungewollter Überschreibungen? Möglich müsste es sein. Aber wenn zuviel Stress, lassen wir es. Unsererseits wäre es ok, denn Stefania und ich würden am Ende den Textapparat noch einmal komplett überprüfen

**Comment by Wallsporn** [comment]
@dariok 
Bitte um Ersetzung einer falschen Abkürzung in EE110text Anm. 275:
Statt Bern. i.c.c.s. 10,8
bitte
Bern. SC 10,8
Danke!

**Comment by dariok** [comment]
Bzgl. Kommentar: Die Markierung ist für allgemeine Ergänzungen zu Standardformulierungen gedacht; die normalen Formulierungen werden in die passende Kodierung umgesetzt, wenn sie dem üblichen Aufbau entsprechen. Gibt es aber eine Ergänzung dazu im Freitext würde das nicht klappen und dieser Text als Teil der Angabe der Textzeugen interpretiert; dafür ist die Vorlage Kommentar gedacht.
Ich korrigiere diese Fälle bei der Durchsicht, da ich sie ja sofort sehe.

**Comment by dariok** [comment]
@Wallsporn: bzgl. der Anmerkung, daß das Lemma nicht wiederholt werden muß: ist korrigiert.

Aber eine Frage zu Anm. cs: Lemma ist „exemplum“, die Anm: „folgt rursus A, B; gestrichten A1Br, A5Lp“ – hier ist also „exemplum“ gestrichen? Wenn „rursus“ gestrichen ist, wäre das hier nicht einheitlich – wie würden wir das behandeln? So belassen oder „rursus“ wiederholen?

**Comment by dariok** [comment]
Und hier die PDF zur 110: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2945259/karlstadt-2.pdf)

Quid nunc?

**Comment by Wallsporn** [comment]
Danke! Ich sehe mir die PDFs nächste Woche an. Neuer Issue mit EE von Alex entsteht gleich
