### ISSUE TITLE
EE77, 77A, 78, 79, 80, 84, 85, 86, 87, 88B, 89, 89A, 90, 91, 93, 93A, 93B, 94, 95, 96, 97, 98

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#303]
- Bitte folgende EE in PDF umwandeln:
- [x] EE77,
- [x]  77A,
- [x]  78,
- [x]  79,
- [x]  80,
- [x]  84,
- [x]  85,
- [x]  86,
- [x]  87,
- [x]  88B,
- [x]  89,
- [x]  89A,
- [x]  90,
- [x]  91,
- [x]  93,
- [x]  93A,
- [x]  93B,
- [x]  94,
- [x]  95,
- [x]  96,
- [x]  97,
- [x]  98
- Randgl. von EE78 werden angehängt
- Bitte hebräische und (evtl.) griechische Zeichensätze nun einsetzen
- Ist es noch möglich, EE78text und Randgl. von EE78 separat zu transformieren?
- Mitgeschickt wird auch ein kleiner Erläuterungstext mit der Frage, ob er vor dem Text von EE78 mit Sternchen an "Text" eingesetzt werden kann. Wenn nicht, bitte woanders.
- Probleme: 
-- EE95text läßt sich nicht transformieren, daher angehängt
-- EE86 und Randgl. von EE78: Expansionszeichen in HTML wieder nicht umgesetzt -> in Word noch einmal eine Ersetzung proben?
-- EE91: 
--- Textapp.-Anm. aw) durcheinander
--- Textapp.-Anm. cz) und da) mit Spatium vor Semikolon
--- Anm. 1 ein zusätzlicher, unnötiger Punkt am Ende generiert

[EE78_text_hslRGL-2019-03-06.docx](https://github.com/dariok/karlstadt-issues/files/2945979/EE78_text_hslRGL-2019-03-06.docx)
[Epitome-Editions-Hinweis.docx](https://github.com/dariok/karlstadt-issues/files/2945980/Epitome-Editions-Hinweis.docx)
[EE95_text_2019-01-11.docx](https://github.com/dariok/karlstadt-issues/files/2945981/EE95_text_2019-01-11.docx)

**Comment by Wallsporn** [comment]
Noch offen: EE99, 105, 107A, 111, 111A

**Comment by Wallsporn** [comment]
Nachtrag: die Expansionen in EE78 können wir am Montag sonst ändern, wenn nötig, vorher schlecht

**Comment by dariok** [comment]
PDF zur EE077: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2947601/karlstadt-2.pdf)

**Comment by dariok** [comment]
PDF zur 077A: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2948589/karlstadt-2.pdf)

**Comment by dariok** [comment]
Bei 078 ist für die Expansionen ein ganz anderes Zeichen hinterlegt – vmtl. eine automatische Ersetzung von Word. Das habe ich bereits ersetzt und bin in der 078.

**Comment by Wallsporn** [comment]
Super, danke! In den Randglossen wird es leider wohl ähnlich aussehen.

**Comment by dariok** [comment]
Kein Problem, das läßt sich leicht erledigen.

Eine anderes Sache ist mir aufgefallen, die ihr besprechen solltet: Wenn in einem Handexemplar ein fehlerhafter Text korrigiert ist, soll dann nur stehen „korrigiert“ oder „hsl. korrigiert“?

**Comment by Wallsporn** [comment]
Ja, stimmt. Das müssen wir kurz durchdenken.

**Comment by Wallsporn** [comment]
Zurück zu Expansion: die Namenseinträge mit falchen Expansionszeichen konnten ja nicht automatisch als Registereintrag ausgelesen werden - müssen die nachgetaggt werden?

**Comment by dariok** [comment]
Die müßten nachgetragen werden. Im Text sind es knapp 40 Fälle, in der Einleitung 2.
Mit dem Plugin sollte das recht schnell gehen. Soll ich das machen?

**Comment by Wallsporn** [comment]
Du hast sicherlich anderes zu tun - wir können das nachtaggen, nachdem Du soweit fertig bist. Wenn die Stellen irgendeine Sichtbarkeit bekommen würden, wäre das hilfreich.

**Comment by dariok** [comment]
Hier die PDF zur 078, die Randglossen stehen hinter dem Text.

Alle Stellen, die von euch zu prüfen sind, sind als TODO und/oder Fehler markiert (blaue bzw. rote Markierung), damit solltet ihr diese Stellen leicht finden. Bei Fragen bitte einfach melden.

**Comment by Wallsporn** [comment]
Danke! Das wird hoffentlich schnell gehen, ich schaue mir die XML demnächst an, wahrscheinlich arbeiten wir daran nächste Woche zusammen.
Zwei Fragen sogleich: 
1) Die Seitenumbrüche stehen alle wieder in einer separaten Zeilen und unterbrechen damit den Fließtext. Musst Du das im letzten Durchgang bearbeiten und wir können es ignorieren? Andernfalls wäre es besser, wenn Du diesen "Fehler" behebst und ich dann die PDF an Alex zur Kontrolle weiterleite. 
2) Ebenso verdoppeln sich manchmal eckige Klammern, vgl. Anm. 55 in Randgl. (PDF der EE78,  S. 53). Das Prinzip, wann Verdoppelungen auftreten, habe ich noch nicht verstanden. Egal: ebenso im letzten Durchgang oder gleich?
Danke und bis dahin

**Comment by dariok** [comment]
ad 1) Das würde ich beim Erstellen der Druckfahnen am Stück machen. Wenn es aber zu sehr irritiert, kann ich das aber auch heute angehen. 

ad 2) Sind das immer Auslassungen oder auch andere Fälle?

**Comment by Wallsporn** [comment]
ad 1) Ok, dann teile ich das Alex mit
ad 2) Bei Auslassungen [...], aber eben nicht bei jeder, siehe Beispiel
![grafik](https://user-images.githubusercontent.com/28565515/54275342-abb3c700-458a-11e9-933c-9fd95974ca05.png)

**Comment by Wallsporn** [comment]
Revidiere: ich glaube, hier liegt ein Fehler im Original vor - es ist nur diese eine Stelle. Das werde ich anmerken und muss danach getilgt werden

**Comment by dariok** [comment]
PDF zur EE079: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2972193/karlstadt-2.pdf)

**Comment by dariok** [comment]
@Wallsporn Frage zur Vereinheitlichung: Bei hsl. korrigierten „Unterexemplaren“ wie „A5Lp“ schreiben Stefania und Du „_hsl. korrigiert_ (ggf. in x) _A5Lp_“; Alex schreibt hingegen „_korrigiert in ASch_“ – hier solltet ihr ggf. überlegen, ob ihr das vereinheitlichen wollte.

**Comment by dariok** [comment]
@Wallsporn Bitte auch klären: in EE091 sind Überschriften als mehrere Absätze kodiert (z.B. A3r) – soll das so sein oder sollte das nicht besser als Überschrift ausgezeichnet werden?

**Comment by Wallsporn** [comment]
ad 1) Ja, es ist sicher besser, es zu vereinheitlichen, auch wenn sich ASch immer nur auf die Glossen Schliebens bezieht. Alex geht die gesamte EE78 gerade durch, wir können nebenbei in der XML per Suchen den Zusatz "hsl." einfügen.

ad 2) auch geht Alex die gesamte Einheit durch und gibt an, was als Überschrift zu formatieren ist - einige Heraushebungen im Original sind keine Überschriften, andere Überschriften sind nicht herausgehoben etc. Frage: können wir das noch in Word nachbearbeiten oder besser schon in XML? Dann an Dich schicken oder wie?

**Comment by dariok** [comment]
ad 1) den Zusatz braucht ihr nicht manuell einfügen. Die Mehrzahl der Stellen ist bereits als app kodiert und man muß nur einmal die Kodierung per Suchen und Ersetzen anpassen.
Bitte auch im Moment die XML nicht überschreiben, weil sonst die Querverweise wieder verloren gehen!

ad 2) bitte in der PDF markieren oder nach Abschluss der Arbeiten an diesem Issue in der XML.

**Comment by Wallsporn** [comment]
Kurze Nachfrage: nachdem Du die PDF verschickt hast, bist du doch soweit fertig, dass wir noch einmal in der XML nacharbeiten können, oder? Das machen wir ja gerade. Hochgeladen aus Word wird dann natürlich nicht mehr.

**Comment by dariok** [comment]
Wenn ich einen Issue fertig habe, könnt ihr im XML korrigieren. Aber bis dahin soll ich ja auch Querverweise machen, z.B. aus der Auslegung in die Flugblätter und von denen in die Epitome – dafür muß ich an den Dateien arbeiten, die im Issue stehen.

**Comment by Wallsporn** [comment]
Also noch keine kleinen Verbesserungen unsererseits in EE78 möglich, ja?

**Comment by Wallsporn** [comment]
Würde Dir dennoch EE78 bald schicken, weil dort einige Seltsamkeiten (Verdoppelungen bei Worttrennung und Marginalie; Ausfall ganzer Sachanmerkungen und Textapparatnoten bzw. seltsame Aufspaltung und Verdoppelung letzterer) auftauchen, zudem die letzte Seite in der PDF vollkommen fehlt.

**Comment by dariok** [comment]
Genau, an den Texten, die hier im Issue gelistet sind, noch keine Änderungen machen.
PDF mit Anm. zur 078 kannst Du mir schicken, ich schaue dann als nächstes da rein.

**Comment by Wallsporn** [comment]
Fehler in EE78

Einleitung: 
Anm. 5 wird im Text angezeigt, aber der Inhalt fehlt.

Text:
1. Solange die Seitenangaben in einer Zeile für sich stehen, passt die Zeilennummerierung nicht zu den Zeilenzuordnungs-Nr. für die Randglossen. Immer eine Zeile zu viel.
2. fol. B1r: Marg. „Oseae. vii“ gehört zur Anfangszeile von fol. B1v
3. fol. B3v: Marg. „Psal. cxliii.“ und „Iob, xiiii.“ gehören zur Anfangszeile von fol. B4r
4. fol. C3v: Marg. „Matth. vi“ gehört zur Anfangszeile von fol. C4r
5. Wort(teil)verdoppelun(gen):
	B2v Z.25: brium brium adolescentiae 
 	C1r Z.6: regnabunt. regnabunt. Piam 
 	C1r Z.21 vocavi. vocavi. multa 
6. Aus TxtApp „hochgezogene Versatzstücke“
 	B4r Z.8 am Zeilenende: „xv. A“ (reingezogen!)
 	B4r Z.10 am Zeilenende: „ii. A“ (reingezogen!)
7. Anm. cp streichen, durch Transformation unnötig generiert!
8. Anm. dh) fehlt am Ende Ak
9. Anm. ar) ay) bc) bm) bn) bo) bs) bt) bx) ca) cb) cq) dq) dr) dw) und ea) statt „hinzugefügt“ steht dort „folgt“
10. Anm. du) folgt  ist zu streichen
11. Am Textende fehlt die ganze Schlussseite D4r!

[karlstadt-EE78-20190319-hb-az.pdf](https://github.com/dariok/karlstadt-issues/files/2985707/karlstadt-EE78-20190319-hb-az.pdf)

**Comment by dariok** [comment]
Ich wäre jetzt einmal mit allen Texten hier durch, hier eine komplette PDF nach aktuellem Stand:
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/2991291/karlstadt-2.pdf)

Soll ich die Probleme in der 078 gleich angehen oder abwarten, bis ihr einmal kontrolliert habt?

**Comment by Wallsporn** [comment]
Hallo Dario, vielen Dank! Ein Problem: wir müssen leider noch einmal die EE86 bearbeiten, da wir gestern sensationell die verloren geglaubten Texte des Currus wieder entdeckt haben. Ich hatte Dir das gestern per Skype mitgeteilt (in der Hoffnung, dass Du noch nicht mit der Bearbeitung durch bist). Lass uns bitte kurz telefonieren oder skypen. Wann?

**Comment by Wallsporn** [comment]
Fortgang:
- EE99, 105, 107A, 111, 111A sind nicht auf dem letzten Bearbeitungsstand (ich hatte sie als noch offen bezeichnet, hochgeladen wurde der letzte Stand Freitag und Montag = 15./18.3.).
- Ebenso EE110B, an dem ich gerade eine letzte Verbesserung vorgenommen habe - würde ich hochladen, ok?
- Dann Einarbeiten des angehängten Vorwerks:
-- Abkürzungsverzeichnis (Korrigierte PDF)
-- Kurztitelverzeichnis
-- Chronologie
-- Editionsrichtlinien in XML - kann ich hier nicht anhängen - schicke ich per Mail
- Ich schicke Dir heute noch Korrekturen an Randglossen von EE78. Bitte diese bearbeiten.
- Danach schicken Stefania und ich die Korrekturen an unseren EE.
- Dann die Korekturen an den EE von Alex.
- Danach kommt der Currus (EE86) in letzter Version.
[ListeAbk_KGK II_StS_AZ_HB.pdf](https://github.com/dariok/karlstadt-issues/files/2991464/ListeAbk_KGK.II_StS_AZ_HB.pdf)
[ABvK_ Chron_1519.docx](https://github.com/dariok/karlstadt-issues/files/2991465/ABvK_.Chron_1519.docx)
[Kurztitelverzeichnis_2019-03-20.docx](https://github.com/dariok/karlstadt-issues/files/2991467/Kurztitelverzeichnis_2019-03-20.docx)

**Comment by dariok** [comment]
Das ist ja eine wunderbare Fügung! :)
Ich bin gerade im Zug und erst gegen 14.45 angekommen (in Heidelberg). Wir können dann ger.ne kurz telefonieren oder aber heute Abend per Skype.

Die meisten Verweise auf die 086 gehen aber sowieso auf die Einträge gesamt, das ist recht leicht zu rekonstruieren. Am besten also die bisherige Word-Datei ergänzen und neu hochladen, wenn alles fertig ist. Ich habe die Bearbeitungen alle versioniert

**Comment by Wallsporn** [comment]
Anbei die PDF der EE78 mit allen Korrekturen (in Intro, Text und Randglossen). Wenn Du, Dario, fertig bist, würden wir in der XML-Textdatei noch einige wenige Korrekturen vornehmen. In die Randglossen habe ich alle Korrekturen eingetragen, auch die, die über Transformationsfehler hinausgehen (vergessene Bibelstellen o.ä.). Wenn wir das übernehmen sollen, sag bitte kurz Bescheid.
[karlstadt-EE78-20190321-hb-az.pdf](https://github.com/dariok/karlstadt-issues/files/2992478/karlstadt-EE78-20190321-hb-az.pdf)

**Comment by dariok** [comment]
Hier eine PDF aller EE auf aktuellem Stand: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3028482/karlstadt-2.pdf)


@Wallsporn leider konnte ich aus der PDF nicht alle Korrekturen ersehen – insbes. bei den grünen Markierungen, da hier keine weiteren Informationen standen. Bitte noch einmal genau vergleichen und ggf. noch einmal eintragen.

**Comment by Wallsporn** [comment]
Hallo Dario,
beziehst Du Dich auf die Korrekturen zur EE78? Ich habe meine PDF sowohl mit Acrobat als auch Foxit geöffnet und konnte alle Kommentare lesen.

**Comment by dariok** [comment]
Gut, dann prüfe ich das später noch mal am anderen Rechner. Die Punkte, die offensichtlich waren, habe ich schon erledigt, es sollten nur ein paar wenige betroffen sein.

**Comment by Wallsporn** [comment]
Hallo Dario,
die EE78 müsste neu bearbeitet werden, teilweise sind neue Fehler drin, ich werde Dir eine PDF schicken. Fehlerhaft sind insbesondere auch die Zuordnungen der Sachanmerkungen. Frage: wir würden auf Grund der Currus-Entdeckungen noch an einigen Fußnoten arbeiten müssen; es kämen sogar ein paar dazu. Sollen wir das in die XML eintragen? Danach könntest Du die Datei auf letztem Stand überarbeiten.

**Comment by Wallsporn** [comment]
Letzte Fassung von EE86 Currus
Datei wurde nicht auf Validität geprüft, da kein Upload möglich war (WDB-Störung)
Bitte wieder einen editorischen Hinweis einbauen mit Asterisk an Überschrift "Text"
Thanks!

[EE86text_2019-04-02.docx](https://github.com/dariok/karlstadt-issues/files/3042192/EE86text_2019-04-02.docx)
[EE 86_intro_2019-04-02.docx](https://github.com/dariok/karlstadt-issues/files/3042193/EE.86_intro_2019-04-02.docx)
[EditHinweisEE86Text.docx](https://github.com/dariok/karlstadt-issues/files/3042194/EditHinweisEE86Text.docx)

**Comment by Wallsporn** [comment]
Hallo Dario,
ich schicke Dir die PDF von KGK II nur mit Änderungen in EE78. Da ist etwas mit den Anmerkungen grundsätzlich durcheinander gegangen. Noch sind auch die Zuordnungen von Glossen zu Textseiten nicht gut - weiß nicht, ob Du das erst mit LaTeX lösen wirst, aber so ist die doppelseitige Gegenkontrolle schwierig. Ok, mit Bitte um Bearbeitung und vielen Grüßen zurück.  Harald

[KGK-II_2019-04-04.pdf](https://github.com/dariok/karlstadt-issues/files/3043859/KGK-II_2019-04-04.pdf)

**Comment by dariok** [comment]
Leider sind hier immer noch nicht die fehlenden Referenzierungen eingetragen. Das wird mich jetzt erst einmal ein wenig Zeit kosten, bis ich anfangen kann.

**Comment by dariok** [comment]
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3050793/karlstadt-2.pdf)

Ich hänge den Text nochmal hintereinander ausgegeben an. Dabei ist dann aber die Seitenzahl in der Seitenzählung enthalten.
Gerade aufgrund der Zeilenlänge sollten die Seitenzahlen übrigens nicht in der Zeile stehen, sondern in einer eigenen Zeile davor. So ist auch der Seitenwechsel besser nachvollziehbar.

Weitere Anmerkung: Typographische Anmerkungen wie „Zeile zu lang“ sind vor den Druckfahnen nicht sinnvoll. Um diese Punkte kümmere ich mich erst dann, wenn ich den Umbruch und die Typographie anfange (dazu gehört auch das Abstimmen des Parallelsatzes in der Epitome).
Das kann ich erst sinnvoll machen, wenn der Text stabil ist und alle Referenzierungen inkl. Binnendifferenzierung erfolgt sind, denn sonst habe ich doppelte Arbeit.

**Comment by Wallsporn** [comment]
Hallo Dario,
der Text endet weiterhin unvermittelt auf fol. D4r. Wurde bereits in vorletzter Pdf angemerkt.
Welche Referenzlerungen fehlen? Worauf beziehst Du Dich? Mir unklar, ist nicht meine EE und daher kann ich nicht wissen, worum es geht. Bitte genauer beschreiben. Die Glossen sind nun wieder hinter dem Text - sollte das so?

**Comment by Wallsporn** [comment]
Angehängt sind EE78intro und EE78text neueste Version (nach Durchsicht der Scans)
- Bitte fettgedruckten Text auch fettgedurckt ausgeben
- Nach Transformation in XML und Upload bitte noch einmal aus WDB nehmen
[EE86text_2019-04-09-1.docx](https://github.com/dariok/karlstadt-issues/files/3057906/EE86text_2019-04-09-1.docx)
[EE 86_intro_2019-04-09.docx](https://github.com/dariok/karlstadt-issues/files/3057907/EE.86_intro_2019-04-09.docx)

**Comment by Wallsporn** [comment]
Habe noch einmal EE86 zurückgezogen, da Stefania falsche Expansionszeichen bemerkte. Wir gehen die Dateien noch einmal durch und senden sie dann.

**Comment by dariok** [comment]
Zur Epitome: Es waren insgesamte ca. 60 Personen noch nicht referenziert. Diese habe ich nachgetragen.
Daß die RG dahinter stehen, ist Absicht: den Parallelsatz gehe ich erst an, wenn der Text fertig ist. Wenn es problematisch ist, den Parallelsatz so zu verwenden, dann ist es vielleicht hintereinander besser.

Gut, dann warte ich nochmal auf den Currus. Werde dann allerdings in dieser Woche nicht mehr dazu kommen, hier tätig zu werden.

**Comment by Wallsporn** [comment]
Hm, einfach signalisieren, dann hätten wir es durchgeschaut. An einigen EE arbeiten auch auf unserer Seite mehrere Leute mit. Dass Du Dich damit aufhältst, halte ich nicht für sinnvoll.
EE86 ist noch mal an Alex zur letzten Durchsicht, es geht um hsl. Sonderzeichen. Danach (morgen) kann ich sie einfach hochladen.
Es klingt so, als ob es Dir jetzt an Arbeit mangelt. Aber die EE78 war abgebrochen (fol. D4r), und die späteren EE99, 105, 107A, 111, 111A waren auch in letzter PDf nicht auf dem neuesten, hochgeladenen Stand.

**Comment by dariok** [comment]
Daß die Referenzierungen noch zu machen sind, haben wir schon besprochen: Diese Stellen sind als TODO markiert, werden bei der Validierung als Fehler angezeigt und online farbig hinterlegt. Zum Ausfüllen dieser Stellen hatte ich ja auch schon ein oXygen-Plugin erstellt, das euch das Abrufen erleichtert.

Zu den genannten 5 EE: ich hatte nicht gesehen, daß diese überarbeitet waren. Das bitte immer signalisieren (am besten mit einem neuen Issue).

**Comment by dariok** [comment]
Um die noch offenen Referenzierungen schneller zu sehen habe ich jetzt 2 Änderungen eingefügt: online werden auch bibliographische Angaben ohne Referenz angezeigt (rot hinterlegt), in der PDF werden ab jetzt Stellen ohne Referenz fett gedruckt.

**Comment by dariok** [comment]
Hier mit D4r der Epitome und den 5 genannten EE auf dem letzten Stand: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3064031/karlstadt-2.pdf)
