### ISSUE TITLE
Harald EE81, 83, 108, 110 Vor-Manuskript

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#307]
@dariok 
Ich schicke die PDF meiner EE mit den letzten Korrekturen bzw. Hinweisen auf QV. Bei den Korrekturen handelt es sich um solche (Textapparat, Verdoppelungen von Querverweisen, fehlende ebd.), die ich nicht in der XML eintragen konnte. Die überlappenden Marginalien habe ich nicht angemerkt, da sich das Layout noch änderte. Fall gewünscht, bitte kurz Nachricht an mich. Ebenso bei Anfragen wegen Nachtagging.  - **Bitte erst nach Fertigstellung des Currus EE86 bearbeiten.**

[karlstadt-pdf_EE110-2019-04-09-hb.pdf](https://github.com/dariok/karlstadt-issues/files/3069310/karlstadt-pdf_EE110-2019-04-09-hb.pdf)
[karlstadt-pdf-EE81-2019-03-21-hb.pdf](https://github.com/dariok/karlstadt-issues/files/3069311/karlstadt-pdf-EE81-2019-03-21-hb.pdf)
[karlstadt-pdf-EE83-2019-03-21-hb.pdf](https://github.com/dariok/karlstadt-issues/files/3069312/karlstadt-pdf-EE83-2019-03-21-hb.pdf)
[karlstadt-pdf-EE108-2019-03-21hb.pdf](https://github.com/dariok/karlstadt-issues/files/3069313/karlstadt-pdf-EE108-2019-03-21hb.pdf)

**Comment by dariok** [comment]
@Wallsporn: Zu 110 Text, Anm. 9: einfache Anfühungszeichen hatten wir bisher nicht (außer bei Zitaten in Zitaten). Kommt dieser Fall jetzt häufiger vor? Dann müßte die Kodierung angepaßt werden.

**Comment by Wallsporn** [comment]
Benutze ich immer bei Übersetzungen, um sie von Zitaten zu unterscheiden. Wenn es problematisch ist, einfach steichen; ich würde dann aber angebellt in "angefahren" ändern

**Comment by Wallsporn** [comment]
Grundsätzlicher Hinweis zur EE81: Positionierung der Marginalien habe ich in PDF nicht angemerkt, muss aber erfolgen. Falls etwa dafür notwendig, bitte melden

**Comment by dariok** [comment]
Positionierung der Marginalien erfolgt, wenn ich den Umbruch mache; der folgt erst, wenn der Text stabil ist.

**Comment by dariok** [comment]
@Wallsporn zu den Anm. zum Register:
- zu Aug., S. 516: dort steht „enarr. in Ps.“
- in anderen Texten Hieronymus immer als „Hier.“ abgekürzt – vereinheitlichen?
- zu Quintilian, Inst./inst: Schreibung wie in der Vorlage!

**Comment by dariok** [comment]
@Wallsporn In 081 ergänze ich bei den Vg-Zitaten in den FN die fehlenden Anführungszeichen; in der 110 ergänze ich gleich noch die Klammer um „LXX“

**Comment by dariok** [comment]
Hier die PDF zur 081: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3100012/karlstadt-2.pdf)

Die Ansetzung zu Pucher steht so im Personenregister.

**Comment by dariok** [comment]
Hier die PDF zur 083: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3100084/karlstadt-2.pdf)

**Comment by dariok** [comment]
Und 108: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3100248/karlstadt-2.pdf)

**Comment by Wallsporn** [comment]
> 
> 
> @Wallsporn In 081 ergänze ich bei den Vg-Zitaten in den FN die fehlenden Anführungszeichen; in der 110 ergänze ich gleich noch die Klammer um „LXX“

Danke!

> * zu Aug., S. 516: dort steht „enarr. in Ps.“
> hm, hatte nach Registerdurchsicht alle Stellen vereinnheitlicht
> * in anderen Texten Hieronymus immer als „Hier.“ abgekürzt – vereinheitlichen?
> soll ich das machen??
> * zu Quintilian, Inst./inst: Schreibung wie in der Vorlage!
hatte ich auch vereinheitlicht - unklar
-> soll ich in XML dies vereinheitlichen oder soll ich besser nicht mehr rangehen?

**Comment by dariok** [comment]
@Wallsporn: Die Punkte mache ich bei nächster Gelegenheit.

**Comment by Wallsporn** [comment]
Danke! Nur eines: ich hatte in der Zwischenzeit, als die Dateien freigegeben waren, auch im XML Verbesserungen vorgenommen. Ich hoffe, dass wir uns nicht überschnitten haben ...

**Comment by dariok** [comment]
Naja, bevor ich angefangen habe mit diesem Issue, habe ich den letzten Stand übernommen und versioniert. Wenn Du dazwischen etwas geändert hast, dann müssen wir schauen.

**Comment by Wallsporn** [comment]
Nachdem Du die Dateien in PDF umgewandelt an uns geschickt hast, habe ich auf dieser Basis Veränderungen in XML vorgenommen. Das macht - meines Wissens - auch Stefania so. Und ich hielt das für die gängige Praxis. Kann erst in ein paar Tagen in Stichproben vergleichen

**Comment by dariok** [comment]
Ich habe am 14. den aktuellen Stand übernommen und dann die Arbeit begonnen an diesen 4 EE – um die QV zu erstellen, mußte ich dabei zwangsläufig auch auf andere Dateien schreiben; hierbei nehme ich alle, die aktuell in Issues als fertig gemeldet sind. Welche Dateien ich bearbeitet habe, siehst Du bei den einzelnen Commits.
Wenn Du dazwischen, also seit dem 14., keine Änderungen gemacht hast, dann ist alles in Ordnung. 

Auch nach dem 14. habe ich vereinzelt einmal alles übernommen, aber nichts systematisch. Wenn Du nach dem 14. Änderungen gemacht hast, müssen wir das mit den Commits abgleichen.

Zum Erstellen der QV muß ich alleine an den Dateien arbeiten – auch in der Zieldatei müssen ja Markierungen erstellt werden! Ich war davon ausgegangen, daß ihr ihr kurz sagt, wenn ihr an einer Datei arbeiten wollt, die im Issue genannt ist – so hatten wir das ja eigentlich auch einmal gesagt.
Sonst muß ich die PDF zurückhalten, bis alles erledigt ist – was hier jetzt heißen würde, daß Du auch für die 110 keine PDF bekommen kannst, bis die aktuell offenen Issues abgearbeitet sind.

**Comment by Wallsporn** [comment]
Wie aus dem Issue ersichtlich, habe ich die Dateien in XML zuletzt vor 14 Tagen, am 11.4. bearbeitet. Irritiert hat mich folgendes:
    zu Aug., S. 516: dort steht „enarr. in Ps.“
    in anderen Texten Hieronymus immer als „Hier.“ abgekürzt – vereinheitlichen?
    zu Quintilian, Inst./inst: Schreibung wie in der Vorlage!

Das hatte ich in XML korrigiert. Wenn es noch in alter Version auftauchte, ist das irritierend. Um mehr geht es nicht. Geändet wurde seit 14 Tagen nichts.

**Comment by dariok** [comment]
Gut, dann sollte es eigentlich keine Überschneidungen gegeben haben. Ich hatte die Dateien am 14. übernommen, da war an der 110 keine Änderung sichtbar gewesen – ich exportiere immer den gesamten Inhalt der DB und versioniere das mit git.

Eine Möglichkeit: Als die HAB zwischendrin ihren Speichercrash hatte, wurde ein Backup eingespielt, das Deine Änderungen nicht hatte.

Ich werde versuchen, jetzt vordringlich eine noch genauere Versionierung einzubauen: sobald eine Datei neu in der Datenbank gespeichert wird, wird sie gleich in git versioniert. Das sollte solche Fälle verhindern.

**Comment by Wallsporn** [comment]
Der Zusammenhang mit dem HAB-Server-Crash erscheint mir möglich. Ich habe alle meine in XML vorgenommenen Korrekturen in einer PDf in Göttingen vermerkt und müsste dementsprechend alles noch einmal vergleichen. Wie gehen wir vor?

**Comment by Wallsporn** [comment]
ENTWARNUNG: die Korrekturen, die ich vor dem 11.4. in XML vorgenommen habe, sind enthalten.
"Enarr. in ps." habe ich nirgends entdeckt, auf S. 518 u. a. "en. Ps."
Habe bei der Durchsicht 3 kleine Fehler entdeckt, zudem müssten die von Dir oben angemerkten Fehler (Quint. inst.; Hieron.) korrigiert werden,
Frage: Soll ich in XML verbessern? Oder alles in PDF anmerken?

**Comment by Wallsporn** [comment]
@dariok 
Hallo Dario, ich bin die obigen PDF durchgegangen. Neben ein paar zu korrigierenden Kommata, Punkten oder Klammern würde ich in EE110intro Anm. 2 eine Passage ergänzen (ist nicht lebensnotwendig, wäre aber schön).
Frage: 
1. Kann ich dies jetzt noch in XML erledigen oder ist alles Dir per PDF zu signalisieren? 
2. Viele Querverweise sind fehlerhaft (in der vorherigen PDF waren sie es nicht). Alles Dir signalisieren oder liegt das am Stand der Bearbeitung, d.h. erst in letzter PDF erscheinen die richtigen QV?
3. Die Binnendifferenzierung habe ich in PDF eingetragen.

**Comment by dariok** [comment]
@Wallsporn In der 110 kannst Du die Korrekturen noch in die XML eintragen, ich werde sie erst gegen Ende der Woche erreichen.
Die QV liegen vmtl. am Stand der PDF – hier ist es besser, zu warten, bis ich den Umbruch fertig habe (hierzu kommt bald die neue PDF der ersten Hälfte)

**Comment by Wallsporn** [comment]
@dariok Danke!
Punkte, Klammern etc., auch mal ein vergessener Buchstabe sind aber auch in EE81, 83, 108 zu ergänzen, in der Regel alles in Fußnoten. Da EE81 und 108 (= KGK 137 und 138) zum zweiten Teil von KGK II gehören, müsste ich auch noch in XML arbeiten können, oder? Die wenigen Korrekturen für EE83 = KGK 106 würde ich direkt Dir per PDF-Korrektur übergeben.

Grundsätzliche Frage von Stefania und mir:
Die neue PDF, die Du uns dann schicken wirst, entspricht dem Druckmanuskript samt Umbruch?
Dort würde wir dann Korrekturen der Querverweise, des Zeilen- und Seitenumbruchs sowie die Binnendifferenzierung eintragen, richtig?
