### ISSUE TITLE
Stefania EE82/92/100/101/102/103/104/106/107 Vor-Manuskript

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#308]
HIer meine EE mit den Korrekturen, die nach der Fertigstellung des Currus eingearbeitet werden koennen.
Ich habe einige Formalia/Kodierungen, einige fehlende textkrit. Anm. in der LD (sind im Text nihct aber im Apparat) und fehlende/falsche QV (warum auch immer..) markiert.
Korrekturen auch in den Registern.

Fuer Fragen stehe ich jederzeit zur Verfuegung

[karlstadt_EEStS_FinalCorrections.pdf](https://github.com/dariok/karlstadt-issues/files/3070529/karlstadt_EEStS_FinalCorrections.pdf)

**Comment by dariok** [comment]
@stefaniasalvadori Zur LD, Einleitung:
- Das Zitat in der Einleitung kann nicht weiter eingerückt werden – der gesamte Abschnitt ist bereits eingerückt
- Zu Anm. 175: Den zitierten Text kann ich nirgends finden

**Comment by stefaniasalvadori** [comment]
@dariok 
- ok - gaebe es eine Alternative? Sonst muss das lange Zitat so stehen..

-  Zu Anm. 175 in der Einleitung LD - Mein Fehler, das Zitat ist in KGK 132 geloescht worden.
Bitte Verweis auf Eck, Briefwechsel, 97 einfuegen. Die Fussnote ist nun:
175 Eck an Kurfürst Friedrich III., 8. 11. 1519 **: "Aber daß Ludder vor seinem Landsfürsten darf ohn Scham leugnen, als hätt er die heiligen Doctores nit verleugnet, zeuch ich mich auf der Notari Geschrift, und so D. Bodenstain ein Exemplar heimlich hinweg geführt hat zu Leypßig wider fürstlicher Rät und der Universität Bot [...]" (Eck, _Briefwechsel_, Nr. 97).**
Wenn diese Ergaenzung nun problematisch ist, einfach Verweis auf Eck, Briefwechsel Nr. 97 einfuegen.

**Comment by stefaniasalvadori** [comment]
Am Freitag habe ich meine EE in der Online Edition benutzt (um QV von KGK III auf KGK II in den neuen EE zu markieren) und könnte feststellen, dass alle meine Korrekturen eingearbeitet sind. Dafür herzlichen Dank!
Ich weiss es nicht, ob und evtl. wann ich die neue PDF bekommen werde, um die Binnendifferenzierungen Ks einzutragen und damit meine EE für die LaTex Bearebeitung absegnen. Ich wäre jedoch sehr dankbar, wenn Du mir kurz Signal geben kannst, wann ich damit evtl rechnen soll - sodass ich meine Arbeit in den kommenden Wochen einplanen kann (bin Ende des Monats unterwegs).
