### ISSUE TITLE
Alejandros EE

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#309]
In letzter PDF fehlen Querverweise in EE87text. Ob wir die letzte Variante nicht hochgeladen haben - ich weiß es nicht. Wie wollen wir vorgehen: sollen wir die QV in XML eintragen? - Grundsätzlich würde ich einige Kleinigkeiten in den XML von ALejandros EE korrigieren - ok?

**Comment by Wallsporn** [comment]
- Wir haben in XML Korrekturen vorgenommen in EE78text und intro, EE86text und intro
- Korrekturen in EE78rg konnte ich nicht hochladen, da ich keine Zugangsberechtigung habe - Datei unter leicht geändertem Namen EE78rdgl nun auf meinem Laptop, da ich auch diese Datei nicht über URL in der exist-DB speichern konnte - what to do?
- EE87intro letzter Stand der XML und WDB entspricht nicht PDF

**Comment by dariok** [comment]
- 087rg sollten jetzt überschreibbar sein
- letzten Stand der 087 habe ich hochgeladen
- aktuellen Stand 086, 087 übernehmen ich später

**Comment by Wallsporn** [comment]
- EE87-rg ist neu hochgeladen, ok
