### ISSUE TITLE
Verschollene

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#31]
u.a. EE 84=Nr. 106 verschollen: Transformation funktioniert noch nicht

**Comment by stefaniasalvadori** [comment]
EE 84 (=Nr 106) 
Verschollen - Überlieferung ui hochladen
[EE 84_JuniC_2017-6-7.docx](https://github.com/dariok/karlstadt-issues/files/1193687/EE.84_JuniC_2017-6-7.docx)

**Comment by dariok** [comment]
note to self: manchmal fehlt in Überschrift »verschollen« – warum?

**Comment by stefaniasalvadori** [comment]
EE 88B (= Nr 112)
Verschollen - Überlieferung zu hochladen
[EE 88B_JuniC_2017-7-20.docx](https://github.com/dariok/karlstadt-issues/files/1193695/EE.88B_JuniC_2017-7-20.docx)

**Comment by stefaniasalvadori** [comment]
EE93A (= Nr. 116)
Verschollen - Überlieferung zu hochladen
[EE 93A_JuniC_2017.docx](https://github.com/dariok/karlstadt-issues/files/1193702/EE.93A_JuniC_2017.docx)

**Comment by stefaniasalvadori** [comment]
EE 93B (= Nr. 117)
Verschollen - Überlieferung zu hochladen
[EE 93B_JuniC_2017.docx](https://github.com/dariok/karlstadt-issues/files/1193705/EE.93B_JuniC_2017.docx)

**Comment by stefaniasalvadori** [comment]
EE 94 (= Nr. 119)
Verschollen - Überlieferung zu hochladen
[EE_94_119_K_Sig_v_Thüng_versch-MSW.docx](https://github.com/dariok/karlstadt-issues/files/1193709/EE_94_119_K_Sig_v_Thung_versch-MSW.docx)

**Comment by stefaniasalvadori** [comment]
EE 107A (= Nr. 134)
Verschollen - Überlieferung zu hochladen
[EE107A_134_K-Sp_versch-MSW.docx](https://github.com/dariok/karlstadt-issues/files/1193711/EE107A_134_K-Sp_versch-MSW.docx)

**Comment by stefaniasalvadori** [comment]
EE 114 (= Nr. 144)
Verschollen - Überlieferung zu hochladen
[EE 114_144_Sp-K_versch_MSW.docx](https://github.com/dariok/karlstadt-issues/files/1193714/EE.114_144_Sp-K_versch_MSW.docx)

**Comment by stefaniasalvadori** [comment]
EE 116 (= Nr. 146)
Verschollen - Überlieferung zu hochladen
[EE116_146_versch_MSW.docx](https://github.com/dariok/karlstadt-issues/files/1193718/EE116_146_versch_MSW.docx)

**Comment by stefaniasalvadori** [comment]
EE 116 (= Nr. 146)
Verschollen - Überlieferung hochgeladen - einfach prüfen
[EE-122A-Überl.docx](https://github.com/dariok/karlstadt-issues/files/1193724/EE-122A-Uberl.docx)

**Comment by dariok** [comment]
aktueller Stand:

- [ ] EE84
- [ ] EE88B
- [ ] EE93A
- [ ] EE93B
- [ ] EE94
- [ ] EE107A
- [ ] EE114
- [ ] EE116
- [ ] EE122A

**Comment by dariok** [comment]
EE 114 und EE 116 haben beide als neue Nummer die 144!

**Comment by stefaniasalvadori** [comment]
EE114=KGK 144
EE116=KGK 146
soll ich sie korrigieren und nochmals hochladen?

**Comment by dariok** [comment]
Das kann ich schnell machen, kein Problem.

**Comment by stefaniasalvadori** [comment]
ok, danke Dir
Ich signalisiere den Tippfehler an Alex, damit er die Numerierung in den Word-Vorlagen korrigieren kann

**Comment by dariok** [comment]
Nach Möglichkeit bitte die in der Liste hinterlegten Dateien verwenden; die Originalen hatten teilw. keine Formatierung.
Damit es beim nächsten Mal klappt, bitte die formatierten Dokumente oben benutzen.

**Comment by stefaniasalvadori** [comment]
Die neue (von Dir hintergelegten) docx-Files habe ich in W nun gespeichert 
Ich leite sie auch an Alex weiter, damit wir ab sofort diese neue formatierten Vorlagen benutzen können

**Comment by dariok** [comment]
Die Dateien sind jetzt alle hochgeladen.
