### ISSUE TITLE
Titelei: Untertitel: Timo Janssen aufnehmen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#310]
Bisheriger Untertitel:
Herausgegeben von Thomas Kaufmann, bearbeitet von Harald Bollbuck, Ulrich Bubenheimer, Stefania Salvadori, und Alejandro Zorzin, unter Mitarbeit von Alyssa Lehr Evans, Dario Kampkaspar und Antje Marx

a) Komma hinter Salvadori streichen
b) Timo Janssen aufnehmen
Frage: unter bearbeitet?
Ich kläre das mit ThK

**Comment by Wallsporn** [comment]
Neuer Untertitel nach Absprache mit ThK:

Herausgegeben von Thomas Kaufmann, bearbeitet von Harald Bollbuck, Ulrich Bubenheimer, Timo Janssen, Stefania Salvadori und Alejandro Zorzin, unter Mitarbeit von Alyssa Lehr Evans, Dario Kampkaspar und Antje Marx

Danke!

**Comment by dariok** [comment]
Alles klar, übernehme ich dann für die nächste PDF.
