### ISSUE TITLE
Anmerkungen zu Korrekturen

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#311]
Ich möchte hier noch einmal zusammenfassen, wie die Korrekturen aussehen, um unnötige Arbeit zu vermeiden und hoffentlich die Arbeit auch zu beschleunigen:

- Korrekturen an Seiten- und Zeilenumbrüchen sowie Trennungen sind erst dann sinnvoll und machbar, wenn ich tatsächlich einen Umbruch gemacht habe, also erst an einer Fahne. Solange noch Korrekturen an den Texten erfolgen, übergehe ich diese Anmerkungen komplett.
- Das gleiche gilt für Querverweise. Um diese zu erstellen, muß ich auch die Zieldatei bearbeiten können, was nicht geht, da ihr sie ja weiter bearbeiten wollt. Außerdem werden insbesondere die Zeilenangaben nicht stimmen, bevor der Umbruch feststeht.
- Ganz genauso ist es nicht sinnvoll, anzumerken, wenn bei Verweisen mehrmals die gleiche Seite hintereinander steht, da sich die Seitenzahl ändern kann.

Da das jetzt immer wieder viel Arbeit und Zeit gekostet hat, werde ich (ab jetzt beim aktuellen und generell bei nächsten Band) mit Querverweisen jetzt erst weitermachen, wenn ich für alle Texte die Bestätigung habe, daß sie fertig sind und ich somit auch den Umbruch machen kann. 
Die Arbeit in den letzten Tagen hat gezeigt, daß der jetzige Ansatz nicht sinnvoll ist,

- da doch die Gefahr besteht, daß man gegenseitig versehentlich Arbeit überschreibt,
- weil ihr Zeit zum Kontrollieren aufwendet, obwohl die Zahlen nicht korrekt sind und
- ich immer wieder korrekte Verweise, die aber markiert sind, kontrolliere (bei der LD waren bisher gerade einmal 2 Verweise tatsächlich nicht korrekt und zwar auf eine ganze These in 092 bezogen, statt nur auf die erste Hälfte), was auf Dauer frustrierend ist.

**Comment by stefaniasalvadori** [comment]
@dariok in Ordnung.
Mir ist aber ein Punkt nicht ganz klar.
Du schreibst "Das gleiche gilt für Querverweise. Um diese zu erstellen, muß ich auch die Zieldatei bearbeiten können, was nicht geht, da ihr sie ja weiter bearbeiten wollt."
Ich will meine EE nicht weietr bearbeiten und habe an meine EE seit mindenstens 4 Wochen gar nichts gemacht, wie in unserer urspruenglichen Zeitplanung vereinbart. Ich habe, die Korrekturen nur in PDF markiert, damit Du die letzte Korrekturen einarbeiten konntest.  
Da EE92 auch eine Einheit von mir ist und ich sie nicht weiter bearbeite seit lange (wie alle andere EE), ging ich davon aus, dass die QV zwischen EE103 und EE92 (und generell QV inneralb meiner EE) kodiert werden koennten.
Wie vereinbart, habe ich sie nochmals alle ganz genau in meiner PDF geprueft und nur QV markiert, die falsch waren - z.B. QV auf Thesen in EE92. 
Wenn Du aus anderen Gruenden nun denkt, dass diese QV momentan nicht erstellt werden koennen, ich passe mich an. Ignoriert meine Korrekturen zu QV in meinen EE und ich werde sie noch einmal pruefen, wenn Du mir Signal gibst.

**Comment by dariok** [comment]
@stefaniasalvadori Da habe ich mich etwas mißverständlich ausgedrückt, weil mehrere Punkte zusammenkommen – das hätte ich vielleicht anders schreiben sollen.

Daß ich die QV zusammen am Ende mache, betrifft überwiegend die Zukunft, da ja jetzt die meisten bereits gemacht sind. Dies sollte also eher eine Anmerkung über die zukünftigen Abläufe sein – bei @wallsporn könnte es nämlich sein, daß wir uns zufällig in die Quere gekommen sind, als ich QV zwischen seinen EE erstellt habe.
Du hast Dir sehr viel Mühe gemacht, die QV zu prüfen und oft gab es nur eine oder 2 Zeilen Abweichung – das kommt daher, daß manchmal eine Zeile zwischen 2 Seiten „springt“ und damit alle folgenden Zeilenverweise falsch sind. Wenn Du dann am Ende alles noch einmal prüfst, hast Du doppelte Arbeit.

Bei Deinen EE aus dem aktuellen Issue ist es natürlich kein Problem, denn Du hast ja schon „fertig“ gemeldet und ich kann hier den Umbruch bereits vornehmen. Aus der LD in die anderen Deiner EE, die Du im Issue aufgezählt hast, habe ich die QV alle kontrolliert; nur ein Verweis (oder 2?) auf die Epitome muß noch offen bleiben.

Es sollte gar nicht als Kritik gemeint sein, sondern eher als Referenz für uns und als Dokumentation der Abläufe. Ich denke, daß es auch für euch eine Erleichterung ist – es ist ja sehr viel Aufwand, die Verweise zu kontrollieren und es erscheint mir einfacher, das am Stück zu machen, wenn die Zeilenangaben sicher sind, damit ihr nicht doppelte Arbeit habt.

**Comment by stefaniasalvadori** [comment]
Nein, nein, Dario, ich habe es nicht als Kritik gemeint. Ich hatte es einfach nicht verstanden, worum es ging und ich wollte es genau verstehen, um in Zukunft alles auf dem Schirm zu halten.
Wie ich mehrmals geschrieben habe, es ist/war mir wichtig, dass Du bequem arbeiten kannst - deshalb habe ich es versucht, die Korrekturen zu redukieren und in der PDF alles so klar wie moeglich zu markieren. Da Du das Issue mir und Timo "assigned" hattest, dachte ich, ich war besonders betroffen oder hatte was zu korrigieren. 
Nun ist es alles klar.
Ich stimme aber zu: Fuer KGK III sollten wir Editoren die QV in Word genau speichern, aber nur am Ende in XML sie Dir kodieren lassen und nur einmal pruefen.
Danke Dir nochmals und vG

**Comment by Wallsporn** [comment]
Auch meinerseits nochmals: nach Freigabe der Dateien am 11.4. und Übersendung der PDF gab es keine Korrekturen mehr. Es sind auch keine geplant. Zu dem Vorgang siehe Issue #307. Umbruch wäre möglich, ist nun durch den evtl. Datenverlust problematisch. Ich denke nicht, dass wir uns überschrieben haben. sondern der Serverausfall Ursache ist. Mein Plan: 
- Vergleich evtl. Datenverluste
- Einarbeiten der verlorengegangenen KOrrekturen
- Einarbeiten der Binnendifferenzierung

**Comment by Wallsporn** [comment]
Wir haben heute noch einmal über die oben genannten Fragen gesprochen. Die Korrekturen an den Texten in XML waren von Stefania und mir abgeschlossen und diese zur Endkorrektur freigegeben und gemeldet. Nach jetzigem Stand sind nur noch Kleinigkeiten zu korrigieren. Auch an den "Zieldateien" wurde von uns nicht mehr gearbeitet. Sind damit Alex' Dateien gemeint? Sie sind unseres Wissens seit Samstag bei Dir und damit auch für die Letzbearbeitung freigegeben.
Da wir davon ausgingen, dass sich die Dateien nun in der letzten Korrektur für das Druck-Mss befanden, haben wir alles eingetragen, was für die Druckfahne anzumerken ist. Also alle Probleme bei Querverweisen etc. Dass es noch einmal 2 Korrekturvorgänge werden, war zu erwarten, nicht aber, dass wir die Korrekturen in 2 PDf eintragen sollen - oder verstehe ich/wir falsch? Klar, das Layout wird erst am Ende mit LaTeX bearbeitet, aber wie mit den Querverweisen umzugehen ist, wenn dort nur Fragezeichen, leere Klammern oder aber die benannten Wiederholungen stehen, war uns augenscheinlich nicht klar. Deshalb wurde das angemerkt. Wir sind in einem gegenseitigen ersten Arbeitsprozess auf diese Weise, daher müssen wir gegenseitig nach- und umsichtig sein. Wir wollen Dich nicht überfordern, aber auch für uns ist es nicht effektiv, immer wieder Korrekturdurchgänge anzusetzen. Also: wie gehen wir vor: was sollen wir jetzt in die neue PDF eintragen? Erneut alle Formalkorrekturen mit Binnendifferenzierung? Das erste wäre eine komplette Verdoppelung schon erledigter Arbeit, aber Du hast jetzt diese Frage aufgebracht. Was ist für Dich und für uns am besten? Wir würden natürlich präferieren, wenn wir in die neuen PDF nur die letzten Minikorrekturen und die Binnedifferenzierungen eintragen.
