### ISSUE TITLE
KGK 105/113/117/128/129/130/131/132/134/135 - PDF Korrekturen

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#313]
@dariok - ich habe auch die QV nochmals geprüft; LayOut Details habe ich ebenso signalisiert; einfach ignorieren, was nicht momentan sinnvoll ist
[karlstadt_Juni2019_Korr.BD.StS-12Juni2019.pdf](https://github.com/dariok/karlstadt-issues/files/3281597/karlstadt_Juni2019_Korr.BD.StS-12Juni2019.pdf)

KGK 
- [x] 105
- [x] 113
- [x] 117
- [x] 128
- [x] 129
- [x] 130
- [x] 131
- [x] 132
- [x] 134
- [x] 135

**Comment by dariok** [comment]
Zu 128: Hier würde ich vorschlagen, den Text unter HS a eingerückt zu lassen. Generell haben wir es so, daß die Anmerkungen zu exakt einer Quelle eingerückt unter dieser stehen, hier würde ich das (auch wenn es nur die eine HS gibt) so belassen.

**Comment by stefaniasalvadori** [comment]
In Ordnung
Wichtig ist nur, dass alle ähnliche Fällen in KGK II einheitlicht sind

**Comment by dariok** [comment]
Ich prüfe das am Ende noch einmal an der kompletten PDF.

**Comment by dariok** [comment]
@stefaniasalvadori Was mir gerade beim Durchlesen für die Mikrotypographie aufgefallen ist: In EE092 gibt es die Variante A5Lp und A5Zü – allerdings zu F5, während es nur A gibt.
Sollte es nicht F5Lp und F5Zü heißen?

**Comment by stefaniasalvadori** [comment]
@dariok Ja, voellig richtig! F5Lp und F5Zue

**Comment by dariok** [comment]
Diese Korrekturen sind jetzt eingearbeitet. Nicht alle Layout-Wünsche konnten umgesetzt werden – in der LD hat sich schon ein weitgehender Neuumbruch ergeben.

Es sind durch den Neuumbruch in der LD noch ein paar Eingriffe nötig, aber sonst sind auch die wichtigsten Kleinigkeiten erledigt.
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3343583/karlstadt-2.pdf)

**Comment by stefaniasalvadori** [comment]
Ich schaue mir diese PDF heute - danke

**Comment by stefaniasalvadori** [comment]
Hallo Dario, fast alle Kleinigkeiten sind tatsaechlich erledigt, nur ein paar sind noch offen. Da sie sehr wenig sind, mache ich hier eine Liste der einzelnen Korrekturen mit Seiten (Umbruch Seite [=PDF Seite]) und dazu HInweise zu deren Prioritaet, damit Du den Ueberblickt hast. Eine 2. Liste mit allgemeinen Fragen folgt. Ich haenge die PDF auch hier an.

LETZE KORREKTUREN: 
IM TEXT
- [x] S. 165 [=195PDF] --> Umbruch vor "tuen-" einfuegen.  WENN diese Korrektur zu Umbruch-Probleme fuehrt, bitte so stehen lassen!
- [x] S. 166 [=196PDF] --> Anm. 13 ---> Hier. **I**n Eph. --> «in» klein geschrieben --> kann auch so stehen, wenn das nicht Probleme im Register verursacht
- [ ] S. 272 [=301PDF] --> Die Einrueckung in der Ueberlieferung kann auch so stehen, nur muss es in dem Band KGK II vereinheitlicht; KGK 113 hat z.B. anderes LayOut
- [x] S. 287f. [=317f.PDF]  --> Titel und folgende Kolumnentitel bitte anpassen/vereinheitlichen. Im Titel muss auch 15. ergaenzt werden. Im Kolumnentitel muss 27. (nicht 26.) stehen
- [x] S. 293 [=323PDF]  ---> in der Signatur von a bitte "r" und "v" hochstellen --> nur wenn es moeglich ist
- [x] S. 335 [=365PDF]  --> Die QV in Amn. 126 und 128 sind noch zu justieren - ich habe die Stellen nochmals angegeben
- [ ] S. 382 [=412PDF]  --> in aNM: 378; 379 u. 380 einen Punkt nach "nat" einfügen = Nemes. nat. hom.
- [ ] S. 401 [=431PDF]  ---> Anm. 491 --> Hier. Brev. in **P**s. 79 ---> «ps.» klein geschrieben --> kann auch so stehen, wenn das nicht Probleme im Register verursacht
- [ ] S. 409 [=439PDF] ---> unmittelbar vor [D3v] --> leere Zeile zu loeschen, Abstand zwischen Abschnitten muss weg
- [ ]  S. 411 [=441PDF] ---> unmittelbar vor "Porro. dicit..." --> leere Zeile zu loeschen, Abstand zwischen Abschnitten muss weg
- [ ] S. 416 [=446PDF] --> Im Text, Anfang von Anm. ueber mehrere Woerter **biy** unmittelbar vor "Finita est disputatio..." ziehen
- [ ] S. 460 [=490PDF]  --> Im Kolumnentitel, Spatium zwischen Tag (18.) und Monat (8.) --> in anderen EE ohne Spatium --> bitte vereinheitlichen
IM REGISTER
- [ ] Augustinus, BD, zwei Stellen sind unter "ep. Io." ---> sie muessen unter "ep. Io. tr."  Die Stellen sind auf S. 343[=373PDF], Anm. 171 und S. 373[=403PDF], Anm. 338. 
- [ ] Karlstadt BD --> die BD muessen (laut KGK I) vereinheitlicht werden. Im allgemein, ich signalisiere:
- **Geplant**  --> Tippfehler, einfach als **geplant** 
- **Ironie** UND **Polemik** UND **Polemik/Ironie**  ---> vereinheitlichen als **Polemik/Ironie**
- **Leser** UND **Leser(Kreis)/Rezipienten** ---> vereinheitlichen als **Leser(kreis)/Rezipienten**
- **Stil** UND **Stil/Ausdrucksweise** ---> vereinheitlichen als **Stil/Ausdrucksweise**

Detaillierte Korrekturen zu den Register sind nun in einer neuen PDF eingetragen. [09.07.2019]

Im Allgemein noch diese Fragen/Vorschlaege (auch auf der 1. Seite meiner PDF)
- [ ]  In KGK I hattest Du auch die ISBN in die fertige PDF eingefuegt - bruachst Du die ISBN hier auch? Sollen wir bei dem Verlag nachfragen?
- [ ] in KGK I ist Bibliographie VOR Registern
- [ ] Kurztitelverzeichnis einzufuegen

[karlstadt-2.UNITA.STEF-1.pdf](https://github.com/dariok/karlstadt-issues/files/3374037/karlstadt-2.UNITA.STEF-1.pdf)

**Comment by stefaniasalvadori** [comment]
Die noch nicht eingearbeitete Korrekturen liste ich in Issue #323 damit wir ab jetzt nur eine PDF haben
