### ISSUE TITLE
Einleitende Texte und Register

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#314]
in NEW PDF NOCH ZU ERGÄNZEN: 

- [ ] Verzeichnis der erwähnten Kurztitel der Karlstadtwerke - vgl. #289 

- [ ] Bibliographie

KORREKTUREN:

[karlstadt_Juni2019_Korr BibelRegister StS.pdf](https://github.com/dariok/karlstadt-issues/files/3277490/karlstadt_Juni2019_Korr.BibelRegister.StS.pdf)

**Comment by Wallsporn** [comment]
Von mir die Korrekturen zum Orts-und Personenregister 

[KGK II_Pers-Orts-Register_HB_StS-2019-06-11.pdf](https://github.com/dariok/karlstadt-issues/files/3277839/KGK.II_Pers-Orts-Register_HB_StS-2019-06-11.pdf)

**Comment by Wallsporn** [comment]
Hier die Korrekturen zum "Vorwerk"

[KGK II_einleitende Texte_HB_StS-2019-06-06.pdf](https://github.com/dariok/karlstadt-issues/files/3277843/KGK.II_einleitende.Texte_HB_StS-2019-06-06.pdf)
