### ISSUE TITLE
Kommentare in Überlieferung

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#32]
Kommentare zur Überlieferung einzelner Druckchargen wie in EE 81, 110, 127, 132 erscheinen noch nicht

**Comment by stefaniasalvadori** [comment]
Hier die WordFiles, wo Kommentare auftauchen
[EE-81-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1193823/EE-81-Uberlieferung.docx)
[EE-110-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1193826/EE-110-Uberlieferung.docx)
[EE-127-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1193828/EE-127-Uberlieferung.docx)
[EE-132-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1193831/EE-132-Uberlieferung.docx)

**Comment by Marxistin** [comment]
Gleicher Inhalt in #44
