### ISSUE TITLE
Präfahne Korrekturen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#323]
Hallo Dario,
hier die letzten Korrekturen von Tippfehlern, Fehlcodierungen bzw. formatierungen etc. Sieht mehr aus, als es ist. Ein paar Hinweise:
- Einige der Anmerkungskorrekturen "korrigiert in ..." sind erwünscht, aber wenn sie einen neuen Satz auslösen, nicht notwendig.
- wichtig: S. 66 Anm. cj) ist fehlerhaft, die muss korrigiert werden
- Satzbild von Epitome und Auslegung ist für uns so in Ordnung, auch generell die Absatzeinrückungen. Nur müssten die Absatzeinrückungen nach den bereits eingerückten Wagensprüchen leider raus - das ist jetzt uneinheitlich. Ich befürchte dann Satzprobleme - what to do?
- Bilder der Epitome besser auf ungezählter Doppelseite hinter dem Text.
- Die im Register verbesserten Tippfehler und falschen Werkangaben sind auch im Text an den jeweiligen Stellen korrigiert, nicht aber die Umstellungen, Korrekturen der Binnendifferenzierungen etc.
Danke Dir!

[KGK-II-2019-07-07-hb-korr.pdf](https://github.com/dariok/karlstadt-issues/files/3383084/KGK-II-2019-07-07-hb-korr.pdf)
[KGK II_Register Bibliographie_Korr_StS_2019Jul9.pdf](https://github.com/dariok/karlstadt-issues/files/3383085/KGK.II_Register.Bibliographie_Korr_StS_2019Jul9.pdf)
[Abb_Anleitung_KGK-II_1519.docx](https://github.com/dariok/karlstadt-issues/files/3383093/Abb_Anleitung_KGK-II_1519.docx)

**Comment by stefaniasalvadori** [comment]
Wie gerade per Email angekuendigt - hier die Liste der noch nicht eingearbeiteten Korrekturen oder Fragen in KGK II, die Du @dariok auch in der angehaengten PDF findest:

- [ ] ISBN Nr. zu korrigieren? Die richtige (siehe Email von AM vom 5.7.2019) ist: ISBN: 978-3-579-05847-4
- [ ] Extra-Ueberschrift "Einleitung" nach Inhaltverzeichnis hatte wir in KGK I nicht
- [ ] Bilder der Epitome besser auf **ungezählter** Doppelseite hinter dem Text. Auf S. 84 ist nicht die richtige Abbildung. FRAGE: Wirdst Du Dario oder der Verlag diese Abbildungen einfuegen?
Auf jeden Fall muss diese Doppelseite ungezaehlt sein! Sonst rutschen die Seitenangaben...
- [ ] Auf S. 136, Kommentar zu den Abbildungen nach dem Currus  - wenn der Verlag dafuer zustaendig ist, einfach ignorieren
- [ ] Auf S. 169, Anm. 20 --> Abk. Hor. **a. p.** (nicht ars)
- [ ] Auf S. 181, unter Titel, in der Datierung, am Ende Mai**]]** --> eckige Klammer zu loeschen (eine ist zu viel) 
- Worttrennung _Provenien-zhinweis_ zu pruefen/korrigieren
- [ ] Auf S. 196  --> Kommentar zu Abbildung --> @ DK oder Verlag? - wenn der Verlag dafuer zustaendig ist, einfach ignorieren
- [ ] Auf S. 271, KGK 128 --> Einrueckung in der Ueberlieferung --> uneinheitlich? Vgl. KGK 113. Oder ist es hier ein Sonderfall, da es um "Referenz" geht?
- [ ] Auf S. 287, unter Titel, in der Datierung ---> bitte "15." ergaenzen
- [ ] Auf S. 424  --> zweite kursivierte "Beilage 1:" loeschen
- [ ] Auf S. 430 --> zweite kursivierte "Beilage 2:" loeschen
- [ ] Auf S. 471 + 475 (x2) + 476   --> Punkt unmittelbar nach "autograph" loeschen - keine Abk.!
- [ ] Auf S. 476, Anm. 20 --> Zeichnen im griech. Zitat korrigieren - vgl. Korrektur Haralds
- [ ] Auf S. 508, Anm. 40  --> bibliographische Angabe NICHT fett
- [ ] Auf S. 625, REGISTER  --> bitte Andrea (bibl.)/Andreas (bibl.)/Andrea (hl.) als **Andreas (bibl.)** zusammenstellen
- [ ] Auf S. 626, REGISTER  --> unter Augustinus, **hypomn** loeschen ---> gehoert zu **Ps. Augustinus**, dort (=auf S. 632) die Seitenangaben einfuegen
- [ ] Auf S. 626, REGISTER  --> korrigieren in **Capestrano, Johannes De**  - d.h. "De" am Ende ziehen
- [ ] Auf. S. 626, REGISTER ---> QV korrigieren in **Zedlitz** Fontinus, Petrus
- [ ] Auf S. 629, REGISTER  ---> "Autobiographisches" auf folgende Seite ziehen
- [ ] Auf S. 631, REGISTER  ---> Korrigieren in **Marck, Erard de la**  - d.h. "de la" am Ende ziehen
- [ ] Auf S. 631, REGISTER  ---> **Mörlin, Joachim** ist verschwunden!! Bitte hier auch die Reihenfolge (Moerlin, Joachim | Moerlin, Jodokus | Moeller, Andreas) pruefen und korrigieren!
- [ ] Auf S. 631, REGISTER  ---> Nemesius Emesenus  --> QV muss weg --> hier richtige Angabe **nat hom + Seiteangabe (=382)**  "39" muss weg
- [ ] Auf S. 632, REGISTER  ---> Pistorius, Simon d. Ae + d. J. ---> Reihenfolge korrigieren
- [ ] Auf S. 632, REGISTER  --> QV verschwunden! Bitte vor Ps. Hieronymus nochmals einfuegen:
Ps. Gregorius Nyssenus
nat. hom.   --> Nemesius Emesenus
- [ ] Auf S. 633, REGISTER  --> Punkt unmittelbar nach Sueton tilgen
- [ ] Auf S. 644, REGISTER  --> wir nutzen NIE "ff." - hier die richtige Stelle ist: Dan 3,**24-90**

- [ ]  FALLS du @dariok die Abbildungen einarbeiten musst und zusaetzliche Infos/Dateien brauchst, einfach Bescheid geben. Falls der Verlag lieber sich darum kummern muss, ebenso einfach Bescheid geben. 

Die von Harald angegebene Korrktueren zu den Einzuege in der Auslegung-Wagen sind ignoriert worden, da sie so von Alex gewuenscht waren - wenn ich es richtig verstanden haben. Ich habe sie deshalb auch ignoriert

Und hier die gesamte PDF mit Korrekturen
[karlstadt_KGK II_completo_16luglio2019.pdf](https://github.com/dariok/karlstadt-issues/files/3398349/karlstadt_KGK.II_completo_16luglio2019.pdf)

**Comment by dariok** [comment]
> Auf S. 644, REGISTER --> wir nutzen NIE "ff." - hier die richtige Stelle ist: Dan 3,24-90

Natürlich benutzen wir nie „ff.“ Aber ich habe den Text ja nicht geschrieben, ich kann also nicht wissen, was gemeint ist.
Entschuldigt, das soll nicht böse sein, aber bisher stand die richtige Stelle nie dabei, es war immer nur gestrichen oder mit einem „?“ versehen. Die Registereinträge werden aus dem von euch geschriebenen Text generiert (außer bei manuellen Korrekturen) – wenn da ein Fehler ist, müßt ihr die Stelle im Text anschauen und dort korrigieren, dann wird auch der Registereintrag richtig.

---

Kann ich euch diese Arbeit irgendwie vereinfachen? Wäre es z.B. hilfreich, wenn es – zusätzlich zur farbigen Hervorhebung von Personen und Orten – am Ende des Textes auch ein „Vorschauregister“ gibt, in dem einfach die markierten Personen, Orte, Bibelstellen aufgeführt sind, damit Tippfehler oder eben solche „ff.“ einfacher zu sehen sind?

**Comment by stefaniasalvadori** [comment]
Ja, ich weiss, es ist nich boese gemeint. Ich hoffe Du weisst, es war auch von mir nicht boese - und vor allem nicht gegen Dir! - gemeint.
Nun, granz pragmatisch:
- Die Stelle so belassen, wenn es ein Problem ist. 
- Zu Deiner Angebot  - wir muessen das Work-Flow mit den Formalia erstmal unter uns Editoren, dann mit Dir fuer KGK III anders organisieren. Das habe ich schon gesagt und werden wir auch es gemeinsam versuchen

Fuer weitere Fragen stehe ich zur Verfuegung

**Comment by dariok** [comment]
Hier die PDF: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3410813/karlstadt-2.pdf)


Die Abbildungen sollten besser vom Verlag gemacht werden, da sie vmtl. auf anderem Papier gesondert gedruckt werden.
Die Titelei hat letztes Mal auch der Verlag gemacht. Wenn ich sie umsetzen soll, brauche ich vom Verlag die Angaben, was drauf soll.

**Comment by stefaniasalvadori** [comment]
Ich prüfe die PDF heute Nachmittag und leite sie an Kaufmann weiter, damit er ab Montag KGK II durchblättern kann.
Abbildungen und Titelei werden vom Verlag gemacht.

**Comment by stefaniasalvadori** [comment]
Einige Korrektuen (z.B. autograph. - Punkt am Ende zu loeschen / Im Titel der LD - Datierung - "15." wurde richtig ergaenzt, nun ist aber "14." verschwunden) sind noch nicht eingearbeitet worden.

Die Einrueckung in Ueberlieferung/Referenz zu KGK 128 habe ich noch nicht verstanden. I give up. Sie wird nun so belassen.

Die PDF mit den fehlenden Korrekturen hier:

[KGK II Fahne 19_07_2019.pdf](https://github.com/dariok/karlstadt-issues/files/3411825/KGK.II.Fahne.19_07_2019.pdf)

**Comment by dariok** [comment]
Zur Einrückung bei Nr. 128: Eingerückt sind immer die Texte, die sich nur auf eine Quelle beziehen. Das ist hier der Fall, es ist die Beschreibung der HS a.

Zur LD: Da habe ich Deine Korrektur falsch verstanden, entschuldige.
