### ISSUE TITLE
Fahne KGK II Schlusskorrekturen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#324]
Korrekturen von Herrn Kaufmann, v.a. Formalien.
Auf folgende darüber hinausgehende Besonderheiten bitte achten:

1) Titelei: bitte „Schriften“ hinter „Band II“ entfernen, denn wir edieren ja Schriften und Briefe. Das ist abweichend zu Band I, doch sollte dieser Fehler nicht weitergetragen werden.

2) Bei den Seitenangaben zu Erasmus, Instrumentum (1516) muss zur Paginierung die Folioangabe gesetzt werden, weil der Band zwei Mal mit der Paginierung neu einsetzt.

3) An drei Stellen fehlt der zitierte Text in der Anmerkung (S. 214, 244f.)! Uns ist bekannt, dass die Einfügung noch einmal Arbeit bedeutet. Aber wir kommen um diese Korrektur nicht herum.

4) An zwei Stellen sind – uns unerklärlich – Transformationsfehler im Zusammenhang mit der Auflösung von Expansionen aufgetaucht („kern1pt“ auf S. 460): Frage: Kannst Du irgendwie automatisiert ausschließen, dass so etwas passiert?

[KGK.II.Fahne-2019-08-06-Endkorrektur.pdf](https://github.com/dariok/karlstadt-issues/files/3477946/KGK.II.Fahne-2019-08-06-Endkorrektur.pdf)

**Comment by Wallsporn** [comment]
Eines wurde vergessen: In der Bibliographie kann eine Angabe gestrichen werden:
Paltz, Werke (Hamm) — Paltz, Johannes von: Werke, 3 Bde., hg. von Bernd Hamm u. a., Berlin/New York 1983–1989

Falls das zu Verschiebungen führt, bitte die Angabe so ändern:
Paltz, Werke (Burger/Hamm) — Paltz, Johannes von: Werke, 3 Bde., hg. von Christoph Burger, Bernd Hamm u. a., Berlin/New York 1983–1989

Im Text taucht die Angabe noch nicht auf, deshalb könnte sie gestrichen werden. Bei der Titelaufnahme fehlt der Herausgeber Burger.

Das war es definitely!
Danke!

**Comment by dariok** [comment]
Ich sammele hier einmal (wächst mit der Bearbeitung):

- auf S. xv auch „(KGK II, NR. 106)“ (nicht markiert) korrigert
- „de|mons|trie|ren“ ist die vom Duden empfohlene Trennung (durch anderen Zeilenfall nach Korrekturne ggf. nicht mehr relevant)

- S. 69, zu 14: weitere spitze Klammer muß weg
- S.72, Anm.: Ja, das ist mir bekannt. Aber S. 71 ist _voll_! Da jetzt aber eh ein neuer Umbruch notwendig ist (der 5. in der Epitome), ist das hinfällig.
- S. 212, Anm. 14: „trias“ → „Trias“
- S. 220, Anm. 74: Komma hinter schließender Klammer ergänzt
- Nr. 137 Text, Anm. 34: An dieser Stelle liegt, wenn ich meinen Unterricht noch richtig im Kopf habe, eine Krasis vor; das Zeichen hierfür, die Koronis, ist aber typographisch eigentlich immer identisch zum Spiritus lenis ’. Das Zeichen ' – eigentlich eine Bogenminute oder ein engl. Fuß anzeigend – ist hier eigentlich falsch.
- Nr. 139 Intor, Anm. 7: »Bensing/Trillitzsch« in Kapitälchen

**Comment by Wallsporn** [comment]
Danke für die aufmerksame Korrektur! Eine Dokumentation der Arbeiten und Einwände ist gut.

**Comment by dariok** [comment]
Hier die PDF: 
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3503273/karlstadt-2.pdf)

In der 078, 103, 110 ist durch die Korrekturen wieder ein neuer Umbruch erforderlich geworden.

Aufgrund des bisherigen Aufwandes werde ich abschließend nur noch die wirklich dringenden Fälle mikrotypographisch angehen und den Rest belassen.

**Comment by dariok** [comment]
Änderungen beim Durchlesen zur MT:

- S. 13, FN 6: „Hieronymus lat. Übertragung der Septuaginta / Hieronymus lat
Übertragung“ → „Hieronymus’ lat. Übertragung der Septuaginta / Hieronymus’ lat.
Übertragung“
- S. 16, FN 26: Epitome kursiv; Zitat „Hättest...Gegner“ mit einfachen Guillemets (fehlendes am Ende eingefügt).
- S. 30, FN 26: hinter Punkt/Komma gesetzt
- S. 32, FN 41: dto.
- S. 33, FN 46: dto.
- S. 34, FN 61: dto.
- S. 36, FN 78, 79, 80,81: dto.
- S. 38, FN 83, 84, 85, 86, 87, 89: dto.
- S. 39, FN 100: Punkt am Ende entfernt
- S. 40, FN 101, 102, 103, 105, 111: hinter Punkt/Komma gesetzt
- S. 41, FN 115: dto.
- S. 42, FN 121: dto.
- S. 44, FN 137, 140: dto.
- S. 46, FN 154, 155: dto.
- S. 48, FN 163, 169: dto.
- S: 50, FN 176, 180: dto.
- S. 52, FN (197), 199, 200, 202: dto.
- S. 54, FN 223: dto.
- S. 56, FN 232, 233, 236, 237, 239: dto.
- S. 58, FN 253, 259, 260: dto.
- S. 60, FN 271, 272: dto.
- S. 62, FN 288, 293, 294, 295, 296: dto.
- S. 64, FN 312: dto.
- S. 66, FN 327, 328, 330: dto.
- S. 68, FN 345, 346, 348, 349, 351: dto.
- S. 70, FN 363, 364, 366, 367, 368: dto.
- S. 72, FN 388, 389: dto.
- S. 74, FN 401, 402: dto.
- S: 76, FN 417, 420, 421, 423, 425: dto. – Hinweis: FN 418 so nicht sinnvoll; die Markierung ist rechts beschrieben!
- S. 78, FN 434, 436, 441: dto.
- S. 80, FN 456: dto.

**Comment by Wallsporn** [comment]
Hallo Dario,

danke für die gründliche Durchsicht! Ich hatte die Abweichungen vom Prinzip "FN hinter Interpunktion" in der Epitome gesehen, sie aber als zu großen Aufwand für Dich zurückgestellt. Wenn Du es nun bereits erledigt hast, umso besser. Danke! Und richtig: Das vereinheitlicht unser Erscheinungsbild ungemein.
Ich schicke Dir nun die letzten mir auffälligen und notwendigen Korrekturen. Meist falsche Trennungen und unserer- oder Deinerseits übersehene Korrekturen/Fehler, zudem eine zusätzliche Binnendifferenzierung und eine fehlerhafte Registersortierung. Es ist wirklich übersichtlich und nur Mikrotypie.

Danke und gutes Gelingen,
Harald

[KGK-II-Druckfahne-2019-08-15.pdf](https://github.com/dariok/karlstadt-issues/files/3524665/KGK-II-Druckfahne-2019-08-15.pdf)

**Comment by timojanssentj** [comment]
Moin Dario, 

bei einer kurzen Durchsicht sind mir leider auch noch zwei kleine Fehler aufgefallen. Als Grundlage dient die bearbeitete PDF von Harald. 

Danke dir!
Herzliche Grüße,
Timo

[KGK-II-Druckfahne-2019-08-15_+TJ.pdf](https://github.com/dariok/karlstadt-issues/files/3529005/KGK-II-Druckfahne-2019-08-15_%2BTJ.pdf)

**Comment by dariok** [comment]
Weitere Änderungen:
- S. 85, FN 1 hinter Komma
- S. 86, FN 4: hinter Punkt
- S. 91, FN 18: dto; FM 23: Punkt am Ende entfernt
- S. 92, FN 36: überzähliger Punkt nach Zitat entfernt
- S. 93, FN 38: hinter Komma, Punkt am Ende entfernt
- S. 94, FN 46: hinter Komma
- S. 95, FN 59: dto.

Weiter dann nicht mehr kontrolliert

S. 307, FN 68: Punkt am Ende entfernt

**Comment by dariok** [comment]
[karlstadt-2.pdf](https://github.com/dariok/karlstadt-issues/files/3538583/karlstadt-2.pdf)

**Comment by Wallsporn** [comment]
Hallo Dario,
das Manuskript ist jetzt super. Danke für Deine Arbeit! Timo bittet nur um einen Nachtrag in der Binnendifferenzierung. Danach schicken wir die Datei zur Imprimatur an Herrn Kaufmann, und dann geht es endlich in den Druck.
Herzliche Grüße von allen

[KGK-II-Druckfahne-2019-08-26.pdf](https://github.com/dariok/karlstadt-issues/files/3550068/KGK-II-Druckfahne-2019-08-26.pdf)
