### ISSUE TITLE
Darstellung von Dölsch in der Online-Edition

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#329]
Darstellung von Dölsch ist fehlerhaft

![Doelsch](https://user-images.githubusercontent.com/38648721/73464692-981a7600-437f-11ea-9ab8-866f2f946cb5.PNG)

**Comment by dariok** [comment]
Der Teil von `@` kann natürlich ausgeblendet werden, muß aber im Register stehenbleiben, da er für die Sortierung der Register notwendig ist.

**Comment by JBunselmeier** [comment]
@dariok, warum hast du mir das assigned? Soll ich irgendetwas tun?
