### ISSUE TITLE
Transformation funktioniert nicht mehr

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#330]
Fehlermeldung bei Transformation der EE mit QV (EE125 intro+text) und ohen QV (EE131 intro+text). Diese Dateien habe ich vorletzte Woche problemlos hochgeladen/transformiert:

**This XML file does not appear to have any style information associated with it. The document tree is shown below.
<exception>
<path>/db/edoc/ed000240/scripts/xquery/convert2.xql</path>
<message>
err:XPTY0004 checking function parameter 2 in call transform:transform($word, doc("../xslt/pre.xml"), ): XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: transform:transform($node-tree as node()*, $stylesheet as item(), $parameters as node()?) node()?. Expected cardinality: exactly one, got 0. [at line 70, column 46, source: /db/edoc/ed000240/scripts/xquery/convert2.xql]
</message>
</exception>**

**Comment by dariok** [comment]
Bitte noch einmal probieren!

**Comment by stefaniasalvadori** [comment]
Es funktioniert wieder!
