### ISSUE TITLE
!!! Hochladen von EE119A bzw. KGK 155

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#333]
Sobald ich versuche die EE119A hochzuladen, kommt folgende Fehlermeldung. Siehe Anhang. NB: Die KGK Nummern der Einheiten haben sich zuvor verschoben (EE119A war vorher KGK 153)

Als generelle Fragen: Können wir bei solchen Problemen überhaupt etwas selbst machen oder musst du das beheben?
![EE119A](https://user-images.githubusercontent.com/38648721/74322865-e3bc1f00-4d84-11ea-9852-2c7e1ea10220.PNG)

**Comment by timojanssentj** [comment]
Das gleiche Problem taucht auch bei der Einheit EE121 auf (Intro wie Text)

**Comment by timojanssentj** [comment]
EE 122 ebenso.

**Comment by timojanssentj** [comment]
EE 122A auch

**Comment by timojanssentj** [comment]
EE 123 intro = selbes Problem

**Comment by timojanssentj** [comment]
EE 124 intro kann auch nicht hochgeladen werden

**Comment by dariok** [comment]
Bitte immer die Dateien mit anhängen, damit ich diese prüfen kann.

**Comment by timojanssentj** [comment]
Upload hat geklappt. Ich schließe daher das Issue
