### ISSUE TITLE
allgemeine Probleme bei der Transformation neuer EE

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#336]
Die Zeilenumbrüche werden oft in der Online Edition falsch (z.B. mit Verdoppelungen) angezeigt
Hier ein Beispiel aus EE125_text - **sanctorum ctorum**:
![grafik](https://user-images.githubusercontent.com/28624747/74342909-88048c80-4daa-11ea-8044-d4017e117962.png)

**Das habe ich nun in XML justiert - ich lasse diese Nachricht als Reminder**

**Comment by stefaniasalvadori** [comment]
Probleme bei der Transformation von EE125 und EE131 in der Online Edition


- [x] Allgemein beobachte ich im Sachapparat eine **Vedroppelung von "Anm."**:

Anm. Anm. 17.

- [ ] Noch akuter sind die **Probleme bei Transformation von Namen mit Line Break. Wo die LineBreak ist, wird ein Spatium Mitte im Name eingefuegt:**

Ardens istud, ad sanctas literas, desyderium, Eruditissime Guolph gange, quod istic,
![grafik](https://user-images.githubusercontent.com/28624747/74415654-0f520e80-4e44-11ea-8d90-ef683c76e74b.png)


et pluribus placuit Augu stinus, non displiceat quod hodie
![grafik](https://user-images.githubusercontent.com/28624747/74415695-2133b180-4e44-11ea-94d6-4b556dbcec0d.png)

**Das habe ich nun in meinen EE in XML justiert - ich lasse diese Nachricht als Reminder**
**

**EE125 TEXT - Fehler im Textkritischem Apparat**


- [ ] vom Editor verbessert für 12.; xii. C    -->> fehlt A, B nach 12   RICHTIG WAERE: vom Editor verbessert für 12. A, B; xii. C 

**das gilt AUCH in**
vom Editor verbessert für ab hominationum; abhominationum C
vom Editor verbessert für ανονωνυμοις – im Korrekturverzeichnis ausgeführt; άννωνμοις C    --> hier dazu falsche Kursivierung in griech. Zitaten
Aug'ustinus' de ci'vitate' li. 28. c. 28. C

**Das markiere ich der schnellen PDF, da ich in XML nicht justieren kann - ich lasse diese Nachricht als Reminder**

- [ ] Noch diese Stellen falsch angezeigt:

Aug'ustinus' li. 18. de Civi'tate' dei. ca. 25. Item 1. Esd. 5. A, B   --> Anm. bei der Marginalie wird nicht angezeigt und im textkrit. Apparat mit 3 "hd" angegeben


folgt fehlt C   -->diese letzte Anm. waere eine Anm. über mehrere Wörter, d.h. ueber die Corrigenda-Liste. Die Anm. ist nicht richtig angezeigt - nachkodieren?

**Das habe ich nun in meinen EE in XML justiert - ich lasse diese Nachricht als Reminder**

**Fehler im EE125 Text**


- [x] si Evangelicas Mat kc literas, --> "Mat" - unvollstaendigt

- [x] meus271, hic Esdras putatur opinione tam Hierony'mi'lh272quam Augli273  --> "Aug" - unvollstaendigt

**Fehler im Sachapparat EE125**

- [x] Manchmal sind die QV auf Anm. in XML nicht transformiert und in HTML nicht angezeigt:

in Word
<img width="207" alt="Annotazione Word" src="https://user-images.githubusercontent.com/28624747/75687884-ca7d0300-5c9e-11ea-9a05-8249e3148861.png">

in HTML
<img width="207" alt="Annotazione HTML" src="https://user-images.githubusercontent.com/28624747/75687909-d2d53e00-5c9e-11ea-8510-58b0226f4b17.png">

**Comment by dariok** [comment]
Kannst Du mir die Dateien anhängen? Dann kann ich mir das in den  nächsten Tagen anschauen.

Edit: Oder kann ich die Texte aus #338 benutzen?

**Comment by stefaniasalvadori** [comment]
Die Word-Dateien meiner EE sind in Issue #338  angehängt

**Comment by nhenningKGK** [comment]
Ich beobachte, dass bei Bibelstellen das Spatium zwischen Buch und Kapitelangabe wegfällt. Z.B. "Röm12" statt "Röm 12".
Bsp. EE139 Anm. 12:

![EE139_github1](https://user-images.githubusercontent.com/60478046/75430797-2288d200-594c-11ea-8e33-14ebe793dd56.PNG)

**Comment by dariok** [comment]
Das ist nicht grundsätzlich so. Die hier genannte Stelle ist nur nicht am Stück formatiert.
Hier muß entweder später in der XML korrigiert werden (zu einer Stelle zusammenziehen und die Referenz kodieren) oder in Word beide Teile gelöscht werden, dann neu tippen und am Stück formatieren.

Ich kann das zwar generell immer zusammenziehen, aber dann werden 2 getrennt Bibelstellen auch zusammengezogen und nicht erkant.
