### ISSUE TITLE
Formatierung der QV in Word und Transformation

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#338]
In beiden meinen EE (EE125 und EE131) sind die QV in Word formatiert. Ausnahme sind QV auf gesemate EE (einfach als EE-Verweis formatiert, nicht mit Textmarke und Verlinkung) und sehr wenige QV auf EE, die nicht von mir ediert sind.

In der OnlineEdition funktioniert die Transformation dieser QV nicht.
Zur Info hier die Word-Fassungen, der gerade hochgeladenen EE125 und EE131:

**Comment by stefaniasalvadori** [comment]
Ich haenge die neue Fassung hier - ein paar Stellen in EE131intro auf EE125Text waren nicht verlinkt.

GRUNDFRAGE: Ich habe lokal, d.h. auf meinem LapTop die QV formatiert und verlinkt. D.h. die Verlinkungen laufen via einen lokalen Pfad; z.B. die Verlinkung in Anm. in EE131_intro auf EE131_text sieht folgendermasse aus: **C:\Users\Utente\Desktop\KGK III QV\EE131upload\EE131text2019-1-22.docx#q010**
Wenn ich die Dateien in Laufwerk-W speichere, funktioniert die Verlinkung weiter? Bzw. wird die Verlinkung die Quellen-Textmarke finden? Weil von W (Laufwerk) sind die Quellen-Datei auf meinem Laptop, auf Desktop, im Ordner KGK III QV nicht direkt zu finden.
Ich wusste es nicht, ob diesen Details Probleme bereiten, deshalb habe ich meine EE NUR auf meinem Laptop formatiert und hochgeladen.
Waere es aber problematisch, wenn man die EE teil auf dem Laptop, teil auf dem Buero PC formatiert, oder wenn man die Dateien sukzessiv in unterschiedlichen Ordnern (mal lokal auf PC, mal auf W) speichert und hochlaedst?

[EE131intro2020-1-22.docx](https://github.com/dariok/karlstadt-issues/files/4236500/EE131intro2020-1-22.docx)
[EE131text2019-1-22.docx](https://github.com/dariok/karlstadt-issues/files/4236501/EE131text2019-1-22.docx)
[EE125intro2020-feb-05.docx](https://github.com/dariok/karlstadt-issues/files/4236502/EE125intro2020-feb-05.docx)
[EE125_transcript_2020-feb-05.docx](https://github.com/dariok/karlstadt-issues/files/4236503/EE125_transcript_2020-feb-05.docx)

**Comment by dariok** [comment]
Ich habe hier eine Überarbeitung der Skripte erstellt. In meinen Tests funktioniert jetzt alles. Das Laufwerk sollte keine Probleme machen, solange der Dateiname mit EE anfängt, dann die Nummer und dann „transcript“ (oder „text“) oder „introduction“. Wenn sich noch Probleme ergeben, müssen wir das nochmal etwas schärfen, aber grundsätzlich ist es kein Problem

**Comment by stefaniasalvadori** [comment]
Ich habe meine EE nochmals hochgeladen. 

Es sieht besser aus und in HTML wird zwischen internen QV (Textstelle) und externen QV (KGK).

![Annotazione textstelle](https://user-images.githubusercontent.com/28624747/75959338-5325ba00-5ebe-11ea-99f1-af4f6d6bacca.jpg)



![Annotazione 2020-03-05 084910](https://user-images.githubusercontent.com/28624747/75959296-3e492680-5ebe-11ea-8480-a44763835850.jpg)


Wenn ich auf 2. Beispiel (KGK ) kliecke:
In HTML funktioniert die Verlinkung nicht.

![Annotazione 2020-03-05 084701](https://user-images.githubusercontent.com/28624747/75959180-fb874e80-5ebd-11ea-85aa-c7435a84f5dd.jpg)

Nur ein HTML-Script Problem?
In XML die Stelle sieht so aus:
ptr type="wdb" target="../EE125/EE125_Intro###.xml#q004"/


Ist es richtig so?


HIer nochmals meine EE
[EE125_transcript_2020-feb-05.docx](https://github.com/dariok/karlstadt-issues/files/4291611/EE125_transcript_2020-feb-05.docx)
[EE125intro2020-feb-05.docx](https://github.com/dariok/karlstadt-issues/files/4291614/EE125intro2020-feb-05.docx)
[EE131text2019-1-22.docx](https://github.com/dariok/karlstadt-issues/files/4291616/EE131text2019-1-22.docx)
[EE131intro2020-1-22.docx](https://github.com/dariok/karlstadt-issues/files/4291617/EE131intro2020-1-22.docx)

**Comment by dariok** [comment]
Ich habe die Verarbeitung des Dateinamens angepasst. Bitte noch einmal probieren.

**Comment by stefaniasalvadori** [comment]
Hallo Dario, habe gerade EE125 nochmals hochgeladen - ich bekomme nochmals die gleiche Fehlermeldung (auch wenn ich die Dateien nach hochladen mi F5 "aktualisiere")
Vielleicht mache ich etwas falsch?
Soll ich lieber die Dateien umbenennen: EE125_text / EE125_intro

![Fehlermeldung](https://user-images.githubusercontent.com/28624747/76112990-96c61400-5fe3-11ea-9115-59c5616fe401.jpg)

**Comment by nhenningKGK** [comment]
Bei in Word formatierten QV auf andere EE wird teilweise die EE-Nummer nicht aus dem Dateinamen ausgelesen. So verweist, um ein konkretes Beispiel zu nennen, in EE126[=Nr. 165] die Fußnote 16 auf einen leeren Link ohne EE-Nummer:
![grafik](https://user-images.githubusercontent.com/60478046/76228704-5e137e00-6221-11ea-84e7-f9eadb09bb2c.png)
http://dev2.hab.de/edoc/view.html?id=..//_introduction.xml#q002#q002

[EE126Intro2020-03-08.docx](https://github.com/dariok/karlstadt-issues/files/4307451/EE126Intro2020-03-08.docx)

**Comment by dariok** [comment]
Die Links sollten jetzt funktionieren, bitte testen.

@JBunselmeier Die Anpassungen sind in tei-common.xsl – da kommen noch ein paar Kleinigkeiten dazu bis heute Abend.

**Comment by nhenningKGK** [comment]
Vielen Dank schon einmal!!

Ich habe die QV eben stichprobenartig geprüft und von vielen Links, an denen "KGK " steht, kommt man nun zur richtigen EE.
Nur bei meinem o.g. Beispiel (Fußnote 16 in EE126intro) scheint es nicht zu funktionieren. Ich habe EE126intro und EE128text (die Zieldatei) neu hochgeladen und der leere Link besteht nach wie vor. Folgende Fehlermeldung erscheint:

![grafik](https://user-images.githubusercontent.com/60478046/76304965-94eea000-62c4-11ea-80f8-96ada9d9dc42.png)

[EE128Text2020-03-08.docx](https://github.com/dariok/karlstadt-issues/files/4311855/EE128Text2020-03-08.docx)
[EE126Intro2020-03-10.docx](https://github.com/dariok/karlstadt-issues/files/4311857/EE126Intro2020-03-10.docx)

**Comment by stefaniasalvadori** [comment]
Die Verlinkung der QV scheint innerhalb einer EE zu funktionieren.
QV auf andere EE sind dagegen nicht immer verlinkt.

In EE125 finde ich in der Online Ausgabe nur "KGK I"
![EE125 online](https://user-images.githubusercontent.com/28624747/76307372-016b9e00-62c9-11ea-8f5b-ce2ab01271ad.jpg)

Wenn ich auf "KGK I" clicke lande ich richtig auf Widmungsbrief von EE131

ABER

In EE131 finde ich in der Online Ausgabe richtig "KGK 163"
![EE131 online](https://user-images.githubusercontent.com/28624747/76307483-31b33c80-62c9-11ea-96fb-3c659e2f5d28.jpg)

Wenn ich aber auf "KGK 163" clicke, bekomme ich Fehlermeldung

![EE131 error](https://user-images.githubusercontent.com/28624747/76307557-57404600-62c9-11ea-883f-3a219455c78b.jpg)

Beide sind aber in XML aehnlich kodiert:
Hier Beispiel aus EE125: ptr type="wdb" target="../131/131_transcript.xml#n001"/
Hier Beispiel aus EE131: ptr type="wdb" target="../125/125_transcript.xml#q023"

**Comment by dariok** [comment]
Der Fall von 126 Intro sollte jetzt nach neuem Upload funktionieren.

**Comment by dariok** [comment]
Auch der Fall in 131 sollte jetzt stimmen. Ich muss nur noch die Anzeige des Links anpassen.

**Comment by stefaniasalvadori** [comment]
Indeed. It works!
Danke.

**Comment by stefaniasalvadori** [comment]
Noch offen bleibt die Frage von **allgemeine QV auf EE von KGK III**. Z.B. "vgl. EE126##"
Die Stellen sind in Word als "KGK: EE-Verweis" formatiert
In XML und HTML sind sie aber nicht transformiert:

![allgemeine QV 1](https://user-images.githubusercontent.com/28624747/76341977-17478600-62fe-11ea-9e1c-ca204277aa0c.jpg)

**Comment by dariok** [comment]
Generelle Verweise auf EE funktionieren, wenn sie die Form haben EE123##
