### ISSUE TITLE
Verdopplung des Wortes "Text" beim Transformieren

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#339]
Bei der Transformation verdoppelt er "Text"
![EE 123 text](https://user-images.githubusercontent.com/38648721/74913724-839b2d80-53c1-11ea-8279-d60ac705572b.PNG)
[EE123_text_2020-02-20_TJ.docx](https://github.com/dariok/karlstadt-issues/files/4229546/EE123_text_2020-02-20_TJ.docx)

Edit: Das Problem ergibt sich auch in Kombination mit dem Buchtitel. Ich schaffe es, den Buchtitel anzeigen zu lassen, wenn ich zwischen EE Titel und "Text" einen Absatz setze. Dann erscheint aber "Text" selbst im Text. Entferne ich diesen, taucht das als Buchtitel formatiertes gar nicht.

**Comment by timojanssentj** [comment]
Ähnliches geschieht auch bei der Einheit 124.
[EE 124_text_2019-12-12_TJ_test.docx](https://github.com/dariok/karlstadt-issues/files/4229988/EE.124_text_2019-12-12_TJ_test.docx)

**Comment by timojanssentj** [comment]
In EE127 wird der Buchtitel nicht eigens dargestellt.
![EE 127 text Text](https://user-images.githubusercontent.com/38648721/75426677-6fb57580-5945-11ea-94b2-869fdca34573.PNG)
[EE127text_2020-01-14.docx](https://github.com/dariok/karlstadt-issues/files/4260433/EE127text_2020-01-14.docx)

**Comment by timojanssentj** [comment]
Ähnliches auch in EE 133.
[EE133text2020-01-13.docx](https://github.com/dariok/karlstadt-issues/files/4261209/EE133text2020-01-13.docx)

**Comment by dariok** [comment]
_Vor_ „Text“/„Einleitung“ darf keine Leerzeile stehen, danach muß eine stehen.

Die erste leere Zeile dient der Abgrenzung von Kopf und Text. Ich kann das auch wieder auf die Erkennung von „Überschrift1“ umstellen, aber dann muß sichergestellt sein, daß exakt und ausschließlich „Text“/„Einleitung“ als „Überschrift1“ formatiert ist.

**Comment by dariok** [comment]
Die Erkennung von Einleitung/Text sowie des Anfanges des Textes ist jetzt angepaßt. Wenn die Formatierung paßt, sollte es jetzt keine Probleme mehr geben.
