### ISSUE TITLE
Bibliographische Angaben nicht verlinkt

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#341]
Manche (nicht alle!) neuen (= erst in KGK III auftauchenden) bibliographischen Angaben in meinen EE131 und EE125 (Texte in Issue #338 ) werden nicht getaggt/verlinkt, auch wenn die Short-Titles in der neuen Bibliographie richtig eingefuegt wurden.

Ich habe versucht, sie neu zu formatieren und transformieren, klappt es aber nicht und da es nur willkuerlich das Problem aufftritt, weiss ich nicht, woran es liegt.

**Comment by stefaniasalvadori** [comment]
Auch die - anscheinend richtig getaggten - bibliographischen Angaben sind nicht in der rechten Spalte angezeigt

**Comment by stefaniasalvadori** [comment]
Hier zum Testen der Verlinkung Bibliographie
[EE125intro2020-feb-05.docx](https://github.com/dariok/karlstadt-issues/files/4313281/EE125intro2020-feb-05.docx)
[EE125_transcript_2020-feb-05.docx](https://github.com/dariok/karlstadt-issues/files/4313282/EE125_transcript_2020-feb-05.docx)

**Comment by dariok** [comment]
Zur Dokumentation: Es wird ab jetzt generell ed000216/register/kgk_bibliography.xml ausgewertet.

**Comment by stefaniasalvadori** [comment]
@dariok 
In Ordnung
Wenn ich aber nun die EE hochlade, sind viele Namen, Orte und bibl. Angaben nicht mehr referenziert. Frueher waren sie doch referenziert.

Z.B. die name "Karlstadt" ist nicht referenziert - und tatsaechlich ist die Variante im Register im Ordner 216 nicht drin. Das ist sehr komisch, da diese Name schon in KGK II als Variante in XML eingetragen war.

![fehler 2](https://user-images.githubusercontent.com/28624747/76358395-ab731680-6319-11ea-9251-0af4c7f2af11.jpg)

Auch die bibliographische Angaben sind nicht mehr referenziert, auch wenn sie in Bibliographie XML im Ordner 216 gespeichert sind.
![fehler biblio angabe](https://user-images.githubusercontent.com/28624747/76358398-ac0bad00-6319-11ea-9150-545b5c986db0.jpg)


**Wenn diese Referenzierungen nicht klappen, koennen wir nicht mehr unterscheiden, welche Namen und Angaben authomatisch verlinkt werden koennen und welche nachkodiert werden muessen. Das ist ein Problem.**

Was sollen wir tun?

**Comment by stefaniasalvadori** [comment]
Loesung: Die fehlende Personennamen im Register Ordner 216 kann ich ggf. morgen ergaenzen. Die sind sowieso im Register Ordner 240 (von mir dort falsch gespeichert) und ich habe ein BackUp dieser Ergaenzungen. Es sollte schnell gehen.
