### ISSUE TITLE
Hyperlink auf Fremddigitalisaten in Sachapparat - Anzeige zu verbessern fuer HTML

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#343]
Wir hatten uns entschieden, die von Karlstadt selbst verwendeten (d.h. ausdrucklich zitierten) Ausgaben im Sachapparat auf die Digitalisate der entsprechenden Folia zu verlinken.

Z.B. wenn Karlstadt im Text eine Augustin-Stelle mit Angabe von Kolumna, Folia oder Zeilen zitiert, dann wird im Sachanmerkung neben der mordernen Edition (PL/CSL/CCSL) auch die von Karlstadt verwendete Edition angegeben (Augustinus, Libri (1506)).

Ich habe solche Stelle in Word auch entsprechen mit den Fremddigitalisaten verlinkt. Die Verlinkung funktioniert, nur sieht sie nicht schoen aus (Beispiel aus EE125_text):

<img width="370" alt="Annotazione 2020-02-21 160903" src="https://user-images.githubusercontent.com/28624747/75046015-a104f000-54c4-11ea-8a82-b1a36c7b8a32.png">

Am besten _[Digitalisat]_ nach der bibliographischen Angabe setzen.

FRAGE: Sind diese Verlinkungen fuer Herstellung der Druck-PDF problematisch?

**Comment by stefaniasalvadori** [comment]
Bei Hyperlink auf Fremddigitalisaten in Sachapparat sind hochgestellte Buchstaben r v nicht richtig angezeigt:

Word:
<img width="376" alt="Annotazione Word" src="https://user-images.githubusercontent.com/28624747/75684886-f3e76000-5c99-11ea-9861-425994048c56.png">

HTML
<img width="385" alt="Annotazione HTML" src="https://user-images.githubusercontent.com/28624747/75684896-fa75d780-5c99-11ea-9ed9-c3d53cdcbee7.png">

**Comment by stefaniasalvadori** [comment]
Zur Druck-PDF bitte auch diese Transformationsfehler (auch in XML) beachten - in Word die Stelle korrigieren?

![fehler biblio angabe](https://user-images.githubusercontent.com/28624747/76338334-d436e400-62f8-11ea-8c78-b737f4c3985f.jpg)

**Comment by dariok** [comment]
Hier dürfen die Links auf die Digitalisate nicht als bibliographische Angabe markiert sein.

**Comment by stefaniasalvadori** [comment]
Wo/Wie sollen wir die Stellen in Word und in XML verlinken?

**Comment by dariok** [comment]
In dem letzten Beispiel sollte nur „Augustinus, Libri (1506)“ als bibliographische Angabe markiert sein; die Links auf die Digitalisate können bleiben, wie sie sind, sollten aber eben nicht asl bibl. Angabe markiert sein. Es sollte reichen, einfach die Stelle zu markieren und die Zeichenvorlage zu löschen.

**Comment by stefaniasalvadori** [comment]
Ok, ich werde in meinen EE nachkodieren muessen. 
D.h. diese falsche Stelle

![Annotazione 2020-03-16 162218 prima](https://user-images.githubusercontent.com/28624747/76773264-814ea800-67a2-11ea-8c8e-c0204c09790f.jpg)

wird nun so korrigiert:

![Annotazione 2020-03-16 162218 seconda](https://user-images.githubusercontent.com/28624747/76773304-8d3a6a00-67a2-11ea-8537-84f8792856fb.jpg)

Ist es richtig?

**Comment by dariok** [comment]
`<rs type="bibl" ref="augustinus_libir_1505"> 5</rs>, <ref type="digitalisat" target="...">fol. c3v</ref>` wäre die beste Variante.

Wenn in Word die Formatierung wegfällt, sollte auch das richtige Ergebnis herauskommen, ich habe die Upload-Skripte angepaßt.

**Comment by stefaniasalvadori** [comment]
Alles klar, danke!

**Comment by stefaniasalvadori** [comment]
@dariok  Zu beiden Problemen (Verlinkung Fremddigi und hochgestellte "r"/"v") ist diese die richtige Kodierung?
(ich - und vielleicht auch Timo - muessen nachkodieren...

![image](https://user-images.githubusercontent.com/28624747/76947656-3cdc1d00-6906-11ea-8e37-9801f5e568e1.png)

**Comment by stefaniasalvadori** [comment]
Oder sollen wir zwischen rs und ptr eine ; und Spatium einfuegen - wie in Deinem Beispiel oben?
Fuehrt dies nicht zu Problemen in PDF? z.B. wird in der PDF nicht eine ; und Spatium auch auftauchen?
![image](https://user-images.githubusercontent.com/28624747/76953755-85e49f00-690f-11ea-9e6a-2e03eb909e38.png)

**Comment by stefaniasalvadori** [comment]
In EE125_text habe ich nun die Stellen entsprechen nachkodiert.
Koennen wir eine PDF davon erstellen, und angucken, wie sie in der PDF nun aussehen?
