### ISSUE TITLE
EE 127 intro

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#344]
Bei der Transformation passieren zwei Fehler: 
1. Die Handschriftensiegel werden nicht korrekt ausgegeben. Die Hochstellung fehlt.
2. Unter Siegel G fehlen Autor und Titel der Sammelausgabe.
![EE 127 intro Hochstellen](https://user-images.githubusercontent.com/38648721/75425823-c02bd380-5943-11ea-9352-f2b0b49c2cd9.PNG)
![EE 127 intro G Auslassung](https://user-images.githubusercontent.com/38648721/75425828-c15d0080-5943-11ea-83e0-67ba711ae38f.PNG)
[EE127Intro2020-02-26_TJ.docx](https://github.com/dariok/karlstadt-issues/files/4260379/EE127Intro2020-02-26_TJ.docx)

**Comment by stefaniasalvadori** [comment]
Die  Handschriftensiegel werden nicht korrekt ausgegeben und muessen nachkodiert werden. Sie muessen aber NICHT als "KS Sigle" formatiert, sonst klappt die Transformation nich.
In G war etwas falsch formatiert. Online nun die korrigierte Version - Issue zu closen.
Hier die neue Word Fassung 
[EE127Intro2020-03-14.docx](https://github.com/dariok/karlstadt-issues/files/4332964/EE127Intro2020-03-14.docx)
