### ISSUE TITLE
Darstellung Fol in EE112

### ISSUE THREAD

**Issue by nhenningKGK** [dariok/karlstadt-issues#347]
Die Seitenangabe wird auf der Website nicht ausgegeben:

![grafik](https://user-images.githubusercontent.com/60478046/75458422-13bb1300-597e-11ea-8def-5ab0264a39c3.png)

Liegt es daran, dass die Angaben "A1r" etc. nicht nur mit KS:Text formatiert, sondern auch mit einem Hyperlink nach "http://diglib.hab.de/show_image.php?dir=&distype=imgs&image=" versehen sind?

**Comment by Wallsporn** [comment]
Das sollte nicht sein. Bitte den Link rausnehmen und einfach A1r etc. eintragen. Das muss in einer frühen Fassung erfolgt sein.
HG
Harald
