### ISSUE TITLE
EE112 Issues

### ISSUE THREAD

**Issue by nhenningKGK** [dariok/karlstadt-issues#348]
Beim Übergang von E1v auf E2r gibt es einen Umbruch, der falsch ausgegeben wird:
Website:
![grafik](https://user-images.githubusercontent.com/60478046/75468948-600e4f00-598e-11ea-86d3-b6d721c8b5bb.png)

Word-Dokument:
![grafik](https://user-images.githubusercontent.com/60478046/75468978-6c92a780-598e-11ea-93e8-302471e4b4ef.png)

**Comment by nhenningKGK** [comment]
Ebenso am Übergang von G2r nach G2v

**Comment by nhenningKGK** [comment]
In Fußnote 149 werden die Formatierungen nicht erkannt.

![grafik](https://user-images.githubusercontent.com/60478046/75478723-bb483d80-599e-11ea-9b3c-58e95c4f7333.png)

So ist z.B. die letzte Angabe (Vgl. Bubenheimer...) im docx als bibliograph. Angabe formatiert.

**Comment by stefaniasalvadori** [comment]
Es handelt sich um LineBreak + Folioangabe innerhalb eines Wortes. 
Nach der Folioangabe muss man nich nochmals "Enter" haben geht das Wort durcheinander.

Die Word-Dateien habe ich korrigiert und in W gespeichert.
