### ISSUE TITLE
Korrekte Wiedergabe des FN Apparats

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#349]
In EE127 werden zwei textkritische Anmerkungen nicht korrekt ausgeworfen.
[EE127text_2020-01-14.docx](https://github.com/dariok/karlstadt-issues/files/4267475/EE127text_2020-01-14.docx)
![EE127 text FNApparat](https://user-images.githubusercontent.com/38648721/75556546-bb981580-5a3e-11ea-8115-f2ec5a74ea2d.PNG)

**Comment by timojanssentj** [comment]
Textkritische Anmerkung wird nicht korrekt ausgegeben
[EE129text-2019-11-14.docx](https://github.com/dariok/karlstadt-issues/files/4267633/EE129text-2019-11-14.docx)
![EE129 text FNApparat](https://user-images.githubusercontent.com/38648721/75559498-dc169e80-5a43-11ea-93f1-ad03fd289a12.PNG)

**Comment by dariok** [comment]
2. Fall kann nicht automatisch funktionieren, da „hinzugefügt“ eine Standard-Formulierung ist, die zu `add` umgesetzt wird.
Hier entweder eine nadere Fomulierung nehmen oder manuell im fertigen XML korrigieren.
