### ISSUE TITLE
Titelfehler KGK I Nr. 57

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#35]
KGK I hat im Inhaltsverzeichnis für Nr. 57 einen Titelfehler:
Richtig: Karlstadt an das Kapitel des Wittenberger Allerheiligenstifts
Nicht: an Kfst. Friedrich
Im Dokument ist der Titel richtig

**Comment by Marxistin** [comment]
Nach Prüfung geschlossen :-)
