### ISSUE TITLE
Bibliographisches Tagging

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#350]
Mir ist etwas bei der Formatierung von DWb aufgefallen. Sobald beispielsweise "DWb 1, 124f." der Punkt in "f." mit formatiert wird, wird die Bibliographie nicht erkannt. Formatiert man nur bis "f", dann schon.

**Comment by stefaniasalvadori** [comment]
Bei mir scheint zu funktionieren. Bitte nochmals pruefen
![Dwb angabe](https://user-images.githubusercontent.com/28624747/76321621-9333d500-62e2-11ea-8024-ec08b6ce1736.jpg)
