### ISSUE TITLE
Scheinbar falsche Registereinbindung?

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#358]
Nach einigen Versuchen ist mir aufgefallen, dass Nachtragungen im Personenregister von 216 nicht dazu führen, dass diese in den jeweiligen HTML Dateien registriert werden. Beispielsweise "[Johannes] Capreolus" in EE28, welche sich bereits im Register von 216 befindet. Greift das Skript eventuell noch auf 240 zurück?
![Bildschirmfoto 2020-03-09 um 15 30 39](https://user-images.githubusercontent.com/38648721/76227017-f2301600-621e-11ea-85dc-05a6861d9c1c.png)

**Comment by stefaniasalvadori** [comment]
Problematisch sind hier die eckige Klammer - bitte sie loeschen und einfach Johannes Capreolus und Gabriel Biel belassen
