### ISSUE TITLE
Upload von EE127text, 129text, EE133text, 139text funktioniert nicht

### ISSUE THREAD

**Issue by nhenningKGK** [dariok/karlstadt-issues#359]
Der Upload von genannten EE 127text, 129text, EE133text, 139text funktioniert leider nicht.

Sollten die einen gemeinsamen Fehler aufweisen den ich selbst beheben kann, freue ich mich über eine kurze Info!

[EE139text_2020-03-09.docx](https://github.com/dariok/karlstadt-issues/files/4307409/EE139text_2020-03-09.docx)
[EE133text2020-03-09.docx](https://github.com/dariok/karlstadt-issues/files/4307411/EE133text2020-03-09.docx)
[EE129text-2020-03-08.docx](https://github.com/dariok/karlstadt-issues/files/4307412/EE129text-2020-03-08.docx)
[EE127text_2020-03-09.docx](https://github.com/dariok/karlstadt-issues/files/4307413/EE127text_2020-03-09.docx)

**Comment by nhenningKGK** [comment]
[EE127text_2020-03-11.docx](https://github.com/dariok/karlstadt-issues/files/4320534/EE127text_2020-03-11.docx)
[EE129text-2020-03-11.docx](https://github.com/dariok/karlstadt-issues/files/4320535/EE129text-2020-03-11.docx)
[EE133text2020-03-09.docx](https://github.com/dariok/karlstadt-issues/files/4320539/EE133text2020-03-09.docx)
[EE139text_2020-03-11.docx](https://github.com/dariok/karlstadt-issues/files/4320541/EE139text_2020-03-11.docx)



Hab es nochmal getestet, es geht noch nicht.

**Comment by Wallsporn** [comment]
Upload von EE133text funktioniert, aber fehlerhaft:
Alle Thesennummern mit "1"
Text in einer Zeile mit Seitenzahl und Thesentitel

![grafik](https://user-images.githubusercontent.com/28565515/76506805-0c9b0700-644c-11ea-8d45-362ad3d68426.png)

**Comment by Wallsporn** [comment]
Upload von EE127text funktioniert, aber mit Fehler:
Transfo verschluckt "Wit-
tembergk" mit dazugehöriger Anm.
![grafik](https://user-images.githubusercontent.com/28565515/76507471-2ab53700-644d-11ea-8f05-f1c4385106c6.png)
![grafik](https://user-images.githubusercontent.com/28565515/76507500-33a60880-644d-11ea-8739-3802a9961054.png)

**Comment by nhenningKGK** [comment]
Was hast du geändert, um (wenn auch fehlerhaft) hochladen zu können?

**Comment by Wallsporn** [comment]
Upload von EE129text ok, EE139text mit Fehler wie bei EE133text (Thesennummern alle auf "i" gesetzt
![grafik](https://user-images.githubusercontent.com/28565515/76508327-79af9c00-644e-11ea-816b-26474f7b6588.png)

**Comment by dariok** [comment]
Zu 133: Die einzelnen Einträge einer Liste fürfen nicht mit `F05E` abgeschlossen werden.

**Comment by Wallsporn** [comment]
Das sind sie nicht und auch nicht gewesen. Fehler lag darin, dass die erste Seitenzahl mit Überschrift formatiert war.

**Comment by stefaniasalvadori** [comment]
Ja, sie waren, Dario hatte recht.
EE133_text ist nun hochgeladen und die Thesen sind richtig nummeriert.
Die neue Word Fassung wie immer in W Odner Upload

**Comment by stefaniasalvadori** [comment]
Auch EE139 wurde entsprechen (wie EE133) in Word korrigiert.
I close this Issue and open a new one with the new Word-Files.
