### ISSUE TITLE
Störungen "Spielwiese" KGK II

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#36]
Seit gestern funktioniert die "Spielwiese" nicht mehr - keine Ahnung woran es liegt
Falls ich/wir was tun sollen, bitte ich um kurze Rückmeldung

![unbenannt](https://user-images.githubusercontent.com/28624747/28058345-89963936-6621-11e7-989a-4ea940f92ea3.JPG)

**Comment by dariok** [comment]
Bei der Nr. 168 war die alte Zählung »mitgelaufen« in die neue, weshalb er nach der Nummer nicht sortieren konnte. Das ist jetzt behoben.
Ich habe bei der Gelegenheit auch die doppelte Nr. 168 entfernt.

**Comment by stefaniasalvadori** [comment]
Danke, es funktioniert nun wieder!
