### ISSUE TITLE
EE123_text, 124_text  in XML kann nicht nochmals hochgeladen werden

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#360]
Diese EE hatten wir hochgeladen. Sie sind noch in XML. Wir koennen sie aber nicht nochmals hochladen
Wir bekommen diese Fehlermeldung
![Cattura1](https://user-images.githubusercontent.com/28624747/76561790-4d266f00-64a4-11ea-9df1-8e8fec23c220.JPG)

[EE123_text_2020-03-11.docx](https://github.com/dariok/karlstadt-issues/files/4326256/EE123_text_2020-03-11.docx)
[EE 124_text_2020-03-11.docx](https://github.com/dariok/karlstadt-issues/files/4326268/EE.124_text_2020-03-11.docx)

**Comment by dariok** [comment]
Auch hier müssen die Einträge in der METS manuell ergänzt werden.

**Comment by stefaniasalvadori** [comment]
Ok, danke! Du gibt Signal, falls ich sie nochmals hochladen soll.

**Comment by stefaniasalvadori** [comment]
Soweit ich gerade sehe, sind diese EE wieder Online erreichbar.
