### ISSUE TITLE
EE114 und EE120A werden nicht hochgeladen

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#362]
Hier die Fehlermeldung
![Cattura2](https://user-images.githubusercontent.com/28624747/76562971-c45d0280-64a6-11ea-97b8-1e6b2fc0d5fe.JPG)

[EE114_intro_2020-01-22.docx](https://github.com/dariok/karlstadt-issues/files/4326366/EE114_intro_2020-01-22.docx)
[EE120A_intro_2020-01-22.docx](https://github.com/dariok/karlstadt-issues/files/4326369/EE120A_intro_2020-01-22.docx)

**Comment by dariok** [comment]
Die Struktur der METS-Datei hat sich geändert. Daher muß ich das Upload-Skript anpassen, damit die Dateien angezeigt werden können, die dort noch nicht eingetragen sind.

**Comment by dariok** [comment]
Diese beiden habe ich erst einmal manuell eingetragen.

**Comment by stefaniasalvadori** [comment]
Ok, alles klar, danke!
Zur Sicherheit: d.h. wir duerfen diese EE nicht mehr hochladen, oder?
Ist kein Problem, nur signalisiere auch den anderen...

**Comment by dariok** [comment]
Doch, kann hochgeladen werden.
Nur beim ersten Mal, das eine Datei hochgeladen wird, muß der Eintrag erstellt werden. Das geht aber derzeit nicht automatisch.

**Comment by stefaniasalvadori** [comment]
Danke!
Ich habe nun auch die Orts- und Personennamen-Varianten fuer diese EE nachkodiert und sie sind m.E. fertig. Leite nun die direkte Links an Alex weiter!

**Comment by timojanssentj** [comment]
Der Upload hat bei mir erneut nicht funktioniert. Gleiche Fehlermeldung

**Comment by dariok** [comment]
Bitte prüfen! Vielleicht noch im Cache?

**Comment by stefaniasalvadori** [comment]
EE114 text und EE120A_text sind auch bei mir nicht erreichbar, auch wenn ich mit F5 die HTML aktualisiere

**Comment by dariok** [comment]
Beide EE sind verschollen; die Intros sind beide erreichbar. Ggf. mit Strg+r

**Comment by stefaniasalvadori** [comment]
Vero! So' pirla!
Danke!
