### ISSUE TITLE
"r" und "v" werden in bibl. Angaben nicht hochgestellt

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#364]
"r" und "v" (recto - verso) werden bei Folioangabe in bibl. Angaben nicht hochgestellt:
![recto verso](https://user-images.githubusercontent.com/28624747/76690157-b42b5b80-663d-11ea-8f98-841cf52f9c01.jpg)

**Comment by dariok** [comment]
Vgl. #343 

Wenn die fol.-Angaben nicht formatiert sind, stimmt auch die Hochstellung.
