### ISSUE TITLE
Siglen der einzigen Exemplaren in Ueberlieferung sind zu justieren

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#365]
Die Siglen der "Weitere Exemplare" in Ueberlieferung sind nicht richtigt angezeigt/kodiert. Ort-Siglen muessen tiefgestellt werden:
![sigle exemplaren](https://user-images.githubusercontent.com/28624747/76690197-184e1f80-663e-11ea-993c-31172d570c0d.jpg)

**Comment by JBunselmeier** [comment]
@stefaniasalvadori  um welche Einheit geht es?

**Comment by stefaniasalvadori** [comment]
EE112 intro z.B.
gibt es auch andere EE, wo sigle nachkodiert werden sollen

**Comment by JBunselmeier** [comment]
XSL ist angepasst. Ich glaube, die als `<hi rend="super">` kodierten Foliogangaben r und v waren auch nicht hochgestellt angezeigt, kann das sein? Jetzt sind sie es auf jeden Fall.

**Comment by stefaniasalvadori** [comment]
infinite grazie @JBunselmeier !
