### ISSUE TITLE
EE119text Textkritischer Apparat wird fehlerhaft dargestellt

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#367]
Die textkritischen Anmerkungen a und b werden nicht richtig transformiert. Da ich ungerne in XML das selbst behebe, gebe ich lieber die Aufgabe weiter.

[EE119_text_2020-01-22.docx](https://github.com/dariok/karlstadt-issues/files/4334507/EE119_text_2020-01-22.docx)

**Comment by stefaniasalvadori** [comment]
Anm. **a** kann nicht transformiert werden, da sie nicht unsere "Richtlinien" enstpricht - wir machen nie eine textkrit. Anm zu Seiteangabe! Muss es so sein?

Diese Stellen in der Schnelle-PDF fuer Dario markieren - sie koennen m.E. leicht in XML korrigiert werden, da sie schon drin sind.
