### ISSUE TITLE
EE120 Textkritischer Apparat beinhaltet Fehler

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#368]
Anm. b: nach „... tractatus nostri,...“ ist: „... tuum praestolor consilium.b“ verschwunden
Anm. c: wird als a ausgegeben
[EE120_text_2020-01-15.docx](https://github.com/dariok/karlstadt-issues/files/4337518/EE120_text_2020-01-15.docx)

**Comment by dariok** [comment]
Der Punkt hinter „consilium“ ist nicht formatiert.
