### ISSUE TITLE
EE121text Textkritischer Apparat

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#369]
zwischen denTextkrit.Anm.Zeichen „j“ und „k“ ist ein ganzer Satz verschwunden: „j literarum quas cum his misi sarcinulam, sie fieri potest, cum fideli nuncio k“

**Comment by dariok** [comment]
Anm. j ist hier fehlerhaft; sie müßte lauten „davor gestrichen _hac_“
