### ISSUE TITLE
Einleitungstexte zu KGK III

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#370]
- [ ] Tabelle mit Kolumnentiteln 
**Bitte die Reihenfolge der EE soll nach dieser Tabelle angepasst werden. Bitte EE139A (Probationes zu den 33 Conclusiones) entfernen, da die EE zu KGK IV gehoert**

[Kolumnentitel und Reihenfolge KGK III_2020-3-31_StS_HB.docx](https://github.com/dariok/karlstadt-issues/files/4413647/Kolumnentitel.und.Reihenfolge.KGK.III_2020-3-31_StS_HB.docx)

- [ ] Vorwort und Einleitung zu KGK III

[KGKIII_Vorwort+Einleitung2020-03-16 (1).docx](https://github.com/dariok/karlstadt-issues/files/4339256/KGKIII_Vorwort%2BEinleitung2020-03-16.1.docx)

- [ ] Editionsrichtlinien
[KGK-III-Richtlinien-2020-03-31_HB.pdf](https://github.com/dariok/karlstadt-issues/files/4414170/KGK-III-Richtlinien-2020-03-31_HB.pdf)

- [ ] AbkürzungenundSiglen
[KGK-III-Abkürzungsliste_HB_StS.pdf](https://github.com/dariok/karlstadt-issues/files/4413650/KGK-III-Abkurzungsliste_HB_StS.pdf)

- [ ] Verzeichnis der erwähnten Kurztitel der Karlstadtwerke
**s.u.**

- [ ] Karlstadt-Chronologie1520
**s.u.**

**Comment by Wallsporn** [comment]
Verzeichnis der erwähnten Kurztitel der Karlstadtwerke
[Kurztitel-KGK-III-2020-04-01.docx](https://github.com/dariok/karlstadt-issues/files/4417996/Kurztitel-KGK-III-2020-04-01.docx)

**Comment by Wallsporn** [comment]
Chronologie 1520
[Chronologie.1520-hb.docx](https://github.com/dariok/karlstadt-issues/files/4420782/Chronologie.1520-hb.docx)
