### ISSUE TITLE
Seltsame Phänomene in EE125

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#371]
Ein Titel in Literatur von EE125_intro - Kessler, Andreas Bodenstein - ist in der PDF verschwunden, auch wenn der Titel sowohl in Word als auch in XML und HTML enthalten ist.

Das ist ein bisschen beunruhigend, da wir die Texte genau in Word und in HTML geprueft habe. Wir koennen nun nich so gruendlich die PDF korrekturlesen.
Wir kann man solche Auslassungen in der PDF verhindern?

Hier die PDF:
![Annotazione 2020-03-17 174517 pdf](https://user-images.githubusercontent.com/28624747/76880034-6863f680-6877-11ea-9dc9-9d30418bae31.jpg)

Hier die HTML
![Annotazione 2020-03-17 174517 html](https://user-images.githubusercontent.com/28624747/76880048-70239b00-6877-11ea-9ee4-efb81a11a443.jpg)

Hier die XML
![Annotazione 2020-03-17 174517 xml](https://user-images.githubusercontent.com/28624747/76880086-7c0f5d00-6877-11ea-9232-f7d59b895630.jpg)

**Comment by stefaniasalvadori** [comment]
Jetzt sehe ich, das der Titel in XML ist nur getaggt, der Titel selbst ist aber dabei verschwunden... noch beunruhigend... Ich werde es nachkodieren, wenn aber Du, Dario, eine Idee hat, wie man diese Transformationsfehler identifizieren kann, waere super, da wir sie weder in Word noch in HTML entdecken koennen...

**Comment by stefaniasalvadori** [comment]
Die QV sind einfach zu ignorieren in der schnellen PDF, oder?

**Comment by stefaniasalvadori** [comment]
Diese textkrit. Anm. (una alle dieser Art!) ist richtig in HTML angezeigt
![image](https://user-images.githubusercontent.com/28624747/77048352-93109500-69c6-11ea-8e16-580a913e6c2d.png)

Nicht aber in der PDF
![image](https://user-images.githubusercontent.com/28624747/77048390-a1f74780-69c6-11ea-97ef-79173be01585.png)

So sieht sie in XML aus
![image](https://user-images.githubusercontent.com/28624747/77048470-c3583380-69c6-11ea-9c25-1f9409cf2d65.png)

Was soll ich tun? Gedankenstrich streichen oder nicht?

**Comment by stefaniasalvadori** [comment]
Textstellen vor textkrit. Anm. verschwunden - passiert mehrmals...
Ich habe nun nachkodiert, sollte es aber nicht passieren und ich kann nun nicht alles nochmals kollationieren.

So in der PDF
![image](https://user-images.githubusercontent.com/28624747/77117895-3bf4d980-6a33-11ea-825a-be6d1cfa68e9.png)

So in der XML - vor Nachkodierung
![image](https://user-images.githubusercontent.com/28624747/77118033-9130eb00-6a33-11ea-876f-a5f1232d16d0.png)

So in der XML - nach der Nachkodierung
![image](https://user-images.githubusercontent.com/28624747/77118094-b6255e00-6a33-11ea-9866-16f35cf8b8ce.png)

**Comment by dariok** [comment]
- Die Seiten- und Zeilenangaben der QV sind in der schnellen PDF nicht richtig, da der Seitenumbruch noch nicht stabil ist – das also bitte erst in der Druckfahne prüfen.
- Diese Anmerkungen lassen sich am Stück automatisch bearbeiten.
- Zum letzten Fall: Diese Stelle fehlt ja schon im XML (und also war sie auch im HTML nicht da). Ich muß mir diese Stelle anschauen, um zu sehen, woran das liegt.

**Comment by stefaniasalvadori** [comment]
- In Ordnung - das merken wir in der schnellen PDF also nicht
- Ich habe sie in meinen EE nachkodiert - kann sein dass bei den Anderen aehlich ist (falls ich ein Beispiel finde, signalisiere ich Dir hier)
 - Idem, die Fehler in meinen EE habe ich gleich in XML korrigiert. Falls ich ein Beispiel in anderen EE finden, signalisiere ich Dir hier, damit Du es pruefen kannst
