### ISSUE TITLE
KGK III - Titelblatt

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#372]
Bitte, auch "Niklas Henning" auf Titelblatt einfuegen

<img width="359" alt="Titelblatt" src="https://user-images.githubusercontent.com/28624747/76941827-fd5d0300-68fc-11ea-962e-d2fdf0a53bb2.png">

**Comment by timojanssentj** [comment]
Und da ich dieses Mal keine eigene EE bearbeitet habe, müsste ich von "bearbeitet von" zu "unter Mitarbeit von" verschoben werde.
