### ISSUE TITLE
EE118 und EE119 text

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#375]
EE118_text fehlt in der PDF  - nicht aber in der HTML!

Text fehlt vermutlich weil als closer kodiert ist
![image](https://user-images.githubusercontent.com/28624747/77166924-61c2c280-6ab5-11ea-9312-095b8b903f4c.png)

Hier die Word-Fassung
[EE118_text_2020-03-11.docx](https://github.com/dariok/karlstadt-issues/files/4359703/EE118_text_2020-03-11.docx)

**Comment by stefaniasalvadori** [comment]
Lass mich wissen, ob ich einfach die "closer" Kodierung loeschen soll (am Anfang und Ende)

**Comment by stefaniasalvadori** [comment]
Das gilt auch fuer EE119_text

![image](https://user-images.githubusercontent.com/28624747/77175618-321ab700-6ac3-11ea-90af-634b9c58506e.png)

**Comment by dariok** [comment]
Bei 117 – 119 steht hier fälschlicherweise ein closer. Ich stelle korrigerte Dateien auf dev2.

**Comment by dariok** [comment]
Auch 121
