### ISSUE TITLE
Dringend - Biblische Stellen in den Einleitungen werden in HTML nicht richtig kodiert

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#377]
@dariok 

In den Einleitungen - sehe ich erst nun in Haralds EE112! - sind die Bibelstellen nicht richtig verlinkt
Was sollen wir machen? 
Ich wollte nachkodieren, mache aber jetzt nicht weiter, damit wir evtl. diese EE nochmals hochladen koennen
Kannst Du es justieren?

So in der Einleitung
![image](https://user-images.githubusercontent.com/28624747/77232353-d0c91580-6ba0-11ea-99a2-387a4296de86.png)

In transcript dagegen sind die Stellen richtig verlinkt
![image](https://user-images.githubusercontent.com/28624747/77232381-01a94a80-6ba1-11ea-8b91-55dad2130594.png)

**Comment by dariok** [comment]
Das sollte bei neuen Uploads jetzt funktionieren.

**Comment by stefaniasalvadori** [comment]
die stellen habe ich nun nachkodiert - die waren nicht viele und ich woltte mit der Nachkodierung fertig sein. Danke trotzdem
