### ISSUE TITLE
[...] durch gap ersetzen

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#378]
Sehr oft wurde [...] nicht richtig transformiert 
Ist es moeglich, n XML automatisch [...] mit gap zu ersetzen?
Haendisch die Stellen zu finden und nachzukodieren ist mir zu zeitaufwendig....

**Comment by JBunselmeier** [comment]
Die Ursache hierfür ist wohl, dass das Auslassungszeichen als typographisch hübscheres Sonderzeichen aus Word importiert wurde, nicht als Klammern mit drei Punkten. 

Ich kann die alle global suchen und durch <gap/> ersetzen, muss dazu aber erst sicherstellen, dass die XML-Dokumente nicht in Bearbeitung sind. Passt dir das?

**Comment by dariok** [comment]
Das sollte über Suchen/Ersetzen recht schnell gehen. Das Schematron sollte auch alle Stellen finden.

Ich passe die Upload-Skripte an für zukünftige Uploads.
