### ISSUE TITLE
EE124_text Folio-Umbruch nicht richtig transformiert

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#379]
Ich kann das leider nicht in XML justieren 

![image](https://user-images.githubusercontent.com/28624747/77427632-02c3bd00-6dd7-11ea-9832-81ba601c38b9.png)

oder

![image](https://user-images.githubusercontent.com/28624747/77427593-f3dd0a80-6dd6-11ea-9f8b-eb0513919a00.png)

Bitte bei PDF erstellung beachten und korrigieren

**Comment by dariok** [comment]
Wir hatten gesagt, daß recto und verso in den eckigen Klammern für den Seitenumbruch nicht hochgestellt sein dürfen. Mit Hochstellung kann der Umbruch nicht erkannt werden!

**Comment by stefaniasalvadori** [comment]
eh.... diese ist nicht meine EE und habe erst jetzt gesehen...
wie soll ich sie nachkodieren?

**Comment by dariok** [comment]
Die Kodierung wäre (statt `[A3<hi rend="super">r</hi>]`): `<pb n="A3r" />`

**Comment by stefaniasalvadori** [comment]
Ok...ich probiere diese Stellen in XML zu justieren

Heute Abend gebe ich Dir @dariok Signal - ich brauche eine neue gesamte schnelle PDF, um in den Register zu pruefen, ob noch etwas zu korrigieren ist

**Comment by stefaniasalvadori** [comment]
@dariok 
Ich habe in EE124 einheitlich - wie in allen anderen EE - so reinkodiert
`pb xml:id="pag23" n="[C4r]"/`

Jetzt mache ich mit EE123 das gleiche....

**Comment by stefaniasalvadori** [comment]
Erledigt - melde mich spaeter fuer die schnelle PDF von KGK III
