### ISSUE TITLE
Ausgabe der Sigle bei Handschriften

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#38]
Seltsamerweise wird das Sigle bei Handschriften nicht mehr ausgegeben, vgl. Nr. 105. Ich hänge die Worddatei an.
[EE-83-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1147789/EE-83-Uberlieferung.docx)

**Comment by stefaniasalvadori** [comment]
Dasselbe Problem mit der Sigel in EE88A = KGK nr.111
Datei in Issue #51

**Comment by dariok** [comment]
Sigle wird jetzt ausgegeben. Weitere Probleme bei Handschriften beobachten (ggf. eigene Issues)
