### ISSUE TITLE
sic/corr - mit mehreren witnesses

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#380]
Ist diese Kodierung richtig
![image](https://user-images.githubusercontent.com/28624747/77429977-be3a2080-6dda-11ea-9983-e22ed5658e30.png)

In HTML wird ohne Spatien zwischen Witnesses angezeigt 
![image](https://user-images.githubusercontent.com/28624747/77430093-ede92880-6dda-11ea-8e00-9ce893e8fcbc.png)

So sollte es angezeigt werden:
![image](https://user-images.githubusercontent.com/28624747/77430380-6223cc00-6ddb-11ea-8d19-ba2d61a456ac.png)

@dariok  soll ich Spatien und Semikolon reinkodieren?

**Comment by dariok** [comment]
Die Kodierung ist richtig.

@JBunselmeier bitte in den XSLT für HTML prüfen.

**Comment by stefaniasalvadori** [comment]
@dariok 
ok - dann passe ich enstprechend alle aehnliche Faelle, die ich finden kann

**Comment by JBunselmeier** [comment]
@stefaniasalvadori  um welche EE/KGK geht es? In EE123 finde ich die Stelle nicht.

**Comment by stefaniasalvadori** [comment]
Die hier angezeigte Stelle ist in EE124_text

@JBunselmeier  darf ich inszwischen EE123_text vereinheitlichen?

Hier:
http://dev2.hab.de/edoc/view.html?id=edoc_ed000240_124_transcript

**Comment by JBunselmeier** [comment]
XSL ist geändert, stimmt es jetzt so? Bitte auch 123 prüfen, wenn das derselbe Fall gewesen ist.

**Comment by stefaniasalvadori** [comment]
Yessa - ich pruefe noch alle aehnliche Faelle in alle EE, ok?
