### ISSUE TITLE
note in app/lem

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#381]
@dariok  kannst Du auch mir sagen, ob diese Kodierung richtig ist oder ob ich das Spatium am Anfang der note type comment loeschen soll?
Dann wuerde ich auch diese Stellen pruefen und korrigieren

![image](https://user-images.githubusercontent.com/28624747/77450538-ae7b0600-6df3-11ea-83eb-7626ab47e56b.png)

Auch hier soll man die HTML verbessern - witnes und comment sollten mit Spatium/Gedankenstrich/Spatium getrennt werden - @JBunselmeier  kannst Du villeicht das verbessern - z.B. hier in EE125_text

![image](https://user-images.githubusercontent.com/28624747/77450686-eda95700-6df3-11ea-9f05-11a8032ed2f3.png)

**Comment by dariok** [comment]
Am Anfang und Ende einer note (comment oder auch footnote) sollte kein Spatium stehen.
In diesem Fall hier sollte es aber keine Probleme bereiten.

**Comment by stefaniasalvadori** [comment]
Ok, das Spatium hatte ich in meine EE125 eingefuegt - das nehme ich raus, damit alles sauber ist. 
Danke Dir!
