### ISSUE TITLE
Korrekturen der Editoren zu den EE KGK III und Registern

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#382]
HARALD

**Comment by stefaniasalvadori** [comment]
ALEX
**Korrekturen sowohl in extra Kommentar als auch in den farbigen Markierungen - also mit der Liste der Kommenatren im Dokument arbeiten oder immer auch auf die farbige Markierungen clicken**

- [ ] Briefe
[KGK III_BriefeKorr_27-3-2020_AZ.pdf](https://github.com/dariok/karlstadt-issues/files/4413423/KGK.III_BriefeKorr_27-3-2020_AZ.pdf)

- [ ] EE123 und EE124
[KGK III_Korr_EE123 und EE124_TJ_StS_AZ.pdf](https://github.com/dariok/karlstadt-issues/files/4413471/KGK.III_Korr_EE123.und.EE124_TJ_StS_AZ.pdf)

- [ ] EE132A
[KGK III_AZ_StS_EE132A.pdf](https://github.com/dariok/karlstadt-issues/files/4413873/KGK.III_AZ_StS_EE132A.pdf)

**Comment by stefaniasalvadori** [comment]
STEFANIA
**Korrekturen sowohl in extra Kommentar als auch in den farbigen Markierungen - also mit der Liste der Kommenatren im Dokument arbeiten oder immer auch auf die farbige Markierungen clicken**

In dieser PDF:

- [ ] EE125 = KGK 163

- [ ] EE131 = KGK 171 (nicht KGK 172! Da KGK 170 Probationes zu den 33 Conclusiones nicht zu KGK III gehoert!)

- [ ] Register der Personen / Orte /Bibelstellen

[KGK III_EE125_EE131_Register_StS.pdf](https://github.com/dariok/karlstadt-issues/files/4413617/KGK.III_EE125_EE131_Register_StS.pdf)

**Comment by Wallsporn** [comment]
HARALD
KORREKTUR-PDF

[KGK-III-HB-2020-03-29.pdf](https://github.com/dariok/karlstadt-issues/files/4414120/KGK-III-HB-2020-03-29.pdf)

**Comment by Wallsporn** [comment]
HARALD
Korrekturhinweise, 31.3.2020, für EE112, 113, 126, 127, 128, 129, 132, 133, 139

Grundsätzlich:
Fehler in EE-Titeln bitte korrigieren
Buchtitel wurden nicht ausgegeben
Textfluss bei <pb> unterbrochen
manche <p> erzeugen Leerzeile, andere nur Absatz, vgl. EE113text S. 120f., 125, 127, 130, 131, 134, 144, 152, 155, 156, 164, 165, 166, 168, 169, 170, 179
ergänzte Punkte/Satzzeichen sind nicht kodiert, nur mit Klammer versehen
teils fehlende Spatien innerhalb von EE-Verweisen

Überarbeitung des Inhaltsverzeichnis s. PDF S. v-vi

EE112text
<p xml:id=“29“> hinter „disdiapason“ bitte entfernen - markiert
[habe ich wegen der Zählung nicht gemacht]
PDF S. 63-65 Die Tabelle funktioniert in HTML, in PDF gar nicht markiert markiert
Zeilen 1465 u. 2378 gelöscht, da generiert aufgrund <pb>-Fehler

EE113
Anm. 10 Verlinkungen nachtaggen

EE113text
div 2 und div 9 sind Dedikationen (inkl. div 1 u. div, die Salute der Dedikation) <- markiert
Anm. 100 Verweis auf Anm. 42 ist gelöscht! muss wieder rein <- markiert mit ##
Anm. 407 u. 414 Griechisch <- markiert
Anm. 437 Hebräisch <- markiert
Marginalien S. 178 <- markiert
S. 179 „Ad Othonem“ muss in neuen Absatz <- markiert
S. 120f., 125, 127, 130, 131, 134, 144, 152, 155, 156, 164, 165, 166, 168, 169, 170, 179 Absatz mit Leerzeile
Anm. 65 Stat. Theb. mit seltsam zerstückelten Reg.eintrag: <ref type="classical" cRef="Statius!">Statius</ref>, <choice><sic>tumor</sic><corr>timor</corr></choice> pessimus augur<note type="footnote" xml:id="n65"><ref type="classical" cRef="Stat. !">Stat. </ref><ref type="classical" cRef="Theb. 3!3,6">Theb. 3,6</ref>

EE126intro
Anm. 19 2 Verlinkungen

EE126text
S. 454: hinter „auffbringen“ fehlt Anm. h: auff bringen B
Kodierung falsch, in Word richtig!
auffbringenn<anchor xml:id="q007e"><app><lem/><rdg wit="#B">auff bringen</rdg></app></anchor>
richtige Kodierung:
<anchor xml:id="q007e"><app><lem>auffbringenn</lem><rdg wit="#B">auff bringen</rdg></app></anchor>
wozu anchor??
Anm. 45 zwei Verlinkungen, Anm. 52 eine
Anm. 42 Griechisch

EE127intro
Anm. 10 Geviertstrich zwischen die erwähnten Verwandten/Personen jeweils vor der Zahl

EE127text
Teil aus Textapp. f in Text gerutscht, Anm. f mit Strichen und falschen Kursivierungen
Anm. 1 Verlinkung bitte nachtaggen
Buchtitel neu getaggt, Einfügen eines <lb> in En-dres <- Zählung der lb muss justiert werden
Anm. dr wird Teil nicht ausgegeben: fehlt B, C, D
Anm. dv hinter „erwegen“ (S. 476) fehlte ganz: verwegen B, C, D, E [weil mit <anchor> umgeben! s. u.]
<app><lem>erwegen</lem><rdg wit="#B #C #D #E">verwegen</rdg></app><anchor xml:id="q007e"></anchor>
Anm. dy in XML korrigiert  
Anm. hi war nicht ausgegeben, weil von anchor umgeben:
<note type="crit_app"> <orig>zumachem</orig> A; hsl. korrigiert A<hi rend="sub">Dr</hi></note>.<anchor xml:id="q010e"></anchor>

Schluss der EE muss nachgetaggt werden (in Word Formatierung nicht möglich, in XML bin ich gescheitert):
<app><lem>Datum .... 1520</lem><rdg wit=“#B #C #D #E“></rdg></app>
<app><lem>dornstag ... 1520</lem><rdg wit=“#G“> ec. Gedruckt Anno. M.D. xxi. Mense Augusto.</rdg></app>
<app><lem>nach Christi ... 1520</lem><rdg wit=“#F“>durch Johannem Grunenbergk/ 1521.</rdg></app>
Anm. f Kursivierung nicht in Ordnung
Bo-denstein in Salute <lb> eingefügt, nun ohne Trennstrich
Anm. di (PDF: dv) mit Fehlern
Anm. dr: vom Editor verbessert für 20.8; fehlt B, C, D <- fehlt nicht ausgegeben
<choice><sic wit="#A">20.8</sic><sic wit="#B #C #D"/><corr>8</corr></choice>
Anm. 64 2 Verlinkungen

EE128text
Textanm. df, di, dy: „korrigiert aus ... a“ nicht: „korrigiert in ... a“
[die Hs. hatte einen eigenen Fehler korrigiert!]
S. 380 Anm. 19 fehlt Verlinkung: EE128intro_Voraussetzung seien also...besteht.#
S. 385 Anm. 41 fehlt Verlinkung auf Anm. 388
S. 432 Anm. 370 fehlt Verlinkung auf Anm. 275
S. 436 graphische Kreuze
S. 436 Anm. 393 Verlinkung fehlt

EE132intro
Anm. 25 fehlende Verlinkungen

EE132text
Nachdenken über Darstellung des originalen Verweissystems
Anm. 16, 23 fehlende Verlinkungen

EE139intro
Kreuz in Überlieferung A:
Verlinkungen am Textanfang u. Anm. 9, 21

EE139text
pb C2r ans Ende von These XIII]
Anm. 10 eine Verlinkung
