### ISSUE TITLE
Fehler Upload EE168, KGK 204

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#388]
Leider kam diese Meldung beim Upload von EE168. 
![Bildschirmfoto 2020-06-23 um 12 33 18](https://user-images.githubusercontent.com/38648721/85393781-d6424d00-b54d-11ea-84fc-7baaa82d861d.png)
[EE 168_intro_2020-06-23.docx](https://github.com/dariok/karlstadt-issues/files/4818793/EE.168_intro_2020-06-23.docx)

**Comment by timojanssentj** [comment]
Der Fehler scheint sich bei EE199 zu duplizieren.
[EE 199_intro_2020-06-24.docx](https://github.com/dariok/karlstadt-issues/files/4825650/EE.199_intro_2020-06-24.docx)

**Comment by dariok** [comment]
Beide EE sind korrekt transformiert.

Bitte beachten, daß die Einträge für neue Texte von @JBunselmeier erstellt werden müssen.

**Comment by JBunselmeier** [comment]
Die beiden Einleitungen sind eingetragen und sollten jetzt korrekt angezeigt werden.

**Comment by timojanssentj** [comment]
Upload funktioniert
