### ISSUE TITLE
Fehler im Upload EE180, KGK 209

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#389]
Sigle D wird nicht korrekt ausgegeben.
![Bildschirmfoto 2020-06-24 um 15 06 30](https://user-images.githubusercontent.com/38648721/85562064-6e166880-b62c-11ea-96a3-47d091e061ed.png)
[EE_180_intro_2020-06-24.docx](https://github.com/dariok/karlstadt-issues/files/4825531/EE_180_intro_2020-06-24.docx)

**Comment by dariok** [comment]
Da fehlt eine Leerzeile vor Sigle D

**Comment by timojanssentj** [comment]
Trotz Leerzeile besteht das Problem weiterhin

**Comment by dariok** [comment]
Vielleicht noch alte Seite im Cache?

**Comment by timojanssentj** [comment]
Wird korrekt ausgegeben! Danke!
