### ISSUE TITLE
Fehler im Upload EE207A

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#390]
Beim Upload erschien ein mir noch völlig unbekannter Fehler.

![Bildschirmfoto 2020-06-30 um 12 37 01](https://user-images.githubusercontent.com/38648721/86116956-87a52d80-bace-11ea-8a55-c7fb998d0ac9.png)
[EE-207A_intro_2020-06-30.docx](https://github.com/dariok/karlstadt-issues/files/4851188/EE-207A_intro_2020-06-30.docx)

**Comment by dariok** [comment]
Diese EE ist korrekt transformiert. 
Neue EE müssen von @JBunselmeier eingetragen werden.

**Comment by timojanssentj** [comment]
Es hat sich nun einer neuer Fehler ergeben. An der Formatierung kann es nicht liegen.
![EE207A-Neuer Fehler](https://user-images.githubusercontent.com/38648721/86922789-6cb96580-c12d-11ea-8b56-74c97edfed88.PNG)

**Comment by dariok** [comment]
Das kann ich nicht bestätigen, die Datei ist eingetragen und wird korrekt angezeigt – vielleicht noch eine alte Seite im Browser-Cache?

**Comment by timojanssentj** [comment]
Wird korrekt ausgegeben. Danke! Warum es vorher nicht so war, kann ich leider nicht sagen.
