### ISSUE TITLE
"Weitere Exemplare" in EE227A tauchen nicht auf

### ISSUE THREAD

**Issue by timojanssentj** [dariok/karlstadt-issues#395]
Wie im Bild zu sehen transformiert er "Weitere Exemplare" nicht mit.
![EE227A-Weitere Exemplare](https://user-images.githubusercontent.com/38648721/86917886-28769700-c126-11ea-8b5d-d09394af77ea.PNG)
[EE_227A-intro_2020-07-08.docx](https://github.com/dariok/karlstadt-issues/files/4890577/EE_227A-intro_2020-07-08.docx)

**Comment by dariok** [comment]
Word hat hier den Text „Weitere Exemplare“ zerteilt. Ich habe dafür jetzt die Erkennung der weiteren Exemplare angepaßt.

**Comment by timojanssentj** [comment]
Funktioniert nun! Danke!
