### ISSUE TITLE
KGK I, Nr. 28

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#40]
Ist so nicht ganz korrekt, oder?
![grafik](https://user-images.githubusercontent.com/23031457/28210643-b38b3fce-6898-11e7-8ac5-ad5cc6df25cd.png)
2.1 und 2.2 sollten vielleicht gelöscht werden?

**Comment by Wallsporn** [comment]
Ja, das hatte ich auch schon gesehen. Ist in 1. und 2. umzuwandeln

**Comment by Marxistin** [comment]
... und der Text muss noch angepasst werden. Zweimal "Inhalt und Entstehung" geht auch nicht.
