### ISSUE TITLE
Einrückungen in KGK 1

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#43]
Bitte Gedicht vor Questio anders einrücken: 3. Vers linksbündig, 4. Vers ans Ende
In Questio principalis: "Opinio" und "est" möglichst zwischen zwischen "secunda" und "tercia"
![grafik](https://user-images.githubusercontent.com/28565515/28470531-43493566-6e3a-11e7-810b-56f35a848025.png)
Ebenso Questio septima bearbeiten
![grafik](https://user-images.githubusercontent.com/28565515/28470574-649b8872-6e3a-11e7-8210-e63f1d787e30.png)

**Comment by dariok** [comment]
dariok@1835568a0f8dd968d5845a22bd5e9ba9d53eb583 ordnet die Tabellen besser an
