### ISSUE TITLE
Kommentare in Überlieferung

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#44]
Kommentare zur Überlieferung bitte in Transformation berücksichtigen
Höher- und Tiefergestellte Zeichen

[EE-110-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1165999/EE-110-Uberlieferung.docx)

**Comment by Wallsporn** [comment]
IN EE 128 = KGK 160 scheint die Höherstellung von Zeichen zu funktionieren?!

**Comment by dariok** [comment]
https://github.com/dariok/w2tei/commit/0d95d654a941036942d6f7a25276862a4dfe5b75
