### ISSUE TITLE
Transformationsfehler EE 128

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#47]
[EE-128-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1196764/EE-128-Uberlieferung.docx)

**Comment by Marxistin** [comment]
Handschriftensigle ist hier fälschlicherweise eingerückt

**Comment by dariok** [comment]
Gerade neu hochgeladen, sieht gut aus.

**Comment by dariok** [comment]
Anmerkungen zur Hand etc. bitte in Klammern setzen.
[EE-128-Uberlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1385581/EE-128-Uberlieferung.docx)
