### ISSUE TITLE
EE 88B (=Nr.112) / Probleme mit der Transformation + Verdoppelung

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#49]
Ich habe EE 88B (Nr.112) neu hochgelagen - neue Version Alexs mit "inhaltliche Hinweise" (siehe EE116 = Nr. 144)
Die Transformation hat nicht 100% geklappt
Die Einheit ist nun im Inhaltverzeichnis verdoppelt  (sorry!!!)
Hier die docx:
[EE088B_Intro2017_8_8.docx](https://github.com/dariok/karlstadt-issues/files/1212648/EE088B_Intro2017_8_8.docx)

**Comment by dariok** [comment]
Ich habe die Doppelung entfernt.

Vor dem 2. Teil fehlte vmtl. die Überschrift? 
[EE088B_Intro2017_8_8.docx](https://github.com/dariok/karlstadt-issues/files/1215422/EE088B_Intro2017_8_8.docx)

**Comment by stefaniasalvadori** [comment]
Ich habe "inhaltliche Hinweise" als Überschrift formatiert.
[EE088B_Intro2017_8_8.docx](https://github.com/dariok/karlstadt-issues/files/1217117/EE088B_Intro2017_8_8.docx)

Nun aber musste ich **[]** als Sigel vor "Referenz" formatieren, sonst klappt die Transformation des 1. Teils nicht. Kann man es weg lassen?

Darüber hinaus fehlt "inhaltliche Hinweise" in anderen verschollen EE - der Abschnitt folgt "literatur", wie z.B. Nr. 146.
![nr 146](https://user-images.githubusercontent.com/28624747/29203743-443a948a-7e73-11e7-8d12-472345c8183f.png)

Soll ich die verschollenen EE vereinheitlichen oder lieber so stehen lassen?

**Comment by dariok** [comment]
Ich habe jetzt noch etwas korrigiert, sodaß die Ausgabe auch ohne Sigle stimmt.

[EE088B_Intro2017_8_8 (1).docx](https://github.com/dariok/karlstadt-issues/files/1217227/EE088B_Intro2017_8_8.1.docx)

**Comment by stefaniasalvadori** [comment]
Danke Dir!
