### ISSUE TITLE
KGK 64 - Überschriften 2 falsch angezeigt

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#50]
@dariok 
In der normalen WDB zu KGK 64 (Augustinkommentar), Einleitung
Verdoppelung der Überschrift »Überlieferung« 
auch wo unnötig ist (**1.1. Überlieferung** und **1.11. Überlieferung**) 
oder wo die einzelnen Exemplaren genannt sind 
( **1.2. Überlieferung** STATT _Su California State Library, San Francisco, O9⒊A92v.Sutro, Nr.9_ ) 
--> **_bis 1.10. Überlieferung_**

PS **I. Projektphase (Entwicklungsumgebung) zur Zeit nicht erreichbar** --> vmtl. die Verdoppelung taucht auch dort auf

**Comment by dariok** [comment]
Wie im Druck: igle fett, tandort und ignatur - ggf. mit Fußnote

**Comment by dariok** [comment]
Korrigiert mit https://github.com/dariok/karlstadt/commit/ed0eecdc6015c6ff196b01612a31dcd648c6ef0b
