### ISSUE TITLE
EE88A (Nr 111) - Probleme bei der Transformation und Doppelung in Navigationliste

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#51]
Ich habe gerade eine korrigierte Fassung von EE88A (Nr.111) von Bubenheimer bekommen und sie hochgeladen.
- Die EE wird nich vollständigt hochgeladen - es fehlt nicht nur ein Kommentar/Beschreibung zu der Handschrift, sondern auch die letzte Absätzte
- Die Nr. 111 ist nun in der Navigationliste verdoppelt - sorry (kannst Du mir erklären, was ich falsch mache, damit ich nicht immer wieder solche Probleme verursache? Der Titel der Datei soll immer unverändert bleiben?)

**Comment by stefaniasalvadori** [comment]
Hier die Datei
[EE88A_Intro_2017_8_21.docx](https://github.com/dariok/karlstadt-issues/files/1238190/EE88A_Intro_2017_8_21.docx)

**Comment by Marxistin** [comment]
Sigle ist noch nicht gelöst.

**Comment by dariok** [comment]
Prüfen: Generierung ID

**Comment by dariok** [comment]
Die Literaturangaben unter "Edition" und der Zitatblock waren nicht markiert, was auch Probleme machte. Bitte ggf. mit der angehängten Datei weiterarbeiten.
[EE88A_Intro_2017_8_30.docx](https://github.com/dariok/karlstadt-issues/files/1385389/EE88A_Intro_2017_8_30.docx)

**Comment by stefaniasalvadori** [comment]
Ich habe die von Dir bearbeiten Dateien nochmals bearbeitet - bzw. "Entstehung und Inhalt" formatiert.
Es klappt. Die 1. Anm nach der Signatur wird aber verdoppelt. Habe ich irgendetwas falsch formatiert?

Word:
![unbenannt2](https://user-images.githubusercontent.com/28624747/33273631-319e46c6-d38e-11e7-8451-d47f6c30645c.JPG)


DigiEdition:
![unbenannt](https://user-images.githubusercontent.com/28624747/33273639-35b728b8-d38e-11e7-9216-5161a116bcb1.JPG)

Hier die Word-Vorlage:
[EE88Aintro2017-11-27.docx](https://github.com/dariok/karlstadt-issues/files/1506361/EE88Aintro2017-11-27.docx)

**Comment by stefaniasalvadori** [comment]
Hier die neue Fassung der EE88A_Intro.
Die 1. Anm nach der Signatur wird aber verdoppelt. Falsche Formatierung?

[EE88Aintro2017-12-12.docx](https://github.com/dariok/karlstadt-issues/files/1550870/EE88Aintro2017-12-12.docx)
