### ISSUE TITLE
Einrückung von längeren Zitaten

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#54]
KGK 58 längeres Zitat in Überlieferung der Handschrift nicht komplett eingerückt

![grafik](https://user-images.githubusercontent.com/28565515/30804786-f6f84b5a-a1ee-11e7-8166-a3d38d097761.png)

**Comment by dariok** [comment]
Ggf. it auch die erte Zeile dahinter (ggf. jede weitere erte Zeile eine Abatze) falch eingerückt...
Die Einrückung der igle muß ggf. ganz ander gelöt werden...

**Comment by dariok** [comment]
`span.blockquote` braucht `text-indent:0`

**Comment by dariok** [comment]
Weiter offen die zu große Länge der erten Zeile de Abatze danach; hier verchwindet dann ein Teil von "römichen"

**Comment by dariok** [comment]
Erledigt zusammen mit der Lösung für #57
