### ISSUE TITLE
Sammelbände

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#6]
Wir haben bei den Formatvorlagen für Überlieferungen nicht über Sammelbände gesprochen, was bei Briefen und Thesen oft vorkommt, also:
Karlstadt, Andreas Bodenstein von
Conclusiones decem
in:
Insignium theologorum etc.

Hattest Du das schon in Deine Scriptanpassungen einbezogen?
Geht die Konversion ebenso ohne Verwendung einer Formatvorlage?

**Comment by Marxistin** [comment]
Wir wollen ja nicht verzichten, wir haben nur noch keine Vorlage. Oder steht sie irgendwo und ich hab sie noch nicht gesehen?

**Comment by Wallsporn** [comment]
Der Verzicht auf Formatvorlagen bezog sich NUR auf die besprochenen Teile innerhalbd der Überlieferung, also Autor, Titel, "in", Sammelband etc. Alles andere wie abgesprochen.

**Comment by dariok** [comment]
Ah, sorry, das hatte ich falsch verstanden.
Die Sammelbände sind kein Problem, da hier der Aufbau in der Regel gleich ist.
