### ISSUE TITLE
Wiedergabe der Titelseiten

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#60]
Die Wiedergabe der Titelseiten in den Texten von KGK 1,2,64,85,88 und 90 entspricht nicht der Wiedergabe nach Originalzeilenfall im Druck.

Bsp. KGK 64
![grafik](https://user-images.githubusercontent.com/28565515/31300094-15bea9f6-aaf2-11e7-8e4d-b2709e21550f.png)

Vergleich mit unserem Druck:
![grafik](https://user-images.githubusercontent.com/28565515/31300147-6d99c688-aaf2-11e7-8374-726221ff57ac.png)

KGK 1,2,85 müsste zentriert gesetzt werden.

**Comment by dariok** [comment]
Bitte prüfen

**Comment by Wallsporn** [comment]
Sehr gut, bis auf 2 Monita:
KGK 2: Motto ist mit Leerzeile, diese bitte herausnehmen
KGK 64: doppelte Lehrzeile zwischen Textteilen - eine Zeile herausnehmen

**Comment by dariok** [comment]
Sollte jetzt auch behoben sein.
