### ISSUE TITLE
Sigle weiter mit Problemen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#66]
KGK 105 Sigle erscheint, aber mit leerer eckiger Klammer

![grafik](https://user-images.githubusercontent.com/28565515/31441406-62f51972-ae93-11e7-8500-900ff2ee251d.png)

KGK 111 und 128 keine Sigle

![grafik](https://user-images.githubusercontent.com/28565515/31441390-5913bc1a-ae93-11e7-9968-d9cdb511f51c.png)

**Comment by dariok** [comment]
[EE-83-Uberlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1413992/EE-83-Uberlieferung.docx)

111 bereits korrekt
128 bitte neu hochladen
