### ISSUE TITLE
KGK 168 (=EE 132A) - Angaben nicht angezeigt

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#67]
Auch in dieser EE werden die Angabe zu "Edition" nicht angezeigt.
Darüber hinaus werden die erste 3 Anmerkungen in "Ueberlieferung" nicht angezeigt. (Die Anm in "Enstehung und Inhalt" sind dagegen korrekt angezeigt)

[EE 132A_Intro_2017_10_13_StS.docx](https://github.com/dariok/karlstadt-issues/files/1383487/EE.132A_Intro_2017_10_13_StS.docx)

**Comment by stefaniasalvadori** [comment]
Soll dies auch in #64 eingeordnet werden?

**Comment by dariok** [comment]
- [ ] Fußnote zu Exemplare Torre Pellice
- [ ] FN in Anmerkung

**Comment by dariok** [comment]
[EE.132A_Intro_2017_10_13_StS.docx](https://github.com/dariok/karlstadt-issues/files/1430023/EE.132A_Intro_2017_10_13_StS.docx)

Die Editionsangabe ist jetzt als bibliographische Angabe markiert
