### ISSUE TITLE
Probleme bei Hochladung von EE82 [=Nr.104]

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#68]
Probleme mit den Signaturen? Datei angehängt

![unbenannt](https://user-images.githubusercontent.com/28624747/32045861-a5f588a6-ba41-11e7-98d2-94028eeda488.JPG)
[EE82_Intro_2017_10_26.docx](https://github.com/dariok/karlstadt-issues/files/1417737/EE82_Intro_2017_10_26.docx)

**Comment by dariok** [comment]
[EE82_Intro_2017_10_26.docx](https://github.com/dariok/karlstadt-issues/files/1418206/EE82_Intro_2017_10_26.docx)
