### ISSUE TITLE
Transkript zum Testen der Transformation

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#69]
Hier 3 Word-Datei mit Transkriptionen.
Damit kannst Du das Transformationsszenarium

[EE 132A_Text_2017_10_26_StS.docx](https://github.com/dariok/karlstadt-issues/files/1418667/EE.132A_Text_2017_10_26_StS.docx)
[EE88A_Text_2017_10_26_StS.docx](https://github.com/dariok/karlstadt-issues/files/1418668/EE88A_Text_2017_10_26_StS.docx)
[EE-128-Text+Kommentar.docx](https://github.com/dariok/karlstadt-issues/files/1418669/EE-128-Text.Kommentar.docx)

 testen

**Comment by dariok** [comment]
Die aktuellen Probleme in #92 #93 und #94
