### ISSUE TITLE
Verlinkungen von Ortsnamen, Personennamen, bibl. Angaben 

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#7]
für Spielwiese und WDB

**Comment by dariok** [comment]
Sowohl auf dev2 als auch diglib umgesetzt.

**Comment by Marxistin** [comment]
Auf diglib funktionieren die bibliographischen Angaben nicht. Hier ein Ausschnitt aus Nr. 8:
![grafik](https://cloud.githubusercontent.com/assets/23031457/26346334/211080b6-3fa6-11e7-9f06-7af5265fc399.png)
VD16 funktioniert gut.

**Comment by dariok** [comment]
Was stimmt nicht?

**Comment by Marxistin** [comment]
Bei Proctor, German Prints / Grossmann, Wittenberg Drucke / Zorzin, Flugschriftenautor geht bei diglib kein Fenster auf, auf dev2 werden die bibliographischen Angaben angezeigt.

**Comment by dariok** [comment]
Das kann ich nicht bestätigen.
![image](https://cloud.githubusercontent.com/assets/1765292/26547010/2e40068c-446d-11e7-95a5-c9f1227a4995.png)

**Comment by Marxistin** [comment]
Jetzt funktioniert es bei mir auch. Dann schließe ich das hier mal.
