### ISSUE TITLE
KGK 104 und 136 Signaturen fehlen

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#73]
KGK 104 und KGK 136 (EE 81)
Standort und Signaturen der Exemplare in "Editionsvorlage" und "Weitere Exemplare" fehlen

**Comment by dariok** [comment]
Hier brauche ich die Vorlagen.

**Comment by stefaniasalvadori** [comment]
zu **KGK 104** - seltsam! die Einheit war richtig angezeigt...
Ich habe sie nochmals hochgeladen und in der Tat fehlen Signaturen und Standort.

Hier die WordDatei
[EE82_Intro_2017_11_3.docx](https://github.com/dariok/karlstadt-issues/files/1441730/EE82_Intro_2017_11_3.docx)

**Comment by stefaniasalvadori** [comment]
Hier auch **KGK 136 (EE81)**
[EE-81-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1441734/EE-81-Uberlieferung.docx)

**Comment by dariok** [comment]
Danke!

**Comment by stefaniasalvadori** [comment]
Danke Dir!
Ich habe gerade mit @Wallsporn telefoniert - KGK 136 (EE81) funktioniert nun.

Für KGK 104 war vermütlich mein Fehler, ich hatte die Signaturen noch nicht angepasst. Das mache ich später und signalisiere es, falls die Transformation nicht funktionier

Danke Dir nochmals

**Comment by dariok** [comment]
Ja, es fehlt vermutlich das Leerzeichen vor dem Komma; dann müßte es funktionieren.

**Comment by stefaniasalvadori** [comment]
Richtig! Es funktioniert! 
auch in KGK 104 sind nun Signaturen und Standort richtig angezeigt
