### ISSUE TITLE
EE 107 (KGK 133) und EE 106 (KGK 132)  + EE81 (KGK 136) Höherstellung von Ziffern

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#74]
EE 106 = KGK 136
nur „Walch“ statt Walch mit hochgestellter 2
EE 107 = KGK 133
Unter Editionen: Walch2

**Comment by dariok** [comment]
Auch hier benötige ich die Vorlagen.

**Comment by stefaniasalvadori** [comment]
EE 107 = KGK 133
EE 106 = KGK 132
--> sind nun richtig angezeigt

![unbenannt](https://user-images.githubusercontent.com/28624747/32385190-9bf05598-c0bd-11e7-8a83-4ed9e416dfa5.JPG)

![unbenannt](https://user-images.githubusercontent.com/28624747/32385363-2bb2acb2-c0be-11e7-9d51-d343db67b5f1.JPG)

**Comment by stefaniasalvadori** [comment]
zu EE81 (KGK 136) wird @Wallsporn später evtl. die Word-Vorlage weiterleiten

**Comment by dariok** [comment]
Okay, dann schaue ich da nochmal rein.

**Comment by Wallsporn** [comment]
Sorry, habe gestern für Verwirrung gesorgt: eshandelt sich um EE 81 = KGK 136. Diese Worddatei habe ich heute mittag schon geschickt,aber kein Problem: hier ist sie noch einmal
[EE-81-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1442731/EE-81-Uberlieferung.docx)

**Comment by dariok** [comment]
Habe EE 081 gerade neu hochgeladen, auch hier ist es korrekt.
