### ISSUE TITLE
KGK 165 Datierung

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#76]
KGK 165
Datierung [1520, Herbst] fehlt bis auf Kommata in Titelei
in Navigation fälschlich: „nach 1520“
[EE-139-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1438627/EE-139-Uberlieferung.docx)

**Comment by dariok** [comment]
[EE-139-Uberlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1441775/EE-139-Uberlieferung.docx)
