### ISSUE TITLE
KGK 136 (EE 81) Anzeige keiner Editionsvorlage

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#77]
Für Druckvariante [F:] von KGK 136 liegt kein Exemplar vor, sondern nur eine alte Beschreibung. 
Ideale Ausgabe:
_Editionsvorlage_: Kein Exemplar überliefert, ehemals Sammlung Knaackes.
Diese Angabe wird nur angezeigt, indem sie als KS: Anmerkung in Überlieferung formatiert wird. Davor erscheint das hier störende Komma. Ich habe versucht, das Beste daraus zu machen, aber die Doppelung von "Keine/Kein" ist nicht wirklich schön.
![grafik](https://user-images.githubusercontent.com/28565515/32370570-e33157e8-c08d-11e7-9d7f-a4f5a53cbb56.png)
Angehängt ist die nun überarbeitete Word-
[EE-81-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1440793/EE-81-Uberlieferung.docx)
Datei.

**Comment by stefaniasalvadori** [comment]
@dariok - Harald wird evtl. später die neue bearbeitete Version der Word-Dataie Dir weiterleiten

@Wallsporn - Achtung: Walch (in Editionen) und Barge (in Literatur) sind momentan unvollständig angezeigt

**Comment by dariok** [comment]
Ich weiß noch nicht, wie ich das umsetzen soll. Es dürfte in jedem Fall ein größeres Unterfangen werden.

**Comment by Wallsporn** [comment]
Bravissimo! Am Donnerstag muss ich daran denken zu fragen, wie Du das gelöst hast
