### ISSUE TITLE
EE 101 [=KGK 127] u. EE 102 [=KGK 128] - Probleme bei der Transformation der Signatur

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#79]
Die Signatur wird nicht richtig angezeigt

**[a:]** Sächsisches Staatsarchiv Hauptstaatsarchiv Dresden , 10024 Geheimer Rat (Geheimes Archiv) Loc. 10300/02 fol. 48a/b , (Stempel, nach alter handschriftlicher Folierung fol. 33a/b).

![unbenannt](https://user-images.githubusercontent.com/28624747/32560657-81238d48-c4aa-11e7-8579-56f5af198c0f.JPG)

auch höhergestellte Zeichen sind nicht richtig angezeigt

[EE 101_Intro_2017_11_08.docx](https://github.com/dariok/karlstadt-issues/files/1454625/EE.101_Intro_2017_11_08.docx)

**Comment by stefaniasalvadori** [comment]
Das gilt auch für EE 102 [ KGK 128], die eine ähnliche Signatur hat.

(ich vermute, das Problem ligt an die runden Klammern nach _Geheimner Rat_ und for Signatur _Loc. 10300/02_)

**[a:]** Sächsisches Staatsarchiv Hauptstaatsarchiv Dresden , 10024 Geheimer Rat (Geheimes Archiv),  Loc. 10300/02, fol. 34a–35b , (Stempel, nach alter handschriftlicher Foliierung fol. 20a–21b).

![unbenannt](https://user-images.githubusercontent.com/28624747/32561214-042ae884-c4ac-11e7-8e68-36d1426b6411.JPG)

[EE 102_Intro_2017_11_08.docx](https://github.com/dariok/karlstadt-issues/files/1454652/EE.102_Intro_2017_11_08.docx)

**Comment by dariok** [comment]
In beiden Fällen: Komma vor "fol. 48a/b", kein Komma vor der Anmerkung.
[EE.101_Intro_2017_11_08.docx](https://github.com/dariok/karlstadt-issues/files/1468203/EE.101_Intro_2017_11_08.docx)
[EE.102_Intro_2017_11_08.docx](https://github.com/dariok/karlstadt-issues/files/1468204/EE.102_Intro_2017_11_08.docx)

Noch offen: Hochstellung.

**Comment by dariok** [comment]
Mit der korrigierten Kommasetzung (s.o.) korrekte Ausgabe.
