### ISSUE TITLE
Spaltenverbreiterung, Umbrüche in den Marginalien

### ISSUE THREAD

**Issue by Marxistin** [dariok/karlstadt-issues#8]
Die Spalte für die Transkriptionen wird verbreitert (auf 50%), in den Marginalien Umbrüche eingefügt, um die bisherigen Probleme einer Überlappung bzw. einer Verstümmelung des Transkriptionstextes am rechten Rand zu beenden.

**Comment by dariok** [comment]
Dabei auch berücksichtigen: Fußnoten nach der Positionierung der Marginalien

**Comment by dariok** [comment]
066-2 komisch; 001, 002, 046 (AK) gehen → Problem mit den Nummern (float) der Thesenreihe.
