### ISSUE TITLE
Darstellung von höhergestellten Zeichen in Handschriften

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#81]
Die Darstellung von höher- und tiefergestellten Zeichen scheint für Handschriften nicht zu funktionieren.
Formatiere ich falsch oder ist ein allgemein Problem? 

Siehe z. B. recto-verso Angabe hier EE 107 [=KGK 133]

![unbenannt](https://user-images.githubusercontent.com/28624747/32563731-49b4583a-c4b2-11e7-8e50-b52db7b9243f.JPG)

[EE 107_Intro_2017_11_8.docx](https://github.com/dariok/karlstadt-issues/files/1454809/EE.107_Intro_2017_11_8.docx)

Oder in EE 100 [KGK 126]
[EE 100_Intro_2017_11_8.docx](https://github.com/dariok/karlstadt-issues/files/1454811/EE.100_Intro_2017_11_8.docx)

Oder noch in
EE101 (KGK 127) und EE 102 (KGK 128) - WordDatei in #79 
EE103 (KGK 129) - WordDatei in #78

**Comment by dariok** [comment]
Mit korrigiertem Komma funktioniert es:
[EE.107_Intro_2017_11_8.docx](https://github.com/dariok/karlstadt-issues/files/1475987/EE.107_Intro_2017_11_8.docx)
[EE.100_Intro_2017_11_8.docx](https://github.com/dariok/karlstadt-issues/files/1475994/EE.100_Intro_2017_11_8.docx)
