### ISSUE TITLE
KGK 159 (= EE 127)

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#86]
Transformation läßt bei Chargen F und G Druckort/-jahr und Druckbeschreibung aus
![grafik](https://user-images.githubusercontent.com/28565515/32568613-1c79a840-c4bf-11e7-909e-73f648af5137.png)
[EE-127-Überlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1455044/EE-127-Uberlieferung.docx)

**Comment by dariok** [comment]
Bei F war das Komma innerhalb der eckigen Klammer.
Bei G war ein Monat angegeben, was bisher nie der Fall war → gesamtes Datum in Klammer oder Monat streichen.
[EE-127-Uberlieferung.docx](https://github.com/dariok/karlstadt-issues/files/1501313/EE-127-Uberlieferung.docx)

**Comment by Wallsporn** [comment]
Danke! Habe eine kleine Änderung vorgenommen und erneut hochgeladen - es klappt!
