### ISSUE TITLE
Sonderfall "Beilagen"

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#9]
Bei den Formatvorlagen haben wir für Überlieferungen nicht über Beilagen gesprochen (siehe z.B. in KGK I.1, Nr. 16).
Also, in KGK II, z.B. für EE 104 [=Nr. 128]:
 
## Überlieferung
Editionen: Wit deutsch 9, fol. 69v‒70 r  (VD 16 L 3333 ). ...

**Beilage 1: Eck an Kurfürst Friedrich III, Leipzig, 1519, 22. Juli.**
Edition: Luther...

**Beilage 2: Kurfürst Friedrich III an Eck, Altenburg, 1519, 24. Juli.**
Edition: Luther,....

Hattest Du das schon in Deine Scriptanpassungen einbezogen?
Brauchen wir eine Sonderkodierung/Sondervorlage? Oder geht die Konversion ebenso ohne Verwendung einer Formatvorlage?

**Comment by Marxistin** [comment]
siehe dazu auch #26
