### ISSUE TITLE
Transformation 128 Transcript

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#91]
Anmerkungen HB:

- [x] Allein wenn eine Zeilenumbruchstrennung mit einer Marginalie zusammenfällt, ist noch keine Lösung gefunden. Sollten wir über einen Umbruch im Worddokument nachdenken?
- [x] Wegfallen sollte der Doppelstrich bei Seitenumbruch. Der ist ja allein durch die Folioangabe in eckigen Klammern gekennzeichnet.
- [x] Textapparatanmerkung e zieht das "auch" aus der Handschrift fälschlich nach oben in den Text.
- [x] Zu den Anmerkungen: bei allen Textapparatanmerkungen und in einigen Fällen von Sachanmerkungen erscheint folgender Satz: The requested URL /start.htm was not found on this server. 
- [ ] Aber in der Bibliographie simulieren noch, oder? Da müssten ja irgendwann die id mit den Kurztiteln verbunden werden. Können wir vielleicht am Donnerstag besprechen.

**Comment by Wallsporn** [comment]
You are right, in this way we communicate.

Nachfrage - wirklich außerhalb gitHub: Weißt Du, mit welchem Font der Verlag arbeitet? Ist das auch Junicode? Es geht um unser künftiges Hebräisch. Hast Du dafür auch Junicode verwendet?

Grüße von
Harald

Dr. Harald Bollbuck
Akademie der Wissenschaften zu Göttingen
- Karlstadt-Edition -
Theaterstraße 7
37073 Göttingen

Tel.: +49-551-39-33640
Mail: harald.bollbuck@mail.uni-goettingen.de<mailto:harald.bollbuck@mail.uni-goettingen.de>
http://karlstadt-edition.org/edition/
https://adw-goe.de/forschung/weitere-forschungsprojekte/karlstadt-edition/
________________________________
Von: Dario Kampkaspar [notifications@github.com]
Gesendet: Freitag, 12. Januar 2018 13:18
An: dariok/karlstadt-issues
Cc: Subscribed
Betreff: [dariok/karlstadt-issues] Transformation 128 Transcript (#91)


Anmerkungen HB:

  *    Allein wenn eine Zeilenumbruchstrennung mit einer Marginalie zusammenfällt, ist noch keine Lösung gefunden. Sollten wir über einen Umbruch im Worddokument nachdenken?
  *    Wegfallen sollte der Doppelstrich bei Seitenumbruch. Der ist ja allein durch die Folioangabe in eckigen Klammern gekennzeichnet.
  *    Textapparatanmerkung e zieht das "auch" aus der Handschrift fälschlich nach oben in den Text.
  *    Zu den Anmerkungen: bei allen Textapparatanmerkungen und in einigen Fällen von Sachanmerkungen erscheint folgender Satz: The requested URL /start.htm was not found on this server.
  *    Aber in der Bibliographie simulieren noch, oder? Da müssten ja irgendwann die id mit den Kurztiteln verbunden werden. Können wir vielleicht am Donnerstag besprechen.

**Comment by dariok** [comment]
Auch im Druck wurde *Junicode* verwendet für die Stellen, die nicht Hebräisch oder Griechisch sind.
Hebräisch wurde gesetzt in *SBLHebrew*, Griechisch in *FreeSerif*

**Comment by Wallsporn** [comment]
Danke!

**Comment by dariok** [comment]
Bzgl. Doppelstrich beim Seitenumbruch: Bisher haben wir den so in KGK I online auch genutzt.
Soll ich das dort auch ändern?

**Comment by Wallsporn** [comment]
Ja, bitte! Wieso habe ich das bisher nur übersehen ... Der Seitenumbruch mit Seitenangabe in eckiger Klammer genügt völlig.
