### ISSUE TITLE
Probleme bei der Tranformation EE88A_text

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#92]
Lieber Dario,
die Transformation von EE88A klappt noch nicht ganz.
Zwei Stellen hatte ich falsch formatiert (in Anm. 6 - ein "l" nicht kursiv + Autorstelle bei Quintilian falsch Kodiert). Du findest die korrigierte Word-Datei im Anhang.

Weitere - seltsame - Probleme tauchen auf. Vor allem:

- [x] Seitenumbrüche "komisch" angezeigt
- [x] lat. Wörter im textkrit. Apparat kursiv  
- [ ] Zitaten sind nur unregelmäßig mit <quote> kodiert (vgl. Anm. 2 und 4)
- [x] lat. Begriffe, die in Word einfach kursiv sind, sind verrutscht und falsch angezeigt (Anm. 4, 6 u. 10)
- [x] Querverweise (in Word) werden noch nicht berücksichtigt.

Im Anhang findest Du die PDF mit meinen Korrekturen. 
Vielleicht kannst Du mir (am Donnerstag) erklären, was ich ggf. falsch formatiert habe. 

[EE88A_Text_2018_1_16_StS.docx](https://github.com/dariok/karlstadt-issues/files/1636165/EE88A_Text_2018_1_16_StS.docx)
[EE88A_text_StS_2018-1-16.pdf](https://github.com/dariok/karlstadt-issues/files/1636166/EE88A_text_StS_2018-1-16.pdf)

**Comment by dariok** [comment]
Anm. 4 wird komplizierter, da hier mit der Bibelstelle der Text unterbrochen ist. Darum kümmere ich mich später.
