### ISSUE TITLE
Probleme bei der Transformation EE132A text

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#93]
Hier auch die EE132A.

Die Transformation des textkrit. Apparatus klappt nicht ganz.
Mehrere Anm. sind einfach verschwunden. ich befürchte, es häng mit der automatisch generierte (Thesennummer)Liste.

- [x] Alle textkrit. Anm. im Thesenreihetitel sind verschwunden: eine "über mehrere Wörter" kritische Anm. (richtig formatiert in Word) und eine zusätzliche Anm. (a-a und b)
- [x] Auch zwei textkrit. Anm, die auf Thesennummer (Th. 2 und 9) sich beziehen, sind nicht angezeigt (und nicht transformiert)
- [x] Die in Word formatierte "korrrigierte Thesennummer" in Th. 4 ist falsch angezeigt. 
- [x] In der 9. These wurde die Expansion von Aug'ustino' nicht transformiert/xlmsiert.

Im Anhang Scan mit meiner Korrekturen.

Dazu die korriegierte Word-Datei - ebendo im Anhang.

Zwei Stelle hatte ich falsch formatiert. Die letzte Zeile habe ich nun korriegiert. Problematisch ist nun die textkrit. Anm. über mehrere Wörter »egere coacti« in der 10. These, wo ich die ursprungliche Formatierung nicht korriegiet hatte (Anm. d. in der online version, Anm. i-h in der Word-Vorlage). Wenn ich nun diese 2 Wörter entsprechend formatiere, ist die ganze These anders formatiert:
![unbenannt](https://user-images.githubusercontent.com/28624747/35003214-665ecea0-faec-11e7-8170-636ce2860a90.JPG)
Die Stelle ist nun gelb markiert. Kannst Du mir helfen? 

[EE.132A_Text_2018_1_16_StS.docx](https://github.com/dariok/karlstadt-issues/files/1636338/EE.132A_Text_2018_1_16_StS.docx)

[EE132A_text_StS_2018-1-16.pdf](https://github.com/dariok/karlstadt-issues/files/1636340/EE132A_text_StS_2018-1-16.pdf)

**Comment by dariok** [comment]
Herzlichen Dank für die Rückmeldungen! Ich werde mir das bis Donnerstag anschauen.
