### ISSUE TITLE
EE 128 weitere Transformationsfehler

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#94]
- [x] Marginalien übereinander fol. C4v, D3r, E2v
- [x] Folgt einem über Zeilenumbruch getrenntem Wort eine Anmerkung, fällt der Wortteil nach dem Trennstrich aus. Fol. E2v "befohl-" (folgt. Anm. 136), fol. E4v "vor" (Anm. 138)

**Comment by dariok** [comment]
Auch Dir herzlichen Dank für die Anmerkungen, das hilft sehr weiter.
