### ISSUE TITLE
Wiedergabe der Titelseite

### ISSUE THREAD

**Issue by Wallsporn** [dariok/karlstadt-issues#95]
Wiedergabe der Titelseite in "Text" soll in Zeilenfall und Ausrichtung dem Original entsprechen, also auch Wiedergabe der Zentrierung etc. Das ist noch nicht der Fall.

**Comment by dariok** [comment]
Umsetzung Umbruch mit https://github.com/dariok/w2tei/commit/b1466508127b07163007241cab4ca7e3e609b469
