### ISSUE TITLE
EE132A - Backup Probleme und neue Fassung für die Transformation

### ISSUE THREAD

**Issue by stefaniasalvadori** [dariok/karlstadt-issues#98]
Lieber Dario, ich sende Dir nochmals die EE132A, damit Du die Transformation der Transkriptionen testen kannst.
Ich weiss, dass Du die Probleme in anderen Issues schon signalisiert hast, dennoch fasse ich hier die Probleme in dieser EE132 nochmals zusammen.

- [ ] rdg mit zusätzlichem Text #97
- [ ] Anmerkungen die auf automatisch generierten Thesenummer sich beziehen (Anm. c und e)
- [ ] die Formatierung "KS: kritische Anmerkung über mehrere Wörter" ist manchmal problematisch. Ich kann hier z.B. die Anm. g über die Wörter "egere coacti" nicht entsprechend formatieren, da die ganze These sonst verändert wird. Ich sehe aber, dass die Stelle in der [Online Edition](http://dev2.hab.de/edoc/view.html?id=edoc_ed000240_132A_transcript) - entspricht der alten Anm. h - nun richtig angezeigt ist. Wie hast Du das geregelt? Wie sollen wir solche Stellen formatieren? Harald signalisiert auch das Problem: 
> wenn  man die Formate der Wordvorlage "KS:Anrede" oder "textkritische Anmerkung über mehrere Worte" verwendet, verändert sich das Format des ganzen Absatzes, da die Formatvorlage Absatz benutzt wurde. Das ist aber oft falsch: Anrede und die Anmerkungen enden oft mitten in einer Zeile. 

Hier nun die aktuelle Fassung dieser Einheit:
[EE.132A_Text_2018_1_24_StS.docx](https://github.com/dariok/karlstadt-issues/files/1661965/EE.132A_Text_2018_1_24_StS.docx)

**Comment by dariok** [comment]
- die Vorlage "kritische Anmerkung über mehrere Wörter" müßtet ihr bitte von einer Absatz- zu einer Zeichenvorlage ändern: Unter den Vorlagen rechts darauf klicken, Ändern, und dann unter "Typ": "Zeichenvorlage" auswählen. Sollte das so nicht funktionieren, dann bitte die Vorlage umbenennen und eine neue Zeichenvorlage mit dem Namen "KS: kritische Anmerkung über mehrere Wörter" erstellen.
- entsprechend auch für "KS:Anrede"
- gleich zu Anfang muß hinter "Text" eine Leerzeile sein, die keine Formatierung hat; ggf. also dort bei den Formatvorlagen "Alle löschen" auswählen. Es sollte also sein: "Text" als Überschrift1, danach eine leere Zeile ohne Vorlage (oder als "Standard").
- Auch bei Thesenreihen muß ganz am Ende einmal das Zeichen `F05E` stehen.
- Anmerkung auf Thesennummer. Ich kann das umsetzen, falls sichergestellt ist, daß diese ganz am Anfang der These steht (also ohne Leerzeichen) und danach ein Leerzeichen kommt. Sonst ließen sie sich nicht von normalen Anmerkungen am Anfang der These unterscheiden.

**Comment by stefaniasalvadori** [comment]
Danke Dario!
Ich habe nun:
- eine neue Vorlage "krit. Anmerkung über mehrere Wörter" als Zeichenvorlage eingefügt und die Stelle entsprechend formatiert. Nun klappt es (in Word).
- Leere Zeile ohne Vorlage unmittelbar nach der Ueberschrift "Text" eingefügt
- Am Ende jeder These habe ich nun das Sonderzeichen für Ende des Absatzes eingefügt
- Die Anmerkungen c und e auf Thesennummer I und  II stehen ganz am Anfang der These. Zwischen Thesennummer und Anmerkungen gibt es aber einen (von Word durch Option"numerierte Liste") automatisch generierten Abstand. Diesen Abstand kann ich nicht löschen.

Hier die neue Word-Vorlage. Falls ich sie noch ändern muss, stehe ich gerne zur Verfügung.

[EE.132A_Text_2018_1_25_StS.docx](https://github.com/dariok/karlstadt-issues/files/1663964/EE.132A_Text_2018_1_25_StS.docx)

**Comment by dariok** [comment]
Es reicht, das Sonderzeichen einmal am Ende einzufügen. Ich benötige es allerdings, um die Begrenzungen der einzelnen Teile korrekt zu erkenne. Ein Verzicht würde andere Probleme nach sich ziehen.

**Comment by stefaniasalvadori** [comment]
Okey.
Hier nochmals die Word-Fassung. Nun mit Sonderzeichen einmal am Ende der Thesenreihe und nochmals am Ende des Textes 
[EE.132A_Text_2018_1_25_StS.docx](https://github.com/dariok/karlstadt-issues/files/1664655/EE.132A_Text_2018_1_25_StS.docx)

**Comment by dariok** [comment]
Merci!

Ich habe noch eine kleine Korrektur bei mri vorgenommen: In den Anm. a und d müßte jeweils am Anfang `A;` kursiv sein.

**Comment by stefaniasalvadori** [comment]
Giusto! Grazie a te!
Hier die korrigierte Version - damit Deine Korrekturen in meiner Vorlage nicht verloren gehen und die verbesserte Version hier gespeichert ist
[EE.132A_Text_2018_1_25_StS.docx](https://github.com/dariok/karlstadt-issues/files/1664819/EE.132A_Text_2018_1_25_StS.docx)

**Comment by dariok** [comment]
Habe doch noch eine Kleinigkeit gefunden, damit es ganz problemlos geht:
[EE.132A_Text_2018_1_25_StS.docx](https://github.com/dariok/karlstadt-issues/files/1664852/EE.132A_Text_2018_1_25_StS.docx)

**Comment by stefaniasalvadori** [comment]
Wunderbar! Danke Dir Dario!

**Comment by dariok** [comment]
siehe weiter #123
