### ISSUE TITLE
EE088A Transkript

### ISSUE THREAD

**Issue by dariok** [dariok/karlstadt-issues#99]
In Th. 4, vor Anm. a steht:

    luc<e>ndo:

und die Anm. a lautet

      Vom Editor verbessert für lucando: Kolde, 471, ändert stillschweigend in non lucendo.

M.E. sind hier die spitzen Klammern um `e` überflüssig, da die originale Form ja in der Fußnote genannt wird. Hieraus ergeben sich Probleme bei der Übersetzung in die korrekte Kodierung.

**Comment by stefaniasalvadori** [comment]
Ich bin einverstanden.
Die korrigierte Word-Fassung - auch hier mit Sonderzeichen einmal am Ende 
[EE88A_Text_2018_1_25_StS.docx](https://github.com/dariok/karlstadt-issues/files/1664645/EE88A_Text_2018_1_25_StS.docx)

**Comment by dariok** [comment]
[EE88A_Text_2018_1_25_StS.docx](https://github.com/dariok/karlstadt-issues/files/1741913/EE88A_Text_2018_1_25_StS.docx)

**Comment by stefaniasalvadori** [comment]
Die Einheit ist noch nicht richtig angezeigt (soweit ich sehe):
- Titel **[76v]  Alia1 Posicio Circularis:** bitte zentrieren
- textkrit. Anm. **a** - im textkrit. Apparat: Text bitte kursiv setzen (vgl. Word-Datei):
_vom Editor verbessert für_: lucando: _**Kolde, 471, ändert stillschweigend in non lucendo.**_
- textkrit. Anm **b** verdoppelt und im Text angezeigt. 
- im Sachapparat sind die bibliographische Angaben in Xml kodiert? Z.B. CSEL?
- Im Sachapparat "FN" Angabe in den Querverweisen zwischen Anmerkugen bitte löschen

**Comment by dariok** [comment]
biliographische Angaben sind kodiert.
FN wird nicht mehr angezeigt.

**Comment by dariok** [comment]
✓ Überschrift als `KS: Zwischenüberschrift` formatiert
✓ Ausgabe für Kommentar in textkrit. Anm. angepaßt

**Comment by dariok** [comment]
✓ Inhalt von `del` wird nicht im Text ausgegeben

**Comment by dariok** [comment]
Bitte noch einmal prüfen.
